Repository GoogleCloudPlatform/DataflowTemplates, pull requests merged in 2022-06, with the labels that each got.

#381 Exclude older snappy-java dependency pulled from avro dependency
  v2/common/pom.xml
  v2/kafka-common/pom.xml
Labels: Google LGTM, size/S

#409 Revert "Exclude older snappy-java dependency pulled from avro dependency"
  v2/common/pom.xml
  v2/kafka-common/pom.xml
Labels: size/S

#412 Running all unit tests before throwing failure
  cicd/cmd/run-unit-tests/main.go
  cicd/internal/workflows/maven-workflows.go
Labels: Google LGTM, size/XS
