Repository GoogleCloudPlatform/DataflowTemplates, pull requests merged in 2023-05, with the labels that each got.

#669 Update syndeo pom file
  syndeo-template/pom.xml
Labels: Google LGTM, size/XS

#660 Differentiate between Dataflow legacy runner and Runner V2.
  it/common/src/main/java/com/google/cloud/teleport/it/common/AbstractPipelineLauncher.java
  it/common/src/main/java/com/google/cloud/teleport/it/common/PipelineLauncher.java
  it/common/src/test/java/com/google/cloud/teleport/it/common/AbstractPipelineLauncherTest.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/LoadTestBase.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/dataflow/ClassicTemplateClient.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/dataflow/DefaultPipelineLauncher.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/dataflow/FlexTemplateClient.java
  it/google-cloud-platform/src/test/java/com/google/cloud/teleport/it/gcp/dataflow/ClassicTemplateClientTest.java
  it/google-cloud-platform/src/test/java/com/google/cloud/teleport/it/gcp/dataflow/FlexTemplateClientTest.java
Labels: Google LGTM, size/L

#676 Add Splunk Resource Manager
  cicd/internal/op/maven.go
  it/common/src/main/java/com/google/cloud/teleport/it/common/utils/ResourceManagerUtils.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/pubsub/conditions/PubsubMessagesCheck.java
  it/jdbc/src/main/java/com/google/cloud/teleport/it/jdbc/AbstractJDBCResourceManager.java
  it/jdbc/src/main/java/com/google/cloud/teleport/it/jdbc/JDBCResourceManagerUtils.java
  it/jdbc/src/test/java/com/google/cloud/teleport/it/jdbc/JDBCResourceManagerUtilsTest.java
  it/mongodb/src/main/java/com/google/cloud/teleport/it/mongodb/MongoDBResourceManager.java
  it/pom.xml
  it/splunk/pom.xml
  it/splunk/src/main/java/com/google/cloud/teleport/it/splunk/DefaultSplunkResourceManager.java
  it/splunk/src/main/java/com/google/cloud/teleport/it/splunk/SplunkContainer.java
  it/splunk/src/main/java/com/google/cloud/teleport/it/splunk/SplunkResourceManager.java
  it/splunk/src/main/java/com/google/cloud/teleport/it/splunk/SplunkResourceManagerException.java
  it/splunk/src/main/java/com/google/cloud/teleport/it/splunk/SplunkResourceManagerUtils.java
  it/splunk/src/main/java/com/google/cloud/teleport/it/splunk/conditions/SplunkEventsCheck.java
  it/splunk/src/main/java/com/google/cloud/teleport/it/splunk/conditions/package-info.java
  it/splunk/src/main/java/com/google/cloud/teleport/it/splunk/matchers/SplunkAsserts.java
  it/splunk/src/main/java/com/google/cloud/teleport/it/splunk/matchers/package-info.java
  it/splunk/src/main/java/com/google/cloud/teleport/it/splunk/package-info.java
  it/splunk/src/test/java/com/google/cloud/teleport/it/splunk/DefaultSplunkResourceManagerIT.java
  it/splunk/src/test/java/com/google/cloud/teleport/it/splunk/DefaultSplunkResourceManagerTest.java
  it/splunk/src/test/java/com/google/cloud/teleport/it/splunk/SplunkResourceManagerUtilsTest.java
  v1/pom.xml
Labels: size/XXL

#654 Add metadata to generated configs
  syndeo-template/src/main/java/com/google/cloud/syndeo/GenerateConfiguration.java
  syndeo-template/src/main/java/com/google/cloud/syndeo/transforms/bigtable/BigTableWriteSchemaTransformConfiguration.java
  syndeo-template/src/main/proto/transforms_api.proto
Labels: size/M

#673 Add default HOST_IP behavior to base Testcontainer class
  it/common/src/main/java/com/google/cloud/teleport/it/common/testcontainers/TestContainerResourceManager.java
  it/common/src/test/java/com/google/cloud/teleport/it/common/testcontainers/TestContainerResourceManagerTest.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/LoadTestBase.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/TemplateTestBase.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/pubsub/DefaultPubsubResourceManager.java
  it/kafka/src/test/java/com/google/cloud/teleport/it/kafka/KafkaIOLT.java
  v1/src/test/java/com/google/cloud/teleport/bigtable/CassandraToBigtableIT.java
  v1/src/test/java/com/google/cloud/teleport/templates/JdbcToBigQueryIT.java
  v2/googlecloud-to-elasticsearch/src/test/java/com/google/cloud/teleport/v2/elasticsearch/templates/BigQueryToElasticsearchIT.java
  v2/googlecloud-to-elasticsearch/src/test/java/com/google/cloud/teleport/v2/elasticsearch/templates/GCSToElasticsearchIT.java
  v2/googlecloud-to-elasticsearch/src/test/java/com/google/cloud/teleport/v2/elasticsearch/templates/PubSubToElasticsearchIT.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/JdbcToBigQueryIT.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/JdbcToPubsubIT.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/PubsubToJdbcIT.java
  v2/kafka-to-bigquery/src/test/java/com/google/cloud/teleport/v2/templates/KafkaToBigQueryIT.java
  v2/mongodb-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/mongodb/templates/MongoDbToBigQueryIT.java
  v2/mqtt-to-pubsub/src/test/java/com/google/cloud/teleport/v2/templates/MqttToPubsubTestIT.java
  v2/pubsub-to-kafka/src/test/java/com/google/cloud/teleport/v2/templates/PubsubToKafkaIT.java
  v2/streaming-data-generator/src/test/java/com/google/cloud/teleport/v2/templates/StreamingDataGeneratorIT.java
  v2/streaming-data-generator/src/test/java/com/google/cloud/teleport/v2/templates/StreamingDataGeneratorLT.java
Labels: size/L

#686 Add JUnit report action to gitactions
  .github/workflows/java-pr-report.yml
Labels: size/M

#674 Switch Nullable annotations from jetbrains to javax
  it/cassandra/src/main/java/com/google/cloud/teleport/it/cassandra/matchers/CassandraAsserts.java
  it/common/src/main/java/com/google/cloud/teleport/it/common/matchers/TemplateAsserts.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/artifacts/matchers/ArtifactAsserts.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/artifacts/matchers/ArtifactsSubject.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/bigquery/matchers/BigQueryAsserts.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/bigtable/matchers/BigtableAsserts.java
Labels: size/S

#688 Fix folder structure for PubSubToMongoDBIT
  v2/pubsub-to-mongodb/src/test/java/com/google/cloud/teleport/v2/templates/PubSubToMongoDBIT.java
  v2/pubsub-to-mongodb/src/test/java/com/google/cloud/teleport/v2/templates/PubSubToMongoDBTest.java
Labels: size/M

#690 Drop `@Experimental` annotation following Beam's decision
  syndeo-template/pom.xml
  syndeo-template/src/main/java/com/google/cloud/syndeo/transforms/TypedSchemaTransformProvider.java
  v1/src/main/java/com/google/cloud/teleport/kafka/connector/KafkaIO.java
  v1/src/main/java/com/google/cloud/teleport/splunk/SplunkIO.java
  v1/src/main/java/org/apache/beam/sdk/io/gcp/spanner/LocalSpannerIO.java
  v2/datastream-to-postgres/src/main/java/com/google/cloud/teleport/v2/io/CdcJdbcIO.java
  v2/datastream-to-sql/src/main/java/com/google/cloud/teleport/v2/io/CdcJdbcIO.java
  v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/utils/ElasticsearchIO.java
Labels: size/S

#689 Add IT for Avro to Bigtable template
  v1/src/test/java/com/google/cloud/teleport/templates/AvroToBigtableIT.java
  v1/src/test/resources/AvroToBigtableIT/bigtable-to-avro-file_test.avro
Labels: size/M

#694 [Integration tests] Add Bigtable to Avro IT
  v1/src/test/java/com/google/cloud/teleport/templates/BigtableToAvroIT.java
Labels: size/L

#692 Migrate JdbcToBigQuery and JdbcToPubsub templates from DynamicJdbcIO to JdbcIO.
  v1/src/main/java/com/google/cloud/teleport/io/DynamicJdbcIO.java
  v1/src/main/java/com/google/cloud/teleport/templates/JdbcToBigQuery.java
  v1/src/test/java/com/google/cloud/teleport/io/DynamicJdbcIOTest.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/io/DynamicJdbcIO.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/DataplexJdbcIngestion.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/JdbcToBigQuery.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/JdbcToPubsub.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/utils/Schemas.java
  v2/googlecloud-to-googlecloud/src/main/java/org/apache/beam/sdk/io/jdbc/BeamSchemaUtil.java
  v2/googlecloud-to-googlecloud/src/main/java/org/apache/beam/sdk/io/jdbc/package-info.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/io/DynamicJdbcIOTest.java
  v2/pom.xml
Labels: size/XXL

#682 Remove lombok from Neo4j module
  v2/googlecloud-to-neo4j/pom.xml
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/helpers/SourceQuerySpec.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/helpers/SqlQuerySpec.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/helpers/TargetQuerySpec.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/job/Aggregation.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/job/Config.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/job/FieldNameTuple.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/job/JobSpec.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/job/Mapping.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/job/OptionsParams.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/job/Source.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/job/Target.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/job/Transform.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/providers/bigquery/BigQueryImpl.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/templates/GoogleCloudToNeo4j.java
Labels: size/XL

#680 Added a test case for max Pubsub msg size
  syndeo-template/pom.xml
  syndeo-template/src/main/java/com/google/cloud/syndeo/SyndeoTemplate.java
  syndeo-template/src/main/java/com/google/cloud/syndeo/dlq/pubsub/PubsubDlqSchemaTransformProvider.java
  syndeo-template/src/main/java/com/google/cloud/syndeo/transforms/TypedSchemaTransformProvider.java
  syndeo-template/src/main/java/com/google/cloud/syndeo/transforms/pubsub/SyndeoPubsubReadSchemaTransformProvider.java
  syndeo-template/src/test/java/com/google/cloud/syndeo/dlq/pubsub/PubsubDlqSchemaTransformProviderTest.java
  syndeo-template/src/test/java/com/google/cloud/syndeo/it/PubsubDlqIT.java
Labels: size/L

#699 Fix advertised host on Kafka tests
  v2/kafka-to-bigquery/src/test/java/com/google/cloud/teleport/v2/templates/KafkaToBigQueryIT.java
  v2/pubsub-to-kafka/src/test/java/com/google/cloud/teleport/v2/templates/PubsubToKafkaIT.java
Labels: size/XS

#696 Support Parallel reads in JdbcToBigQuery template.
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/options/JdbcToBigQueryOptions.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/JdbcToBigQuery.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/JdbcToBigQueryIT.java
Labels: size/L

#675 Add Smoke Tests to gitactions
  .github/workflows/java-pr.yml
  cicd/cmd/run-it-smoke-tests/main.go
  cicd/internal/flags/it-flags.go
  cicd/internal/workflows/maven-workflows.go
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/TemplateTestBase.java
  metadata/src/main/java/com/google/cloud/teleport/metadata/DirectRunnerTest.java
  pom.xml
Labels: size/L

#700 Clean up active dataflow jobs after test completes.
  it/common/src/main/java/com/google/cloud/teleport/it/common/AbstractPipelineLauncher.java
  it/common/src/main/java/com/google/cloud/teleport/it/common/PipelineLauncher.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/IOLoadTestBase.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/LoadTestBase.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/TemplateTestBase.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/dataflow/ClassicTemplateClient.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/dataflow/DefaultPipelineLauncher.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/dataflow/FlexTemplateClient.java
Labels: size/M

#701 Spanner VertexAI Integaration: Refactor SizedType
  v1/src/main/java/com/google/cloud/teleport/spanner/common/SizedType.java
  v1/src/main/java/com/google/cloud/teleport/spanner/ddl/Column.java
Labels: size/L

#705 [Integration Tests] Add Parquet-BQ and BQ-Parquet ITs
  v1/src/test/java/com/google/cloud/teleport/templates/BigtableToParquetIT.java
  v1/src/test/java/com/google/cloud/teleport/templates/ParquetToBigtableIT.java
  v1/src/test/resources/ParquetToBigtableIT/bigtable-to-parquet-file_test.parquet
Labels: size/L

#710 Use java Pattern instead of re2j Pattern.
  it/cassandra/src/main/java/com/google/cloud/teleport/it/cassandra/CassandraResourceManagerUtils.java
  it/common/src/main/java/com/google/cloud/teleport/it/common/utils/ResourceManagerUtils.java
  it/common/src/test/java/com/google/cloud/teleport/it/common/utils/ResourceManagerUtilsTest.java
  it/elasticsearch/src/main/java/com/google/cloud/teleport/it/elasticsearch/ElasticsearchUtils.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/artifacts/ArtifactClient.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/artifacts/GcsArtifactClient.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/bigquery/BigQueryResourceManagerUtils.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/bigtable/BigtableResourceManagerUtils.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/dataflow/DefaultPipelineLauncher.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/pubsub/PubsubUtils.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/spanner/utils/SpannerResourceManagerUtils.java
  it/google-cloud-platform/src/test/java/com/google/cloud/teleport/it/gcp/artifacts/GcsArtifactClientTest.java
  it/jdbc/src/main/java/com/google/cloud/teleport/it/jdbc/JDBCResourceManagerUtils.java
  it/kafka/src/main/java/com/google/cloud/teleport/it/kafka/KafkaResourceManagerUtils.java
  it/mongodb/src/main/java/com/google/cloud/teleport/it/mongodb/MongoDBResourceManagerUtils.java
  it/pom.xml
  v1/src/test/java/com/google/cloud/teleport/spanner/ExportPipelineLT.java
  v1/src/test/java/com/google/cloud/teleport/templates/BigtableToAvroIT.java
  v1/src/test/java/com/google/cloud/teleport/templates/BigtableToParquetIT.java
  v1/src/test/java/com/google/cloud/teleport/templates/BulkCompressorIT.java
  v1/src/test/java/com/google/cloud/teleport/templates/BulkCompressorLT.java
  v1/src/test/java/com/google/cloud/teleport/templates/BulkDecompressorIT.java
  v1/src/test/java/com/google/cloud/teleport/templates/DatastoreToTextIT.java
  v1/src/test/java/com/google/cloud/teleport/templates/PubSubToAvroIT.java
  v1/src/test/java/com/google/cloud/teleport/templates/SpannerToTextLT.java
  v1/src/test/java/com/google/cloud/teleport/templates/TextImportPipelineIT.java
  v2/bigquery-to-parquet/src/test/java/com/google/cloud/teleport/v2/templates/BigQueryToParquetIT.java
  v2/file-format-conversion/src/test/java/com/google/cloud/teleport/v2/templates/FileFormatConversionIT.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/pubsubtotext/PubsubToTextIT.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/pubsubtotext/PubsubToTextLT.java
  v2/streaming-data-generator/src/test/java/com/google/cloud/teleport/v2/templates/StreamingDataGeneratorIT.java
  v2/streaming-data-generator/src/test/java/com/google/cloud/teleport/v2/templates/StreamingDataGeneratorLT.java
Labels: size/L

#668 Refactor options validation
  v2/mqtt-to-pubsub/src/main/java/com/google/cloud/teleport/v2/templates/MqttToPubsub.java
  v2/mqtt-to-pubsub/src/test/java/com/google/cloud/teleport/v2/templates/MqttToPubsubTest.java
Labels: Google LGTM, size/L

#707 Add Throughput (Elements/Sec) metric in Load tests.
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/LoadTestBase.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/monitoring/MonitoringClient.java
Labels: size/L

#712 Fix DataGenerator errors due to runner v2.
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/datagenerator/DataGenerator.java
Labels: size/XS

#709 Spanner VertexAI Integaration: Add Model DDL
  v1/src/main/java/com/google/cloud/teleport/spanner/ddl/Ddl.java
  v1/src/main/java/com/google/cloud/teleport/spanner/ddl/Model.java
  v1/src/main/java/com/google/cloud/teleport/spanner/ddl/ModelColumn.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ddl/DdlTest.java
Labels: size/L

#711 Add Splunk IT's
  .github/workflows/java-pr.yml
  cicd/cmd/run-build/main.go
  cicd/cmd/run-it-smoke-tests/main.go
  cicd/cmd/run-unit-tests/main.go
  it/jdbc/src/main/java/com/google/cloud/teleport/it/jdbc/JDBCDriverFactory.java
  it/splunk/src/main/java/com/google/cloud/teleport/it/splunk/SplunkClientFactory.java
  it/splunk/src/main/java/com/google/cloud/teleport/it/splunk/SplunkResourceManager.java
  it/splunk/src/main/java/com/google/cloud/teleport/it/splunk/SplunkResourceManagerUtils.java
  it/splunk/src/test/java/com/google/cloud/teleport/it/splunk/SplunkResourceManagerIT.java
  it/splunk/src/test/java/com/google/cloud/teleport/it/splunk/SplunkResourceManagerTest.java
  it/splunk/src/test/java/com/google/cloud/teleport/it/splunk/SplunkResourceManagerUtilsTest.java
  pom.xml
  v1/src/test/java/com/google/cloud/teleport/templates/PubSubToSplunkIT.java
Labels: size/XL

#721 Apply spotless:apply over the project
  v2/spanner-change-streams-to-sink/README.md
  v2/spanner-change-streams-to-sink/README_Spanner_Change_Streams_to_Sink.md
Labels: size/XS

#717 Cancel threads upon termination of DirectRunner tests
  it/common/src/main/java/com/google/cloud/teleport/it/common/PipelineLauncher.java
  it/common/src/main/java/com/google/cloud/teleport/it/common/PipelineOperator.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/IOLoadTestBase.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/LoadTestBase.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/TemplateTestBase.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/dataflow/DirectRunnerClient.java
  v1/src/test/java/com/google/cloud/teleport/templates/JdbcToBigQueryIT.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/JdbcToBigQueryIT.java
Labels: size/M

#720 Parallelize Unit Tests and Smoke Tests
  .github/workflows/java-pr.yml
Labels: size/XS

#729 Update the snapshot version in the pom.xml
  syndeo-template/pom.xml
Labels: size/XS

#718 Spanner VertexAI Integration: DDL-Avro converters for Model entity.
  v1/src/main/java/com/google/cloud/teleport/spanner/AvroSchemaToDdlConverter.java
  v1/src/main/java/com/google/cloud/teleport/spanner/DdlToAvroSchemaConverter.java
  v1/src/test/java/com/google/cloud/teleport/spanner/AvroSchemaToDdlConverterTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/DdlToAvroSchemaConverterTest.java
Labels: size/L

#731 [Integration Tests] Add ITs for Avro-Spanner templates
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/spanner/SpannerResourceManager.java
  it/google-cloud-platform/src/test/java/com/google/cloud/teleport/it/gcp/spanner/SpannerResourceManagerTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ImportPipelineIT.java
  v1/src/test/resources/ImportPipelineIT/googlesql/EmptyTable-manifest.json
  v1/src/test/resources/ImportPipelineIT/googlesql/EmptyTable.avro
  v1/src/test/resources/ImportPipelineIT/googlesql/Singers-manifest.json
  v1/src/test/resources/ImportPipelineIT/googlesql/Singers.avro
  v1/src/test/resources/ImportPipelineIT/googlesql/spanner-export.json
  v1/src/test/resources/ImportPipelineIT/postgres/EmptyTable-manifest.json
  v1/src/test/resources/ImportPipelineIT/postgres/EmptyTable.avro
  v1/src/test/resources/ImportPipelineIT/postgres/Singers-manifest.json
  v1/src/test/resources/ImportPipelineIT/postgres/Singers.avro
  v1/src/test/resources/ImportPipelineIT/postgres/spanner-export.json
Labels: size/L

#713 [Integration Tests] Add Sequence-Bigtable ITs
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/TemplateTestBase.java
  v1/pom.xml
  v1/src/test/java/com/google/cloud/teleport/templates/ExportJobIT.java
  v1/src/test/java/com/google/cloud/teleport/templates/ImportJobIT.java
  v1/src/test/resources/ImportJobIT/sequence-file-to-bigtable-file_test
Labels: size/L

#733 Refactor: Create static constants for all Spanner Avro properties.
  v1/src/main/java/com/google/cloud/teleport/spanner/AvroSchemaToDdlConverter.java
  v1/src/main/java/com/google/cloud/teleport/spanner/AvroUtil.java
  v1/src/main/java/com/google/cloud/teleport/spanner/DdlToAvroSchemaConverter.java
  v1/src/main/java/com/google/cloud/teleport/spanner/ImportTransform.java
  v1/src/main/java/com/google/cloud/teleport/spanner/SpannerRecordConverter.java
  v1/src/test/java/com/google/cloud/teleport/spanner/DdlToAvroSchemaConverterTest.java
Labels: size/XL

#719 Add Spanner IT's
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/spanner/matchers/SpannerAsserts.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ExportPipelineIT.java
  v1/src/test/java/com/google/cloud/teleport/templates/SpannerToTextIT.java
Labels: size/L

#740 [Integration Tests] Add spannerProjectId as parameter to some Spanner tests
  v1/src/test/java/com/google/cloud/teleport/spanner/ExportPipelineIT.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ImportPipelineIT.java
Labels: size/XS

#736 [Integration Tests] Add ExportPipeline IT for Postgres Spanner
  v1/src/test/java/com/google/cloud/teleport/spanner/ExportPipelineIT.java
Labels: size/M

#739 [Integration Tests] Add postgres ITs for SpannerToText and TextImportPipeline
  v1/src/test/java/com/google/cloud/teleport/templates/SpannerToTextIT.java
  v1/src/test/java/com/google/cloud/teleport/templates/TextImportPipelineIT.java
Labels: size/L

#734 [Load tests] Fix AvroToBigtableLT OOM errors.
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/bigtable/BigtableResourceManager.java
  v1/src/test/java/com/google/cloud/teleport/bigtable/AvroToBigtableLT.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/TextIOtoBigQueryLT.java
Labels: size/S

#743 Update currentState to CANCELLED when DirectRunner job is aborted
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/dataflow/DirectRunnerClient.java
Labels: size/XS

#744 [Integration Tests] Rename 'createTable' function to 'executeDdlStatement'
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/spanner/SpannerResourceManager.java
  it/google-cloud-platform/src/test/java/com/google/cloud/teleport/it/gcp/spanner/SpannerResourceManagerTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ExportPipelineIT.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ExportPipelineLT.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ImportPipelineIT.java
  v1/src/test/java/com/google/cloud/teleport/templates/SpannerToTextIT.java
  v1/src/test/java/com/google/cloud/teleport/templates/SpannerToTextLT.java
  v1/src/test/java/com/google/cloud/teleport/templates/TextImportPipelineIT.java
  v2/streaming-data-generator/src/test/java/com/google/cloud/teleport/v2/templates/StreamingDataGeneratorIT.java
  v2/streaming-data-generator/src/test/java/com/google/cloud/teleport/v2/templates/StreamingDataGeneratorLT.java
Labels: size/M

#745 Ignore Eventhub incomplete test
  v2/azure-eventhub-to-pubsub/src/test/java/com/google/cloud/teleport/v2/templates/AzureEventhubToPubsubIT.java
Labels: size/XS

#716 Cloud Bigtable CDC to BigQuery dataflow template added
  it/common/src/main/java/com/google/cloud/teleport/it/common/utils/ResourceManagerUtils.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/bigtable/BigtableTableSpec.java
  v2/bigtable-common/src/main/java/com/google/cloud/teleport/v2/bigtable/options/BigtableCommonOptions.java
  v2/bigtable-common/src/main/java/com/google/cloud/teleport/v2/bigtable/utils/BigtableConfig.java
  v2/googlecloud-to-googlecloud/README.md
  v2/googlecloud-to-googlecloud/README_Bigtable_Change_Streams_to_BigQuery.md
  v2/googlecloud-to-googlecloud/docs/BigtableChangeStreamsToBigQuery/README.md
  v2/googlecloud-to-googlecloud/pom.xml
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/options/BigtableChangeStreamToBigQueryOptions.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstobigquery/BigQueryDeadLetterQueueSanitizer.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstobigquery/BigtableChangeStreamsToBigQuery.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstobigquery/FailsafeModJsonToChangelogTableRowTransformer.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstobigquery/model/BigQueryDestination.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstobigquery/model/BigtableSource.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstobigquery/model/ChangelogColumn.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstobigquery/model/Mod.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstobigquery/model/ModType.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstobigquery/model/TransientColumn.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstobigquery/model/UnsupportedEntryException.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstobigquery/model/package-info.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstobigquery/package-info.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstobigquery/schemautils/BigQueryUtils.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstobigquery/schemautils/BigQueryValueFormatter.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstobigquery/schemautils/package-info.java
  v2/googlecloud-to-googlecloud/src/main/resources/bigtable-changestreams-to-bigquery-command-spec.json
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstobigquery/BigQueryDynamicDestinationsTest.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstobigquery/TestUtil.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstobigquery/model/BigQueryDestinationTest.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstobigquery/schemautils/BigQueryUtilTest.java
Labels: Google LGTM, size/XXL

#746 Skip shade plugin on GitHub Actions (it and load)
  cicd/cmd/run-it-tests/main.go
  cicd/cmd/run-load-tests/main.go
Labels: size/XS

#747 Wrap credentials in a ValueProvider for KMS encrypted keys
  v2/common/src/main/java/com/google/cloud/teleport/v2/utils/KMSUtils.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/DataplexJdbcIngestion.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/JdbcToBigQuery.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/JdbcToPubsub.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/PubsubToJdbc.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/io/DynamicJdbcIOTest.java
  v2/googlecloud-to-splunk/src/main/java/com/google/cloud/teleport/v2/templates/GCSToSplunk.java
Labels: size/M

#735 Update generated docs
  v1/README_Cloud_Spanner_to_GCS_Avro.md
  v1/README_Jdbc_to_BigQuery.md
  v1/README_Spanner_to_GCS_Text.md
  v2/googlecloud-to-googlecloud/README_Jdbc_to_BigQuery_Flex.md
  v2/googlecloud-to-googlecloud/README_Spanner_Change_Streams_to_BigQuery.md
  v2/googlecloud-to-googlecloud/README_Spanner_Change_Streams_to_Google_Cloud_Storage.md
  v2/googlecloud-to-googlecloud/README_Spanner_Change_Streams_to_PubSub.md
  v2/spanner-change-streams-to-sink/README_Spanner_Change_Streams_to_Sink.md
Labels: size/M

#741 Spanner VertexAI Integration: export and import for Models
  v1/src/main/java/com/google/cloud/teleport/spanner/ExportTransform.java
  v1/src/main/java/com/google/cloud/teleport/spanner/ImportTransform.java
  v1/src/test/java/com/google/cloud/teleport/spanner/CopyDbTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ExportTransformTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ImportFromAvroTest.java
Labels: size/L

#748 [Integration Tests] Add ITs for Spanner ChangeStreams to GCS
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/artifacts/utils/JsonTestUtil.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/SpannerChangeStreamsToGcsIT.java
Labels: size/L

#750 implemented SchemaIO Transform for generating testing data
  syndeo-template/src/main/java/com/google/cloud/syndeo/transforms/datagenerator/DataGeneratorSchemaTransform.java
  syndeo-template/src/main/java/com/google/cloud/syndeo/transforms/datagenerator/DataGeneratorSchemaTransformProvider.java
  syndeo-template/src/main/java/com/google/cloud/syndeo/transforms/datagenerator/RecordCreator.java
  syndeo-template/src/test/java/com/google/cloud/syndeo/transforms/datagenerator/DataGeneratorSchemaTransformTest.java
  syndeo-template/src/test/java/com/google/cloud/syndeo/transforms/datagenerator/RecordCreatorTest.java
Labels: size/XL

#752 Fix scheduled Java PR and Syndeo PR workflows
  .github/workflows/java-pr.yml
  .github/workflows/scorecards-analysis.yml
  .github/workflows/syndeo-pr.yml
Labels: size/S
