Repository GoogleCloudPlatform/DataflowTemplates, pull requests merged in 2023-10, with the labels that each got.

#1083 Fix format for bigtableChangeStreamAppProfile
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstobigquery/BigtableChangeStreamsToBigQueryIT.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstogcs/BigtableChangeStreamsToGcsIT.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstopubsub/BigtableChangeStreamsToPubSubIT.java
Labels: size/XS

#1084 Remove note that GCS to BigQuery doesn't support structs
  v1/src/main/java/com/google/cloud/teleport/templates/TextIOToBigQuery.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/TextIOToBigQuery.java
Labels: size/XS

#1086 Update release script to execute tests and publish artifacts.
  .github/workflows/load-tests.yml
  .github/workflows/release.yml
Labels: Google LGTM, size/M

#1078 Add `requirementsFile` parameter to LaunchConfig.
  it/common/src/main/java/org/apache/beam/it/common/PipelineLauncher.java
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/dataflow/DefaultPipelineLauncher.java
Labels: Google LGTM, size/M

#1076 Improve annotations / regenerate docs
  v1/README_Cloud_PubSub_to_Datadog.md
  v1/README_Cloud_PubSub_to_Splunk.md
  v1/README_Datastore_to_Datastore_Delete.md
  v1/README_Datastore_to_GCS_Text.md
  v1/README_Firestore_to_Firestore_Delete.md
  v1/README_Firestore_to_GCS_Text.md
  v1/README_GCS_Text_to_BigQuery.md
  v1/README_GCS_Text_to_Datastore.md
  v1/README_GCS_Text_to_Firestore.md
  v1/README_Jdbc_to_BigQuery.md
  v1/README_PubSub_Subscription_to_BigQuery.md
  v1/README_PubSub_to_BigQuery.md
  v1/README_Stream_GCS_Text_to_BigQuery.md
  v2/bigtable-changestreams-to-hbase/README_Bigtable_Change_Streams_to_HBase.md
  v2/datastream-to-bigquery/README_Cloud_Datastream_to_BigQuery.md
  v2/gcs-to-sourcedb/README_GCS_to_Sourcedb.md
  v2/googlecloud-to-elasticsearch/README_BigQuery_to_Elasticsearch.md
  v2/googlecloud-to-elasticsearch/README_GCS_to_Elasticsearch.md
  v2/googlecloud-to-elasticsearch/README_PubSub_to_Elasticsearch.md
  v2/googlecloud-to-googlecloud/README_Bigtable_Change_Streams_to_BigQuery.md
  v2/googlecloud-to-googlecloud/README_Bigtable_Change_Streams_to_PubSub.md
  v2/googlecloud-to-googlecloud/README_Firestore_to_BigQuery_Flex.md
  v2/googlecloud-to-googlecloud/README_GCS_Text_to_BigQuery_Flex.md
  v2/googlecloud-to-googlecloud/README_PubSub_to_BigQuery_Flex.md
  v2/googlecloud-to-googlecloud/README_Pubsub_to_Jdbc.md
  v2/googlecloud-to-googlecloud/README_Stream_GCS_Text_to_BigQuery_Flex.md
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstobigquery/BigtableChangeStreamsToBigQuery.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstopubsub/BigtableChangeStreamsToPubSub.java
  v2/googlecloud-to-neo4j/README_Google_Cloud_to_Neo4j.md
  v2/googlecloud-to-splunk/README_GCS_To_Splunk.md
  v2/jdbc-to-googlecloud/README_Jdbc_to_BigQuery_Flex.md
  v2/jdbc-to-googlecloud/README_Jdbc_to_PubSub.md
  v2/kafka-to-bigquery/README_Kafka_to_BigQuery.md
  v2/mysql-to-googlecloud/README_MySQL_to_BigQuery.md
  v2/ordered-changestream-buffer-to-sourcedb/README_Ordered_Changestream_Buffer_to_Sourcedb.md
  v2/ordered-changestream-buffer-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/OrderedChangestreamBufferToSourceDb.java
  v2/postgresql-to-googlecloud/README_PostgreSQL_to_BigQuery.md
  v2/pubsub-binary-to-bigquery/README_PubSub_Proto_to_BigQuery.md
  v2/pubsub-cdc-to-bigquery/README_PubSub_CDC_to_BigQuery.md
  v2/pubsub-to-kafka/README_PubSub_to_Kafka.md
  v2/pubsub-to-mongodb/README_Cloud_PubSub_to_MongoDB.md
  v2/pubsub-to-redis/README_Cloud_PubSub_to_Redis.md
  v2/pubsub-to-redis/src/main/java/com/google/cloud/teleport/v2/templates/PubSubToRedis.java
  v2/spanner-change-streams-to-sharded-file-sink/README_Spanner_Change_Streams_to_Sharded_File_Sink.md
  v2/sqlserver-to-googlecloud/README_SQLServer_to_BigQuery.md
Labels: size/L

#1096 Add parallelism to release workflow.
  .github/workflows/release.yml
Labels: Google LGTM, size/XS

#1094 Fix errorprone alerts for templates
  plugins/core-plugin/src/main/java/com/google/cloud/teleport/plugin/docs/TemplateDocsUtils.java
  plugins/core-plugin/src/main/java/com/google/cloud/teleport/plugin/model/MethodDefinitions.java
  v1/src/main/java/com/google/cloud/teleport/avro/AvroPubsubMessageRecord.java
  v1/src/main/java/com/google/cloud/teleport/kafka/connector/ProducerSpEL.java
  v1/src/main/java/com/google/cloud/teleport/spanner/ddl/Index.java
Labels: size/M

#1091 [MQTT to Pub/Sub] Fix username/password validation logic.
  v2/mqtt-to-pubsub/src/main/java/com/google/cloud/teleport/v2/templates/MqttToPubsub.java
  v2/mqtt-to-pubsub/src/test/java/com/google/cloud/teleport/v2/templates/MqttToPubsubTest.java
Labels: Google LGTM, size/S

#1095 Fix errorprone alerts for templates [2]
  v2/cdc-parent/cdc-change-applier/src/main/java/com/google/cloud/dataflow/cdc/applier/ChangelogTableDynamicDestinations.java
  v2/cdc-parent/cdc-embedded-connector/src/main/java/com/google/cloud/dataflow/cdc/connector/DebeziumSourceRecordToDataflowCdcFormatTranslator.java
  v2/common/src/main/java/com/google/cloud/teleport/v2/cdc/merge/MergeInfo.java
  v2/common/src/main/java/com/google/cloud/teleport/v2/transforms/PythonTextTransformer.java
  v2/common/src/main/java/com/google/cloud/teleport/v2/utils/MetadataValidator.java
  v2/common/src/main/java/com/google/cloud/teleport/v2/utils/WriteToGCSUtility.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/ddl/Index.java
Labels: size/M

#1099 Fix errorprone alerts for templates [3]
  pom.xml
  v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/utils/ElasticsearchIO.java
  v2/gcs-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/common/ProcessingContext.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/avro/AvroPubsubMessageRecord.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/spannerchangestreamstobigquery/model/TrackedSpannerTable.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/job/Target.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/utils/DataCastingUtils.java
  v2/ordered-changestream-buffer-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/common/ProcessingContext.java
  v2/ordered-changestream-buffer-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/common/Shard.java
  v2/spanner-change-streams-to-sink/src/main/java/com/google/cloud/teleport/v2/templates/common/Shard.java
  v2/spanner-change-streams-to-sink/src/main/java/com/google/cloud/teleport/v2/templates/sinks/KafkaConnectionProfile.java
  v2/spanner-change-streams-to-sink/src/main/java/com/google/cloud/teleport/v2/templates/sinks/PubSubConnectionProfile.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/schema/ColumnPK.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/schema/NameAndCols.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/schema/Schema.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/schema/SourceColumnDefinition.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/schema/SourceColumnType.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/schema/SourceTable.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/schema/SpannerColumnDefinition.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/schema/SpannerColumnType.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/schema/SpannerTable.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/schema/SyntheticPKey.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/shard/Shard.java
Labels: size/L

#1102 [GCS SequenceFile to Bigtable] Make `mutationThrottleLatencyMs` parameter optional.
  v1/src/main/java/com/google/cloud/teleport/templates/ImportJobPlaceholder.java
Labels: Google LGTM, size/XS

#1105 Add gitactions scripts
  .github/scripts/configure-runners.sh
  .github/scripts/shutdown-script.sh
  .github/scripts/startup-script.sh
Labels: size/L

#1104 Fix Jdbc to BigQuery StackOverflowError when parsing arrays in Postgres
  it/jdbc/src/main/java/org/apache/beam/it/jdbc/AbstractJDBCResourceManager.java
  v1/src/main/java/com/google/cloud/teleport/templates/common/JdbcConverters.java
  v2/jdbc-common/src/main/java/com/google/cloud/teleport/v2/utils/JdbcConverters.java
  v2/postgresql-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/PostgreSQLToBigQueryIT.java
Labels: size/L

#1106 Add IT and generated doc for Spanner-to-BigQuery template
  v2/googlecloud-to-googlecloud/README_Cloud_Spanner_to_BigQuery_Flex.md
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/options/SpannerToBigQueryOptions.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/SpannerToBigQuery.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/SpannerToBigQueryIT.java
Labels: size/L

#1114 Do not duplicate already shaded resources in the Flex container
  plugins/core-plugin/src/main/java/com/google/cloud/teleport/plugin/TemplateSpecsGenerator.java
  plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesStageMojo.java
  v2/cdc-parent/cdc-embedded-connector/pom.xml
  v2/pom.xml
Labels: size/M

#1116 Flaky builds, rollback autovalue to previous version
  pom.xml
Labels: size/XS

#1087 Fix ResultSet closed errors in JDBCResourceManager.
  it/jdbc/src/main/java/org/apache/beam/it/jdbc/AbstractJDBCResourceManager.java
  it/jdbc/src/main/java/org/apache/beam/it/jdbc/JDBCResourceManager.java
  it/jdbc/src/main/java/org/apache/beam/it/jdbc/PostgresResourceManager.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/PubsubToJdbcIT.java
  v2/streaming-data-generator/src/test/java/com/google/cloud/teleport/v2/templates/StreamingDataGeneratorLT.java
Labels: Google LGTM, size/L

#1119 Keep a single SpannerUtils (common) to avoid name clashing
  v2/common/src/main/java/com/google/cloud/teleport/v2/utils/SpannerUtils.java
  v2/common/src/test/java/com/google/cloud/teleport/v2/utils/SpannerUtilsTest.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/spannerchangestreamstobigquery/BigQueryDynamicDestinations.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/spannerchangestreamstobigquery/FailsafeModJsonToTableRowTransformer.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/spannerchangestreamstobigquery/schemautils/SpannerChangeStreamsUtils.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/utils/SpannerUtils.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/spannerchangestreamstobigquery/SchemaUtilsTest.java
Labels: size/L

#1121 [Tech Debt] Remove forked KafkaIO and classic KafkaToBigQuery template.
  v1/src/main/java/com/google/cloud/teleport/kafka/connector/ConsumerSpEL.java
  v1/src/main/java/com/google/cloud/teleport/kafka/connector/CustomTimestampPolicyWithLimitedDelay.java
  v1/src/main/java/com/google/cloud/teleport/kafka/connector/KafkaCheckpointMark.java
  v1/src/main/java/com/google/cloud/teleport/kafka/connector/KafkaExactlyOnceSink.java
  v1/src/main/java/com/google/cloud/teleport/kafka/connector/KafkaIO.java
  v1/src/main/java/com/google/cloud/teleport/kafka/connector/KafkaPublishTimestampFunction.java
  v1/src/main/java/com/google/cloud/teleport/kafka/connector/KafkaRecord.java
  v1/src/main/java/com/google/cloud/teleport/kafka/connector/KafkaRecordCoder.java
  v1/src/main/java/com/google/cloud/teleport/kafka/connector/KafkaTimestampType.java
  v1/src/main/java/com/google/cloud/teleport/kafka/connector/KafkaUnboundedReader.java
  v1/src/main/java/com/google/cloud/teleport/kafka/connector/KafkaUnboundedSource.java
  v1/src/main/java/com/google/cloud/teleport/kafka/connector/KafkaWriter.java
  v1/src/main/java/com/google/cloud/teleport/kafka/connector/ProducerSpEL.java
  v1/src/main/java/com/google/cloud/teleport/kafka/connector/TimestampPolicy.java
  v1/src/main/java/com/google/cloud/teleport/kafka/connector/TimestampPolicyFactory.java
  v1/src/main/java/com/google/cloud/teleport/kafka/connector/package-info.java
  v1/src/main/java/com/google/cloud/teleport/kafka/connector/serialization/InstantDeserializer.java
  v1/src/main/java/com/google/cloud/teleport/kafka/connector/serialization/InstantSerializer.java
  v1/src/main/java/com/google/cloud/teleport/kafka/connector/serialization/package-info.java
  v1/src/main/java/com/google/cloud/teleport/templates/KafkaToBigQuery.java
  v1/src/test/java/com/google/cloud/teleport/kafka/connector/CustomTimestampPolicyWithLimitedDelayTest.java
  v1/src/test/java/com/google/cloud/teleport/kafka/connector/KafkaRecordCoderTest.java
  v1/src/test/java/com/google/cloud/teleport/templates/KafkaToBigQueryTest.java
Labels: Google LGTM, size/XXL

#1120 [JdbcToBigQuery] Allow overriding JdbcIO fetchSize
  v2/jdbc-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/options/JdbcToBigQueryOptions.java
  v2/jdbc-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/JdbcToBigQuery.java
  v2/jdbc-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/JdbcToBigQueryIT.java
Labels: size/M

#1123 [Cassandra RM] Add microseconds to prevent keyspace clash
  it/cassandra/src/main/java/org/apache/beam/it/cassandra/CassandraResourceManagerUtils.java
Labels: size/XS

#1125 Fix CassandraResourceManagerTest.
  it/cassandra/src/test/java/org/apache/beam/it/cassandra/CassandraResourceManagerTest.java
Labels: Google LGTM, size/XS

#1124 [Release] Upload test reports in release workflow.
  .github/workflows/release.yml
Labels: Google LGTM, size/XS

#1107 [Security] Bump Avro to 1.11.3 due to CVE-2023-39410
  pom.xml
Labels: size/XS

#1122 [Security] Bump org.json:json dependency due to CVE-2023-5072
  pom.xml
Labels: size/XS

#1127 Add timestamp to SQLServerToBigQueryIT
  v2/sqlserver-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/SQLServerToBigQueryIT.java
Labels: size/S

#1048 Fix date/time pattern
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/utils/DataCastingUtils.java
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/utils/DataCastingUtilsTest.java
Labels: Google LGTM, size/M

#955 Add support for targets which only define a custom write query
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/InputRefactoring.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/InputValidator.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/enums/ActionExecuteAfter.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/enums/ArtifactType.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/enums/TargetType.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/helpers/TargetMapper.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/job/Config.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/job/JobSpec.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/job/Target.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/job/Transform.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/templates/GoogleCloudToNeo4j.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/transforms/Neo4jRowWriterTransform.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/utils/BeamBlock.java
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/model/InputRefactoringTest.java
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/model/InputValidatorTest.java
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/model/helpers/TargetMapperTest.java
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/model/job/TargetTest.java
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/templates/CustomNeo4jWriteQueryIT.java
  v2/googlecloud-to-neo4j/src/test/resources/testing-specs/custom-query/northwind-jobspec-ordered.json
  v2/googlecloud-to-neo4j/src/test/resources/testing-specs/custom-query/northwind-jobspec.json
Labels: Google LGTM, size/XXL

#1129 Fix Neo4j flake by sorting checked elements
  it/neo4j/src/main/java/org/apache/beam/it/neo4j/conditions/Neo4jQueryCheck.java
Labels: size/S

#1128 Adjust docs generation with issues identified on Spanner Vector export
  plugins/core-plugin/src/main/java/com/google/cloud/teleport/plugin/docs/TemplateDocsUtils.java
  plugins/core-plugin/src/main/resources/site-template.md
  v1/README_Cloud_Spanner_vectors_to_Cloud_Storage.md
  v1/src/main/java/com/google/cloud/teleport/spanner/ExportPipeline.java
  v1/src/main/java/com/google/cloud/teleport/spanner/ImportPipeline.java
  v1/src/main/java/com/google/cloud/teleport/spanner/TextImportPipeline.java
  v1/src/main/java/com/google/cloud/teleport/templates/BigQueryToTFRecord.java
  v1/src/main/java/com/google/cloud/teleport/templates/SpannerVectorEmbeddingExport.java
  v2/common/src/test/java/com/google/cloud/teleport/v2/transforms/CsvConvertersTest.java
  v2/googlecloud-to-splunk/src/main/java/com/google/cloud/teleport/v2/transforms/SplunkConverters.java
Labels: size/M

#1134 Support KMS for mongodburi using maybeDecrypt function
  v2/mongodb-to-googlecloud/README_MongoDB_to_BigQuery.md
  v2/mongodb-to-googlecloud/README_MongoDB_to_BigQuery_CDC.md
  v2/mongodb-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/mongodb/options/MongoDbToBigQueryOptions.java
  v2/mongodb-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/mongodb/templates/MongoDbToBigQuery.java
  v2/mongodb-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/mongodb/templates/MongoDbToBigQueryCdc.java
Labels: Google LGTM, size/M

#1053 Fix schema statement generation
  v2/googlecloud-to-neo4j/docs/testing-specs/compact-syntax/bigquery/bq-gdelt-test-spec.json
  v2/googlecloud-to-neo4j/docs/testing-specs/compact-syntax/bigquery/bq-gdelt-test-spec2.json
  v2/googlecloud-to-neo4j/docs/testing-specs/compact-syntax/bigquery/bq-northwind-jobspec.json
  v2/googlecloud-to-neo4j/docs/testing-specs/compact-syntax/bigquery/bq-northwind-name-only.json
  v2/googlecloud-to-neo4j/docs/testing-specs/compact-syntax/composite/bq-gdelt-postload-actions.json
  v2/googlecloud-to-neo4j/docs/testing-specs/compact-syntax/composite/bq-northwind-actions-jobspec.json
  v2/googlecloud-to-neo4j/docs/testing-specs/compact-syntax/other/only-actions-jobspec.json
  v2/googlecloud-to-neo4j/docs/testing-specs/compact-syntax/text/inline-northwind-jobspec.json
  v2/googlecloud-to-neo4j/docs/testing-specs/compact-syntax/text/text-northwind-jobspec.json
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/database/CypherGenerator.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/InputRefactoring.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/InputValidator.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/helpers/MappingMapper.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/job/JobSpec.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/job/Mapping.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/transforms/Neo4jRowWriterTransform.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/utils/ModelUtils.java
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/database/CypherGeneratorTest.java
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/model/InputRefactoringTest.java
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/model/InputValidatorTest.java
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/model/helpers/MappingMapperTest.java
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/model/job/MappingTest.java
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/templates/ConstraintsIndicesIT.java
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/templates/SinglePassGraphImportIT.java
  v2/googlecloud-to-neo4j/src/test/resources/testing-specs/constraints-indices/edge-spec.json
  v2/googlecloud-to-neo4j/src/test/resources/testing-specs/constraints-indices/node-spec.json
  v2/googlecloud-to-neo4j/src/test/resources/testing-specs/cypher-generator-test/multi-distinct-keys-single-pass-import.json
  v2/googlecloud-to-neo4j/src/test/resources/testing-specs/cypher-generator-test/multi-label-single-pass-import.json
  v2/googlecloud-to-neo4j/src/test/resources/testing-specs/cypher-generator-test/single-target-relation-import-create-rels-merge-nodes.json
  v2/googlecloud-to-neo4j/src/test/resources/testing-specs/cypher-generator-test/single-target-relation-import-merge-all.json
  v2/googlecloud-to-neo4j/src/test/resources/testing-specs/cypher-generator-test/single-target-relation-import-with-keys-spec.json
  v2/googlecloud-to-neo4j/src/test/resources/testing-specs/cypher-generator-test/single-target-relation-import-without-keys-spec.json
  v2/googlecloud-to-neo4j/src/test/resources/testing-specs/inline-data/northwind-jobspec-single-pass-merge-all.json
  v2/googlecloud-to-neo4j/src/test/resources/testing-specs/inline-data/northwind-jobspec.json
  v2/googlecloud-to-neo4j/src/test/resources/testing-specs/inline-data/northwind-subset-jobspec-single-pass-create-edge-merge-nodes.json
  v2/googlecloud-to-neo4j/src/test/resources/testing-specs/property-mappings/booleans-bq-spec.json
  v2/googlecloud-to-neo4j/src/test/resources/testing-specs/property-mappings/booleans-text-spec.json
  v2/googlecloud-to-neo4j/src/test/resources/testing-specs/text-northwind-jobspec.json
Labels: Google LGTM, size/XXL

#1135 fix: fix json format
  v2/pubsub-cdc-to-bigquery/README.md
Labels: Google LGTM, size/XS

#1132 BulkCompressor: Add optional parameter outputFilenameSuffix to overwrite default
  v1/README_Bulk_Compress_GCS_Files.md
  v1/src/main/java/com/google/cloud/teleport/templates/BulkCompressor.java
Labels: Google LGTM, size/M

#1139 Fix `inputTableSpec` to be optional
  v2/common/src/main/java/com/google/cloud/teleport/v2/transforms/BigQueryConverters.java
Labels: Google LGTM, size/XS

#1145 Avoid flakiness due to HashSet nondeterminism (use LinkedHashSet)
  v1/src/test/java/com/google/cloud/teleport/bigtable/CassandraRowMapperFnTest.java
Labels: size/S

#1141 Keep Jdbc dependencies only on modules that need
  v2/datastream-to-postgres/pom.xml
  v2/datastream-to-sql/pom.xml
  v2/jdbc-common/pom.xml
  v2/jdbc-common/src/main/java/com/google/cloud/teleport/v2/auto/blocks/ReadFromJdbc.java
  v2/jdbc-common/src/main/java/com/google/cloud/teleport/v2/auto/blocks/package-info.java
  v2/jdbc-common/src/main/java/com/google/cloud/teleport/v2/utils/JsonStringToQueryMapper.java
  v2/jdbc-common/src/test/java/com/google/cloud/teleport/v2/utils/JsonStringToQueryMapperTest.java
  v2/pom.xml
  v2/streaming-data-generator/pom.xml
Labels: size/M
