Repository GoogleCloudPlatform/DataflowTemplates, pull requests merged in 2023-09, with the labels that each got.

#610 :sparkles: add postgresql compatibility for datastream-to-bigquery template
  v2/common/src/main/java/com/google/api/services/datastream/v1/model/DiscoverConnectionProfileRequest.java
  v2/common/src/main/java/com/google/api/services/datastream/v1/model/DiscoverConnectionProfileResponse.java
  v2/common/src/main/java/com/google/api/services/datastream/v1/model/PostgresqlColumn.java
  v2/common/src/main/java/com/google/api/services/datastream/v1/model/PostgresqlRdbms.java
  v2/common/src/main/java/com/google/api/services/datastream/v1/model/PostgresqlSchema.java
  v2/common/src/main/java/com/google/api/services/datastream/v1/model/PostgresqlSourceConfig.java
  v2/common/src/main/java/com/google/api/services/datastream/v1/model/PostgresqlTable.java
  v2/common/src/main/java/com/google/api/services/datastream/v1/model/SourceConfig.java
  v2/common/src/main/java/com/google/cloud/teleport/v2/utils/DataStreamClient.java
  v2/common/src/main/java/com/google/cloud/teleport/v2/values/DatastreamRow.java
Labels: Google LGTM, size/XL

#1023 [Docs] Add plugin-generated docs for Python templates
  plugins/core-plugin/src/main/java/com/google/cloud/teleport/plugin/docs/TemplateDocsGenerator.java
  plugins/core-plugin/src/main/java/com/google/cloud/teleport/plugin/model/TemplateDefinitions.java
  plugins/core-plugin/src/main/resources/README-template.md
  python/README_Streaming_LLM.md
  python/README_Word_Count_Python.md
Labels: size/L

#1019 Add Tour of Beam, Beam Playground and other links to README.
  README.md
Labels: Google LGTM, size/XL

#1022 Change reloading to only use one parameter
  v1/pom.xml
  v1/src/main/java/com/google/cloud/teleport/templates/KafkaToBigQuery.java
  v1/src/main/java/com/google/cloud/teleport/templates/PubSubToBigQuery.java
  v1/src/main/java/com/google/cloud/teleport/templates/PubSubToDatadog.java
  v1/src/main/java/com/google/cloud/teleport/templates/PubSubToSplunk.java
  v1/src/main/java/com/google/cloud/teleport/templates/PubsubToDatastore.java
  v1/src/main/java/com/google/cloud/teleport/templates/common/JavascriptTextTransformer.java
  v1/src/test/java/com/google/cloud/teleport/templates/KafkaToBigQueryTest.java
  v1/src/test/java/com/google/cloud/teleport/templates/PubSubToBigQueryIT.java
  v1/src/test/java/com/google/cloud/teleport/templates/PubsubToBigQueryTest.java
  v1/src/test/java/com/google/cloud/teleport/templates/common/JavascriptTextTransformerTest.java
  v2/common/pom.xml
  v2/common/src/main/java/com/google/cloud/teleport/v2/transforms/BigQueryConverters.java
  v2/common/src/main/java/com/google/cloud/teleport/v2/transforms/CsvConverters.java
  v2/common/src/main/java/com/google/cloud/teleport/v2/transforms/JavascriptTextTransformer.java
  v2/common/src/main/java/com/google/cloud/teleport/v2/transforms/UDFTextTransformer.java
  v2/common/src/test/java/com/google/cloud/teleport/v2/transforms/CsvConvertersTest.java
  v2/common/src/test/java/com/google/cloud/teleport/v2/transforms/JavascriptTextTransformerTest.java
  v2/common/src/test/java/com/google/cloud/teleport/v2/transforms/UdfSamplesTest.java
  v2/datastream-to-bigquery/src/main/java/com/google/cloud/teleport/v2/templates/DataStreamToBigQuery.java
  v2/googlecloud-to-elasticsearch/src/main/java/com/google/cloud/teleport/v2/elasticsearch/transforms/PubSubMessageToJsonDocument.java
  v2/googlecloud-to-elasticsearch/src/test/java/com/google/cloud/teleport/v2/elasticsearch/templates/GCSToElasticsearchTest.java
  v2/googlecloud-to-elasticsearch/src/test/java/com/google/cloud/teleport/v2/elasticsearch/templates/PubSubToElasticsearchTest.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/FirestoreToBigQuery.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/PubSubToBigQuery.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/TextIOToBigQuery.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/TextToBigQueryStreaming.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/PubSubToBigQueryIT.java
  v2/kafka-to-bigquery/src/main/java/com/google/cloud/teleport/v2/templates/KafkaToBigQuery.java
  v2/kafka-to-pubsub/src/main/java/com/google/cloud/teleport/v2/transforms/FormatTransform.java
  v2/pubsub-binary-to-bigquery/src/main/java/com/google/cloud/teleport/v2/templates/PubsubProtoToBigQuery.java
  v2/pubsub-cdc-to-bigquery/src/main/java/com/google/cloud/teleport/v2/templates/PubSubCdcToBigQuery.java
  v2/pubsub-cdc-to-bigquery/src/test/java/com/google/cloud/teleport/v2/templates/PubSubCdcToBigQueryTest.java
  v2/pubsub-to-kafka/src/main/java/com/google/cloud/teleport/v2/transforms/FormatMessageTransform.java
  v2/pubsub-to-mongodb/src/main/java/com/google/cloud/teleport/v2/templates/PubSubToMongoDB.java
  v2/pubsub-to-mongodb/src/test/java/com/google/cloud/teleport/v2/templates/PubSubToMongoDBIT.java
  v2/pubsub-to-mongodb/src/test/java/com/google/cloud/teleport/v2/templates/PubSubToMongoDBTest.java
Labels: size/XL

#1025 Fix DLQ folder to poll for BigtableChangeStreamsToPubSubIT
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/TemplateTestBase.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstopubsub/BigtableChangeStreamsToPubSubIT.java
Labels: size/S

#1026 Use static instances on Bigtable CDC tests
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/bigtable/BigtableResourceManager.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstobigquery/BigtableChangeStreamsToBigQueryIT.java
Labels: size/L

#1033 Spotless apply
  plugins/core-plugin/src/main/java/com/google/cloud/teleport/plugin/docs/TemplateDocsUtils.java
Labels: size/XS

#1035 Remove preview flag from BigQuery to Bigtable and Pub/Sub to Splunk
  v1/src/main/java/com/google/cloud/teleport/templates/PubSubToSplunk.java
  v2/bigquery-to-bigtable/src/main/java/com/google/cloud/teleport/v2/templates/BigQueryToBigtable.java
Labels: size/XS

#1014 Amended template readme to include data divergence scenario
  v2/bigtable-changestreams-to-hbase/README.md
Labels: Google LGTM, size/M

#1036 Creating JdbcToPubsubAuto
  metadata/src/main/java/com/google/cloud/teleport/metadata/auto/AutoTemplate.java
  plugins/core-plugin/src/main/java/com/google/cloud/teleport/plugin/model/TemplateDefinitions.java
  v2/common/src/main/java/com/google/cloud/teleport/v2/auto/blocks/ReadFromJdbc.java
  v2/common/src/main/java/com/google/cloud/teleport/v2/auto/blocks/WriteToPubSub.java
  v2/common/src/main/java/com/google/cloud/teleport/v2/auto/options/ReadFromJdbcOptions.java
  v2/common/src/main/java/com/google/cloud/teleport/v2/auto/options/package-info.java
  v2/jdbc-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/JdbcToPubSubAuto.java
  v2/jdbc-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/JdbcToPubSubAutoIT.java
Labels: size/L

#810 Use longer messages for tests writing to Pub/Sub
  v1/src/test/java/com/google/cloud/teleport/templates/PubSubToPubSubIT.java
  v1/src/test/java/com/google/cloud/teleport/templates/TextToPubsubIT.java
  v2/jdbc-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/JdbcToPubsubIT.java
Labels: size/M

#1040 Beam Quest Update
  README.md
Labels: Google LGTM, size/XS

#791 PubSubToDatadog: Integration Tests
  it/datadog/pom.xml
  it/datadog/src/main/java/com/google/cloud/teleport/it/datadog/DatadogClientFactory.java
  it/datadog/src/main/java/com/google/cloud/teleport/it/datadog/DatadogLogEntry.java
  it/datadog/src/main/java/com/google/cloud/teleport/it/datadog/DatadogResourceManager.java
  it/datadog/src/main/java/com/google/cloud/teleport/it/datadog/DatadogResourceManagerException.java
  it/datadog/src/main/java/com/google/cloud/teleport/it/datadog/DatadogResourceManagerUtils.java
  it/datadog/src/main/java/com/google/cloud/teleport/it/datadog/conditions/DatadogLogEntriesCheck.java
  it/datadog/src/main/java/com/google/cloud/teleport/it/datadog/conditions/package-info.java
  it/datadog/src/main/java/com/google/cloud/teleport/it/datadog/matchers/DatadogAsserts.java
  it/datadog/src/main/java/com/google/cloud/teleport/it/datadog/matchers/package-info.java
  it/datadog/src/main/java/com/google/cloud/teleport/it/datadog/package-info.java
  it/datadog/src/test/java/com/google/cloud/teleport/it/datadog/DatadogResourceManagerIT.java
  it/datadog/src/test/java/com/google/cloud/teleport/it/datadog/DatadogResourceManagerTest.java
  it/datadog/src/test/java/com/google/cloud/teleport/it/datadog/DatadogResourceManagerUtilsTest.java
  it/pom.xml
  v1/pom.xml
  v1/src/test/java/com/google/cloud/teleport/templates/PubSubToDatadogIT.java
Labels: Google LGTM, size/XXL

#1041 Add randomChars to test id generation to prevent name collision
  it/common/src/main/java/org/apache/beam/it/common/utils/PipelineUtils.java
  it/common/src/test/java/org/apache/beam/it/common/utils/PipelineUtilsTest.java
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/TemplateTestBase.java
  v1/src/test/java/com/google/cloud/teleport/templates/DatastoreToTextIT.java
  v1/src/test/java/com/google/cloud/teleport/templates/PubSubSubscriptionToBigQueryIT.java
  v1/src/test/java/com/google/cloud/teleport/templates/PubSubTopicToBigQueryIT.java
  v1/src/test/java/com/google/cloud/teleport/templates/TextToDatastoreIT.java
Labels: size/M

#1039 Fix usage of static instances in Bigtable CDC to GCS tests
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstogcs/BigtableChangeStreamsToGcsIT.java
Labels: size/L

#1044 Fix typos
  it/truthmatchers/src/main/java/org/apache/beam/it/truthmatchers/LaunchInfoSubject.java
  v1/src/main/java/com/google/cloud/teleport/bigtable/CassandraKeyUtils.java
  v1/src/main/java/com/google/cloud/teleport/kafka/connector/KafkaIO.java
  v1/src/main/java/com/google/cloud/teleport/kafka/connector/KafkaRecord.java
  v1/src/main/java/com/google/cloud/teleport/kafka/connector/TimestampPolicyFactory.java
  v1/src/main/java/com/google/cloud/teleport/spanner/ddl/DdlUtilityComponents.java
  v1/src/main/java/com/google/cloud/teleport/templates/PubsubToAvro.java
  v1/src/main/java/com/google/cloud/teleport/templates/common/BigQueryDynamicConverters.java
  v1/src/main/java/com/google/cloud/teleport/templates/common/SubprocessTextTransformer.java
  v1/src/main/java/org/apache/beam/sdk/io/gcp/spanner/MutationSizeEstimator.java
  v2/common/src/main/java/com/google/cloud/teleport/v2/common/CommonTemplateJvmInitializer.java
  v2/common/src/main/java/com/google/cloud/teleport/v2/transforms/BigQueryDynamicConverters.java
  v2/common/src/main/java/com/google/cloud/teleport/v2/transforms/JavascriptDocumentTransformer.java
  v2/common/src/main/java/com/google/cloud/teleport/v2/transforms/JavascriptTextTransformer.java
  v2/common/src/main/java/com/google/cloud/teleport/v2/transforms/PythonTextTransformer.java
  v2/common/src/main/java/com/google/cloud/teleport/v2/utils/BigQueryTableCache.java
  v2/datastream-to-bigquery/src/main/java/com/google/cloud/teleport/v2/templates/BigQueryDynamicConverters.java
  v2/datastream-to-postgres/src/main/java/com/google/cloud/teleport/v2/utils/DatabaseMigrationUtils.java
  v2/datastream-to-sql/src/main/java/com/google/cloud/teleport/v2/utils/DatastreamToDML.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/PubsubToAvro.java
  v2/googlecloud-to-mongodb/src/main/java/com/google/cloud/teleport/v2/mongodb/options/BigQueryToMongoDbOptions.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/ddl/DdlUtilityComponents.java
Labels: size/M

#1045 Add instructions to work around `File too large` error when staging
  README.md
Labels: Google LGTM, size/XS

#1047 Avoid name clashing when executing same test twice
  v2/jdbc-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/JdbcToPubsubIT.java
Labels: size/XS

#1027 Clean TODOs in the pom.xml files, following Beam 2.50.0 update
  it/pom.xml
  pom.xml
  v2/googlecloud-to-googlecloud/pom.xml
Labels: size/M

#1043 Verify Neo4j connectivity early
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/database/Neo4jConnection.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/templates/GoogleCloudToNeo4j.java
Labels: Google LGTM, size/M

#1050 Avoid name clashing in subscription when executing same test twice
  v2/jdbc-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/JdbcToPubsubIT.java
Labels: size/XS

#359 Add GoogleAdsToBigQuery template
  README.md
  metadata/src/main/java/com/google/cloud/teleport/metadata/TemplateParameter.java
  metadata/src/main/java/com/google/cloud/teleport/metadata/util/MetadataUtils.java
  plugins/core-plugin/src/main/java/com/google/cloud/teleport/plugin/model/ImageSpecParameter.java
  v2/common/src/main/java/com/google/cloud/teleport/v2/utils/SchemaUtils.java
  v2/googlecloud-to-googlecloud/README_Google_Ads_to_BigQuery.md
  v2/googlecloud-to-googlecloud/pom.xml
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/GoogleAdsToBigQuery.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/transforms/GoogleAdsRowToReportRowJsonFn.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/utils/GoogleAdsRateLimitPolicyFactory.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/utils/GoogleAdsUtils.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/transforms/GoogleAdsRowToReportRowJsonFnTest.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/utils/GoogleAdsRateLimitPolicyFactoryTest.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/utils/GoogleAdsUtilsTest.java
Labels: Google LGTM, size/XXL

#1058 Add gcpTempLocation to stage command.
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/TemplateTestBase.java
Labels: Google LGTM, size/XS

#1054 Update generated documentation
  v1/README_Cloud_PubSub_to_Datadog.md
  v1/README_Cloud_PubSub_to_Splunk.md
  v1/README_Datastore_to_Datastore_Delete.md
  v1/README_Datastore_to_GCS_Text.md
  v1/README_Firestore_to_Firestore_Delete.md
  v1/README_Firestore_to_GCS_Text.md
  v1/README_GCS_Text_to_BigQuery.md
  v1/README_GCS_Text_to_Datastore.md
  v1/README_GCS_Text_to_Firestore.md
  v1/README_PubSub_Subscription_to_BigQuery.md
  v1/README_PubSub_to_BigQuery.md
  v1/README_Stream_GCS_Text_to_BigQuery.md
  v2/datastream-to-spanner/README_Cloud_Datastream_to_Spanner.md
  v2/gcs-to-sourcedb/README_GCS_to_Sourcedb.md
  v2/googlecloud-to-googlecloud/README_Google_Ads_to_BigQuery.md
  v2/googlecloud-to-googlecloud/README_Spanner_Change_Streams_to_PubSub.md
  v2/pubsub-to-redis/README_Cloud_PubSub_to_Redis.md
  v2/spanner-change-streams-to-sharded-file-sink/README_Spanner_Change_Streams_to_Sharded_File_Sink.md
  v2/streaming-data-generator/README_Streaming_Data_Generator.md
Labels: size/L

#1060 Change default from 60 to 0 after impl change
  v1/src/main/java/com/google/cloud/teleport/templates/common/JavascriptTextTransformer.java
  v2/common/src/main/java/com/google/cloud/teleport/v2/transforms/JavascriptTextTransformer.java
Labels: size/XS

#1059 Split GoogleAdsToBigQuery to a dedicated module, reduce overall JAR size
  v2/google-ads-to-googlecloud/README_Google_Ads_to_BigQuery.md
  v2/google-ads-to-googlecloud/pom.xml
  v2/google-ads-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/GoogleAdsToBigQuery.java
  v2/google-ads-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/package-info.java
  v2/google-ads-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/transforms/GoogleAdsRowToReportRowJsonFn.java
  v2/google-ads-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/transforms/package-info.java
  v2/google-ads-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/utils/GoogleAdsRateLimitPolicyFactory.java
  v2/google-ads-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/utils/GoogleAdsUtils.java
  v2/google-ads-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/utils/package-info.java
  v2/google-ads-to-googlecloud/src/main/resources/google-ads-to-bigquery-command-spec.json
  v2/google-ads-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/transforms/GoogleAdsRowToReportRowJsonFnTest.java
  v2/google-ads-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/utils/GoogleAdsRateLimitPolicyFactoryTest.java
  v2/google-ads-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/utils/GoogleAdsUtilsTest.java
  v2/googlecloud-to-googlecloud/pom.xml
  v2/pom.xml
Labels: size/L

#1046 Add support for boolean properties
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/helpers/MappingMapper.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/job/Mapping.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/templates/GoogleCloudToNeo4j.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/utils/DataCastingUtils.java
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/model/helpers/MappingMapperTest.java
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/templates/PropertyMappingsIT.java
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/utils/DataCastingUtilsTest.java
  v2/googlecloud-to-neo4j/src/test/resources/testing-specs/property-mappings/booleans-bq-spec.json
  v2/googlecloud-to-neo4j/src/test/resources/testing-specs/property-mappings/booleans-text-spec.json
Labels: Google LGTM, size/XL

#1063 Override tempLocation when gcpTempLocation is passed
  plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesStageMojo.java
Labels: size/XS

#1062 Post sync to beam it framework
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/bigtable/BigtableResourceManager.java
  it/google-cloud-platform/src/main/resources/test-artifact.json
  it/google-cloud-platform/src/main/resources/test-artifact.txt
  it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/storage/GcsResourceManagerTest.java
  it/neo4j/src/test/java/org/apache/beam/it/neo4j/Neo4jResourceManagerIT.java
  it/neo4j/src/test/java/org/apache/beam/it/neo4j/Neo4jResourceManagerTest.java
  it/neo4j/src/test/java/org/apache/beam/it/neo4j/Neo4jResourceManagerUtilsTest.java
  it/splunk/src/main/java/org/apache/beam/it/splunk/SplunkClientFactory.java
  it/splunk/src/main/java/org/apache/beam/it/splunk/SplunkContainer.java
  it/splunk/src/main/java/org/apache/beam/it/splunk/SplunkResourceManagerException.java
  it/splunk/src/main/java/org/apache/beam/it/splunk/SplunkResourceManagerUtils.java
  it/splunk/src/main/java/org/apache/beam/it/splunk/conditions/SplunkEventsCheck.java
  it/splunk/src/main/java/org/apache/beam/it/splunk/matchers/SplunkAsserts.java
  it/splunk/src/test/java/org/apache/beam/it/splunk/SplunkResourceManagerIT.java
  it/splunk/src/test/java/org/apache/beam/it/splunk/SplunkResourceManagerTest.java
  it/splunk/src/test/java/org/apache/beam/it/splunk/SplunkResourceManagerUtilsTest.java
  it/testcontainers/src/main/java/org/apache/beam/it/testcontainers/TestContainerResourceManagerException.java
  it/testcontainers/src/main/java/org/apache/beam/it/testcontainers/TestContainersIntegrationTest.java
Labels: Google LGTM, size/S

#1064 Make launcher methods public in load test base classes.
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/IOLoadTestBase.java
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/LoadTestBase.java
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/TemplateLoadTestBase.java
Labels: Google LGTM, size/XS

#1066 Fix the check for non-initialized clusters when using static instances
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/bigtable/BigtableResourceManager.java
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/bigtable/BigtableResourceManagerUtils.java
  it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/bigtable/BigtableResourceManagerTest.java
Labels: Google LGTM, size/S

#1061 SpannerIO load test
  it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/bigtable/BigTableIOLT.java
  it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/spanner/SpannerIOLT.java
Labels: Google LGTM, size/L

#1069 Handle duplications when finalizing the release
  plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesReleaseFinishMojo.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/PubSubToBigQueryAuto.java
  v2/jdbc-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/JdbcToPubSubAuto.java
Labels: size/M

#1070 Ignore hidden templates in release artifacts
  plugins/core-plugin/src/main/java/com/google/cloud/teleport/plugin/model/ImageSpecMetadata.java
  plugins/core-plugin/src/main/java/com/google/cloud/teleport/plugin/model/TemplateDefinitions.java
  plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesReleaseFinishMojo.java
Labels: size/S

#1071 Fix enum field names to match UI format
  plugins/core-plugin/src/main/java/com/google/cloud/teleport/plugin/model/ImageSpecParameterEnumOption.java
Labels: size/S

#1074 Prepare Jdbc to BigQuery (Flex) metadata for public documentation
  plugins/core-plugin/src/main/java/com/google/cloud/teleport/plugin/docs/TemplateDocsUtils.java
  v1/src/main/java/com/google/cloud/teleport/templates/JdbcToBigQuery.java
  v2/common/src/main/java/com/google/cloud/teleport/v2/options/CommonTemplateOptions.java
  v2/jdbc-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/options/JdbcToBigQueryOptions.java
  v2/jdbc-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/JdbcToBigQuery.java
Labels: size/M

#1073 Fix racing during tear down on Neo4j IT
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/templates/PropertyMappingsIT.java
Labels: size/XS

#1067 Add documentation details to Google Ads to BigQuery template
  v2/google-ads-to-googlecloud/README_Google_Ads_to_BigQuery.md
  v2/google-ads-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/GoogleAdsToBigQuery.java
Labels: size/S

#1080 Use waitUntilDone instead of Finish, as batch jobs can not be drained
  v1/src/test/java/com/google/cloud/teleport/templates/JdbcToBigQueryIT.java
  v2/jdbc-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/JdbcToBigQueryIT.java
  v2/mysql-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/MySQLToBigQueryIT.java
  v2/postgresql-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/PostgreSQLToBigQueryIT.java
  v2/sqlserver-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/SQLServerToBigQueryIT.java
Labels: size/S

#1081 [Bigtable CDC] Add random string on app profile id to increase entropy
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstobigquery/BigtableChangeStreamsToBigQueryIT.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstogcs/BigtableChangeStreamsToGcsIT.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstopubsub/BigtableChangeStreamsToPubSubIT.java
Labels: size/XS

#1082 Hide some templates from UI to match current releases.
  plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesReleaseFinishMojo.java
  python/src/main/java/com/google/cloud/teleport/templates/python/StreamingLLM.java
  python/src/main/java/com/google/cloud/teleport/templates/python/WordCountPython.java
  v2/azure-eventhub-to-pubsub/src/main/java/com/google/cloud/teleport/v2/templates/AzureEventhubToPubsub.java
  v2/gcs-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/GCSToSourceDb.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/DLPTextToBigQueryStreaming.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstobigquery/BigtableChangeStreamsToBigQuery.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstopubsub/BigtableChangeStreamsToPubSub.java
  v2/googlecloud-to-splunk/src/main/java/com/google/cloud/teleport/v2/templates/GCSToSplunk.java
  v2/kafka-to-gcs/src/main/java/com/google/cloud/teleport/v2/templates/KafkaToGCS.java
  v2/kinesis-to-pubsub/src/main/java/com/google/cloud/teleport/v2/templates/KinesisToPubsub.java
  v2/ordered-changestream-buffer-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/OrderedChangestreamBufferToSourceDb.java
  v2/pubsub-cdc-to-bigquery/src/main/java/com/google/cloud/teleport/v2/templates/PubSubCdcToBigQuery.java
  v2/pubsub-to-jms/src/main/java/com/google/cloud/teleport/v2/templates/PubsubToJms.java
  v2/pubsub-to-kafka/src/main/java/com/google/cloud/teleport/v2/templates/PubsubToKafka.java
  v2/spanner-change-streams-to-sharded-file-sink/src/main/java/com/google/cloud/teleport/v2/templates/SpannerChangeStreamsToShardedFileSink.java
  v2/spanner-change-streams-to-sink/src/main/java/com/google/cloud/teleport/v2/templates/SpannerChangeStreamsToSink.java
  v2/sqlserver-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/SQLServerToBigQuery.java
  v2/streaming-data-generator/src/main/java/com/google/cloud/teleport/v2/templates/StreamingDataGenerator.java
Labels: Google LGTM, size/M
