Repository GoogleCloudPlatform/DataflowTemplates, pull requests merged in 2023-06, with the labels that each got.

#753 Fix PubsubDlqIT test
  syndeo-template/src/test/java/com/google/cloud/syndeo/it/PubsubDlqIT.java
Labels: size/XS

#756 Spanner Vertex AI Integration: Add support for required columns.
  v1/src/main/java/com/google/cloud/teleport/spanner/ddl/ModelColumn.java
  v1/src/test/java/com/google/cloud/teleport/spanner/AvroSchemaToDdlConverterTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/DdlToAvroSchemaConverterTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ddl/DdlTest.java
Labels: size/M

#714 Added Capability to Parse Nest Json Configs
  syndeo-template/src/main/java/com/google/cloud/syndeo/SyndeoTemplate.java
Labels: size/M

#754 Add command spec file to syndeo template
  syndeo-template/src/main/resources/syndeo-template-command-spec.json
Labels: size/XS

#758 Fix Splunk RM Hec Token Generator
  it/splunk/src/main/java/com/google/cloud/teleport/it/splunk/SplunkResourceManagerUtils.java
Labels: size/S

#761 Added SpannerChangestreamsReadSchemaTransformProvider to supported urns
  syndeo-template/pom.xml
  syndeo-template/src/main/java/com/google/cloud/syndeo/SyndeoTemplate.java
Labels: size/XS

#737 Add column alias test cases to JdbcToBigQueryIT's
  v1/src/test/java/com/google/cloud/teleport/templates/JdbcToBigQueryIT.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/JdbcToBigQueryIT.java
Labels: size/M

#738 Introduce `PubSubToDatadog` classic template
  v1/README_Cloud_PubSub_to_Datadog.md
  v1/src/main/java/com/google/cloud/teleport/datadog/DatadogEvent.java
  v1/src/main/java/com/google/cloud/teleport/datadog/DatadogEventCoder.java
  v1/src/main/java/com/google/cloud/teleport/datadog/DatadogEventPublisher.java
  v1/src/main/java/com/google/cloud/teleport/datadog/DatadogEventWriter.java
  v1/src/main/java/com/google/cloud/teleport/datadog/DatadogIO.java
  v1/src/main/java/com/google/cloud/teleport/datadog/DatadogWriteError.java
  v1/src/main/java/com/google/cloud/teleport/datadog/DatadogWriteErrorCoder.java
  v1/src/main/java/com/google/cloud/teleport/datadog/package-info.java
  v1/src/main/java/com/google/cloud/teleport/templates/PubSubToDatadog.java
  v1/src/main/java/com/google/cloud/teleport/templates/common/DatadogApiKeySource.java
  v1/src/main/java/com/google/cloud/teleport/templates/common/DatadogConverters.java
  v1/src/main/java/com/google/cloud/teleport/util/DatadogApiKeyNestedValueProvider.java
  v1/src/test/java/com/google/cloud/teleport/datadog/DatadogEventCoderTest.java
  v1/src/test/java/com/google/cloud/teleport/datadog/DatadogEventPublisherTest.java
  v1/src/test/java/com/google/cloud/teleport/datadog/DatadogEventTest.java
  v1/src/test/java/com/google/cloud/teleport/datadog/DatadogEventWriterTest.java
  v1/src/test/java/com/google/cloud/teleport/datadog/DatadogIOTest.java
  v1/src/test/java/com/google/cloud/teleport/datadog/DatadogWriteErrorCoderTest.java
  v1/src/test/java/com/google/cloud/teleport/datadog/DatadogWriteErrorTest.java
  v1/src/test/java/com/google/cloud/teleport/templates/PubsubToDatadogTest.java
  v1/src/test/java/com/google/cloud/teleport/templates/common/DatadogConvertersTest.java
  v1/src/test/java/com/google/cloud/teleport/util/DatadogApiKeyNestedValueProviderTest.java
Labels: Google LGTM, size/XXL

#755 [Load Tests] Add end-to-end latency metric for Pub/Sub to BigQuery Steady State test.
  v1/pom.xml
  v1/src/test/java/com/google/cloud/teleport/templates/PubsubToBigQueryLT.java
Labels: size/M

#751 [Integration Tests] Add Spanner ChangeStreams to Pubsub IT
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/SpannerChangeStreamsToGcsIT.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/SpannerChangeStreamsToPubSubIT.java
Labels: size/L

#767 Add enable_cleanup_state experiment to have batch tests finishing faster
  it/common/src/main/java/com/google/cloud/teleport/it/common/PipelineLauncher.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/TemplateTestBase.java
Labels: size/XS

#765 [Load Tests] Calculate metrics from worker start time to worker stop time.
  it/common/src/main/java/com/google/cloud/teleport/it/common/AbstractPipelineLauncher.java
  it/common/src/main/java/com/google/cloud/teleport/it/common/PipelineLauncher.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/LoadTestBase.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/dataflow/DirectRunnerClient.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/monitoring/MonitoringClient.java
Labels: size/L

#776 [Integration tests] Add Pub/Sub subscription to Avro integration test.
  v1/src/test/java/com/google/cloud/teleport/templates/PubSubToAvroIT.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/PubSubToAvroIT.java
Labels: size/M

#760 Add TextToBigQueryStreamLT
  v1/src/test/java/com/google/cloud/teleport/templates/TextToBigQueryStreamLT.java
Labels: Google LGTM, size/L

#684 Added TextToPubSubStream template Load Test
  v1/src/test/java/com/google/cloud/teleport/templates/TextToPubsubStreamLT.java
Labels: Google LGTM, size/L

#777 [Integration Tests] Add SkipDirectRunnerTest on ImportJobIT due to flakiness
  v1/src/test/java/com/google/cloud/teleport/templates/ImportJobIT.java
Labels: size/XS

#774 Remove resource cleaning up from list of done states, move to finishing
  it/common/src/main/java/com/google/cloud/teleport/it/common/PipelineLauncher.java
Labels: size/XS

#759 Add BigTableIOLT
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/bigtable/BigtableResourceManager.java
  it/google-cloud-platform/src/test/java/com/google/cloud/teleport/it/gcp/bigtable/BigTableIOLT.java
Labels: Google LGTM, size/L

#773 Cleaning up syndeo-template/pom.xml
  syndeo-template/pom.xml
Labels: size/M

#780 Bigtable change stream to Hbase replicator template
  v2/bigtable-cdc-to-hbase/README.md
  v2/bigtable-cdc-to-hbase/pom.xml
  v2/bigtable-cdc-to-hbase/src/main/java/com/google/cloud/teleport/v2/templates/BigtableCdcToHbase.java
  v2/bigtable-cdc-to-hbase/src/main/java/com/google/cloud/teleport/v2/templates/package-info.java
  v2/bigtable-cdc-to-hbase/src/main/java/com/google/cloud/teleport/v2/templates/transforms/ChangeStreamToRowMutations.java
  v2/bigtable-cdc-to-hbase/src/main/java/com/google/cloud/teleport/v2/templates/transforms/package-info.java
  v2/bigtable-cdc-to-hbase/src/main/java/com/google/cloud/teleport/v2/templates/utils/RowMutationsBuilder.java
  v2/bigtable-cdc-to-hbase/src/main/java/com/google/cloud/teleport/v2/templates/utils/package-info.java
  v2/bigtable-cdc-to-hbase/src/test/java/com/google/cloud/bigtable/data/v2/models/ChangeStreamMutationBuilder.java
  v2/bigtable-cdc-to-hbase/src/test/java/com/google/cloud/teleport/v2/templates/ChangeStreamToRowMutationsTest.java
  v2/bigtable-cdc-to-hbase/src/test/java/com/google/cloud/teleport/v2/templates/RowMutationsBuilderTest.java
  v2/bigtable-cdc-to-hbase/src/test/java/com/google/cloud/teleport/v2/templates/package-info.java
  v2/bigtable-cdc-to-hbase/src/test/java/com/google/cloud/teleport/v2/templates/utils/HashUtils.java
  v2/bigtable-cdc-to-hbase/src/test/java/com/google/cloud/teleport/v2/templates/utils/HbaseUtils.java
  v2/bigtable-cdc-to-hbase/src/test/java/com/google/cloud/teleport/v2/templates/utils/TestConstants.java
  v2/pom.xml
Labels: Google LGTM, size/XXL

#785 [Load tests] Add load test tutorial.
  tutorials/README.md
  tutorials/load-test.md
Labels: size/XL

#781 [Bug]: TextToPubsubLT and TextToBigQueryLT jobs aren't drained
  v1/src/test/java/com/google/cloud/teleport/templates/TextToBigQueryStreamLT.java
  v1/src/test/java/com/google/cloud/teleport/templates/TextToPubsubStreamLT.java
Labels: Google LGTM, size/M

#787 Updated readme with bidirectional replication notes and notes on hbas…
  v2/bigtable-cdc-to-hbase/README.md
  v2/bigtable-cdc-to-hbase/src/main/java/com/google/cloud/teleport/v2/templates/BigtableCdcToHbase.java
Labels: Google LGTM, size/M

#789 [Integration Tests] Add debezium-bigquery ITs
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/pubsub/PubsubResourceManager.java
  it/google-cloud-platform/src/test/java/com/google/cloud/teleport/it/gcp/pubsub/PubsubResourceManagerTest.java
  v2/bigtable-cdc-to-hbase/README.md
  v2/cdc-parent/cdc-change-applier/src/test/java/com/google/cloud/dataflow/cdc/applier/CdcToBigQueryChangeApplierPipelineIT.java
  v2/cdc-parent/cdc-common/src/main/java/com/google/cloud/dataflow/cdc/common/DataCatalogSchemaUtils.java
  v2/cdc-parent/pom.xml
Labels: size/L

#796 Guard enable_cleanup_state behind a user option (-DenableCleanupState)
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/TemplateTestBase.java
Labels: size/M

#794 Fix CdcToBigQueryChangeApplierPipelineIT for concurrent tests
  v2/cdc-parent/cdc-change-applier/src/test/java/com/google/cloud/dataflow/cdc/applier/CdcToBigQueryChangeApplierPipelineIT.java
Labels: size/XS

#795 Change fileNamePrefix to match annotations in the same module
  v1/src/main/java/com/google/cloud/teleport/bigtable/BigtableToAvro.java
  v1/src/main/java/com/google/cloud/teleport/bigtable/BigtableToParquet.java
Labels: size/XS

#596 Issue 477: Create Datastream Resource Manager
  it/google-cloud-platform/pom.xml
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/datastream/DatastreamResourceManager.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/datastream/DatastreamResourceManagerException.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/datastream/JDBCSource.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/datastream/MySQLSource.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/datastream/OracleSource.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/datastream/PostgresqlSource.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/datastream/package-info.java
  it/google-cloud-platform/src/test/java/com/google/cloud/teleport/it/gcp/datastream/DatastreamResourceManagerTest.java
Labels: size/XXL

#798 Allow usage of arbitrary hosts in CdcToBigQueryChangeApplierPipelineIT
  v2/cdc-parent/cdc-change-applier/src/test/java/com/google/cloud/dataflow/cdc/applier/CdcToBigQueryChangeApplierPipelineIT.java
Labels: size/XS

#801 Move Java PR workflow to run on self-hosted runner
  .github/workflows/java-pr.yml
  cicd/cmd/run-build/main.go
  cicd/internal/workflows/maven-workflows.go
Labels: size/S

#803 Linearize gitactions workflows to fix build issues
  .github/workflows/java-pr.yml
Labels: size/XS

#793 [Integration Tests] Compile cdc-embedded-connector prior to executing it
  v2/cdc-parent/cdc-change-applier/src/test/java/com/google/cloud/dataflow/cdc/applier/CdcToBigQueryChangeApplierPipelineIT.java
Labels: size/XS

#808 Use named groups to fix matcher and improve readability
  v2/cdc-parent/cdc-change-applier/src/test/java/com/google/cloud/dataflow/cdc/applier/CdcToBigQueryChangeApplierPipelineIT.java
Labels: size/XS

#790 PubSubToDatadog: replace `site` parameter with `url`
  v1/README_Cloud_PubSub_to_Datadog.md
  v1/src/main/java/com/google/cloud/teleport/datadog/DatadogIO.java
  v1/src/main/java/com/google/cloud/teleport/templates/PubSubToDatadog.java
  v1/src/main/java/com/google/cloud/teleport/templates/common/DatadogConverters.java
  v1/src/test/java/com/google/cloud/teleport/datadog/DatadogIOTest.java
Labels: Google LGTM, size/L

#807 Reduce version pins for dependencies in libraries-bom
  v2/common/pom.xml
Labels: size/M

#799 Split jdbc-to-googlecloud to a separate module
  pom.xml
  v1/pom.xml
  v2/googlecloud-to-googlecloud/pom.xml
  v2/jdbc-common/pom.xml
  v2/jdbc-common/src/main/java/com/google/cloud/teleport/v2/utils/JdbcConverters.java
  v2/jdbc-common/src/main/java/com/google/cloud/teleport/v2/utils/package-info.java
  v2/jdbc-common/src/test/java/com/google/cloud/teleport/v2/utils/JdbcConvertersTest.java
  v2/jdbc-common/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
  v2/jdbc-to-googlecloud/README_Jdbc_to_BigQuery_Flex.md
  v2/jdbc-to-googlecloud/README_Jdbc_to_PubSub.md
  v2/jdbc-to-googlecloud/pom.xml
  v2/jdbc-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/options/JdbcToBigQueryOptions.java
  v2/jdbc-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/options/JdbcToPubsubOptions.java
  v2/jdbc-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/options/package-info.java
  v2/jdbc-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/JdbcToBigQuery.java
  v2/jdbc-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/JdbcToPubsub.java
  v2/jdbc-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/package-info.java
  v2/jdbc-to-googlecloud/src/main/resources/jdbc-to-bigquery-command-spec.json
  v2/jdbc-to-googlecloud/src/main/resources/jdbc-to-pubsub-command-spec.json
  v2/jdbc-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/JdbcToBigQueryIT.java
  v2/jdbc-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/JdbcToBigQueryLT.java
  v2/jdbc-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/JdbcToBigQueryTest.java
  v2/jdbc-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/JdbcToPubsubIT.java
  v2/jdbc-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/JdbcToPubsubTest.java
  v2/jdbc-to-googlecloud/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
  v2/pom.xml
Labels: size/L

#715 Add UDF Support to PubSubToMongoDBIT.java
  it/mongodb/pom.xml
  it/mongodb/src/main/java/com/google/cloud/teleport/it/mongodb/MongoDBResourceManager.java
  it/mongodb/src/main/java/com/google/cloud/teleport/it/mongodb/conditions/MongoDBDocumentsCheck.java
  it/mongodb/src/main/java/com/google/cloud/teleport/it/mongodb/conditions/package-info.java
  it/mongodb/src/main/java/com/google/cloud/teleport/it/mongodb/matchers/MongoDBAsserts.java
  it/mongodb/src/main/java/com/google/cloud/teleport/it/mongodb/matchers/package-info.java
  it/mongodb/src/test/java/com/google/cloud/teleport/it/mongodb/MongoDBResourceManagerIT.java
  it/mongodb/src/test/java/com/google/cloud/teleport/it/mongodb/MongoDBResourceManagerTest.java
  it/truthmatchers/src/main/java/com/google/cloud/teleport/it/truthmatchers/PipelineAsserts.java
  v2/pubsub-to-mongodb/src/test/java/com/google/cloud/teleport/v2/templates/PubSubToMongoDBIT.java
Labels: size/L

#762 Add deadletter and more complex test cases to PubSubToBigQueryIT (V1)
  v1/src/test/java/com/google/cloud/teleport/templates/PubSubToBigQueryIT.java
Labels: size/L

#814 Add explicit junit dependency in pubsub-to-jms module
  v2/pubsub-to-jms/pom.xml
Labels: size/XS

#818 Skip jib (Docker image builder) for common modules
  v2/bigtable-common/pom.xml
  v2/common/pom.xml
  v2/elasticsearch-common/pom.xml
  v2/kafka-common/pom.xml
  v2/spanner-common/pom.xml
Labels: size/S

#817 Ignore color output sent by mvn command
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/JDBCBaseIT.java
Labels: size/XS

#778 Add PubSub Proto To BigQuery IT's
  it/conditions/src/main/java/com/google/cloud/teleport/it/conditions/ConditionCheck.java
  it/truthmatchers/src/main/java/com/google/cloud/teleport/it/truthmatchers/RecordsSubject.java
  v2/common/pom.xml
  v2/pom.xml
  v2/pubsub-binary-to-bigquery/src/test/java/com/google/cloud/teleport/v2/templates/PubsubProtoToBigQueryIT.java
  v2/pubsub-binary-to-bigquery/src/test/proto/User.proto
  v2/pubsub-binary-to-bigquery/src/test/resources/PubSubProtoToBigQueryIT/BigQuerySchema.json
  v2/pubsub-binary-to-bigquery/src/test/resources/PubSubProtoToBigQueryIT/BigQuerySchemaPreserved.json
  v2/pubsub-binary-to-bigquery/src/test/resources/protobuf/schema/proto_schema.pb
Labels: size/XL

#820 Reduce verbosity of integration test logs
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/dataflow/AbstractPipelineLauncher.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/dataflow/ClassicTemplateClient.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/dataflow/DefaultPipelineLauncher.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/dataflow/FlexTemplateClient.java
Labels: size/M

#822 Fix pubsub-to-jms dependencies, and split testcases into smaller units
  v2/jms-to-pubsub/src/test/java/com/google/cloud/teleport/v2/templates/JmsToPubsubIT.java
  v2/pubsub-to-jms/pom.xml
  v2/pubsub-to-jms/src/test/java/com/google/cloud/teleport/v2/templates/PubsubToJmsIT.java
Labels: size/L

#824 Embed the Debezium connector in the CDC integration tests
  v2/cdc-parent/cdc-change-applier/pom.xml
  v2/cdc-parent/cdc-change-applier/src/main/java/com/google/cloud/dataflow/cdc/applier/BigQueryStatementIssuingFn.java
  v2/cdc-parent/cdc-change-applier/src/test/java/com/google/cloud/dataflow/cdc/applier/CdcToBigQueryChangeApplierPipelineIT.java
  v2/cdc-parent/cdc-embedded-connector/src/main/java/com/google/cloud/dataflow/cdc/connector/App.java
  v2/cdc-parent/cdc-embedded-connector/src/main/java/com/google/cloud/dataflow/cdc/connector/DebeziumToPubSubDataSender.java
  v2/cdc-parent/pom.xml
Labels: size/L

#804 Support set pipeline name for reporting metrics
  it/common/src/main/java/com/google/cloud/teleport/it/common/PipelineLauncher.java
  it/common/src/main/java/com/google/cloud/teleport/it/common/utils/PipelineUtils.java
  it/common/src/test/java/com/google/cloud/teleport/it/common/utils/PipelineUtilsTest.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/LoadTestBase.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/dataflow/AbstractPipelineLauncher.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/dataflow/DefaultPipelineLauncher.java
Labels: Google LGTM, size/M

#827 Retry Spanner resource creation in case of a quota failure
  it/common/src/main/java/com/google/cloud/teleport/it/common/utils/ExceptionUtils.java
  it/common/src/test/java/com/google/cloud/teleport/it/common/utils/ExceptionUtilsTest.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/spanner/SpannerResourceManager.java
Labels: size/L

#829 Add BigQueryToTFRecordIT
  v1/src/test/java/com/google/cloud/teleport/templates/BigQueryToTFRecordIT.java
  v1/src/test/resources/BigQueryToTFRecordIT/output.tfrecord
Labels: size/M

#830 [Tech Debt] Fix bad/missing declarations in JavaDocs
  it/google-cloud-platform/src/test/java/com/google/cloud/teleport/it/gcp/bigtable/BigtableResourceManagerClusterTest.java
  v1/src/main/java/com/google/cloud/teleport/bigtable/CassandraRowMapperFn.java
  v1/src/main/java/com/google/cloud/teleport/bigtable/CassandraToBigtable.java
  v1/src/main/java/com/google/cloud/teleport/spanner/TextSource.java
  v1/src/main/java/com/google/cloud/teleport/spanner/ddl/IndexColumn.java
  v1/src/main/java/com/google/cloud/teleport/splunk/SplunkIO.java
  v1/src/main/java/com/google/cloud/teleport/templates/common/BigQueryConverters.java
  v1/src/main/java/com/google/cloud/teleport/templates/common/SubprocessTextTransformer.java
  v1/src/main/java/org/apache/beam/sdk/io/gcp/spanner/LocalSpannerIO.java
  v2/common/src/main/java/com/google/cloud/teleport/v2/cdc/mappers/BigQueryMapper.java
  v2/common/src/main/java/com/google/cloud/teleport/v2/cdc/mappers/BigQueryTableRowCleaner.java
  v2/common/src/main/java/com/google/cloud/teleport/v2/cdc/merge/BigQueryMerger.java
  v2/common/src/main/java/com/google/cloud/teleport/v2/cdc/sources/ReadFileRangesFn.java
  v2/common/src/main/java/com/google/cloud/teleport/v2/transforms/FormatDatastreamRecord.java
  v2/common/src/main/java/com/google/cloud/teleport/v2/transforms/PubSubToFailSafeElement.java
  v2/common/src/main/java/com/google/cloud/teleport/v2/transforms/PythonTextTransformer.java
  v2/common/src/main/java/com/google/cloud/teleport/v2/transforms/UDFTextTransformer.java
  v2/common/src/main/java/com/google/cloud/teleport/v2/utils/GCSUtils.java
  v2/common/src/main/java/com/google/cloud/teleport/v2/utils/MappedObjectCache.java
  v2/common/src/test/java/com/google/cloud/teleport/v2/transforms/PythonTextTransformerTest.java
  v2/common/src/test/java/com/google/cloud/teleport/v2/utils/DataStreamClientTest.java
  v2/common/src/test/java/com/google/cloud/teleport/v2/utils/GCSUtilsTest.java
  v2/datastream-to-bigquery/src/test/java/com/google/cloud/teleport/v2/templates/BigQueryDeadLetterQueueSanitizerTest.java
  v2/datastream-to-postgres/src/main/java/com/google/cloud/teleport/v2/transforms/CreateDml.java
  v2/datastream-to-postgres/src/test/java/com/google/cloud/teleport/v2/utils/DatabaseMigrationUtilsTest.java
  v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/SpannerTransactionWriter.java
  v2/datastream-to-sql/src/main/java/com/google/cloud/teleport/v2/io/CdcJdbcIO.java
  v2/datastream-to-sql/src/test/java/com/google/cloud/teleport/v2/utils/DatastreamToDMLTest.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/spannerchangestreamstobigquery/schemautils/SpannerUtils.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/transforms/FileFormatFactorySpannerChangeStreams.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/transforms/FileFormatFactorySpannerChangeStreamsToPubSub.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/transforms/WriteDataChangeRecordsToAvro.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/transforms/WriteDataChangeRecordsToGcsAvro.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/utils/JdbcIngestionWriteDisposition.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/SpannerChangeStreamsToGcsTest.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/SpannerChangeStreamsToPubSubTest.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/transforms/WriteDataChangeRecordsToJsonTest.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/values/BigQueryTablePartitionTest.java
  v2/googlecloud-to-mongodb/src/main/java/com/google/cloud/teleport/v2/mongodb/options/BigQueryToMongoDbOptions.java
  v2/googlecloud-to-splunk/src/main/java/com/google/cloud/teleport/v2/transforms/SplunkConverters.java
  v2/kafka-common/src/test/java/com/google/cloud/teleport/v2/kafka/utils/KafkaCommonUtilsTest.java
  v2/kafka-to-bigquery/src/main/java/com/google/cloud/teleport/v2/templates/KafkaToBigQuery.java
  v2/pubsub-cdc-to-bigquery/src/main/java/com/google/cloud/teleport/v2/templates/PubSubCdcToBigQuery.java
Labels: size/L
