Repository GoogleCloudPlatform/DataflowTemplates, pull requests merged in 2023-07, with the labels that each got.

#834 DLP resource manager + DLP Text to BigQuery integration tests
  it/google-cloud-platform/pom.xml
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/bigquery/BigQueryResourceManager.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/dlp/DlpResourceManager.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/dlp/package-info.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/DLPTextToBigQueryStreaming.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/DLPTextToBigQueryStreamingIT.java
Labels: size/L

#837 Clarify "the runner" -> "Dataflow" in template options
  v1/README_Cloud_Bigtable_to_GCS_Parquet.md
  v1/src/main/java/com/google/cloud/teleport/bigtable/BigtableToParquet.java
  v1/src/main/java/com/google/cloud/teleport/kafka/connector/KafkaIO.java
  v2/common/src/main/java/com/google/cloud/teleport/v2/transforms/AvroConverters.java
  v2/common/src/main/java/com/google/cloud/teleport/v2/transforms/ParquetConverters.java
  v2/common/src/main/java/com/google/cloud/teleport/v2/transforms/WriteToGCSAvro.java
  v2/common/src/main/java/com/google/cloud/teleport/v2/transforms/WriteToGCSParquet.java
  v2/file-format-conversion/README_File_Format_Conversion.md
  v2/streaming-data-generator/README_Streaming_Data_Generator.md
  v2/streaming-data-generator/src/main/java/com/google/cloud/teleport/v2/templates/StreamingDataGenerator.java
Labels: size/S

#839 Reduce tech debt / fix up some javadocs in the `it` modules
  it/cassandra/src/main/java/com/google/cloud/teleport/it/cassandra/CassandraResourceManagerUtils.java
  it/cassandra/src/main/java/com/google/cloud/teleport/it/cassandra/matchers/CassandraAsserts.java
  it/common/src/main/java/com/google/cloud/teleport/it/common/PipelineOperator.java
  it/common/src/main/java/com/google/cloud/teleport/it/common/ResourceManager.java
  it/common/src/main/java/com/google/cloud/teleport/it/common/utils/IORedirectUtil.java
  it/common/src/main/java/com/google/cloud/teleport/it/common/utils/MetricsConfiguration.java
  it/common/src/main/java/com/google/cloud/teleport/it/common/utils/PipelineUtils.java
  it/common/src/main/java/com/google/cloud/teleport/it/common/utils/RetryUtil.java
  it/elasticsearch/src/main/java/com/google/cloud/teleport/it/elasticsearch/ElasticsearchResourceManager.java
  it/elasticsearch/src/main/java/com/google/cloud/teleport/it/elasticsearch/ElasticsearchUtils.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/GoogleCloudIntegrationTest.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/IOLoadTestBase.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/TemplateLoadTestBase.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/artifacts/GcsArtifact.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/artifacts/GcsArtifactClient.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/artifacts/matchers/ArtifactAsserts.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/artifacts/matchers/ArtifactsSubject.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/artifacts/utils/ArtifactUtils.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/artifacts/utils/JsonTestUtil.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/artifacts/utils/ParquetTestUtil.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/bigquery/BigQueryResourceManagerException.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/bigquery/conditions/BigQueryRowsCheck.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/bigquery/utils/BigQueryTestUtil.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/bigtable/BigtableResourceManagerCluster.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/bigtable/BigtableResourceManagerException.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/bigtable/BigtableResourceManagerUtils.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/bigtable/BigtableTableSpec.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/bigtable/matchers/BigtableAsserts.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/dataflow/ClassicTemplateClient.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/dataflow/DirectRunnerClient.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/datagenerator/DataGenerator.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/datastore/DatastoreResourceManager.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/datastore/matchers/DatastoreAsserts.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/datastream/PostgresqlSource.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/kms/KMSResourceManager.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/kms/KMSResourceManagerException.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/pubsublite/PubsubliteResourceManager.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/spanner/utils/SpannerResourceManagerUtils.java
  it/jdbc/src/main/java/com/google/cloud/teleport/it/jdbc/JDBCDriverFactory.java
  it/jdbc/src/main/java/com/google/cloud/teleport/it/jdbc/JDBCResourceManager.java
  it/jdbc/src/main/java/com/google/cloud/teleport/it/jdbc/JDBCResourceManagerException.java
  it/jdbc/src/main/java/com/google/cloud/teleport/it/jdbc/MSSQLResourceManager.java
  it/jdbc/src/main/java/com/google/cloud/teleport/it/jdbc/PostgresResourceManager.java
  it/kafka/src/main/java/com/google/cloud/teleport/it/kafka/KafkaResourceManager.java
  it/mongodb/src/main/java/com/google/cloud/teleport/it/mongodb/matchers/MongoDBAsserts.java
  it/splunk/src/main/java/com/google/cloud/teleport/it/splunk/SplunkClientFactory.java
  it/splunk/src/main/java/com/google/cloud/teleport/it/splunk/SplunkContainer.java
  it/splunk/src/main/java/com/google/cloud/teleport/it/splunk/SplunkResourceManagerUtils.java
  it/splunk/src/main/java/com/google/cloud/teleport/it/splunk/matchers/SplunkAsserts.java
Labels: size/L

#836 Fix test flakiness on the usage of CassandraResourceManager
  it/cassandra/src/main/java/com/google/cloud/teleport/it/cassandra/CassandraResourceManager.java
  v1/src/main/java/com/google/cloud/teleport/bigtable/BeamRowToBigtableFn.java
  v1/src/main/java/com/google/cloud/teleport/bigtable/ParquetToBigtable.java
Labels: size/S

#838 Enforce non-vulnerable version of jettison dependency
  pom.xml
Labels: size/XS

#846 Remove duplicated README file
  v2/pubsub-to-jms/README_PubSub_to_Jms.md
Labels: size/L

#812 Add MySQL to BigQuery template (branding of JDBC to BigQuery)
  plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesStageMojo.java
  v1/src/test/java/com/google/cloud/teleport/templates/JdbcToBigQueryIT.java
  v2/jdbc-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/JdbcToBigQuery.java
  v2/jdbc-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/JdbcToBigQueryIT.java
  v2/jdbc-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/JdbcToPubsubIT.java
  v2/mysql-to-googlecloud/pom.xml
  v2/mysql-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/options/MySQLToBigQueryOptions.java
  v2/mysql-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/options/package-info.java
  v2/mysql-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/MySQLToBigQuery.java
  v2/mysql-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/package-info.java
  v2/mysql-to-googlecloud/src/main/resources/mysql-to-bigquery-command-spec.json
  v2/mysql-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/MySQLToBigQueryIT.java
  v2/pom.xml
Labels: size/L

#856 Add group name to metadata annotations
  metadata/src/main/java/com/google/cloud/teleport/metadata/TemplateParameter.java
  plugins/core-plugin/src/main/java/com/google/cloud/teleport/plugin/model/ImageSpecParameter.java
  v2/jdbc-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/options/JdbcToBigQueryOptions.java
Labels: size/L

#855 Do not fail validation on branded template (hidden parameter)
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/dataflow/DirectRunnerClient.java
Labels: size/XS

#857 Converge hbase dependencies at bigtable-common, and exclude htrace transient dependency
  v2/bigtable-cdc-to-hbase/pom.xml
  v2/bigtable-common/pom.xml
Labels: size/S

#845 Fix mix-up between Neo4j node/edge batch size/parallelism init
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/job/Config.java
Labels: Google LGTM, size/S

#859 Add annotation to ignore parameters without failing validation targets
  metadata/src/main/java/com/google/cloud/teleport/metadata/TemplateIgnoreParameter.java
  plugins/core-plugin/src/main/java/com/google/cloud/teleport/plugin/model/TemplateDefinitions.java
  v2/mysql-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/options/MySQLToBigQueryOptions.java
Labels: size/M

#860 Add Hbase testing dependencies in the submodule
  pom.xml
  v2/bigtable-cdc-to-hbase/pom.xml
  v2/bigtable-common/pom.xml
Labels: size/S

#864 Do not share resources across managers (avoid ConcurrentModificationE…
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/dlp/DlpResourceManager.java
Labels: size/S

#865 Always rebuild `it` module if common module was changed
  cicd/internal/workflows/maven-workflows.go
Labels: size/XS

#870 Add synchronized annotation to cleanupAll for PipelineLaunchers
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/dataflow/AbstractPipelineLauncher.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/dataflow/DirectRunnerClient.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/pubsub/PubsubResourceManager.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/storage/GcsResourceManager.java
Labels: size/M

#871 Add PostgreSQL to BigQuery template, based on Jdbc to BigQuery (branded template)
  v2/pom.xml
  v2/postgresql-to-googlecloud/pom.xml
  v2/postgresql-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/options/PostgreSQLToBigQueryOptions.java
  v2/postgresql-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/options/package-info.java
  v2/postgresql-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/PostgreSQLToBigQuery.java
  v2/postgresql-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/package-info.java
  v2/postgresql-to-googlecloud/src/main/resources/postgresql-to-bigquery-command-spec.json
  v2/postgresql-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/PostgreSQLToBigQueryIT.java
Labels: size/L

#874 Reduce the test name to fulfill the 30 chars limit
  v2/postgresql-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/PostgreSQLToBigQueryIT.java
Labels: size/XS

#862 Upload test results after JUnit runs
  .github/workflows/java-pr-report.yml
  .github/workflows/java-pr.yml
  v2/mysql-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/MySQLToBigQuery.java
Labels: size/S

#851 [PubSubToDatadog] Add origin header
  v1/src/main/java/com/google/cloud/teleport/datadog/DatadogEventPublisher.java
  v1/src/test/java/com/google/cloud/teleport/datadog/DatadogEventPublisherTest.java
  v1/src/test/java/com/google/cloud/teleport/datadog/DatadogEventWriterTest.java
  v1/src/test/java/com/google/cloud/teleport/datadog/DatadogIOTest.java
Labels: Google LGTM, size/M

#853 [PubSubToDatadog] Retry 408 and 429 in addition to 5xx
  v1/src/main/java/com/google/cloud/teleport/datadog/DatadogEventPublisher.java
  v1/src/test/java/com/google/cloud/teleport/datadog/DatadogEventWriterTest.java
Labels: Google LGTM, size/L

#854 [PubSubToDatadog] Modify default batch count, add minimum
  v1/src/main/java/com/google/cloud/teleport/datadog/DatadogEventWriter.java
  v1/src/main/java/com/google/cloud/teleport/datadog/DatadogIO.java
  v1/src/test/java/com/google/cloud/teleport/datadog/DatadogEventWriterTest.java
  v1/src/test/java/com/google/cloud/teleport/datadog/DatadogIOTest.java
Labels: Google LGTM, size/M

#867 Avoid parallelism conflict for extra_libs folder
  v1/pom.xml
  v2/pom.xml
Labels: size/XS

#878 Ignore failing Datadog unit test
  v1/src/test/java/com/google/cloud/teleport/datadog/DatadogEventWriterTest.java
Labels: size/XS

#850 Update json-data-generator / exclude static snakeyaml due to security advisory
  v2/streaming-data-generator/pom.xml
Labels: size/XS

#873 Remove dead code
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/actions/preload/PreloadBigQueryAction.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/actions/preload/PreloadHttpGetAction.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/actions/preload/PreloadHttpPostAction.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/database/CypherGenerator.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/InputValidator.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/helpers/OptionsParamsMapper.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/helpers/SourceMapper.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/helpers/TransposedMappingMapper.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/job/Config.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/job/JobSpec.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/job/Mapping.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/job/OptionsParams.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/job/Source.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/job/Target.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/job/Transform.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/providers/bigquery/BigQueryImpl.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/providers/bigquery/BqQueryToRow.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/providers/text/TextImpl.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/providers/text/TextSourceFileMetadataToRow.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/providers/text/TextSourceFileToRow.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/transforms/CastExpandTargetRowFn.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/transforms/DeleteEmptyRowsFn.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/transforms/Neo4jBlockingUnwindFn.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/transforms/Neo4jRowWriterTransform.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/utils/BeamUtils.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/utils/DataCastingUtils.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/utils/FileSystemUtils.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/utils/GcpSecretUtils.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/utils/ModelUtils.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/utils/TextParserUtils.java
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/providers/text/ListOfStringToRowFnTest.java
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/templates/GoogleToNeo4jTest.java
Labels: Google LGTM, size/L

#858 Ensure byte array to String is converted as UTF-8
  v1/src/main/java/com/google/cloud/teleport/templates/common/ErrorConverters.java
  v2/common/src/main/java/com/google/cloud/teleport/v2/transforms/ErrorConverters.java
  v2/googlecloud-to-elasticsearch/src/main/java/com/google/cloud/teleport/v2/elasticsearch/transforms/FailedPubsubMessageToPubsubTopicFn.java
  v2/googlecloud-to-elasticsearch/src/main/java/com/google/cloud/teleport/v2/elasticsearch/transforms/ProcessFailsafePubSubFn.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/TextIOToBigQuery.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/SpannerChangeStreamsToPubSubTest.java
  v2/pubsub-to-mongodb/src/main/java/com/google/cloud/teleport/v2/templates/PubSubToMongoDB.java
Labels: size/S

#876 Add Neo4j resource manager for integration tests
  it/neo4j/pom.xml
  it/neo4j/src/main/java/com/google/cloud/teleport/it/neo4j/Neo4jResourceManager.java
  it/neo4j/src/main/java/com/google/cloud/teleport/it/neo4j/Neo4jResourceManagerException.java
  it/neo4j/src/main/java/com/google/cloud/teleport/it/neo4j/Neo4jResourceManagerUtils.java
  it/neo4j/src/main/java/com/google/cloud/teleport/it/neo4j/conditions/Neo4jQueryCheck.java
  it/neo4j/src/main/java/com/google/cloud/teleport/it/neo4j/conditions/package-info.java
  it/neo4j/src/main/java/com/google/cloud/teleport/it/neo4j/package-info.java
  it/neo4j/src/test/java/com/google/cloud/teleport/it/neo4j/Neo4jResourceManagerIT.java
  it/neo4j/src/test/java/com/google/cloud/teleport/it/neo4j/Neo4jResourceManagerTest.java
  it/neo4j/src/test/java/com/google/cloud/teleport/it/neo4j/Neo4jResourceManagerUtilsTest.java
  it/pom.xml
  pom.xml
Labels: Google LGTM, size/XL

#825 Fix Neo4j integration issues
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/actions/function/CypherActionFn.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/actions/preload/PreloadCypherAction.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/database/Neo4jConnection.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/templates/GoogleCloudToNeo4j.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/transforms/Neo4jBlockingUnwindFn.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/transforms/Neo4jRowWriterTransform.java
Labels: Google LGTM, size/L

#882 Allow usage of a Bigtable static instance across integration tests
  cicd/cmd/run-it-smoke-tests/main.go
  cicd/cmd/run-it-tests/main.go
  cicd/internal/workflows/maven-workflows.go
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/bigtable/BigtableResourceManager.java
  v1/src/test/java/com/google/cloud/teleport/templates/BigtableToAvroIT.java
  v1/src/test/java/com/google/cloud/teleport/templates/BigtableToParquetIT.java
  v1/src/test/java/com/google/cloud/teleport/templates/ExportJobIT.java
  v1/src/test/java/com/google/cloud/teleport/templates/ImportJobIT.java
  v1/src/test/java/com/google/cloud/teleport/templates/ParquetToBigtableIT.java
  v2/bigquery-to-bigtable/src/test/java/com/google/cloud/teleport/v2/templates/BigQueryToBigtableIT.java
Labels: size/S

#883 Standardize actions usage to tag instead of commit hash
  .github/workflows/go-pr.yml
  .github/workflows/java-pr.yml
  .github/workflows/prepare-java-cache.yml
  .github/workflows/scorecards-analysis.yml
  .github/workflows/syndeo-pr.yml
Labels: size/M

#841 Fix MERGE statement when importing relationships into Neo4j
  v2/googlecloud-to-neo4j/pom.xml
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/database/CypherGenerator.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/helpers/TransposedMappingMapper.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/templates/GoogleCloudToNeo4j.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/transforms/Neo4jRowWriterTransform.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/utils/ModelUtils.java
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/database/CypherGeneratorTest.java
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/templates/InlineDataToNeo4jIT.java
  v2/googlecloud-to-neo4j/src/test/resources/testing-specs/cypher-generator-test/single-target-relation-import-with-keys-spec.json
  v2/googlecloud-to-neo4j/src/test/resources/testing-specs/cypher-generator-test/single-target-relation-import-without-keys-spec.json
  v2/googlecloud-to-neo4j/src/test/resources/testing-specs/verbose-syntax/inline-json-bq-northwind-jobspec.json
Labels: Google LGTM, size/XL

#847 Allow merging start/end nodes instead of matching
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/database/CypherGenerator.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/enums/EdgeNodesMatchMode.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/helpers/TargetMapper.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/job/Target.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/transforms/Neo4jRowWriterTransform.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/utils/ModelUtils.java
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/database/CypherGeneratorTest.java
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/model/helpers/TargetMapperTest.java
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/templates/SinglePassGraphImportIT.java
  v2/googlecloud-to-neo4j/src/test/resources/testing-specs/cypher-generator-test/multi-distinct-keys-single-pass-import.verbose.json
  v2/googlecloud-to-neo4j/src/test/resources/testing-specs/cypher-generator-test/multi-label-single-pass-import.verbose.json
  v2/googlecloud-to-neo4j/src/test/resources/testing-specs/cypher-generator-test/single-pass-import.json
  v2/googlecloud-to-neo4j/src/test/resources/testing-specs/verbose-syntax/inline-json-bq-northwind-single-pass-jobspec.json
Labels: Google LGTM, size/XXL

#888 Allow edge nodes to be merged while creating edges
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/database/CypherGenerator.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/helpers/TargetMapper.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/providers/bigquery/BigQueryImpl.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/providers/text/TextTargetToRow.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/utils/ModelUtils.java
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/database/CypherGeneratorTest.java
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/model/helpers/TargetMapperTest.java
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/templates/SinglePassGraphImportIT.java
  v2/googlecloud-to-neo4j/src/test/resources/testing-specs/cypher-generator-test/single-target-relation-import-create-rels-merge-nodes.json
  v2/googlecloud-to-neo4j/src/test/resources/testing-specs/cypher-generator-test/single-target-relation-import-merge-all.json
  v2/googlecloud-to-neo4j/src/test/resources/testing-specs/verbose-syntax/inline-json-bq-northwind-single-pass-merge-all-jobspec.json
  v2/googlecloud-to-neo4j/src/test/resources/testing-specs/verbose-syntax/inline-json-northwind-subset-single-pass-create-edge-merge-nodes-jobspec.json
Labels: Google LGTM, size/L

#843 Syndeo cleanup
  syndeo-template/pom.xml
  syndeo-template/src/main/java/com/google/cloud/syndeo/SyndeoTemplate.java
  syndeo-template/src/main/java/com/google/cloud/syndeo/common/ProviderUtil.java
  syndeo-template/src/main/java/com/google/cloud/syndeo/common/SchemaIOTransformProviderWrapper.java
  syndeo-template/src/main/java/com/google/cloud/syndeo/common/SchemaUtil.java
  syndeo-template/src/main/java/com/google/cloud/syndeo/dlq/pubsub/PubsubDlqSchemaTransformProvider.java
  syndeo-template/src/main/java/com/google/cloud/syndeo/transforms/SyndeoStatsSchemaTransformProvider.java
  syndeo-template/src/main/java/com/google/cloud/syndeo/transforms/bigtable/BigTableIOWriteSchemaBasedTransform.java
  syndeo-template/src/main/java/com/google/cloud/syndeo/transforms/datagenerator/DataGeneratorSchemaTransform.java
  syndeo-template/src/main/java/com/google/cloud/syndeo/transforms/files/SyndeoFilesReadSchemaTransformProvider.java
  syndeo-template/src/main/java/com/google/cloud/syndeo/transforms/pubsub/SyndeoPubsubReadSchemaTransformProvider.java
  syndeo-template/src/main/java/com/google/cloud/syndeo/transforms/pubsub/SyndeoPubsubWriteSchemaTransformProvider.java
  syndeo-template/src/test/java/com/google/cloud/syndeo/common/SchemaIOTransformProviderWrapperTest.java
  syndeo-template/src/test/java/com/google/cloud/syndeo/dlq/pubsub/PubsubDlqSchemaTransformProviderTest.java
  syndeo-template/src/test/java/com/google/cloud/syndeo/it/ReadFilesTransformIT.java
  syndeo-template/src/test/java/com/google/cloud/syndeo/perf/SyndeoLoadTestUtils.java
  syndeo-template/src/test/java/com/google/cloud/syndeo/perf/SyndeoPubsubLiteToBigTableLT.java
  syndeo-template/src/test/java/com/google/cloud/syndeo/perf/SyndeoPubsubToBigQueryLT.java
  syndeo-template/src/test/java/com/google/cloud/syndeo/transforms/BigTableSchemaTransformTest.java
  syndeo-template/src/test/java/com/google/cloud/syndeo/transforms/SyndeoPubsubReadSchemaTransformProviderTest.java
  syndeo-template/src/test/java/com/google/cloud/syndeo/transforms/datagenerator/DataGeneratorSchemaTransformTest.java
Labels: size/L

#884 Improve resource manager cleanup, do not double fail …
  it/cassandra/src/main/java/com/google/cloud/teleport/it/cassandra/CassandraResourceManager.java
  it/common/src/main/java/com/google/cloud/teleport/it/common/utils/ExceptionUtils.java
  it/common/src/test/java/com/google/cloud/teleport/it/common/utils/ExceptionUtilsTest.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/spanner/SpannerResourceManager.java
Labels: size/M

#891 Do not stage the same template twice
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/TemplateTestBase.java
Labels: size/L

#894 Do not trim stacktraces in JUnit failure reports
  pom.xml
Labels: size/XS

#852 [PubSubToDatadog] Send batches before exceeding 5MB payload limit
  v1/src/main/java/com/google/cloud/teleport/datadog/DatadogEventPublisher.java
  v1/src/main/java/com/google/cloud/teleport/datadog/DatadogEventSerializer.java
  v1/src/main/java/com/google/cloud/teleport/datadog/DatadogEventWriter.java
  v1/src/main/java/com/google/cloud/teleport/datadog/DatadogIO.java
  v1/src/test/java/com/google/cloud/teleport/datadog/DatadogEventPublisherTest.java
  v1/src/test/java/com/google/cloud/teleport/datadog/DatadogEventSerializerTest.java
  v1/src/test/java/com/google/cloud/teleport/datadog/DatadogEventWriterTest.java
Labels: Google LGTM, size/L

#893 Added a BigtableChangeStreamsToGcs template
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/bigtable/BigtableResourceManager.java
  it/google-cloud-platform/src/test/java/com/google/cloud/teleport/it/gcp/bigtable/BigtableResourceManagerTest.java
  v2/bigtable-common/src/main/java/com/google/cloud/teleport/v2/bigtable/options/BigtableCommonOptions.java
  v2/googlecloud-to-googlecloud/README.md
  v2/googlecloud-to-googlecloud/pom.xml
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/options/BigtableChangeStreamsToGcsOptions.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstobigquery/BigtableChangeStreamsToBigQuery.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstobigquery/model/ChangelogColumn.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstogcs/BigtableChangeStreamMutationToChangelogEntryFn.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstogcs/BigtableChangeStreamsToGcs.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstogcs/BigtableChangelogEntryToBigtableRowFn.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstogcs/BigtableUtils.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstogcs/FileFormatFactoryBigtableChangeStreams.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstogcs/WriteChangeStreamMutationToGcsAvro.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstogcs/WriteChangeStreamMutationsToGcsText.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstogcs/WriteChangelogEntryAsJson.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstogcs/model/BigtableSchemaFormat.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstogcs/model/ChangelogColumns.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstogcs/model/DestinationInfo.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstogcs/model/ModType.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstogcs/model/package-info.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstogcs/package-info.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/utils/BigtableSource.java
  v2/googlecloud-to-googlecloud/src/main/resources/bigtable-changestreams-to-gcs-command-spec.json
  v2/googlecloud-to-googlecloud/src/main/resources/schema/avro/bigtablerow.avsc
  v2/googlecloud-to-googlecloud/src/main/resources/schema/avro/changelogentry-text.avsc
  v2/googlecloud-to-googlecloud/src/main/resources/schema/avro/changelogentry.avsc
Labels: Google LGTM, size/XXL

#895 Retry Spanner instance deletion when there are quota exceptions
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/spanner/SpannerResourceManager.java
Labels: size/XS

#897 Optimize database reset queries
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/database/Neo4jConnection.java
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/database/Neo4jConnectionTest.java
Labels: Google LGTM, size/L

#900 Remove unused options setting
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/InputRefactoring.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/InputValidator.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/helpers/JobSpecMapper.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/job/JobSpec.java
Labels: Google LGTM, size/M

#898 Remove unused automap field
  v2/googlecloud-to-neo4j/docs/README.md
  v2/googlecloud-to-neo4j/docs/testing-specs/compact-syntax/bigquery/bq-gdelt-test-spec.json
  v2/googlecloud-to-neo4j/docs/testing-specs/compact-syntax/bigquery/bq-gdelt-test-spec2.json
  v2/googlecloud-to-neo4j/docs/testing-specs/compact-syntax/bigquery/bq-northwind-jobspec.json
  v2/googlecloud-to-neo4j/docs/testing-specs/compact-syntax/composite/bq-gdelt-postload-actions.json
  v2/googlecloud-to-neo4j/docs/testing-specs/compact-syntax/composite/bq-northwind-actions-jobspec.json
  v2/googlecloud-to-neo4j/docs/testing-specs/compact-syntax/text/inline-northwind-jobspec.json
  v2/googlecloud-to-neo4j/docs/testing-specs/compact-syntax/text/text-northwind-jobspec.json
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/helpers/TargetMapper.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/job/Target.java
  v2/googlecloud-to-neo4j/src/test/resources/testing-specs/bq-northwind-jobspec.json
  v2/googlecloud-to-neo4j/src/test/resources/testing-specs/cypher-generator-test/single-target-relation-import-create-rels-merge-nodes.json
  v2/googlecloud-to-neo4j/src/test/resources/testing-specs/cypher-generator-test/single-target-relation-import-merge-all.json
  v2/googlecloud-to-neo4j/src/test/resources/testing-specs/cypher-generator-test/single-target-relation-import-with-keys-spec.json
  v2/googlecloud-to-neo4j/src/test/resources/testing-specs/cypher-generator-test/single-target-relation-import-without-keys-spec.json
  v2/googlecloud-to-neo4j/src/test/resources/testing-specs/inline-northwind-jobspec.json
  v2/googlecloud-to-neo4j/src/test/resources/testing-specs/text-northwind-jobspec.json
Labels: Google LGTM, size/M

#896 Increase integration test parallelism
  cicd/cmd/run-build/main.go
  cicd/cmd/run-it-smoke-tests/main.go
  cicd/cmd/run-it-tests/main.go
  cicd/cmd/run-unit-tests/main.go
  pom.xml
Labels: size/S

#833 Run additional check when job was finished but conditions weren't met
  it/common/src/main/java/com/google/cloud/teleport/it/common/PipelineOperator.java
Labels: size/S

#886 Add "More Information" README section
  README.md
Labels: size/XS

#907 Add timestamp to Spanner databases, to allow usage of static instance
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/spanner/SpannerResourceManager.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/spanner/utils/SpannerResourceManagerUtils.java
  it/google-cloud-platform/src/test/java/com/google/cloud/teleport/it/gcp/spanner/SpannerResourceManagerTest.java
  it/google-cloud-platform/src/test/java/com/google/cloud/teleport/it/gcp/spanner/utils/SpannerResourceManagerUtilsTest.java
Labels: size/M

#913 Do not fail build/unit tests with Spotless, there's a dedicated check for it
  cicd/cmd/run-build/main.go
  cicd/cmd/run-unit-tests/main.go
  cicd/internal/workflows/maven-workflows.go
Labels: size/XS

#912 Allow UDF reloading for streaming templates
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/bigquery/conditions/BigQueryRowsCheck.java
  v1/src/main/java/com/google/cloud/teleport/templates/DatastoreToDatastoreDelete.java
  v1/src/main/java/com/google/cloud/teleport/templates/DatastoreToText.java
  v1/src/main/java/com/google/cloud/teleport/templates/KafkaToBigQuery.java
  v1/src/main/java/com/google/cloud/teleport/templates/PubSubToBigQuery.java
  v1/src/main/java/com/google/cloud/teleport/templates/PubSubToDatadog.java
  v1/src/main/java/com/google/cloud/teleport/templates/PubSubToSplunk.java
  v1/src/main/java/com/google/cloud/teleport/templates/PubsubToDatastore.java
  v1/src/main/java/com/google/cloud/teleport/templates/TextIOToBigQuery.java
  v1/src/main/java/com/google/cloud/teleport/templates/TextToDatastore.java
  v1/src/main/java/com/google/cloud/teleport/templates/common/JavascriptTextTransformer.java
  v1/src/test/java/com/google/cloud/teleport/templates/KafkaToBigQueryTest.java
  v1/src/test/java/com/google/cloud/teleport/templates/PubSubToBigQueryIT.java
  v1/src/test/java/com/google/cloud/teleport/templates/PubsubToBigQueryTest.java
Labels: size/L

#918 Add a v2 flex dynamic template to import data from `AstraDb` into `BigQuery`
  v2/astradb-to-bigquery/README.md
  v2/astradb-to-bigquery/docs/AstraDbToBigQuery/README.md
  v2/astradb-to-bigquery/docs/AstraDbToBigQuery/astradb-to-bigquery-image-spec-metadata.json
  v2/astradb-to-bigquery/docs/troubleshooting.md
  v2/astradb-to-bigquery/pom.xml
  v2/astradb-to-bigquery/src/main/java/com/google/cloud/teleport/v2/astradb/options/AstraDbToBigQueryOptions.java
  v2/astradb-to-bigquery/src/main/java/com/google/cloud/teleport/v2/astradb/options/package-info.java
  v2/astradb-to-bigquery/src/main/java/com/google/cloud/teleport/v2/astradb/templates/AstraDbToBigQuery.java
  v2/astradb-to-bigquery/src/main/java/com/google/cloud/teleport/v2/astradb/templates/package-info.java
  v2/astradb-to-bigquery/src/main/java/com/google/cloud/teleport/v2/astradb/transforms/AstraDbToBigQueryMappingFn.java
  v2/astradb-to-bigquery/src/main/java/com/google/cloud/teleport/v2/astradb/transforms/package-info.java
  v2/astradb-to-bigquery/src/main/resources/application.conf
  v2/astradb-to-bigquery/src/main/resources/astradb-to-bigquery-command-spec.json
  v2/astradb-to-bigquery/src/test/java/com/google/cloud/teleport/v2/astradb/templates/AstraDbToBigQueryIT.java
  v2/astradb-to-bigquery/src/test/resources/logback-test.xml
  v2/pom.xml
Labels: Google LGTM, size/XXL

#915 Use static instance for Spanner integration tests (avoid quota errors)
  cicd/cmd/run-it-smoke-tests/main.go
  cicd/cmd/run-it-tests/main.go
  cicd/internal/workflows/maven-workflows.go
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/spanner/SpannerResourceManager.java
  it/google-cloud-platform/src/main/java/com/google/cloud/teleport/it/gcp/spanner/SpannerResourceManagerException.java
  it/google-cloud-platform/src/test/java/com/google/cloud/teleport/it/gcp/spanner/SpannerResourceManagerTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ExportPipelineIT.java
  v1/src/test/java/com/google/cloud/teleport/templates/SpannerToTextIT.java
  v1/src/test/java/com/google/cloud/teleport/templates/TextImportPipelineIT.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/SpannerChangeStreamsToGcsIT.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/SpannerChangeStreamsToPubSubIT.java
  v2/streaming-data-generator/src/test/java/com/google/cloud/teleport/v2/templates/StreamingDataGeneratorIT.java
Labels: size/L

#917 Update Bigtable-Hbase replicator name to Bigtable_Change_Streams_to_Hbase and fix HbaseIO
  v2/bigtable-cdc-to-hbase/README_bigtable-cdc-to-hbase.md
  v2/bigtable-changestreams-to-hbase/README.md
  v2/bigtable-changestreams-to-hbase/pom.xml
  v2/bigtable-changestreams-to-hbase/src/main/java/com/google/cloud/teleport/v2/templates/BigtableChangeStreamsToHBase.java
  v2/bigtable-changestreams-to-hbase/src/main/java/com/google/cloud/teleport/v2/templates/hbase/HBaseIO.java
  v2/bigtable-changestreams-to-hbase/src/main/java/com/google/cloud/teleport/v2/templates/hbase/HBaseSharedConnection.java
  v2/bigtable-changestreams-to-hbase/src/main/java/com/google/cloud/teleport/v2/templates/hbase/package-info.java
  v2/bigtable-changestreams-to-hbase/src/main/java/com/google/cloud/teleport/v2/templates/package-info.java
  v2/bigtable-changestreams-to-hbase/src/main/java/com/google/cloud/teleport/v2/templates/transforms/ChangeStreamToRowMutations.java
  v2/bigtable-changestreams-to-hbase/src/main/java/com/google/cloud/teleport/v2/templates/transforms/package-info.java
  v2/bigtable-changestreams-to-hbase/src/main/java/com/google/cloud/teleport/v2/templates/utils/RowMutationsBuilder.java
  v2/bigtable-changestreams-to-hbase/src/main/java/com/google/cloud/teleport/v2/templates/utils/package-info.java
  v2/bigtable-changestreams-to-hbase/src/test/java/com/google/cloud/bigtable/data/v2/models/ChangeStreamMutationBuilder.java
  v2/bigtable-changestreams-to-hbase/src/test/java/com/google/cloud/teleport/v2/templates/ChangeStreamToRowMutationsTest.java
  v2/bigtable-changestreams-to-hbase/src/test/java/com/google/cloud/teleport/v2/templates/RowMutationsBuilderTest.java
  v2/bigtable-changestreams-to-hbase/src/test/java/com/google/cloud/teleport/v2/templates/package-info.java
  v2/bigtable-changestreams-to-hbase/src/test/java/com/google/cloud/teleport/v2/templates/utils/HashUtils.java
  v2/bigtable-changestreams-to-hbase/src/test/java/com/google/cloud/teleport/v2/templates/utils/HbaseUtils.java
  v2/bigtable-changestreams-to-hbase/src/test/java/com/google/cloud/teleport/v2/templates/utils/TestConstants.java
  v2/pom.xml
Labels: Google LGTM, size/XL

#924 Update generated documentation
  v1/README_Cloud_PubSub_to_Datadog.md
  v1/README_Cloud_PubSub_to_Splunk.md
  v1/README_Datastore_to_GCS_Text.md
  v1/README_GCS_Text_to_Datastore.md
  v1/README_PubSub_Subscription_to_BigQuery.md
  v1/README_PubSub_to_BigQuery.md
  v1/README_Stream_GCS_Text_to_BigQuery.md
  v2/astradb-to-bigquery/README_AstraDB_To_BigQuery.md
  v2/bigtable-changestreams-to-hbase/README_Bigtable_Change_Streams_to_HBase.md
  v2/datastream-to-bigquery/README_Cloud_Datastream_to_BigQuery.md
  v2/file-format-conversion/README_File_Format_Conversion.md
  v2/pubsub-to-redis/README_Cloud_PubSub_to_Redis.md
Labels: size/XL

#932 [Security] Bump slf4j to 1.7.36
  pom.xml
Labels: size/XS
