Repository GoogleCloudPlatform/DataflowTemplates, pull requests merged in 2023-11, with the labels that each got.

#1110 Bump Truth to 1.1.5
  pom.xml
Labels: size/XS

#1140 Cleanup pinned Data Catalog dependencies
  v2/cdc-parent/cdc-common/pom.xml
  v2/cdc-parent/pom.xml
Labels: size/S

#1146 test: Adding databoost test for SpannerVectorEmbeddingExport.
  v1/src/test/java/com/google/cloud/teleport/spanner/SpannerVectorEmbeddingExportIT.java
Labels: Google LGTM, size/S

#1148 Bigtable CDC tests - increase table name entropy
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstogcs/BigtableChangeStreamsToGcsIT.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstopubsub/BigtableChangeStreamsToPubSubIT.java
Labels: size/XS

#1157 Make database IDs unique across IT parameterized tests
  v1/src/test/java/com/google/cloud/teleport/spanner/SpannerVectorEmbeddingExportIT.java
Labels: size/S

#1163 Add disableCertificateValidation parameter to Elasticsearch templates
  v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/options/ElasticsearchWriteOptions.java
  v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/transforms/WriteToElasticsearch.java
  v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/utils/ElasticsearchIO.java
  v2/googlecloud-to-elasticsearch/README_BigQuery_to_Elasticsearch.md
  v2/googlecloud-to-elasticsearch/README_GCS_to_Elasticsearch.md
  v2/googlecloud-to-elasticsearch/README_PubSub_to_Elasticsearch.md
  v2/googlecloud-to-elasticsearch/src/test/java/com/google/cloud/teleport/v2/elasticsearch/templates/BigQueryToElasticsearchIT.java
Labels: size/M

#1160 Fix flakiness on TextToPubsubIT.testTextToTopic
  it/conditions/src/main/java/org/apache/beam/it/conditions/ConditionCheck.java
  v1/src/test/java/com/google/cloud/teleport/templates/TextToPubsubIT.java
Labels: size/S

#1169 docs: Adding link to template Guide in SpannerVectorEmbeddingExport docs.
  v1/README_Cloud_Spanner_vectors_to_Cloud_Storage.md
  v1/src/main/java/com/google/cloud/teleport/templates/SpannerVectorEmbeddingExport.java
Labels: Google LGTM, size/XS

#1161 Make database name unique across IT parameterized tests
  v1/src/test/java/com/google/cloud/teleport/spanner/SpannerVectorEmbeddingExportIT.java
Labels: size/M

#1166 Move MongoDB driver out of the common deps
  pom.xml
  v2/common/pom.xml
  v2/mongodb-to-googlecloud/pom.xml
  v2/mongodb-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/transforms/JavascriptDocumentTransformer.java
  v2/mongodb-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/transforms/package-info.java
  v2/pom.xml
Labels: size/M

#1171 [Release] Update the staging and libraries buckets for releases.
  .github/workflows/release.yml
Labels: Google LGTM, size/XS

#1170 Add random chars as the job name suffix by default, avoid name collision
  it/common/src/main/java/org/apache/beam/it/common/PipelineLauncher.java
Labels: size/XS

#1158 Add Oracle to BigQuery template (branded JDBC to BigQuery)
  v2/oracle-to-googlecloud/README_Oracle_to_BigQuery.md
  v2/oracle-to-googlecloud/pom.xml
  v2/oracle-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/options/OracleToBigQueryOptions.java
  v2/oracle-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/options/package-info.java
  v2/oracle-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/OracleToBigQuery.java
  v2/oracle-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/package-info.java
  v2/oracle-to-googlecloud/src/main/resources/oracle-to-bigquery-command-spec.json
  v2/oracle-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/OracleToBigQueryIT.java
  v2/pom.xml
Labels: size/XL

#1173 Synchronize JavaScript invokeFunction call, prevent global var issues
  v1/src/main/java/com/google/cloud/teleport/templates/common/JavascriptTextTransformer.java
  v1/src/test/java/com/google/cloud/teleport/templates/common/JavascriptTextTransformerTest.java
  v1/src/test/resources/JavascriptTextTransformerTest/transform.js
  v2/common/src/main/java/com/google/cloud/teleport/v2/transforms/JavascriptTextTransformer.java
Labels: size/M

#1172 [Minor] Beam Quest Update
  README.md
Labels: Google LGTM, size/XS

#1144 [Security] Bump ActiveMQ to 5.17.6
  v2/jms-to-pubsub/pom.xml
  v2/pubsub-to-jms/pom.xml
Labels: size/XS

#1174 Fix custom query flaky test
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/templates/CustomNeo4jWriteQueryIT.java
  v2/googlecloud-to-neo4j/src/test/resources/testing-specs/custom-query/northwind-jobspec-ordered.json
  v2/googlecloud-to-neo4j/src/test/resources/testing-specs/custom-query/northwind-jobspec.json
Labels: Google LGTM, size/L

#1177 Included reference link to Dataflow Metrics Collector repo
  README.md
Labels: Google LGTM, size/XS

#1182 Push only tags (not branches) when releasing from GitHub
  .github/workflows/release.yml
Labels: size/XS

#1176 fixed flaky test com.google.cloud.teleport.templates.TextToBigQueryStreamingTest.wrapBigQueryInsertErrorReturnsValidJSON
  v1/src/test/java/com/google/cloud/teleport/templates/TextToBigQueryStreamingTest.java
Labels: Google LGTM, size/XS

#1184 Fix racing condition when building Jib layers
  plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesStageMojo.java
Labels: size/S

#1159 Bump AutoValue / AutoService dependencies
  pom.xml
  v1/pom.xml
Labels: size/XS

#1186 Fix JdbcToPubsubIT flake (timing issue)
  v1/src/test/java/com/google/cloud/teleport/templates/TextToPubsubIT.java
  v2/jdbc-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/JdbcToPubsubIT.java
Labels: size/S

#1191 Exclude the right interval parameter from the metadata for Batch templates
  v1/src/main/java/com/google/cloud/teleport/templates/DatastoreToDatastoreDelete.java
  v1/src/main/java/com/google/cloud/teleport/templates/DatastoreToText.java
  v1/src/main/java/com/google/cloud/teleport/templates/TextIOToBigQuery.java
  v1/src/main/java/com/google/cloud/teleport/templates/TextToDatastore.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/FirestoreToBigQuery.java
Labels: size/S

#1192 Improve parameters for Jdbc to BigQuery (and derived) templates
  v2/jdbc-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/options/JdbcToBigQueryOptions.java
  v2/mysql-to-googlecloud/README_MySQL_to_BigQuery.md
  v2/mysql-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/options/MySQLToBigQueryOptions.java
  v2/oracle-to-googlecloud/README_Oracle_to_BigQuery.md
  v2/oracle-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/options/OracleToBigQueryOptions.java
  v2/postgresql-to-googlecloud/README_PostgreSQL_to_BigQuery.md
  v2/postgresql-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/options/PostgreSQLToBigQueryOptions.java
  v2/sqlserver-to-googlecloud/README_SQLServer_to_BigQuery.md
  v2/sqlserver-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/options/SQLServerToBigQueryOptions.java
Labels: size/M

#1056 Updating ReadToJdbc block to make it compatible.
  v2/common/src/main/java/com/google/cloud/teleport/v2/auto/blocks/RowToJSONString.java
  v2/common/src/main/java/com/google/cloud/teleport/v2/auto/options/ReadFromJdbcOptions.java
  v2/jdbc-common/src/main/java/com/google/cloud/teleport/v2/auto/blocks/ReadFromJdbc.java
  v2/jdbc-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/JdbcToPubSubAuto.java
Labels: size/L
