Repository GoogleCloudPlatform/DataflowTemplates, pull requests merged in 2023-12, with the labels that each got.

#1203 Remove reload interval param from batch templates
  v1/src/main/java/com/google/cloud/teleport/templates/TextToDatastore.java
  v2/googlecloud-to-elasticsearch/src/main/java/com/google/cloud/teleport/v2/elasticsearch/templates/BigQueryToElasticsearch.java
  v2/googlecloud-to-elasticsearch/src/main/java/com/google/cloud/teleport/v2/elasticsearch/templates/GCSToElasticsearch.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/TextIOToBigQuery.java
  v2/googlecloud-to-splunk/src/main/java/com/google/cloud/teleport/v2/templates/GCSToSplunk.java
Labels: size/XS

#1201 Keep category names as they were before
  metadata/src/main/java/com/google/cloud/teleport/metadata/TemplateCategory.java
Labels: size/XS

#1183 Use IT modules from Beam instead of Templates (cleanup is coming)
  cicd/internal/workflows/maven-workflows.go
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/TemplateTestBase.java
  it/jdbc/pom.xml
  pom.xml
  v1/pom.xml
  v2/cdc-parent/pom.xml
  v2/dataplex/pom.xml
  v2/googlecloud-to-googlecloud/pom.xml
  v2/googlecloud-to-neo4j/pom.xml
  v2/jdbc-common/pom.xml
  v2/jdbc-to-googlecloud/pom.xml
  v2/mysql-to-googlecloud/pom.xml
  v2/oracle-to-googlecloud/pom.xml
  v2/postgresql-to-googlecloud/pom.xml
  v2/sqlserver-to-googlecloud/pom.xml
  v2/streaming-data-generator/pom.xml
Labels: size/L

#1207 Implement secrets manager support for connection metadata
  v2/googlecloud-to-neo4j/pom.xml
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/InputValidator.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/connection/ConnectionParams.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/options/Neo4jFlexTemplateOptions.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/templates/GoogleCloudToNeo4j.java
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/model/InputValidatorTest.java
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/templates/Connections.java
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/templates/ConstraintsIndicesIT.java
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/templates/CustomNeo4jWriteQueryIT.java
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/templates/GoogleToNeo4jTest.java
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/templates/InlineDataToNeo4jIT.java
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/templates/PropertyMappingsIT.java
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/templates/Resources.java
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/templates/SecretManagerIT.java
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/templates/SinglePassGraphImportIT.java
  v2/googlecloud-to-neo4j/src/test/resources/testing-specs/secret-manager/spec.json
Labels: Google LGTM, size/XL

#1208 Add Bigtable to JSON export
  v1/README_Cloud_Bigtable_to_GCS_Json.md
  v1/src/main/java/com/google/cloud/teleport/bigtable/BigtableToJson.java
  v1/src/test/java/com/google/cloud/teleport/templates/BigtableToJsonIT.java
Labels: Google LGTM, size/L

#1202 Kafka Avro to Big Query Support
  v2/kafka-common/src/main/java/com/google/cloud/teleport/v2/kafka/transforms/KafkaTransform.java
  v2/kafka-common/src/main/java/com/google/cloud/teleport/v2/kafka/transforms/SchemaKafkaAvroDeserializer.java
  v2/kafka-to-bigquery/src/main/java/com/google/cloud/teleport/v2/templates/KafkaToBigQuery.java
  v2/kafka-to-bigquery/src/test/java/com/google/cloud/teleport/v2/templates/KafkaToBigQueryAvroIT.java
  v2/kafka-to-bigquery/src/test/java/com/google/cloud/teleport/v2/templates/KafkaToBigQueryTest.java
  v2/kafka-to-bigquery/src/test/resources/KafkaToBigQueryAvroIT/avro_schema.avsc
Labels: size/XL

#1198 Reduce CI build concurrency to avoid reaching AutoValue racing condit…
  cicd/cmd/run-build/main.go
Labels: size/XS

#1168 Fail release scripts fast if a single test fails
  .github/workflows/release.yml
  cicd/cmd/run-it-smoke-tests/main.go
  cicd/cmd/run-it-tests/main.go
  cicd/internal/flags/it-flags.go
  pom.xml
Labels: size/M

#1211 Neo4j. Fix validation for the key values belonging to different fragments
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/InputValidator.java
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/model/InputValidatorTest.java
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/templates/ValidationIT.java
  v2/googlecloud-to-neo4j/src/test/resources/testing-specs/validation/spec.json
Labels: Google LGTM, size/L

#1068 Add support for all authentication types, introduce JSON schema
  v2/googlecloud-to-neo4j/pom.xml
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/database/Neo4jConnection.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/InputValidator.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/Json.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/connection/BasicConnectionParams.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/connection/BearerConnectionParams.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/connection/ConnectionParams.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/connection/CustomConnectionParams.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/connection/KerberosConnectionParams.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/connection/NoAuthConnectionParams.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/templates/GoogleCloudToNeo4j.java
  v2/googlecloud-to-neo4j/src/main/resources/schemas/connection.v1.0.json
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/model/InputValidatorTest.java
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/model/connection/ConnectionParamsTest.java
Labels: Google LGTM, size/XXL

#1214 Fix MongoDB template metadata
  metadata/src/main/java/com/google/cloud/teleport/metadata/util/MetadataUtils.java
  metadata/src/test/java/com/google/cloud/teleport/metadata/util/MetadataUtilsTest.java
  v2/googlecloud-to-mongodb/src/main/java/com/google/cloud/teleport/v2/mongodb/options/BigQueryToMongoDbOptions.java
  v2/mongodb-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/mongodb/options/MongoDbToBigQueryOptions.java
Labels: size/S

#1196 Use customizable output folder to avoid racing conditions
  pom.xml
  v1/pom.xml
  v2/googlecloud-to-googlecloud/pom.xml
  v2/pom.xml
Labels: size/XS

#1197 Use a newer version of maven-compiler-plugin
  plaintext-logging/pom.xml
  pom.xml
Labels: size/XS

#1162 Allow DirectRunner tests to run in parallel
  pom.xml
Labels: size/XS

#1216 Add flatten support for CBT->GCS JSON template
  v1/README_Cloud_Bigtable_to_GCS_Json.md
  v1/src/main/java/com/google/cloud/teleport/bigtable/BigtableToJson.java
  v1/src/test/java/com/google/cloud/teleport/bigtable/BigtableToJsonTest.java
  v1/src/test/java/com/google/cloud/teleport/templates/BigtableToJsonIT.java
Labels: Google LGTM, size/L

#1224 Run Spotless and Checkstyle for all modules
  .github/workflows/java-pr.yml
  cicd/cmd/run-checkstyle/main.go
  cicd/internal/op/maven.go
  cicd/internal/repo/modules.go
  cicd/internal/workflows/maven-workflows.go
Labels: size/M

#1219 Add Sonatype repository to release templates
  pom.xml
Labels: size/M

#826 Add DataStream to Spanner IT
  it/conditions/pom.xml
  it/conditions/src/main/java/org/apache/beam/it/conditions/ChainedConditionCheck.java
  it/conditions/src/main/java/org/apache/beam/it/conditions/package-info.java
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/datastream/DatastreamResourceManager.java
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/datastream/DatastreamResourceManagerUtils.java
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/datastream/JDBCSource.java
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/datastream/MySQLSource.java
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/datastream/OracleSource.java
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/datastream/PostgresqlSource.java
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/spanner/SpannerResourceManager.java
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/spanner/conditions/SpannerRowsCheck.java
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/spanner/conditions/package-info.java
  it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/datastream/DatastreamResourceManagerTest.java
  it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/spanner/SpannerResourceManagerIT.java
  it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/spanner/SpannerResourceManagerTest.java
  it/jdbc/pom.xml
  it/jdbc/src/main/java/org/apache/beam/it/jdbc/CustomMySQLResourceManager.java
  it/jdbc/src/main/java/org/apache/beam/it/jdbc/package-info.java
  it/pom.xml
  v2/datastream-common/src/main/java/com/google/cloud/teleport/v2/datastream/transforms/FormatDatastreamRecordToJson.java
  v2/datastream-to-spanner/pom.xml
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerIT.java
Labels: size/XXL

#1225 Remove obsolete todo
  v1/src/main/java/com/google/cloud/teleport/bigtable/BigtableToJson.java
Labels: Google LGTM, size/XS

#1227 Use unique Pub/Sub names for integration test, avoid conflicts
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/PubSubToBigQueryIT.java
Labels: size/S

#1164 Build the graph with use_runner_v2 for classic templates if -DunifiedWorker=true is used
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/TemplateTestBase.java
  plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesReleaseMojo.java
  plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesRunMojo.java
  plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesStageMojo.java
Labels: size/M

#1200 Disable certificate should work when no certificate is passed
  v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/utils/ElasticsearchIO.java
Labels: size/M

#1220 [Neo4j] Add test id to secret name to prevent conflict
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/templates/SecretManagerIT.java
Labels: size/XS

#1235 Bug template: ask template version instead of Beam version
  .github/ISSUE_TEMPLATE/bug-template.yml
Labels: size/S

#1232 Fix exception class to ignore from failures
  v1/src/test/java/com/google/cloud/teleport/bigtable/CassandraToBigtableIT.java
Labels: size/XS
