Repository GoogleCloudPlatform/DataflowTemplates, pull requests merged in 2023-08, with the labels that each got.

#929 [Security] Bump auto-value to 1.10.2
  pom.xml
Labels: size/XS

#938 Add UDF Reloading to v2 streaming templates
  v2/common/src/main/java/com/google/cloud/teleport/v2/transforms/BigQueryConverters.java
  v2/common/src/main/java/com/google/cloud/teleport/v2/transforms/JavascriptTextTransformer.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/FirestoreToBigQuery.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/PubSubToBigQuery.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/TextIOToBigQuery.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/TextToBigQueryStreaming.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/PubSubToBigQueryIT.java
  v2/kafka-to-bigquery/src/main/java/com/google/cloud/teleport/v2/templates/KafkaToBigQuery.java
  v2/kafka-to-pubsub/src/main/java/com/google/cloud/teleport/v2/transforms/FormatTransform.java
  v2/pubsub-binary-to-bigquery/src/main/java/com/google/cloud/teleport/v2/templates/PubsubProtoToBigQuery.java
  v2/pubsub-to-kafka/src/main/java/com/google/cloud/teleport/v2/transforms/FormatMessageTransform.java
  v2/pubsub-to-mongodb/src/main/java/com/google/cloud/teleport/v2/templates/PubSubToMongoDB.java
  v2/pubsub-to-mongodb/src/test/java/com/google/cloud/teleport/v2/templates/PubSubToMongoDBIT.java
Labels: size/L

#940 Fix parameter name for JavaScript reload on PubSubToBigQueryIT
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/PubSubToBigQueryIT.java
Labels: size/XS

#944 [Security] Upgrade snappy-java to 1.1.10.3
  pom.xml
Labels: size/XS

#943 Revert auto-value version to 1.8.2, intermittently getting "Stream closed"
  pom.xml
Labels: size/XS

#869 Bump Testcontainers dependency to 1.18.3
  it/pom.xml
Labels: size/XS

#948 Override table name to stay under 30 chars limit
  v2/jdbc-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/JdbcToBigQueryIT.java
Labels: size/S

#939 Keep defaultValue for a parameter spec normalized to string
  plugins/core-plugin/src/main/java/com/google/cloud/teleport/plugin/model/ImageSpecParameter.java
  plugins/core-plugin/src/main/java/com/google/cloud/teleport/plugin/model/TemplateDefinitions.java
Labels: size/S

#949 Add command spec for BigtableChangeStreamsToHBase
  v2/bigtable-changestreams-to-hbase/src/main/resources/bigtable-changestreams-to-hbase-command-spec.json
Labels: size/XS

#905 Make "runtime tokens" parameter optional
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/helpers/OptionsParamsMapper.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/job/OptionsParams.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/options/Neo4jFlexTemplateOptions.java
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/templates/InlineDataToNeo4jIT.java
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/templates/SinglePassGraphImportIT.java
Labels: Google LGTM, size/M

#956 Fix connection leak
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/transforms/Neo4jRowWriterTransform.java
Labels: Google LGTM, size/S

#959 [Security] Update maven-dependency-plugin + pin newer plexus-archiver
  pom.xml
  v1/pom.xml
  v2/cdc-parent/pom.xml
  v2/pom.xml
Labels: size/S

#916 Minor fields rename for consistency
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstogcs/BigtableUtils.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstogcs/WriteChangelogEntryAsJson.java
  v2/googlecloud-to-googlecloud/src/main/resources/schema/avro/changelogentry-text.avsc
  v2/googlecloud-to-googlecloud/src/main/resources/schema/avro/changelogentry.avsc
Labels: Google LGTM, size/S

#901 Fix support of multiple key definitions for edge source/target nodes
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/helpers/TransposedMappingMapper.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/job/Mapping.java
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/model/helpers/TransposedMappingMapperTest.java
Labels: Google LGTM, size/L

#962 [Security] Update maven-source-plugin + pin newer plexus-archiver
  pom.xml
  v1/pom.xml
  v2/pom.xml
Labels: size/S

#961 Bump bigtable version to 2.11.0
  v2/bigtable-common/pom.xml
Labels: Google LGTM, size/XS

#966 Fix worker type parameter in document snippet
  v2/googlecloud-to-neo4j/docs/README.md
Labels: Google LGTM, size/M

#953 Add queryLocation option to bigquery to read from authrozied views
  v2/bigquery-to-bigtable/README_BigQuery_to_Bigtable.md
  v2/common/src/main/java/com/google/cloud/teleport/v2/transforms/BigQueryConverters.java
  v2/googlecloud-to-elasticsearch/README_BigQuery_to_Elasticsearch.md
  v2/googlecloud-to-elasticsearch/docs/BigQueryToElasticsearch/README.md
Labels: Google LGTM, size/M

#968 Fix flaky test - explicitly sort mappings by field
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/model/helpers/TransposedMappingMapperTest.java
Labels: Google LGTM, size/XS

#958 Fix options mapping
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/helpers/OptionsParamsMapper.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/job/OptionsParams.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/utils/ModelUtils.java
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/model/helpers/OptionsParamsMapperTest.java
Labels: Google LGTM, size/M

#967 Fix stale documentation around `batchCount`
  v1/README_Cassandra_To_Cloud_Bigtable.md
  v1/README_Cloud_BigQuery_to_Cloud_Datastore.md
  v1/README_Cloud_BigQuery_to_GCS_TensorFlow_Records.md
  v1/README_Cloud_Bigtable_to_GCS_Parquet.md
  v1/README_Cloud_Bigtable_to_GCS_SequenceFile.md
  v1/README_Cloud_PubSub_to_Datadog.md
  v1/README_Cloud_PubSub_to_Splunk.md
  v1/README_Cloud_Spanner_to_GCS_Avro.md
  v1/README_Datastore_to_Datastore_Delete.md
  v1/README_Datastore_to_GCS_Text.md
  v1/README_Firestore_to_Firestore_Delete.md
  v1/README_GCS_Avro_to_Cloud_Spanner.md
  v1/README_GCS_SequenceFile_to_Cloud_Bigtable.md
  v1/README_GCS_Text_to_Cloud_Spanner.md
  v1/README_GCS_Text_to_Datastore.md
  v1/README_Jdbc_to_BigQuery.md
  v1/README_PubSub_Subscription_to_BigQuery.md
  v1/README_PubSub_to_BigQuery.md
  v1/README_Spanner_to_GCS_Text.md
  v1/README_Stream_GCS_Text_to_BigQuery.md
  v1/src/main/java/com/google/cloud/teleport/templates/common/DatadogConverters.java
Labels: Google LGTM, size/L

#972 Neo4j Tests - Always sort fields to prevent flakes
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/model/helpers/TransposedMappingMapperTest.java
Labels: size/S

#971 Improve flakiness on BigtableChangeStreamsToBigQueryIT
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstobigquery/BigtableChangeStreamsToBigQueryIT.java
Labels: size/L

#974 Output Testcontainer logs as test output, make it easier to troubleshoot
  it/testcontainers/src/main/java/org/apache/beam/it/testcontainers/TestContainerResourceManager.java
  it/testcontainers/src/test/java/org/apache/beam/it/testcontainers/TestContainerResourceManagerTest.java
Labels: size/S

#975 Fix mocking for ResourceManager tests
  it/cassandra/src/test/java/org/apache/beam/it/cassandra/CassandraResourceManagerTest.java
  it/elasticsearch/src/test/java/org/apache/beam/it/elasticsearch/ElasticsearchResourceManagerTest.java
  it/kafka/src/test/java/org/apache/beam/it/kafka/KafkaResourceManagerTest.java
  it/mongodb/src/test/java/org/apache/beam/it/mongodb/MongoDBResourceManagerTest.java
  it/neo4j/src/test/java/org/apache/beam/it/neo4j/Neo4jResourceManagerTest.java
  it/splunk/src/test/java/org/apache/beam/it/splunk/SplunkResourceManagerTest.java
Labels: size/S

#935 [Debt] Bump mssql-jdbc to 12.2.0.jre11
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/JDBCBaseIT.java
  pom.xml
Labels: size/XS

#934 [Debt] Bump ojdbc8 to 23.2.0.0
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/JDBCBaseIT.java
  it/jdbc/pom.xml
  pom.xml
Labels: size/XS

#933 [Security] Bump postgresql to 42.6.0
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/JDBCBaseIT.java
  pom.xml
  v2/jdbc-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/JdbcToBigQueryLT.java
Labels: size/XS

#988 Update list of templates in README.md
  README.md
Labels: size/L

#982 Add integration tests for Bigtable CDC to GCS template
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/artifacts/ArtifactClient.java
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/storage/GcsResourceManager.java
  v2/googlecloud-to-googlecloud/src/main/resources/schema/avro/changelogentry-text.avsc
  v2/googlecloud-to-googlecloud/src/main/resources/schema/avro/changelogentry.avsc
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstogcs/BigtableChangeStreamsToGcsIT.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstogcs/BigtableUtilsTest.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstogcs/CharSequenceTypeAdapter.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstogcs/CommitTimeAwarePredicate.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstogcs/LookForBigtableRowAvroRecord.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstogcs/LookForChangelogEntryAvroRecord.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstogcs/LookForChangelogEntryJsonBase64Record.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstogcs/LookForChangelogEntryJsonRecord.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstogcs/Tools.java
Labels: Google LGTM, size/XXL

#992 Set retry backoff settings for Spanner import/export templates
  v1/pom.xml
  v1/src/main/java/org/apache/beam/sdk/io/gcp/spanner/LocalSpannerAccessor.java
Labels: Google LGTM, size/S

#954 Neo4j/remove verbose syntax
  v2/googlecloud-to-neo4j/docs/testing-specs/verbose-syntax/bq-northwind-jobspec.json
  v2/googlecloud-to-neo4j/docs/testing-specs/verbose-syntax/inline-json-bq-northwind-jobspec.json
  v2/googlecloud-to-neo4j/docs/testing-specs/verbose-syntax/inline-json-serialize-targets-bq-northwind-jobspec.json
  v2/googlecloud-to-neo4j/docs/testing-specs/verbose-syntax/inline-newline-bq-northwind-jobspec.json
  v2/googlecloud-to-neo4j/docs/testing-specs/verbose-syntax/inline-tilda-bq-northwind-jobspec.json
  v2/googlecloud-to-neo4j/docs/testing-specs/verbose-syntax/json-musicians-jobspec-options-syntax.json
  v2/googlecloud-to-neo4j/docs/testing-specs/verbose-syntax/text-northwind-jobspec.json
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/helpers/MappingMapper.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/helpers/TargetMapper.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/helpers/VerboseMappingMapper.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/utils/ModelUtils.java
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/database/CypherGeneratorTest.java
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/model/helpers/MappingMapperTest.java
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/model/helpers/TargetMapperTest.java
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/templates/InlineDataToNeo4jIT.java
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/templates/SinglePassGraphImportIT.java
  v2/googlecloud-to-neo4j/src/test/resources/testing-specs/bq-northwind-jobspec.json
  v2/googlecloud-to-neo4j/src/test/resources/testing-specs/cypher-generator-test/multi-distinct-keys-single-pass-import.json
  v2/googlecloud-to-neo4j/src/test/resources/testing-specs/cypher-generator-test/multi-distinct-keys-single-pass-import.verbose.json
  v2/googlecloud-to-neo4j/src/test/resources/testing-specs/cypher-generator-test/multi-label-single-pass-import.json
  v2/googlecloud-to-neo4j/src/test/resources/testing-specs/cypher-generator-test/multi-label-single-pass-import.verbose.json
  v2/googlecloud-to-neo4j/src/test/resources/testing-specs/inline-data/northwind-jobspec-single-pass-merge-all.json
  v2/googlecloud-to-neo4j/src/test/resources/testing-specs/inline-data/northwind-jobspec.json
  v2/googlecloud-to-neo4j/src/test/resources/testing-specs/inline-data/northwind-subset-jobspec-single-pass-create-edge-merge-nodes.json
  v2/googlecloud-to-neo4j/src/test/resources/testing-specs/inline-northwind-jobspec.json
  v2/googlecloud-to-neo4j/src/test/resources/testing-specs/verbose-syntax/bq-northwind-jobspec.json
  v2/googlecloud-to-neo4j/src/test/resources/testing-specs/verbose-syntax/inline-json-bq-northwind-single-pass-merge-all-jobspec.json
  v2/googlecloud-to-neo4j/src/test/resources/testing-specs/verbose-syntax/inline-newline-bq-northwind-jobspec.json
  v2/googlecloud-to-neo4j/src/test/resources/testing-specs/verbose-syntax/inline-tilda-bq-northwind-jobspec.json
  v2/googlecloud-to-neo4j/src/test/resources/testing-specs/verbose-syntax/json-musicians-jobspec-options-syntax.json
  v2/googlecloud-to-neo4j/src/test/resources/testing-specs/verbose-syntax/text-northwind-jobspec.json
Labels: Google LGTM, size/XXL

#993 Change zone for Bigtable tests, avoid stockouts
  it/google-cloud-platform/pom.xml
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/bigtable/BigtableResourceManager.java
  it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/bigtable/BigtableResourceManagerTest.java
  it/pom.xml
  it/splunk/pom.xml
  v1/src/test/java/com/google/cloud/teleport/spanner/ExportPipelineIT.java
  v1/src/test/java/com/google/cloud/teleport/templates/JdbcToBigQueryIT.java
  v1/src/test/java/com/google/cloud/teleport/templates/PubSubToSplunkIT.java
  v1/src/test/java/com/google/cloud/teleport/templates/SpannerToTextIT.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstobigquery/BigtableChangeStreamsToBigQueryIT.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstogcs/BigtableChangeStreamsToGcsIT.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstopubsub/BigtableChangeStreamsToPubSubIT.java
  v2/jdbc-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/JdbcToPubsubIT.java
  v2/mongodb-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/mongodb/templates/MongoDbToBigQueryIT.java
Labels: size/M

#998 Sort to avoid flaky tests on Neo4j MappingMapperTest
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/model/helpers/MappingMapperTest.java
Labels: size/S

#997 [DatastreamToBigQuery] Ignore FileNotFoundException when reading ranges
  v2/common/src/main/java/com/google/cloud/teleport/v2/cdc/sources/DataStreamIO.java
  v2/common/src/main/java/com/google/cloud/teleport/v2/cdc/sources/ReadFileRangesFn.java
Labels: size/M

#996 Sync changes in `it` module with Beam repository.
  it/cassandra/src/main/java/org/apache/beam/it/cassandra/CassandraResourceManager.java
  it/elasticsearch/src/test/java/org/apache/beam/it/elasticsearch/ElasticsearchUtilsTest.java
  it/google-cloud-platform/pom.xml
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/GCPBaseIT.java
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/artifacts/matchers/ArtifactsSubject.java
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/bigtable/BigtableResourceManager.java
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/datastore/matchers/DatastoreAsserts.java
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/datastore/matchers/package-info.java
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/secretmanager/package-info.java
  it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/bigquery/BigQueryResourceManagerTest.java
  it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/bigquery/BigQueryResourceManagerUtilsTest.java
  it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/bigtable/BigtableResourceManagerTest.java
  it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/dataflow/ClassicTemplateClientTest.java
  it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/spanner/utils/SpannerResourceManagerUtilsTest.java
  it/neo4j/src/main/java/org/apache/beam/it/neo4j/Neo4jResourceManager.java
  it/neo4j/src/test/java/org/apache/beam/it/neo4j/Neo4jResourceManagerTest.java
  it/splunk/src/main/java/org/apache/beam/it/splunk/SplunkResourceManager.java
  it/splunk/src/test/java/org/apache/beam/it/splunk/SplunkResourceManagerIT.java
  it/testcontainers/src/main/java/org/apache/beam/it/testcontainers/TestContainerResourceManager.java
Labels: size/L

#987 Add KMS and Secret manager support in Pub/Sub to ElasticSearch template.
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/kms/KMSResourceManager.java
  v1/src/test/java/com/google/cloud/teleport/templates/JdbcToBigQueryIT.java
  v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/options/ElasticsearchWriteOptions.java
  v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/transforms/WriteToElasticsearch.java
  v2/googlecloud-to-elasticsearch/src/main/java/com/google/cloud/teleport/v2/elasticsearch/templates/PubSubToElasticsearch.java
  v2/googlecloud-to-elasticsearch/src/test/java/com/google/cloud/teleport/v2/elasticsearch/templates/PubSubToElasticsearchTest.java
Labels: size/L

#1001 Fix Load Tests.
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/IOLoadTestBase.java
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/dataflow/DefaultPipelineLauncher.java
  it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/dataflow/DefaultPipelineLauncherTest.java
Labels: size/S

#1000 Fixing an unexpected mutation of the ByteBuffers
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstogcs/WriteChangeStreamMutationToGcsAvro.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstogcs/WriteChangeStreamMutationsToGcsText.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstogcs/WriteChangelogEntryAsJson.java
Labels: Google LGTM, size/M

#1003 [Neo4j MappingMapperTest] Sort mappings to avoid test flakes
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/model/helpers/MappingMapperTest.java
Labels: size/XS

#1006 Keep Template metadata as string, otherwise `gcloud` breaks
  plugins/core-plugin/src/main/java/com/google/cloud/teleport/plugin/model/ImageSpecMetadata.java
  plugins/core-plugin/src/main/java/com/google/cloud/teleport/plugin/model/TemplateDefinitions.java
  plugins/core-plugin/src/main/resources/README-template.md
  plugins/core-plugin/src/main/resources/site-template.md
  plugins/core-plugin/src/test/java/com/google/cloud/teleport/plugin/docs/TemplateDocsGeneratorTest.java
  plugins/core-plugin/src/test/java/com/google/cloud/teleport/plugin/model/TemplateDefinitionsTest.java
  plugins/core-plugin/src/test/java/com/google/cloud/teleport/plugin/sample/AtoBOk.java
Labels: size/S

#1008 Add batch transaction execution details
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/database/Neo4jConnection.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/transforms/Neo4jBlockingUnwindFn.java
Labels: Google LGTM, size/S

#1010 Remove unnecessary superclass on TextToPubsubStream
  v1/src/main/java/com/google/cloud/teleport/templates/TextToPubsubStream.java
Labels: size/XS

#1009 Wrap the text on site docs for long lines
  plugins/core-plugin/src/main/java/com/google/cloud/teleport/plugin/docs/TemplateDocsUtils.java
  plugins/core-plugin/src/main/java/com/google/cloud/teleport/plugin/model/TemplateDefinitions.java
  plugins/core-plugin/src/main/resources/README-template.md
  plugins/core-plugin/src/main/resources/site-template.md
  plugins/core-plugin/src/test/java/com/google/cloud/teleport/plugin/docs/TemplateDocsGeneratorTest.java
  plugins/core-plugin/src/test/java/com/google/cloud/teleport/plugin/docs/TemplateDocsUtilsTest.java
  plugins/core-plugin/src/test/java/com/google/cloud/teleport/plugin/model/TemplateDefinitionsTest.java
  plugins/core-plugin/src/test/java/com/google/cloud/teleport/plugin/sample/AtoBOk.java
  v2/astradb-to-bigquery/docs/AstraDbToBigQuery/README.md
  v2/astradb-to-bigquery/src/main/java/com/google/cloud/teleport/v2/astradb/options/AstraDbToBigQueryOptions.java
  v2/astradb-to-bigquery/src/main/java/com/google/cloud/teleport/v2/astradb/templates/AstraDbToBigQuery.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/options/Neo4jFlexTemplateOptions.java
  v2/pubsub-to-kafka/src/main/java/com/google/cloud/teleport/v2/templates/PubsubToKafka.java
Labels: size/L

#1011 Fix asserts after parameters were added
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/dataflow/AbstractPipelineLauncher.java
  it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/dataflow/ClassicTemplateClientTest.java
  it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/dataflow/FlexTemplateClientTest.java
Labels: size/M

#986 Fix duplicate name warning
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/templates/GoogleCloudToNeo4j.java
Labels: Google LGTM, size/XS

#1013 Fix flaky load tests
  .github/workflows/load-tests.yml
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/bigquery/BigQueryResourceManager.java
  pom.xml
  v1/src/test/java/com/google/cloud/teleport/templates/TextToBigQueryStreamLT.java
  v2/jdbc-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/JdbcToBigQueryLT.java
Labels: size/M

#1002 BigtableChangeStreamsToPubSubIT - Qualify test with parameter name
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstopubsub/BigtableChangeStreamsToPubSubIT.java
Labels: size/M

#985 [Integration tests] Retry the operation on Pub/Sub on DeadlineExceeded exceptions
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/pubsub/PubsubResourceManager.java
Labels: size/M

#1015 Improve performance of StreamingDataGenerator writes to spanner.
  v2/common/src/main/java/com/google/cloud/teleport/v2/transforms/JsonStringToMutationFn.java
  v2/common/src/test/java/com/google/cloud/teleport/v2/transforms/JsonStringToMutationFnTest.java
  v2/streaming-data-generator/src/main/java/com/google/cloud/teleport/v2/templates/StreamingDataGenerator.java
  v2/streaming-data-generator/src/main/java/com/google/cloud/teleport/v2/transforms/StreamingDataGeneratorWriteToSpanner.java
Labels: size/L

#926 Templates Blocks Framework
  metadata/pom.xml
  metadata/src/main/java/com/google/cloud/teleport/metadata/Template.java
  metadata/src/main/java/com/google/cloud/teleport/metadata/auto/AutoTemplate.java
  metadata/src/main/java/com/google/cloud/teleport/metadata/auto/Consumes.java
  metadata/src/main/java/com/google/cloud/teleport/metadata/auto/DlqOutputs.java
  metadata/src/main/java/com/google/cloud/teleport/metadata/auto/Outputs.java
  metadata/src/main/java/com/google/cloud/teleport/metadata/auto/Preprocessor.java
  metadata/src/main/java/com/google/cloud/teleport/metadata/auto/TemplateBlock.java
  metadata/src/main/java/com/google/cloud/teleport/metadata/auto/TemplateTransform.java
  metadata/src/main/java/com/google/cloud/teleport/metadata/auto/package-info.java
  plugins/core-plugin/src/main/java/com/google/cloud/teleport/plugin/model/TemplateDefinitions.java
  v2/common/src/main/java/com/google/cloud/teleport/v2/auto/blocks/BlockConstants.java
  v2/common/src/main/java/com/google/cloud/teleport/v2/auto/blocks/PubsubMessageToTableRow.java
  v2/common/src/main/java/com/google/cloud/teleport/v2/auto/blocks/ReadFromPubSub.java
  v2/common/src/main/java/com/google/cloud/teleport/v2/auto/blocks/WriteToBigQuery.java
  v2/common/src/main/java/com/google/cloud/teleport/v2/auto/blocks/package-info.java
  v2/common/src/main/java/com/google/cloud/teleport/v2/auto/dlq/AutoDLQUtil.java
  v2/common/src/main/java/com/google/cloud/teleport/v2/auto/dlq/BigQueryDeadletterOptions.java
  v2/common/src/main/java/com/google/cloud/teleport/v2/auto/dlq/WriteDlqToBigQuery.java
  v2/common/src/main/java/com/google/cloud/teleport/v2/auto/dlq/package-info.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/PubSubToBigQueryAuto.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/PubSubToBigQueryAutoIT.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/PubSubToBigQueryIT.java
Labels: size/XXL

#1020 [Plugins] Remove dockerfilePath parameter and automatically use custom Dockerfiles within a python template's directory
  plugins/core-plugin/src/main/java/com/google/cloud/teleport/plugin/PythonDockerfileGenerator.java
  plugins/core-plugin/src/main/resources/Dockerfile-template
  plugins/core-plugin/src/test/java/com/google/cloud/teleport/plugin/PythonDockerfileGeneratorTest.java
  plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesReleaseMojo.java
  plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesRunMojo.java
  plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesStageMojo.java
  python/src/main/python/word-count-python/Dockerfile
Labels: size/M

#1021 Disable PubsubToBigQueryWithReload for Auto Template, work in progress to fix it
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/PubSubToBigQueryAutoIT.java
Labels: size/S
