Repository GoogleCloudPlatform/DataflowTemplates, pull requests merged in 2024-01, with the labels that each got.

#1236 Fix cascading NPE when there was a failure launching the pipeline
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/TemplateTestBase.java
Labels: size/XS

#1237 Fix pipeline name record in metrics
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/dataflow/DefaultPipelineLauncher.java
Labels: Google LGTM, size/XS

#1245 Support CreateDisposition, withMethod, and schema for FirestoreToBigQuery template
  v2/googlecloud-to-googlecloud/README_Firestore_to_BigQuery_Flex.md
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/FirestoreToBigQuery.java
Labels: Google LGTM, size/M

#1240 Make schema unique to improve debugability of test racing condition
  v2/kafka-to-bigquery/src/test/java/com/google/cloud/teleport/v2/templates/KafkaToBigQueryAvroIT.java
  v2/kafka-to-bigquery/src/test/resources/KafkaToBigQueryAvroIT/avro_schema.avsc
Labels: size/S

#1239 Cleanup ModelColumn builder TODOs.
  v1/src/main/java/com/google/cloud/teleport/spanner/ddl/ModelColumn.java
  v1/src/test/java/com/google/cloud/teleport/spanner/AvroSchemaToDdlConverterTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ddl/DdlTest.java
Labels: size/S

#1222 Match IT framework with Beam diffs (soon to be consolidated)
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/LoadTestBase.java
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/artifacts/utils/JsonTestUtil.java
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/dataflow/DefaultPipelineLauncher.java
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/dataflow/DirectRunnerClient.java
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/datagenerator/DataGenerator.java
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/datastore/matchers/DatastoreAsserts.java
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/dlp/DlpResourceManager.java
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/kms/KMSResourceManager.java
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/monitoring/MonitoringClient.java
  it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/bigtable/BigTableIOLT.java
  it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/storage/FileBasedIOLT.java
Labels: size/L

#1241 [Security] Bump kafka-clients due to CVE-2021-38153
  v2/kafka-common/pom.xml
Labels: size/XS

#1254 Rollback #1209
  python/src/main/java/com/google/cloud/teleport/templates/python/WordCountPython.java
  v1/src/main/java/com/google/cloud/teleport/bigtable/AvroToBigtable.java
  v1/src/main/java/com/google/cloud/teleport/bigtable/ParquetToBigtable.java
  v1/src/main/java/com/google/cloud/teleport/templates/BulkCompressor.java
  v1/src/main/java/com/google/cloud/teleport/templates/BulkDecompressor.java
  v1/src/main/java/com/google/cloud/teleport/templates/DLPTextToBigQueryStreaming.java
  v1/src/main/java/com/google/cloud/teleport/templates/ImportJobPlaceholder.java
  v1/src/main/java/com/google/cloud/teleport/templates/TextIOToBigQuery.java
  v1/src/main/java/com/google/cloud/teleport/templates/TextToPubsub.java
  v1/src/main/java/com/google/cloud/teleport/templates/WordCount.java
  v2/common/src/main/java/com/google/cloud/teleport/v2/transforms/AvroConverters.java
  v2/common/src/main/java/com/google/cloud/teleport/v2/transforms/CsvConverters.java
  v2/common/src/main/java/com/google/cloud/teleport/v2/transforms/ParquetConverters.java
  v2/common/src/main/java/com/google/cloud/teleport/v2/transforms/PythonTextTransformer.java
  v2/datastream-to-mongodb/src/main/java/com/google/cloud/teleport/v2/templates/DataStreamToMongoDB.java
  v2/datastream-to-postgres/src/main/java/com/google/cloud/teleport/v2/templates/DataStreamToPostgres.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/DLPTextToBigQueryStreaming.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/options/Neo4jFlexTemplateOptions.java
  v2/mongodb-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/mongodb/options/MongoDbToBigQueryOptions.java
Labels: size/M

#1260 Skip integration tests if unit tests fail
  .github/workflows/java-pr.yml
Labels: size/XS

#1247 Add Streaming Mode Template parameters
  metadata/src/main/java/com/google/cloud/teleport/metadata/TemplateParameter.java
  plugins/core-plugin/src/main/java/com/google/cloud/teleport/plugin/model/ImageSpecMetadata.java
  plugins/core-plugin/src/main/java/com/google/cloud/teleport/plugin/model/TemplateDefinitions.java
  v2/common/src/main/java/com/google/cloud/teleport/v2/utils/BigQueryIOUtils.java
  v2/common/src/main/java/com/google/cloud/teleport/v2/utils/StreamingModeUtils.java
Labels: size/M

#1255 Support create disposition and assign BQ schema for JdbcToBQ template
  v2/jdbc-to-googlecloud/README_Jdbc_to_BigQuery_Flex.md
  v2/jdbc-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/options/JdbcToBigQueryOptions.java
  v2/jdbc-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/JdbcToBigQuery.java
Labels: Google LGTM, size/M

#1262 Change JVM config to prefer IPv4 stack
  .mvn/jvm.config
Labels: size/XS

#1230 Add pipeline spec parameter to YAML Template
  python/README_Yaml_Template.md
  python/src/main/java/com/google/cloud/teleport/templates/python/YAMLTemplate.java
  python/src/main/python/yaml-template/main.py
  python/src/test/java/com/google/cloud/teleport/templates/python/YAMLTemplateIT.java
Labels: size/L

#1253 Adding Maven artifacts handling/usage to README
  README.md
Labels: size/M

#1261 Add support for streaming modes
  v1/src/main/java/com/google/cloud/teleport/templates/PubSubToBigQuery.java
  v1/src/main/java/com/google/cloud/teleport/templates/PubSubToSplunk.java
  v1/src/main/java/com/google/cloud/teleport/templates/PubsubToPubsub.java
  v1/src/main/java/com/google/cloud/teleport/templates/PubsubToText.java
  v1/src/main/java/com/google/cloud/teleport/templates/TextToPubsubStream.java
  v2/datastream-to-bigquery/src/main/java/com/google/cloud/teleport/v2/templates/DataStreamToBigQuery.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/PubSubToBigQuery.java
  v2/kafka-to-bigquery/src/main/java/com/google/cloud/teleport/v2/templates/KafkaToBigQuery.java
Labels: size/M

#1266 Set Go version to 1.21
  .github/workflows/go-pr.yml
  cicd/go.mod
Labels: Google LGTM, size/XS

#1274 Include file name when throwing
  v2/datastream-common/src/main/java/com/google/cloud/teleport/v2/datastream/sources/ReadFileRangesFn.java
Labels: Google LGTM, size/XS

#1275 Prevent test flake due to Beam's ConvertHelpers thread unsafety
  v2/kafka-to-bigquery/src/test/java/com/google/cloud/teleport/v2/templates/KafkaToBigQueryAvroIT.java
Labels: size/XS

#1223 DataStream to spanner sample integration test
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerIT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerITBase.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerSimpleIT.java
  v2/datastream-to-spanner/src/test/resources/DataStreamToSpannerSimpleIT/mysql-backfill-Movie.jsonl
  v2/datastream-to-spanner/src/test/resources/DataStreamToSpannerSimpleIT/mysql-backfill-Users.jsonl
  v2/datastream-to-spanner/src/test/resources/DataStreamToSpannerSimpleIT/mysql-cdc-Users.jsonl
  v2/datastream-to-spanner/src/test/resources/DataStreamToSpannerSimpleIT/mysql-schema.sql
  v2/datastream-to-spanner/src/test/resources/DataStreamToSpannerSimpleIT/mysql-session.json
  v2/datastream-to-spanner/src/test/resources/DataStreamToSpannerSimpleIT/spanner-schema.sql
Labels: Google LGTM, size/XL

#1256 Bigtable to vector embeddings
  v1/README_Cloud_Bigtable_to_Vector_Embeddings.md
  v1/src/main/java/com/google/cloud/teleport/bigtable/BigtableToVectorEmbeddings.java
  v1/src/test/java/com/google/cloud/teleport/bigtable/BigtableToVectorEmbeddingsTest.java
  v1/src/test/java/com/google/cloud/teleport/bigtable/TestUtils.java
  v1/src/test/java/com/google/cloud/teleport/templates/BigtableToVectorEmbeddingsIT.java
Labels: Google LGTM, size/XXL

#1281 Hide the BigQuery Atleast Once flag in the UI and add E2E tests for templates with ALO support
  v1/src/test/java/com/google/cloud/teleport/templates/PubSubToSplunkIT.java
  v1/src/test/java/com/google/cloud/teleport/templates/PubsubToBigQueryLT.java
  v1/src/test/java/com/google/cloud/teleport/templates/PubsubToPubsubLT.java
  v1/src/test/java/com/google/cloud/teleport/templates/PubsubToTextIT.java
  v1/src/test/java/com/google/cloud/teleport/templates/TextToPubsubStreamLT.java
  v2/datastream-to-bigquery/src/main/java/com/google/cloud/teleport/v2/templates/DataStreamToBigQuery.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/PubSubToBigQuery.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/PubsubToBigQueryLT.java
  v2/kafka-to-bigquery/src/main/java/com/google/cloud/teleport/v2/templates/KafkaToBigQuery.java
  v2/kafka-to-bigquery/src/test/java/com/google/cloud/teleport/v2/templates/KafkaToBigQueryIT.java
Labels: size/L

#1285 minor fixes
  v1/README_Cloud_Bigtable_to_Vector_Embeddings.md
  v1/src/main/java/com/google/cloud/teleport/bigtable/BigtableToVectorEmbeddings.java
  v1/src/test/java/com/google/cloud/teleport/bigtable/BigtableToVectorEmbeddingsTest.java
  v1/src/test/java/com/google/cloud/teleport/templates/BigtableToVectorEmbeddingsIT.java
Labels: Google LGTM, size/M

#1283 Remove unneeded transaction configuration
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/database/Neo4jConnection.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/transforms/Neo4jBlockingUnwindFn.java
Labels: Google LGTM, size/S

#1265 [Fix Bug 1252] Cloud_Spanner_to_GCS_Avro failing on genarated fields
  v1/src/main/java/com/google/cloud/teleport/spanner/SpannerRecordConverter.java
Labels: Google LGTM, size/XS

#1284 Remove Cypher DSL for now
  v2/googlecloud-to-neo4j/pom.xml
Labels: Google LGTM, size/XS

#1290 Fixing Exceptions for PG SPANNER.COMMIT_TIMESTAMP
  v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/datastream/ChangeEventConvertor.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/type/Type.java
Labels: Google LGTM, size/XS

#1286 Set projectId on SpannerConfig to prevent DirectRunner issues
  v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/DataStreamToSpanner.java
Labels: size/XS

#1289 Annotate PropertyMappingsIT as NotThreadSafe, fix flake
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/templates/PropertyMappingsIT.java
Labels: size/XS

#1287 Fix NPE on PipelineOperator
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/dataflow/DirectRunnerClient.java
Labels: size/XS

#1291 Add Cloud SQL socket factory as dependencies
  pom.xml
  v2/mysql-to-googlecloud/pom.xml
  v2/postgresql-to-googlecloud/pom.xml
Labels: size/S

#1293 rename row_key to _key
  v1/README_Cloud_Bigtable_to_Vector_Embeddings.md
  v1/src/main/java/com/google/cloud/teleport/bigtable/BigtableToVectorEmbeddings.java
  v1/src/test/java/com/google/cloud/teleport/bigtable/BigtableToVectorEmbeddingsTest.java
  v1/src/test/java/com/google/cloud/teleport/templates/BigtableToVectorEmbeddingsIT.java
Labels: Google LGTM, size/M

#1269 Add support to load CSV files in GCS to BigQuery.
  v1/src/main/java/com/google/cloud/teleport/templates/CSVToBigQuery.java
  v1/src/main/java/com/google/cloud/teleport/templates/common/CsvConverters.java
Labels: Google LGTM, size/XL

#1294 [TextToDatastore Template] Remove unused parameters from metadata.
  v1/src/main/java/com/google/cloud/teleport/templates/TextToDatastore.java
Labels: Google LGTM, size/S

#1263 Generate dependencies for template specific terraform modules based on Google Provider registry schema
  cicd/cmd/run-terraform-schema/README.md
  cicd/cmd/run-terraform-schema/consts_vars/consts_vars.go
  cicd/cmd/run-terraform-schema/describe/command.go
  cicd/cmd/run-terraform-schema/download/command.go
  cicd/cmd/run-terraform-schema/generate/command.go
  cicd/cmd/run-terraform-schema/generate/freemarker.go
  cicd/cmd/run-terraform-schema/main.go
  cicd/go.mod
  cicd/go.sum
  cicd/internal/terraform/filter.go
  cicd/internal/terraform/filter_test.go
  cicd/internal/terraform/freemarker_preresource_extra.ftl
  cicd/internal/terraform/freemarker_resource_extra.ftl
  cicd/internal/terraform/freemarker_template_path_classic.ftl
  cicd/internal/terraform/freemarker_template_path_flex.ftl
  cicd/internal/terraform/header.tmpl
  cicd/internal/terraform/matcher.go
  cicd/internal/terraform/matcher_test.go
  cicd/internal/terraform/module.tmpl
  cicd/internal/terraform/provider_google.tmpl
  cicd/internal/terraform/provider_google_beta.tmpl
  cicd/internal/terraform/schemas/google-beta.json
  cicd/internal/terraform/schemas/google.json
  cicd/internal/terraform/schemas/schemas.go
  cicd/internal/terraform/templates.go
  cicd/internal/terraform/templates_test.go
  cicd/internal/terraform/variable.tmpl
  plugins/core-plugin/src/main/resources/terraform-classic-template.tf
  plugins/core-plugin/src/main/resources/terraform-flex-template.tf
Labels: Google LGTM, size/XXL

#1298 Update go version in action.yml
  .github/actions/setup-env/action.yml
Labels: Google LGTM, size/XS

#1296 Templates Maven Plugin: bugfixes and staging improvements.
  metadata/src/main/java/com/google/cloud/teleport/metadata/TemplateParameter.java
  plugins/core-plugin/src/main/java/com/google/cloud/teleport/plugin/model/ImageSpec.java
  plugins/core-plugin/src/main/java/com/google/cloud/teleport/plugin/model/ImageSpecParameter.java
  plugins/core-plugin/src/main/java/com/google/cloud/teleport/plugin/model/TemplateDefinitions.java
  plugins/core-plugin/src/test/java/com/google/cloud/teleport/plugin/TemplateSpecsGeneratorTest.java
  plugins/core-plugin/src/test/java/com/google/cloud/teleport/plugin/sample/AtoBOk.java
  plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesStageMojo.java
  pom.xml
Labels: Google LGTM, size/L

#1299 change separator ; to ->
  v1/README_Cloud_Bigtable_to_Vector_Embeddings.md
  v1/src/main/java/com/google/cloud/teleport/bigtable/BigtableToVectorEmbeddings.java
  v1/src/test/java/com/google/cloud/teleport/bigtable/BigtableToVectorEmbeddingsTest.java
  v1/src/test/java/com/google/cloud/teleport/templates/BigtableToVectorEmbeddingsIT.java
Labels: Google LGTM, size/M

#1301 Templates Maven Plugin: Flex template staging improvements.
  plugins/core-plugin/src/main/java/com/google/cloud/teleport/plugin/TemplateSpecsGenerator.java
  plugins/core-plugin/src/main/java/com/google/cloud/teleport/plugin/model/ImageSpecMetadata.java
Labels: Google LGTM, size/M

#1302 add privateConnectivity to TestProperties for Datastream IT's
  .github/workflows/java-pr.yml
  .github/workflows/load-tests.yml
  .github/workflows/release.yml
  cicd/cmd/run-it-smoke-tests/main.go
  cicd/cmd/run-it-tests/main.go
  cicd/cmd/run-load-tests/main.go
  cicd/internal/flags/it-flags.go
Labels: size/M

#1295 Add E2E tests for DatastreamToBigQuery
  v2/datastream-to-bigquery/pom.xml
  v2/datastream-to-bigquery/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToBigQueryIT.java
Labels: size/L

#1303 Expose fetchSize option to DataplexJdbcIngestion template
  v2/dataplex/src/main/java/com/google/cloud/teleport/v2/options/DataplexJdbcIngestionOptions.java
  v2/dataplex/src/main/java/com/google/cloud/teleport/v2/templates/DataplexJdbcIngestion.java
Labels: Google LGTM, size/M
