Repository GoogleCloudPlatform/DataflowTemplates, pull requests merged in 2024-08, with the labels that each got.

#1749 unit test for source writer
  .github/CODEOWNERS
  .github/codecov.yml
  .github/workflows/spanner-pr.yml
  cicd/internal/flags/common-flags.go
  cicd/internal/flags/common-flags_test.go
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/transforms/SourceWriterFn.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/transforms/SourceWriterFnTest.java
  v2/spanner-to-sourcedb/src/test/resources/sourceWriterUTSession.json
Labels: size/XXL

#1760 Adding autoReconnect parameters to jdbc URL for bulk migration
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/options/OptionsToConfigBuilder.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/config/defaults/MySqlConfigDefaults.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/options/OptionsToConfigBuilderTest.java
Labels: size/S

#1740 pipeline parameter updates
  v2/sourcedb-to-spanner/README.md
  v2/sourcedb-to-spanner/README_Sourcedb_to_Spanner.md
  v2/sourcedb-to-spanner/README_Sourcedb_to_Spanner_Flex.md
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/options/OptionsToConfigBuilder.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/options/SourceDbToSpannerOptions.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/PipelineController.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/SourceDbToSpanner.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/options/OptionsToConfigBuilderTest.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/SourceDbToSpannerITBase.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/SourceDbToSpannerTest.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/schema/SessionBasedMapper.java
  v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/schema/SessionBasedMapperTest.java
Labels: size/L

#1762 Add App Profile ID to CBT Dataflow Templates: Bigtable to Avro/Parquet/JSON
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/bigtable/BigtableResourceManagerUtils.java
  v1/README_Cloud_Bigtable_to_GCS_Avro.md
  v1/README_Cloud_Bigtable_to_GCS_Json.md
  v1/README_Cloud_Bigtable_to_GCS_Parquet.md
  v1/src/main/java/com/google/cloud/teleport/bigtable/BigtableToAvro.java
  v1/src/main/java/com/google/cloud/teleport/bigtable/BigtableToJson.java
  v1/src/main/java/com/google/cloud/teleport/bigtable/BigtableToParquet.java
  v1/src/test/java/com/google/cloud/teleport/templates/BigtableToAvroIT.java
  v1/src/test/java/com/google/cloud/teleport/templates/BigtableToJsonIT.java
  v1/src/test/java/com/google/cloud/teleport/templates/BigtableToParquetIT.java
Labels: size/L

#1753 Disable flaky test StreamingDataGeneratorIT#testFakeMessagesToKafka
  v2/streaming-data-generator/src/test/java/com/google/cloud/teleport/v2/templates/StreamingDataGeneratorIT.java
Labels: size/XS

#1729 fix CdcToBigQueryChangeApplierPipelineIT debezium wait logic
  v2/cdc-parent/cdc-change-applier/src/test/java/com/google/cloud/dataflow/cdc/applier/CdcToBigQueryChangeApplierPipelineIT.java
Labels: Google LGTM, size/XS

#1747 DatastreamToSQL - log schema map details
  v2/datastream-to-sql/src/main/java/com/google/cloud/teleport/v2/templates/DataStreamToSQL.java
  v2/datastream-to-sql/src/main/java/com/google/cloud/teleport/v2/transforms/CreateDml.java
  v2/datastream-to-sql/src/main/java/com/google/cloud/teleport/v2/utils/DatastreamToDML.java
Labels: size/XS

#1766 code refactoring common code reuse
  v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/datastream/ChangeEventContext.java
  v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/datastream/ChangeEventConvertor.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/datastream/ChangeEventConvertorTest.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/convertors/ChangeEventSpannerConvertor.java
  v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/convertors/ChangeEventSpannerConvertorTest.java
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/transforms/SourceWriterFn.java
Labels: size/XL

#1733 docs: adding file for load testing data generation
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/README_Load_Testing.md
  v2/datastream-to-spanner/src/test/resources/DataStreamToSpannerLoadTesting/datagenerator-schema.json
  v2/datastream-to-spanner/src/test/resources/DataStreamToSpannerLoadTesting/mysql-schema.sql
  v2/streaming-data-generator/pom.xml
Labels: size/L

#1772 Script to generate shard-config.json
  v2/sourcedb-to-spanner/README.md
  v2/sourcedb-to-spanner/src/main/scripts/create_simple_shard_config.bash
Labels: size/L

#1674 fix: deprecating inputFilePattern
  v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/DataStreamToSpanner.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerIT.java
Labels: Google LGTM, size/M

#1775 Migrate from the deprecated Charsets constants (in Guava) to the StandardCharsets constants (in the JDK).
  plugins/core-plugin/src/test/java/com/google/cloud/teleport/plugin/PythonDockerfileGeneratorTest.java
  plugins/core-plugin/src/test/java/com/google/cloud/teleport/plugin/XlangDockerfileGeneratorTest.java
  plugins/core-plugin/src/test/java/com/google/cloud/teleport/plugin/YamlDockerfileGeneratorTest.java
  v1/src/main/java/com/google/cloud/teleport/templates/DLPTextToBigQueryStreaming.java
  v1/src/main/java/com/google/cloud/teleport/templates/TextToBigQueryStreaming.java
  v1/src/test/java/com/google/cloud/teleport/templates/DLPTextToBigQueryStreamingTest.java
  v1/src/test/java/com/google/cloud/teleport/templates/common/ErrorConvertersTest.java
  v2/common/src/test/java/com/google/cloud/teleport/v2/transforms/ErrorConvertersTest.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/DLPTextToBigQueryStreaming.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/DLPTextToBigQueryStreamingTest.java
  v2/googlecloud-to-splunk/src/test/java/com/google/cloud/teleport/v2/templates/GCSToSplunkTest.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/dialectadapter/mysql/MysqlDialectAdapter.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/uniformsplitter/stringmapper/TestUtils.java
Labels: size/M

#1763 Fix Import/Export Template for Proto type.
  v1/src/main/java/com/google/cloud/teleport/spanner/common/NameUtils.java
  v1/src/main/java/com/google/cloud/teleport/spanner/common/SizedType.java
  v1/src/main/java/com/google/cloud/teleport/spanner/ddl/Ddl.java
  v1/src/main/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScanner.java
  v1/src/test/java/com/google/cloud/teleport/spanner/AvroSchemaToDdlConverterTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ExportTransformTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ImportFromAvroTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/common/SizedTypeTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ddl/DdlTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScannerIT.java
  v1/src/test/proto/protos_test.proto
Labels: size/L

#1768 Added support for search indexes
  v1/src/main/java/com/google/cloud/teleport/spanner/AvroSchemaToDdlConverter.java
  v1/src/main/java/com/google/cloud/teleport/spanner/AvroUtil.java
  v1/src/main/java/com/google/cloud/teleport/spanner/DdlToAvroSchemaConverter.java
  v1/src/main/java/com/google/cloud/teleport/spanner/common/SizedType.java
  v1/src/main/java/com/google/cloud/teleport/spanner/common/Type.java
  v1/src/main/java/com/google/cloud/teleport/spanner/ddl/Column.java
  v1/src/main/java/com/google/cloud/teleport/spanner/ddl/Index.java
  v1/src/main/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScanner.java
  v1/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerSchema.java
  v1/src/test/java/com/google/cloud/teleport/spanner/AvroSchemaToDdlConverterTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/DdlToAvroSchemaConverterTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ExportPipelineIT.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ImportPipelineIT.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScannerIT.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScannerTest.java
  v1/src/test/java/org/apache/beam/sdk/io/gcp/spanner/SpannerSchemaTest.java
Labels: size/L

#1777 Bump Beam to 2.58.0
  plugins/core-plugin/pom.xml
  pom.xml
  v2/googlecloud-to-googlecloud/README_Bigtable_Change_Streams_to_Vector_Search.md
  v2/googlecloud-to-googlecloud/README_Cloud_Spanner_to_BigQuery_Flex.md
  v2/googlecloud-to-googlecloud/README_Pubsub_to_Jdbc.md
  v2/googlecloud-to-googlecloud/README_Stream_GCS_Text_to_BigQuery_Flex.md
  v2/googlecloud-to-googlecloud/README_Stream_GCS_Text_to_BigQuery_Xlang.md
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/options/SpannerToBigQueryOptions.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/SpannerToBigQuery.java
Labels: size/M

#1523 Update release workflow
  .github/actions/publish-site-report/action.yml
  .github/workflows/java-pr.yml
  .github/workflows/release.yml
  cicd/internal/flags/it-flags.go
Labels: size/M

#1778 fix: serialization issues with Cypher actions
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/actions/function/CypherActionFn.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/actions/preload/PreloadCypherAction.java
Labels: size/S

#1776 Added support for PARTITION BY and ORDER BY in search indexes
  v1/src/main/java/com/google/cloud/teleport/spanner/ddl/Index.java
  v1/src/main/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScanner.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ImportPipelineIT.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScannerIT.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScannerTest.java
Labels: size/M

#1773 JdbcToBigQuery: Support loading the source query from Cloud Storage.
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/bigquery/BigQueryResourceManagerUtils.java
  it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/bigquery/BigQueryResourceManagerUtilsTest.java
  v2/common/src/main/java/com/google/cloud/teleport/v2/utils/GCSAwareValueProvider.java
  v2/jdbc-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/options/JdbcToBigQueryOptions.java
  v2/jdbc-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/JdbcToBigQuery.java
  v2/jdbc-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/JdbcToBigQueryIT.java
Labels: size/L

#1785 Enable default splunk and confluent dependencies
  .github/actions/publish-site-report/action.yml
  .github/workflows/release.yml
  cicd/internal/workflows/maven-workflows.go
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/TemplateTestBase.java
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/dataflow/FlexTemplateDataflowJobResourceManager.java
  it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/dataflow/FlexTemplateDataflowJobResourceManagerTest.java
  pom.xml
  v1/pom.xml
  v2/pom.xml
Labels: size/M

#1786 Finetuning DbCp2 Parameters for Bulk Reader for string tall table connection drop issue.
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/JdbcDataSource.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/JdbcIoWrapper.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/config/JdbcIOWrapperConfig.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/config/defaults/MySqlConfigDefaults.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/JdbcDataSourceTest.java
Labels: size/L

#1784 KafkaToBigQueryFlex Template: Expose source message offset in DLQ metadata (for Json format only)
  v2/common/src/main/java/com/google/cloud/teleport/v2/transforms/ErrorConverters.java
  v2/kafka-common/src/main/java/com/google/cloud/teleport/v2/kafka/transforms/KafkaRecordErrorConverters.java
  v2/kafka-common/src/main/java/com/google/cloud/teleport/v2/kafka/transforms/KafkaTransform.java
  v2/kafka-to-bigquery/src/main/java/com/google/cloud/teleport/v2/templates/KafkaToBigQuery.java
  v2/kafka-to-bigquery/src/main/java/com/google/cloud/teleport/v2/templates/KafkaToBigQueryFlex.java
  v2/kafka-to-bigquery/src/main/java/com/google/cloud/teleport/v2/transforms/StringMessageToTableRow.java
  v2/kafka-to-bigquery/src/test/java/com/google/cloud/teleport/v2/templates/KafkaToBigQueryFlexJsonIT.java
Labels: size/L

#1781 chore: use the `!NOTE` notation in `azure-eventhub-to-pubsub`
  v2/azure-eventhub-to-pubsub/README.md
Labels: size/XS

#1780 chore: use backticks for `main` in README
  README.md
Labels: size/XS

#1782 chore: fix spacing in python comment
  v1/src/main/python/transform.py
Labels: size/XS

#1789 Support Timestamp in proto to bigquery schema conversion
  v2/common/pom.xml
  v2/common/src/main/java/com/google/cloud/teleport/v2/utils/SchemaUtils.java
  v2/common/src/test/java/com/google/cloud/teleport/v2/utils/SchemaUtilsTest.java
  v2/common/src/test/proto/proto_definition.proto
Labels: size/M

#1779 Support PLACEMENT schema objects in Spanner's import/export templates
  v1/pom.xml
  v1/src/main/java/com/google/cloud/teleport/spanner/AvroSchemaToDdlConverter.java
  v1/src/main/java/com/google/cloud/teleport/spanner/AvroUtil.java
  v1/src/main/java/com/google/cloud/teleport/spanner/DdlToAvroSchemaConverter.java
  v1/src/main/java/com/google/cloud/teleport/spanner/ExportTransform.java
  v1/src/main/java/com/google/cloud/teleport/spanner/ImportTransform.java
  v1/src/main/java/com/google/cloud/teleport/spanner/ddl/DatabaseOptionAllowlist.java
  v1/src/main/java/com/google/cloud/teleport/spanner/ddl/Ddl.java
  v1/src/main/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScanner.java
  v1/src/main/java/com/google/cloud/teleport/spanner/ddl/Placement.java
  v1/src/main/proto/export.proto
  v1/src/test/java/com/google/cloud/teleport/spanner/AvroSchemaToDdlConverterTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/DdlToAvroSchemaConverterTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ExportTransformTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ImportFromAvroTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/SpannerServerResource.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScannerIT.java
Labels: size/XL

#1802 TF: Update permissions and check if IAM API is enabled
  v2/datastream-to-spanner/terraform/samples/mysql-end-to-end/README.md
  v2/datastream-to-spanner/terraform/samples/mysql-end-to-end/terraform.tf
  v2/datastream-to-spanner/terraform/samples/mysql-sharded-end-to-end/README.md
  v2/datastream-to-spanner/terraform/samples/mysql-sharded-end-to-end/terraform.tf
  v2/datastream-to-spanner/terraform/samples/pre-configured-conn-profiles/README.md
  v2/datastream-to-spanner/terraform/samples/pre-configured-conn-profiles/terraform.tf
Labels: size/S

#1788 Feat: Deploy Spanner Migration Tool for PostgreSQL with Terraform
  v2/datastream-to-spanner/terraform/samples/README.md
  v2/datastream-to-spanner/terraform/samples/postgresql-end-to-end/README.md
  v2/datastream-to-spanner/terraform/samples/postgresql-end-to-end/main.tf
  v2/datastream-to-spanner/terraform/samples/postgresql-end-to-end/outputs.tf
  v2/datastream-to-spanner/terraform/samples/postgresql-end-to-end/terraform.tf
  v2/datastream-to-spanner/terraform/samples/postgresql-end-to-end/terraform.tfvars
  v2/datastream-to-spanner/terraform/samples/postgresql-end-to-end/terraform_simple.tfvars
  v2/datastream-to-spanner/terraform/samples/postgresql-end-to-end/variables.tf
Labels: size/XXL

#1796 updating the default string to gson object for mongodb to bigquery da…
  v2/mongodb-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/mongodb/templates/MongoDbUtils.java
Labels: size/S

#1791 Bump hadoop version
  pom.xml
Labels: size/XS

#1792 Add support for the PLACEMENT KEY column constraint in Spanner import/export templates
  v1/src/main/java/com/google/cloud/teleport/spanner/AvroSchemaToDdlConverter.java
  v1/src/main/java/com/google/cloud/teleport/spanner/AvroUtil.java
  v1/src/main/java/com/google/cloud/teleport/spanner/DdlToAvroSchemaConverter.java
  v1/src/main/java/com/google/cloud/teleport/spanner/ddl/Column.java
  v1/src/main/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScanner.java
  v1/src/test/java/com/google/cloud/teleport/spanner/AvroSchemaToDdlConverterTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/DdlToAvroSchemaConverterTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScannerIT.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScannerTest.java
Labels: Google LGTM, size/L

#1806 secret manager integration added
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/JdbcIoWrapper.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/utils/ShardFileReader.java
  v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/utils/ShardFileReaderTest.java
  v2/spanner-common/src/test/resources/bulk-migration-shards-secret.json
Labels: size/L

#1808 Disable staging Spanner tests on release
  .github/workflows/release.yml
Labels: size/XS

#1799 DLQ implementation
  v2/spanner-to-sourcedb/README_Spanner_to_SourceDb.md
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/SpannerToSourceDb.java
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/changestream/ChangeStreamErrorRecord.java
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/changestream/TrimmedShardedDataChangeRecord.java
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/constants/Constants.java
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/transforms/AssignShardIdFn.java
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/transforms/ConvertChangeStreamErrorRecordToFailsafeElementFn.java
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/transforms/ConvertDlqRecordToTrimmedShardedDataChangeRecordFn.java
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/transforms/SourceWriterFn.java
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/transforms/SourceWriterTransform.java
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/transforms/UpdateDlqMetricsFn.java
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/utils/InputRecordProcessor.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/transforms/SourceWriterFnTest.java
Labels: size/XL

#1814 Adding CodeOwners specification for bigtable
  .github/CODEOWNERS
Labels: size/S

#1754 feat: Adds SourceDBToSpanner PostgreSQL Adapter
  v2/sourcedb-to-spanner/pom.xml
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/options/OptionsToConfigBuilder.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/options/SourceDbToSpannerOptions.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/dialectadapter/postgresql/PostgreSQLDialectAdapter.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/dialectadapter/postgresql/package-info.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/JdbcIoWrapper.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/config/JdbcIOWrapperConfig.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/config/SQLDialect.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/config/defaults/PostgreSQLConfigDefaults.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/rowmapper/JdbcSourceRowMapper.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/rowmapper/provider/PostgreSQLJdbcValueMappings.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/schema/SourceTableSchema.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/schema/typemapping/UnifiedTypeMapper.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/schema/typemapping/provider/PostgreSQLMappingProvider.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/PipelineController.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/transformer/SourceRowToMutationDoFn.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/options/OptionsToConfigBuilderTest.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/dialectadapter/postgresql/PostgreSQLDialectAdapterTest.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/rowmapper/JdbcSourceRowMapperTest.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/schema/SchemaTestUtils.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/schema/SourceTableSchemaTest.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/schema/typemapping/provider/PostgreSQLMappingProviderTest.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/SingleShardIT.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/SourceDbToSpannerITBase.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/postgresql/IdentitySchemaMapperIT.java
  v2/sourcedb-to-spanner/src/test/resources/SchemaMapperIT/company-postgresql-schema.sql
  v2/sourcedb-to-spanner/src/test/resources/SchemaMapperIT/company-spanner-schema-pg.sql
  v2/sourcedb-to-spanner/src/test/resources/SingleShardWithTransformation/mysql-schema.sql
  v2/sourcedb-to-spanner/src/test/resources/SingleShardWithTransformation/postgresql-schema.sql
Labels: size/XXL

#1818 DLQ for bulk to severe folder.
  v2/sourcedb-to-spanner/README.md
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/MigrateTableTransform.java
Labels: size/S

#1821 remove release branch lowercase logic
  .github/workflows/release.yml
Labels: size/XS

#1822 test release
  .github/workflows/release.yml
Labels: size/M

#1823 Jkinard/releasev3
  .github/workflows/release.yml
Labels: size/M

#1820 BigTable to Parquet: only set numShards for >0
  v1/src/main/java/com/google/cloud/teleport/bigtable/BigtableToParquet.java
Labels: size/S

#1824 Jkinard/releasev3
  .github/workflows/release.yml
Labels: size/XS

#1827 Update release to test-only
  .github/workflows/release.yml
Labels: size/L

#1828 Delete release branch upon retry
  .github/workflows/release.yml
Labels: size/S

#1831 Reset release back
  .github/workflows/release.yml
Labels: size/S

#1829 Rollback YamlTemplate to 2.57
  plugins/core-plugin/src/main/resources/Dockerfile-template-yaml
  python/pom.xml
  python/src/test/java/com/google/cloud/teleport/templates/python/PubSubToBigQueryYamlIT.java
  python/src/test/resources/PubSubToBigQueryYamlIT.yaml
Labels: size/L
