Repository GoogleCloudPlatform/DataflowTemplates, pull requests merged in 2024-09, with the labels that each got.

#1825 DLQ UT
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/transforms/ConvertChangeStreamErrorRecordToFailsafeElementFnTest.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/transforms/ConvertDlqRecordToTrimmedShardedDataChangeRecordFnTest.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/transforms/SourceWriterFnTest.java
Labels: size/L

#1798 Add Datastream Owners
  .github/CODEOWNERS
Labels: size/XS

#1832 Removed order attribute from search index tokenlist key parts
  v1/src/main/java/com/google/cloud/teleport/spanner/ddl/IndexColumn.java
  v1/src/main/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScanner.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ExportPipelineIT.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScannerIT.java
Labels: Google LGTM, size/S

#1826 Do not run spanner-pr tests in Java PR
  .github/workflows/java-pr.yml
  .github/workflows/spanner-pr.yml
  cicd/internal/flags/common-flags.go
  cicd/internal/flags/common-flags_test.go
Labels: size/M

#1730 Add IT tests for handling schema update during spanner cdc to big query pipeline running
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/bigquery/BigQueryResourceManager.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/spannerchangestreamstobigquery/BigQueryDynamicDestinations.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/spannerchangestreamstobigquery/FailsafeModJsonToTableRowTransformer.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/spannerchangestreamstobigquery/SpannerChangeStreamsToBigQuery.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/spannerchangestreamstobigquery/model/Mod.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/spannerchangestreamstobigquery/model/ModColumnType.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/spannerchangestreamstobigquery/model/TrackedSpannerTable.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/spannerchangestreamstobigquery/schemautils/OptionsUtils.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/spannerchangestreamstobigquery/schemautils/SchemaUpdateUtils.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/spannerchangestreamstobigquery/schemautils/SpannerChangeStreamsUtils.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/spannerchangestreamstobigquery/schemautils/SpannerToBigQueryUtils.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/spannerchangestreamstobigquery/schemautils/TypesUtils.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/spannerchangestreamstobigquery/BigQueryDynamicDestinationsTest.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/spannerchangestreamstobigquery/FailsafeModJsonToTableRowTransformerTest.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/spannerchangestreamstobigquery/SchemaUpdateUtilsTest.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/spannerchangestreamstobigquery/SchemaUtilsTest.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/spannerchangestreamstobigquery/SpannerChangeStreamsToBigQueryIT.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/spannerchangestreamstobigquery/TestUtils.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/spannerchangestreamstobigquery/TypesUtilsTest.java
Labels: size/XXL

#1842 add spanner-migrations-team as CODEOWNERS for v2/datastream-common
  .github/CODEOWNERS
Labels: size/XS

#1838 Fix a few dependency conflicts
  it/pom.xml
  structured-logging/pom.xml
  v2/googlecloud-to-googlecloud/pom.xml
Labels: size/S

#1816 [KafkaToBigQuery & KafkaToGcs] - Add OAuth Authentication Support For Schema Registries
  v2/kafka-common/src/main/java/com/google/cloud/teleport/v2/kafka/options/SchemaRegistryOptions.java
  v2/kafka-common/src/main/java/com/google/cloud/teleport/v2/kafka/transforms/AvroDynamicTransform.java
  v2/kafka-common/src/main/java/com/google/cloud/teleport/v2/kafka/transforms/KafkaRecordToGenericRecordFailsafeElementFn.java
  v2/kafka-common/src/main/java/com/google/cloud/teleport/v2/kafka/utils/KafkaConfig.java
  v2/kafka-common/src/main/java/com/google/cloud/teleport/v2/kafka/values/KafkaAuthenticationMethod.java
  v2/kafka-to-gcs/src/main/java/com/google/cloud/teleport/v2/transforms/AvroWriteTransform.java
  v2/kafka-to-gcs/src/main/java/com/google/cloud/teleport/v2/transforms/WriteTransform.java
Labels: size/L

#1756 Load test observability: automated regression detection framework
  .github/ISSUE_TEMPLATE/spanner-load-test-failure-issue-template.md
  .github/workflows/spanner-load-tests.yml
  cicd/cmd/run-load-test-observer/main.go
  cicd/internal/workflows/maven-workflows.go
  lt/observability/pom.xml
  lt/observability/src/test/java/com/google/cloud/teleport/lt/AssertAll.java
  lt/observability/src/test/java/com/google/cloud/teleport/lt/dataset/bigquery/BigQueryPerfDataset.java
  lt/observability/src/test/java/com/google/cloud/teleport/lt/dataset/bigquery/BigQueryPerfDatasetFetcher.java
  lt/observability/src/test/java/com/google/cloud/teleport/lt/dataset/bigquery/PerfResultRow.java
  lt/observability/src/test/java/com/google/cloud/teleport/lt/rules/DetectMetricDeviationConditionCheck.java
  lt/observability/src/test/java/com/google/cloud/teleport/lt/spanner/DataStreamToSpannerLTObserver.java
  lt/pom.xml
  pom.xml
Labels: size/XL

#1767 Fix for custom logical types in DatastreamIO
  pom.xml
  v2/datastream-common/src/main/java/com/google/cloud/teleport/v2/datastream/transforms/FormatDatastreamRecordToJson.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerDDLIT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerShardedMigrationWithMigrationShardIdColumnIT.java
  v2/gcs-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/GCSToSourceDbWithoutReaderIT.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/CustomTransformationsNonShardedIT.java
  v2/spanner-custom-shard/src/main/java/com/custom/CustomTransformationWithShardForBulkIT.java
  v2/spanner-custom-shard/src/main/java/com/custom/CustomTransformationWithShardForLiveIT.java
Labels: size/L

#1835 Datastream->BigQuery Template Merge Failure
  v2/datastream-common/src/main/java/com/google/cloud/teleport/v2/datastream/values/DatastreamRow.java
  v2/datastream-common/src/test/java/com/google/cloud/teleport/v2/datastream/values/DatastreamRowTest.java
Labels: size/M

#1771 refactoring load tests for Spanner
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpanner100GbLT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerLTBase.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/loadtesting/DataStreamToSpanner100GbLT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/loadtesting/DataStreamToSpannerLTBase.java
Labels: size/XL

#1845 Revert "Fix for custom logical types in DatastreamIO"
  pom.xml
  v2/datastream-common/src/main/java/com/google/cloud/teleport/v2/datastream/transforms/FormatDatastreamRecordToJson.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerDDLIT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerShardedMigrationWithMigrationShardIdColumnIT.java
  v2/gcs-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/GCSToSourceDbWithoutReaderIT.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/CustomTransformationsNonShardedIT.java
  v2/spanner-custom-shard/src/main/java/com/custom/CustomTransformationWithShardForIT.java
  v2/spanner-custom-shard/src/main/java/com/custom/CustomTransformationWithShardForLiveIT.java
Labels: size/L

#1819 Terraform template to launch a sharded bulk migration
  .github/workflows/spanner-terraform-validator.yml
  v2/sourcedb-to-spanner/terraform/samples/multiple-jobs/README.md
  v2/sourcedb-to-spanner/terraform/samples/multiple-jobs/main.tf
  v2/sourcedb-to-spanner/terraform/samples/multiple-jobs/terraform.tf
  v2/sourcedb-to-spanner/terraform/samples/multiple-jobs/terraform.tfvars
  v2/sourcedb-to-spanner/terraform/samples/multiple-jobs/terraform_simple.tfvars
  v2/sourcedb-to-spanner/terraform/samples/multiple-jobs/variables.tf
  v2/sourcedb-to-spanner/terraform/samples/sharded-bulk-migration/README.md
  v2/sourcedb-to-spanner/terraform/samples/sharded-bulk-migration/main.tf
  v2/sourcedb-to-spanner/terraform/samples/sharded-bulk-migration/outputs.tf
  v2/sourcedb-to-spanner/terraform/samples/sharded-bulk-migration/terraform.tf
  v2/sourcedb-to-spanner/terraform/samples/sharded-bulk-migration/terraform.tfvars
  v2/sourcedb-to-spanner/terraform/samples/sharded-bulk-migration/terraform_simple.tfvars
  v2/sourcedb-to-spanner/terraform/samples/sharded-bulk-migration/variables.tf
  v2/sourcedb-to-spanner/terraform/samples/single-job-bulk-migration/README.md
  v2/sourcedb-to-spanner/terraform/samples/single-job-bulk-migration/main.tf
  v2/sourcedb-to-spanner/terraform/samples/single-job-bulk-migration/outputs.tf
  v2/sourcedb-to-spanner/terraform/samples/single-job-bulk-migration/terraform.tf
  v2/sourcedb-to-spanner/terraform/samples/single-job-bulk-migration/terraform.tfvars
  v2/sourcedb-to-spanner/terraform/samples/single-job-bulk-migration/terraform_simple.tfvars
  v2/sourcedb-to-spanner/terraform/samples/single-job-bulk-migration/variables.tf
Labels: size/XXL

#1850 Revert "updating the default string to gson object for mongodb to bigquery da…"
  v2/mongodb-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/mongodb/templates/MongoDbUtils.java
Labels: size/S

#1852 Update release process
  .github/workflows/release.yml
Labels: size/S

#1854 Sync hadoop version for v2/bigtable-changestream-to-hbase
  v2/bigtable-changestreams-to-hbase/pom.xml
Labels: size/XS

#1856 fix: fix for spanner load test
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/README_Load_Testing.md
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/loadtesting/DataStreamToSpannerLTBase.java
Labels: size/XS

#1853 Bump postgresql version to 42.6.1
  pom.xml
Labels: size/XS

#1769 Support populating Spanner source database id, instance id and a custom metadata field in Spanner CDC to Pub Sub template
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/options/SpannerChangeStreamsToPubSubOptions.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/SpannerChangeStreamsToPubSub.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/transforms/FileFormatFactorySpannerChangeStreamsToPubSub.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/transforms/WriteDataChangeRecordsToAvro.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/transforms/WriteDataChangeRecordsToJson.java
  v2/googlecloud-to-googlecloud/src/main/resources/schema/avro/datachangerecord.avsc
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/SpannerChangeStreamsToPubSubIT.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/transforms/WriteDataChangeRecordsToAvroTest.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/transforms/WriteDataChangeRecordsToGcsAvroTest.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/transforms/WriteDataChangeRecordsToJsonTest.java
Labels: size/XL

#1851 Fix for custom logical types in DatastreamIO
  pom.xml
  v2/datastream-common/src/main/java/com/google/cloud/teleport/v2/datastream/transforms/FormatDatastreamRecordToJson.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerDDLIT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerShardedMigrationWithMigrationShardIdColumnIT.java
  v2/gcs-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/GCSToSourceDbWithoutReaderIT.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/CustomTransformationsNonShardedIT.java
  v2/spanner-custom-shard/src/main/java/com/custom/CustomTransformationWithShardForBulkIT.java
  v2/spanner-custom-shard/src/main/java/com/custom/CustomTransformationWithShardForLiveIT.java
Labels: size/L

#1860 Make utc named timezone to "+00:00"
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/options/SourceDbToSpannerOptions.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/config/defaults/MySqlConfigDefaults.java
Labels: size/XS

#1863 feat: update pg index discovery query for 9.4+
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/dialectadapter/postgresql/PostgreSQLDialectAdapter.java
Labels: size/S

#1855 Add JSON userOption to MongoDbToBigQuery templates
  v2/mongodb-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/mongodb/options/MongoDbToBigQueryOptions.java
  v2/mongodb-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/mongodb/templates/MongoDbUtils.java
  v2/mongodb-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/mongodb/templates/MongoDbToBigQueryIT.java
Labels: size/L

#1864 Fixing isue of discovering unsigned types
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/dialectadapter/mysql/MysqlDialectAdapter.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/rowmapper/JdbcSourceRowMapper.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/dialectadapter/mysql/MysqlDialectAdapterTest.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataTypesIt.java
  v2/sourcedb-to-spanner/src/test/resources/DataTypesIt/data-types.sql
  v2/sourcedb-to-spanner/src/test/resources/DataTypesIt/spanner-schema.sql
Labels: size/L

#1839 Load test fixes and multiple PK mutation in same trx handling
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/SpannerToSourceDb.java
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/constants/Constants.java
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/transforms/AssignShardIdFn.java
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/transforms/SourceWriterFn.java
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/transforms/SourceWriterTransform.java
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/utils/ConnectionException.java
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/utils/ConnectionHelper.java
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/utils/InputRecordProcessor.java
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/utils/MySqlDao.java
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/utils/ShadowTableCreator.java
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/utils/ShadowTableRecord.java
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/utils/SpannerDao.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/transforms/SourceWriterFnTest.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/utils/ShadowTableCreatorTest.java
Labels: size/XL

#1869 fix: PG index cardinality estimate
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/dialectadapter/postgresql/PostgreSQLDialectAdapter.java
Labels: size/S

#1868 Auto-generate fully specified requirements
  .gitignore
  python/generate_all_dependencies.sh
  python/generate_dependencies.sh
  python/src/main/python/streaming-llm/base_requirements.txt
  python/src/main/python/streaming-llm/requirements.txt
  python/src/main/python/word-count-python/base_requirements.txt
  python/src/main/python/word-count-python/requirements.txt
  v1/src/main/python/base_requirements.txt
  v1/src/main/python/requirements.txt
Labels: size/XXL

#1867 Upgrade to Beam 2.59.0
  pom.xml
  v2/google-ads-to-googlecloud/pom.xml
  v2/google-ads-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/GoogleAdsToBigQuery.java
  v2/google-ads-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/transforms/GoogleAdsRowToReportRowJsonFn.java
  v2/google-ads-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/utils/GoogleAdsRateLimitPolicyFactory.java
  v2/google-ads-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/utils/GoogleAdsUtils.java
  v2/google-ads-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/transforms/GoogleAdsRowToReportRowJsonFnTest.java
  v2/google-ads-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/utils/GoogleAdsRateLimitPolicyFactoryTest.java
Labels: size/M

#1873 Improve bulk terraform template to work seamlessly
  v2/sourcedb-to-spanner/terraform/samples/sharded-bulk-migration/README.md
  v2/sourcedb-to-spanner/terraform/samples/sharded-bulk-migration/main.tf
  v2/sourcedb-to-spanner/terraform/samples/sharded-bulk-migration/terraform.tfvars
  v2/sourcedb-to-spanner/terraform/samples/sharded-bulk-migration/terraform_simple.tfvars
  v2/sourcedb-to-spanner/terraform/samples/sharded-bulk-migration/variables.tf
  v2/sourcedb-to-spanner/terraform/samples/single-job-bulk-migration/README.md
  v2/sourcedb-to-spanner/terraform/samples/single-job-bulk-migration/main.tf
  v2/sourcedb-to-spanner/terraform/samples/single-job-bulk-migration/terraform.tfvars
  v2/sourcedb-to-spanner/terraform/samples/single-job-bulk-migration/terraform_simple.tfvars
  v2/sourcedb-to-spanner/terraform/samples/single-job-bulk-migration/variables.tf
Labels: size/L

#1870 DlqRetry for bulk with the current retry flow
  v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/DataStreamToSpanner.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerTest.java
  v2/sourcedb-to-spanner/pom.xml
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/MigrateTableTransform.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/PipelineController.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/writer/DeadLetterQueue.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/writer/DeadLetterQueueTest.java
Labels: size/L

#1876 fixes for multi shard load test
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/transforms/SourceWriterFn.java
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/utils/ConnectionHelper.java
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/utils/InputRecordProcessor.java
Labels: size/S

#1874 Fix discommissioned upload artifact v2 action
  .github/actions/publish-site-report/action.yml
  .github/workflows/scorecards-analysis.yml
Labels: size/XS

#1809 Update codecov to block PRs lower than 80% coverage
  .github/codecov.yml
Labels: size/XS

#1858 Implementing Generic Spanner templates Load test observer
  lt/observability/pom.xml
  lt/observability/src/test/java/com/google/cloud/teleport/lt/AssertAll.java
  lt/observability/src/test/java/com/google/cloud/teleport/lt/dataset/bigquery/BigQueryPerfDatasetFetcher.java
  lt/observability/src/test/java/com/google/cloud/teleport/lt/rules/DetectMetricDeviationConditionCheck.java
  lt/observability/src/test/java/com/google/cloud/teleport/lt/spanner/DataStreamToSpannerLTObserver.java
  lt/observability/src/test/java/com/google/cloud/teleport/lt/spanner/GenericTemplateLTObserver.java
Labels: size/L

#1857 KafkaToBigQueryFlex: Add support for UDFs.
  v2/kafka-to-bigquery/src/main/java/com/google/cloud/teleport/v2/options/KafkaToBigQueryFlexOptions.java
  v2/kafka-to-bigquery/src/main/java/com/google/cloud/teleport/v2/templates/KafkaToBigQueryFlex.java
  v2/kafka-to-bigquery/src/main/java/com/google/cloud/teleport/v2/transforms/StringMessageToTableRow.java
  v2/kafka-to-bigquery/src/test/java/com/google/cloud/teleport/v2/templates/KafkaToBigQueryFlexJsonIT.java
Labels: size/L

#1875 Add workflow for runner_v2 tests
  .github/workflows/uw-tests.yml
  cicd/cmd/run-it-tests/main.go
  cicd/internal/flags/it-flags.go
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/TemplateTestBase.java
Labels: size/L

#1883 Rename UW Tests workflow from Release to UW Tests
  .github/workflows/uw-tests.yml
Labels: size/XS

#1884 Simplify uw-tests logic
  cicd/internal/flags/it-flags.go
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/TemplateTestBase.java
Labels: size/S

#1877 Adding support for bigInt Unsigned as Primary Key for partitioning and connectionProperties in shard-config
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/options/OptionsToConfigBuilder.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/dialectadapter/mysql/MysqlDialectAdapter.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/JdbcIoWrapper.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/uniformsplitter/range/BoundaryExtractorFactory.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/schema/SourceColumnIndexInfo.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/PipelineController.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/options/OptionsToConfigBuilderTest.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/JdbcIoWrapperTest.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/uniformsplitter/range/BoundaryExtractorFactoryTest.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataTypesIt.java
  v2/sourcedb-to-spanner/src/test/resources/DataTypesIt/data-types.sql
  v2/sourcedb-to-spanner/src/test/resources/DataTypesIt/spanner-schema.sql
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/shard/Shard.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/utils/ShardFileReader.java
  v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/utils/ShardFileReaderTest.java
  v2/spanner-common/src/test/resources/bulk-migration-shards.json
Labels: size/L

#1859 Added support for WHERE ... IS NOT NULL for indexes
  v1/src/main/java/com/google/cloud/teleport/spanner/ddl/Index.java
  v1/src/main/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScanner.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScannerIT.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScannerTest.java
Labels: size/S

#1879 Rename MongoDb CDC to BigQuery template
  README.md
  v2/mongodb-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/mongodb/templates/MongoDbCdcToBigQuery.java
  v2/mongodb-to-googlecloud/src/main/resources/mongodb-cdc-to-bigquery-command-spec.json
  v2/mongodb-to-googlecloud/terraform/MongoDB_to_BigQuery_CDC/dataflow_job.tf
Labels: size/M

#1885 Modified BigQueryDynamicDestination destination to support write API with exactly once semantics
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/spannerchangestreamstobigquery/BigQueryDynamicDestinations.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/spannerchangestreamstobigquery/BigQueryDynamicDestinationsTest.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/spannerchangestreamstobigquery/SpannerChangeStreamsToBigQueryIT.java
Labels: size/L

#1880 Adding integration tests for the Spanner to SourceDb template
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/SpannerToSourceDb.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/SpannerToSourceDbCustomShardIT.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/SpannerToSourceDbDatatypeIT.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/SpannerToSourceDbIT.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/SpannerToSourceDbITBase.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/SpannerToSourceDbInterleaveMultiShardIT.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/SpannerToSourceDbTimezoneIT.java
  v2/spanner-to-sourcedb/src/test/resources/SpannerToSourceDbCustomShardIT/mysql-schema.sql
  v2/spanner-to-sourcedb/src/test/resources/SpannerToSourceDbCustomShardIT/session.json
  v2/spanner-to-sourcedb/src/test/resources/SpannerToSourceDbCustomShardIT/spanner-schema.sql
  v2/spanner-to-sourcedb/src/test/resources/SpannerToSourceDbDatatypeIT/mysql-schema.sql
  v2/spanner-to-sourcedb/src/test/resources/SpannerToSourceDbDatatypeIT/session.json
  v2/spanner-to-sourcedb/src/test/resources/SpannerToSourceDbDatatypeIT/spanner-schema.sql
  v2/spanner-to-sourcedb/src/test/resources/SpannerToSourceDbIT/mysql-schema.sql
  v2/spanner-to-sourcedb/src/test/resources/SpannerToSourceDbIT/session.json
  v2/spanner-to-sourcedb/src/test/resources/SpannerToSourceDbIT/spanner-schema.sql
  v2/spanner-to-sourcedb/src/test/resources/SpannerToSourceDbInterleaveMultiShardIT/mysql-schema.sql
  v2/spanner-to-sourcedb/src/test/resources/SpannerToSourceDbInterleaveMultiShardIT/session.json
  v2/spanner-to-sourcedb/src/test/resources/SpannerToSourceDbInterleaveMultiShardIT/spanner-schema.sql
  v2/spanner-to-sourcedb/src/test/resources/SpannerToSourceDbTimezoneIT/mysql-schema.sql
  v2/spanner-to-sourcedb/src/test/resources/SpannerToSourceDbTimezoneIT/session.json
  v2/spanner-to-sourcedb/src/test/resources/SpannerToSourceDbTimezoneIT/spanner-schema.sql
Labels: size/XXL

#1888 added user guide
  v2/spanner-to-sourcedb/README.md
Labels: size/L

#1891 load test automation
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/SpannerToMySqlSourceLT.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/SpannerToSourceDbLTBase.java
  v2/spanner-to-sourcedb/src/test/resources/SpannerToMySqlSourceLT/datagenerator-schema.json
  v2/spanner-to-sourcedb/src/test/resources/SpannerToMySqlSourceLT/mysql-schema.sql
  v2/spanner-to-sourcedb/src/test/resources/SpannerToMySqlSourceLT/session.json
  v2/spanner-to-sourcedb/src/test/resources/SpannerToMySqlSourceLT/spanner-schema.sql
Labels: size/XL

#1892 Revert "Added support for WHERE ... IS NOT NULL for indexes"
  v1/src/main/java/com/google/cloud/teleport/spanner/ddl/Index.java
  v1/src/main/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScanner.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScannerIT.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScannerTest.java
Labels: size/S

#1893 feat: maps AVRO BYTES ByteBuffer column
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/avro/AvroToValueMapper.java
  v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/avro/AvroToValueMapperTest.java
  v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/avro/GenericRecordTypeConvertorTest.java
Labels: size/S

#1846 Merge sharded DF jobs and performance improvements
  v2/datastream-common/src/main/java/com/google/cloud/teleport/v2/datastream/sources/DataStreamIO.java
  v2/datastream-to-spanner/README_Cloud_Datastream_to_Spanner.md
  v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/DataStreamToSpanner.java
  v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/SpannerTransactionWriterDoFn.java
  v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/constants/DatastreamToSpannerConstants.java
  v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/datastream/DatastreamConstants.java
  v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/transform/ChangeEventTransformerDoFn.java
  v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/utils/WatchdogRunnable.java
  v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/utils/package-info.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/SpannerTransactionWriterDoFnTest.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/transform/ChangeEventTransformerDoFnTest.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/utils/WatchdogRunnableTest.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/constants/Constants.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/convertors/ChangeEventSessionConvertor.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/shard/ShardingContext.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/utils/ShardingContextReader.java
  v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/convertors/ChangeEventSessionConvertorTest.java
  v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/utils/ShardingContextReaderTest.java
  v2/spanner-common/src/test/resources/sharding-context.json
Labels: size/XL

#1903 Fixed the broken mysql link
  v2/jdbc-to-googlecloud/README_Jdbc_to_BigQuery_Flex.md
  v2/jdbc-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/options/JdbcToBigQueryOptions.java
  v2/mysql-to-googlecloud/README_MySQL_to_BigQuery.md
  v2/oracle-to-googlecloud/README_Oracle_to_BigQuery.md
  v2/postgresql-to-googlecloud/README_PostgreSQL_to_BigQuery.md
  v2/sqlserver-to-googlecloud/README_SQLServer_to_BigQuery.md
Labels: size/S

#1898 Fix readStringFromKafka and readAvroFromKafka
  v2/kafka-common/src/main/java/com/google/cloud/teleport/v2/kafka/transforms/KafkaTransform.java
  v2/kafka-to-bigquery/src/main/java/com/google/cloud/teleport/v2/templates/KafkaToBigQuery.java
  v2/kafka-to-bigquery/src/main/java/com/google/cloud/teleport/v2/templates/KafkaToBigQueryFlex.java
Labels: size/M

#1902 Added support for WHERE ... IS NOT NULL for indexes
  v1/src/main/java/com/google/cloud/teleport/spanner/ddl/Index.java
  v1/src/main/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScanner.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScannerIT.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScannerTest.java
Labels: size/S

#1906 Add retry settings for notification creation in GCSResourceManager
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/storage/GcsResourceManager.java
Labels: size/M
