Repository GoogleCloudPlatform/DataflowTemplates, pull requests merged in 2024-11, with the labels that each got.

#1981 use Airlock for PyPi packages
  .mvn/settings.xml
  plugins/core-plugin/src/main/java/com/google/cloud/teleport/plugin/DockerfileGenerator.java
  plugins/core-plugin/src/main/resources/Dockerfile-template-python
  plugins/core-plugin/src/main/resources/Dockerfile-template-xlang
  plugins/core-plugin/src/main/resources/Dockerfile-template-yaml
  plugins/core-plugin/src/test/java/com/google/cloud/teleport/plugin/DockerfileGeneratorTest.java
  plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesStageMojo.java
Labels: size/L, ignore-for-release

#1886 Generate SBOM and Provenance for released images
  it/pom.xml
  plugins/core-plugin/src/main/java/com/google/cloud/teleport/plugin/TemplatePluginUtils.java
  plugins/templates-maven-plugin/pom.xml
  plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesReleaseMojo.java
  plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesRunMojo.java
  plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesStageMojo.java
  pom.xml
  python/generate_all_dependencies.sh
  python/src/main/java/com/google/cloud/teleport/templates/python/JobBuilderServer.java
  python/src/main/python/job-builder-server/requirements.txt
  python/src/main/python/job-builder-server/server.py
  yaml/pom.xml
Labels: size/XL, ignore-for-release

#1978 Fix for reserved words in schema: Reverse replication
  session.json
  v2/spanner-to-sourcedb/README.md
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/utils/DMLGenerator.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/SpannerToSourceDbIT.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/utils/DMLGeneratorTest.java
  v2/spanner-to-sourcedb/src/test/resources/SpannerToSourceDbIT/mysql-schema.sql
  v2/spanner-to-sourcedb/src/test/resources/SpannerToSourceDbIT/session.json
  v2/spanner-to-sourcedb/src/test/resources/SpannerToSourceDbIT/spanner-schema.sql
Labels: size/XXL, bug-fix

#1983 added level wise table processing
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/JdbcIoWrapper.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/IncrementTableCounter.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/PipelineController.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/TableSelector.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/IncrementTableCounterTest.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/PipelineControllerTest.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/TableSelectorTest.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/ddl/Ddl.java
  v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/ddl/DdlTest.java
Labels: size/XXL, improvement

#1913 Add new metrics in the live template
  v2/datastream-common/src/main/java/com/google/cloud/teleport/v2/datastream/sources/ReadFileRangesFn.java
  v2/datastream-common/src/main/java/com/google/cloud/teleport/v2/datastream/transforms/FormatDatastreamRecordToJson.java
  v2/datastream-common/src/test/java/com/google/cloud/teleport/v2/datastream/transforms/FormatDatastreamRecordToJsonTest.java
  v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/SpannerTransactionWriterDoFn.java
  v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/datastream/ChangeEventContext.java
  v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/datastream/ChangeEventContextFactory.java
  v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/datastream/ChangeEventConvertor.java
  v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/datastream/MySqlChangeEventContext.java
  v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/datastream/OracleChangeEventContext.java
  v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/datastream/PostgresChangeEventContext.java
  v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/transform/ChangeEventTransformerDoFn.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/SpannerTransactionWriterDoFnTest.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/datastream/ChangeEventConvertorTest.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/constants/Constants.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/convertors/ChangeEventSessionConvertor.java
  v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/convertors/ChangeEventSessionConvertorTest.java
Labels: size/L, improvement

#1987 Enabling ANSI Quotes for MYSQL
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/JdbcIoWrapper.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/config/defaults/MySqlConfigDefaults.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/JdbcDataSourceTest.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/JdbcIoWrapperTest.java
Labels: size/M, bug-fix

#1988 corrected dlq shard id handling
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/MigrateTableTransform.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/PipelineController.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/writer/DeadLetterQueue.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/PipelineControllerTest.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/writer/DeadLetterQueueTest.java
  v2/sourcedb-to-spanner/src/test/resources/session-file-sharded.json
Labels: size/L, bug-fix

#1991 test: test reserved keywords in tables
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/PostgreSQLReservedKeywordsIT.java
  v2/sourcedb-to-spanner/src/test/resources/ReservedKeywordsIT/postgresql-schema.sql
  v2/sourcedb-to-spanner/src/test/resources/ReservedKeywordsIT/spanner-schema.sql
Labels: size/L, integration testing, improvement

#1992 fix release staging
  plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesStageMojo.java
Labels: size/XS, ignore-for-release

#1997 Add TOKENLIST spanner type
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/ddl/Column.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/schema/ISchemaMapper.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/type/Type.java
  v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/type/TypeTest.java
Labels: size/M, improvement

#1977 refactor: remove user todos
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/schema/typemapping/provider/PostgreSQLMappingProvider.java
Labels: size/S, ignore-for-release

#1996 feat: treat empty strings as null values from csv imports
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/helpers/CsvSources.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/utils/BeamUtils.java
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/model/helpers/CsvSourcesTest.java
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/templates/DataConversionIT.java
  v2/googlecloud-to-neo4j/src/test/resources/testing-specs/data-conversion/empty-strings-spec.json
  v2/googlecloud-to-neo4j/src/test/resources/testing-specs/data-conversion/empty-strings.csv
Labels: size/L, improvement

#1999 fix: add yaml support for specification parser
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/helpers/JobSpecMapper.java
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/model/helpers/JobSpecMapperTest.java
  v2/googlecloud-to-neo4j/src/test/resources/testing-specs/job-spec-mapper-test/invalid-json.json
  v2/googlecloud-to-neo4j/src/test/resources/testing-specs/job-spec-mapper-test/invalid-yaml.yaml
  v2/googlecloud-to-neo4j/src/test/resources/testing-specs/job-spec-mapper-test/valid-json-import-spec.json
  v2/googlecloud-to-neo4j/src/test/resources/testing-specs/job-spec-mapper-test/valid-json-legacy-spec.json
  v2/googlecloud-to-neo4j/src/test/resources/testing-specs/job-spec-mapper-test/valid-json-wrong-format-import-spec.json
  v2/googlecloud-to-neo4j/src/test/resources/testing-specs/job-spec-mapper-test/valid-json-wrong-format-legacy-spec.json
  v2/googlecloud-to-neo4j/src/test/resources/testing-specs/job-spec-mapper-test/valid-yaml-import-spec.yaml
  v2/googlecloud-to-neo4j/src/test/resources/testing-specs/job-spec-mapper-test/valid-yaml-wrong-format-import-spec.yaml
Labels: size/XL, improvement

#2009 Removing unsued Cassandra dependency
  v2/sourcedb-to-spanner/pom.xml
Labels: size/S, bug-fix

#2007 Update requirements annotation for JdbcToBigQuery templates
  v2/jdbc-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/JdbcToBigQuery.java
  v2/mysql-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/MySQLToBigQuery.java
  v2/oracle-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/OracleToBigQuery.java
  v2/postgresql-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/PostgreSQLToBigQuery.java
  v2/sqlserver-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/SQLServerToBigQuery.java
Labels: size/S, bug-fix

#2015 Make codecov informational only.
  .github/codecov.yml
Labels: size/XS, ignore-for-release

#2010 Add IT to verify extra cols
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerSessionIT.java
  v2/datastream-to-spanner/src/test/resources/DataStreamToSpannerSessionIT/mysql-session.json
  v2/datastream-to-spanner/src/test/resources/DataStreamToSpannerSessionIT/spanner-schema.sql
Labels: size/L, improvement

#1990 Enable HIDDEN for all column types
  v1/src/main/java/com/google/cloud/teleport/spanner/AvroSchemaToDdlConverter.java
  v1/src/main/java/com/google/cloud/teleport/spanner/DdlToAvroSchemaConverter.java
  v1/src/test/java/com/google/cloud/teleport/spanner/AvroSchemaToDdlConverterTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/DdlToAvroSchemaConverterTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ddl/DdlTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScannerIT.java
Labels: size/M, ignore-for-release

#1803 docs: update template option descriptions
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/options/Neo4jFlexTemplateOptions.java
Labels: size/S, ignore-for-release

#2018 Add enable backfill flag to terraform template var files
  v2/datastream-to-spanner/terraform/samples/mysql-end-to-end/terraform.tfvars
  v2/datastream-to-spanner/terraform/samples/mysql-sharded-end-to-end/terraform.tfvars
  v2/datastream-to-spanner/terraform/samples/mysql-sharded-single-df-job/main.tf
  v2/datastream-to-spanner/terraform/samples/mysql-sharded-single-df-job/outputs.tf
  v2/datastream-to-spanner/terraform/samples/mysql-sharded-single-df-job/terraform.tfvars
  v2/datastream-to-spanner/terraform/samples/mysql-sharded-single-df-job/variables.tf
  v2/datastream-to-spanner/terraform/samples/postgresql-end-to-end/terraform.tfvars
Labels: size/S, improvement

#1951 Tests: Adding Reverse Replication Tests
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/SpannerToSourceDbIT.java
  v2/spanner-to-sourcedb/src/test/resources/SpannerToSourceDbIT/session.json
  v2/spanner-to-sourcedb/src/test/resources/SpannerToSourceDbIT/spanner-schema.sql
Labels: size/M, ignore-for-release

#2030 Use safe deserialization option for Yaml specs
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/helpers/JobSpecMapper.java
Labels: size/XS, bug-fix

#1961 Fix node target reference lookup and node match mode
  v2/googlecloud-to-neo4j/pom.xml
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/validation/NodeMatchModeValidator.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/templates/GoogleCloudToNeo4j.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/utils/BeamBlock.java
  v2/googlecloud-to-neo4j/src/main/resources/META-INF/services/org.neo4j.importer.v1.validation.SpecificationValidator
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/templates/MovieImportIT.java
  v2/googlecloud-to-neo4j/src/test/resources/testing-specs/import-spec/movie-import/spec.json
Labels: size/L, bug-fix

#2019 Cassandra Schema Discovery
  v2/sourcedb-to-spanner/pom.xml
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraConnector.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraDataSource.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/schema/CassandraSchemaDiscovery.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/schema/CassandraSchemaReference.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraConnectorTest.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraDataSourceTest.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/schema/CassandraSchemaDiscoveryTest.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/schema/CassandraSchemaReferenceTest.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/testutils/BasicTestSchema.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/testutils/EmbeddedCassandra.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/testutils/SharedEmbeddedCassandra.java
  v2/sourcedb-to-spanner/src/test/resources/CassandraUT/basicConfig.yaml
  v2/sourcedb-to-spanner/src/test/resources/CassandraUT/basicTest.cql
Labels: addition, size/XXL, ignore-for-release

#2031 Avro format Import/Export support for Spanner NOT ENFORCED Foreign Key
  v1/src/main/java/com/google/cloud/teleport/spanner/ddl/ForeignKey.java
  v1/src/main/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScanner.java
  v1/src/test/java/com/google/cloud/teleport/spanner/AvroSchemaToDdlConverterTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/CopyDbTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/DdlToAvroSchemaConverterTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ddl/DdlTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScannerIT.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ddl/RandomDdlGenerator.java
Labels: size/L, improvement

#2033 Upgrade to Beam 2.61.0
  pom.xml
  v1/src/main/java/org/apache/beam/sdk/io/gcp/spanner/LocalSpannerIO.java
  v2/mqtt-to-pubsub/src/main/java/com/google/cloud/teleport/v2/templates/MqttToPubsub.java
Labels: size/S, improvement

#2024 add KMS key support to BigQueryConverters
  v2/common/src/main/java/com/google/cloud/teleport/v2/transforms/BigQueryConverters.java
  v2/googlecloud-to-elasticsearch/src/test/java/com/google/cloud/teleport/v2/elasticsearch/templates/BigQueryToElasticsearchIT.java
Labels: size/M, improvement

#1841 feat: Modularization: Terraform changes for schema overrides
  v2/datastream-to-spanner/terraform/samples/mysql-end-to-end/README.md
  v2/datastream-to-spanner/terraform/samples/mysql-end-to-end/main.tf
  v2/datastream-to-spanner/terraform/samples/mysql-end-to-end/schema-overrides.json
  v2/datastream-to-spanner/terraform/samples/mysql-end-to-end/terraform.tfvars
  v2/datastream-to-spanner/terraform/samples/mysql-end-to-end/variables.tf
  v2/datastream-to-spanner/terraform/samples/mysql-sharded-end-to-end/README.md
  v2/datastream-to-spanner/terraform/samples/mysql-sharded-end-to-end/main.tf
  v2/datastream-to-spanner/terraform/samples/mysql-sharded-end-to-end/terraform.tfvars
  v2/datastream-to-spanner/terraform/samples/mysql-sharded-end-to-end/variables.tf
  v2/datastream-to-spanner/terraform/samples/postgresql-end-to-end/README.md
  v2/datastream-to-spanner/terraform/samples/postgresql-end-to-end/main.tf
  v2/datastream-to-spanner/terraform/samples/postgresql-end-to-end/terraform.tfvars
  v2/datastream-to-spanner/terraform/samples/postgresql-end-to-end/variables.tf
  v2/datastream-to-spanner/terraform/samples/pre-configured-conn-profiles/README.md
  v2/datastream-to-spanner/terraform/samples/pre-configured-conn-profiles/main.tf
  v2/datastream-to-spanner/terraform/samples/pre-configured-conn-profiles/terraform.tfvars
  v2/datastream-to-spanner/terraform/samples/pre-configured-conn-profiles/variables.tf
Labels: size/L, improvement

#2039 Fixing Custom Transforms for `BigInt Unsigned` and `Boolean` types.
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/rowmapper/provider/MysqlJdbcValueMappings.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/schema/typemapping/provider/MysqlMappingProvider.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/rowmapper/JdbcSourceRowMapperTest.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/schema/typemapping/provider/MysqlMappingProviderTest.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/avro/GenericRecordTypeConvertor.java
  v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/avro/GenericRecordTypeConvertorTest.java
Labels: size/L, bug-fix

#2003 Add support for PropertyGraphs in import/export DDL
  v1/src/main/java/com/google/cloud/teleport/spanner/AvroSchemaToDdlConverter.java
  v1/src/main/java/com/google/cloud/teleport/spanner/AvroUtil.java
  v1/src/main/java/com/google/cloud/teleport/spanner/DdlToAvroSchemaConverter.java
  v1/src/main/java/com/google/cloud/teleport/spanner/ExportTransform.java
  v1/src/main/java/com/google/cloud/teleport/spanner/ImportTransform.java
  v1/src/main/java/com/google/cloud/teleport/spanner/ddl/Ddl.java
  v1/src/main/java/com/google/cloud/teleport/spanner/ddl/GraphElementTable.java
  v1/src/main/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScanner.java
  v1/src/main/java/com/google/cloud/teleport/spanner/ddl/PropertyGraph.java
  v1/src/test/java/com/google/cloud/teleport/spanner/AvroSchemaToDdlConverterTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/DdlToAvroSchemaConverterTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ExportTransformTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ImportFromAvroTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ddl/DdlTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ddl/GraphElementTableTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScannerIT.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ddl/PropertyGraphTest.java
Labels: size/XXL, improvement
