Repository GoogleCloudPlatform/DataflowTemplates, pull requests merged in 2024-10, with the labels that each got.

#1840 feat: Modularization: Schema overrides via string and file
  v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/DataStreamToSpanner.java
  v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/transform/ChangeEventTransformerDoFn.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/transform/ChangeEventTransformerDoFnTest.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/convertors/ChangeEventSessionConvertor.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/schema/ISchemaOverridesParser.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/schema/NoopSchemaOverridesParser.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/schema/SchemaFileOverride.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/schema/SchemaFileOverridesParser.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/schema/SchemaStringOverridesParser.java
  v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/convertors/ChangeEventSessionConvertorTest.java
  v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/schema/SchemaFileOverrideTest.java
  v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/schema/SchemaFileOverridesParserTest.java
  v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/schema/SchemaStringOverridesParserTest.java
  v2/spanner-common/src/test/resources/schema-overrides-cols-tables.json
  v2/spanner-common/src/test/resources/schema-overrides-columns.json
  v2/spanner-common/src/test/resources/schema-overrides-tables.json
Labels: size/XL

#1894 more ut
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/changestream/DataChangeRecordTypeConvertor.java
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/transforms/AssignShardIdFn.java
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/utils/ConnectionHelper.java
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/utils/ShadowTableCreator.java
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/utils/ShadowTableRecord.java
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/utils/SpannerDao.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/changestream/DataChangeRecordTypeConvertorTest.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/transforms/AssignShardIdFnTest.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/transforms/ConvertChangeStreamErrorRecordToFailsafeElementFnTest.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/transforms/SourceWriterFnTest.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/transforms/UpdateDlqMetricsFnTest.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/utils/DMLGeneratorTest.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/utils/MySqlDaoTest.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/utils/ShadowTableCreatorTest.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/utils/ShardIdFetcherImplTest.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/utils/SpannerDaoTest.java
  v2/spanner-to-sourcedb/src/test/resources/errorSchemaSession.json
Labels: size/XXL

#1866 Refactor Dockerfile-based images plugin
  plugins/core-plugin/src/main/java/com/google/cloud/teleport/plugin/DockerfileGenerator.java
  plugins/core-plugin/src/main/java/com/google/cloud/teleport/plugin/PythonDockerfileGenerator.java
  plugins/core-plugin/src/main/java/com/google/cloud/teleport/plugin/XlangDockerfileGenerator.java
  plugins/core-plugin/src/main/java/com/google/cloud/teleport/plugin/YamlDockerfileGenerator.java
  plugins/core-plugin/src/main/resources/Dockerfile-template-python
  plugins/core-plugin/src/main/resources/Dockerfile-template-xlang
  plugins/core-plugin/src/main/resources/Dockerfile-template-yaml
  plugins/core-plugin/src/test/java/com/google/cloud/teleport/plugin/DockerfileGeneratorTest.java
  plugins/core-plugin/src/test/java/com/google/cloud/teleport/plugin/PythonDockerfileGeneratorTest.java
  plugins/core-plugin/src/test/java/com/google/cloud/teleport/plugin/XlangDockerfileGeneratorTest.java
  plugins/core-plugin/src/test/java/com/google/cloud/teleport/plugin/YamlDockerfileGeneratorTest.java
  plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesReleaseMojo.java
  plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesRunMojo.java
  plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesStageMojo.java
Labels: size/XXL

#1899 Reducing JDBC SchemaDiscovery error timeout
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/dialectadapter/mysql/MysqlDialectAdapter.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/dialectadapter/postgresql/PostgreSQLDialectAdapter.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/JdbcDataSource.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/JdbcIoWrapper.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/config/JdbcIOWrapperConfig.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/config/defaults/MySqlConfigDefaults.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/config/defaults/PostgreSQLConfigDefaults.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/JdbcDataSourceTest.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/JdbcIoWrapperTest.java
Labels: size/L

#1887 feat: add several types to PGAdapter
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/rowmapper/provider/PostgreSQLJdbcValueMappings.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/schema/typemapping/provider/PostgreSQLMappingProvider.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/CustomAsserts.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/rowmapper/JdbcSourceRowMapperTest.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/schema/typemapping/provider/PostgreSQLMappingProviderTest.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataTypesIt.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/SourceDbToSpannerITBase.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/postgresql/DataTypesIT.java
  v2/sourcedb-to-spanner/src/test/resources/DataTypesIt/mysql/data-types.sql
  v2/sourcedb-to-spanner/src/test/resources/DataTypesIt/mysql/spanner-schema.sql
  v2/sourcedb-to-spanner/src/test/resources/DataTypesIt/postgresql/data-types.sql
  v2/sourcedb-to-spanner/src/test/resources/DataTypesIt/postgresql/spanner-schema.sql
Labels: size/XXL

#1889 Update live terraform templates to support end to end migration
  v2/datastream-to-spanner/terraform/samples/mysql-end-to-end/README.md
  v2/datastream-to-spanner/terraform/samples/mysql-end-to-end/main.tf
  v2/datastream-to-spanner/terraform/samples/mysql-end-to-end/outputs.tf
  v2/datastream-to-spanner/terraform/samples/mysql-end-to-end/terraform.tfvars
  v2/datastream-to-spanner/terraform/samples/mysql-end-to-end/variables.tf
  v2/datastream-to-spanner/terraform/samples/mysql-sharded-end-to-end/README.md
  v2/datastream-to-spanner/terraform/samples/mysql-sharded-end-to-end/main.tf
  v2/datastream-to-spanner/terraform/samples/mysql-sharded-end-to-end/outputs.tf
  v2/datastream-to-spanner/terraform/samples/mysql-sharded-end-to-end/terraform.tfvars
  v2/datastream-to-spanner/terraform/samples/mysql-sharded-end-to-end/variables.tf
  v2/datastream-to-spanner/terraform/samples/postgresql-end-to-end/README.md
  v2/datastream-to-spanner/terraform/samples/postgresql-end-to-end/main.tf
  v2/datastream-to-spanner/terraform/samples/postgresql-end-to-end/outputs.tf
  v2/datastream-to-spanner/terraform/samples/postgresql-end-to-end/terraform.tfvars
  v2/datastream-to-spanner/terraform/samples/postgresql-end-to-end/variables.tf
  v2/spanner-common/docs/END-TO-END-PRODUCTION-MIGRATION.md
  v2/spanner-common/docs/end-to-end-production-migration.png
  v2/spanner-common/terraform/samples/mysql-vpc-spanner-test-infra/main.tf
  v2/spanner-common/terraform/samples/mysql-vpc-spanner-test-infra/variables.tf
Labels: size/XL

#1911 IT for validating string and file overrides
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerFileOverridesIT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerStringOverridesIT.java
  v2/datastream-to-spanner/src/test/resources/DataStreamToSpannerFileOverridesIT/mysql-cdc-person1.avro
  v2/datastream-to-spanner/src/test/resources/DataStreamToSpannerFileOverridesIT/mysql-schema.sql
  v2/datastream-to-spanner/src/test/resources/DataStreamToSpannerFileOverridesIT/override.json
  v2/datastream-to-spanner/src/test/resources/DataStreamToSpannerFileOverridesIT/spanner-schema.sql
  v2/datastream-to-spanner/src/test/resources/DataStreamToSpannerStringOverridesIT/mysql-cdc-person1.avro
  v2/datastream-to-spanner/src/test/resources/DataStreamToSpannerStringOverridesIT/mysql-schema.sql
  v2/datastream-to-spanner/src/test/resources/DataStreamToSpannerStringOverridesIT/spanner-schema.sql
  v2/spanner-common/src/test/resources/schema-overrides-malformed.json
Labels: size/L

#1909 Add create bucket support for gcs resource manager
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/storage/GcsResourceManager.java
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/storage/GcsResourceManagerException.java
  it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/storage/GcsResourceManagerTest.java
Labels: size/L

#1922 Fixing wrong timestamp logical type conversion for datastream to bigquery
  v2/datastream-common/src/main/java/com/google/cloud/teleport/v2/datastream/transforms/FormatDatastreamRecordToJson.java
  v2/datastream-common/src/test/java/com/google/cloud/teleport/v2/datastream/transforms/FormatDatastreamRecordToJsonTest.java
Labels: size/M

#1871 Require hashes for all pip installs
  plugins/core-plugin/src/main/resources/Dockerfile-template-python
  plugins/core-plugin/src/main/resources/Dockerfile-template-xlang
  plugins/core-plugin/src/main/resources/Dockerfile-template-yaml
  plugins/core-plugin/src/test/java/com/google/cloud/teleport/plugin/DockerfileGeneratorTest.java
  plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesStageMojo.java
  python/src/main/python/streaming-llm/Dockerfile
  python/src/main/python/word-count-python/Dockerfile
Labels: size/M

#1916 tests: Load testing different shapes for MySql to Spanner
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/loadtesting/DataStreamToSpannerBlobTable.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/loadtesting/DataStreamToSpannerForeignKey.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/loadtesting/DataStreamToSpannerInterleavedTable.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/loadtesting/DataStreamToSpannerTallTable.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/loadtesting/DataStreamToSpannerWideTable.java
  v2/datastream-to-spanner/src/test/resources/DataStreamToSpanner100GbLT/spanner-schema-blob.sql
  v2/datastream-to-spanner/src/test/resources/DataStreamToSpanner100GbLT/spanner-schema-foreign-key.sql
  v2/datastream-to-spanner/src/test/resources/DataStreamToSpanner100GbLT/spanner-schema-interleaving.sql
  v2/datastream-to-spanner/src/test/resources/DataStreamToSpanner100GbLT/spanner-schema-tall-table.sql
  v2/datastream-to-spanner/src/test/resources/DataStreamToSpanner100GbLT/spanner-schema-wide-table.sql
Labels: size/XXL

#1927 upgrade postgres version in JDBCBaseIT
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/JDBCBaseIT.java
Labels: size/XS

#1926 It
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/SpannerToSourceDbCustomShardIT.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/SpannerToSourceDbDatatypeIT.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/SpannerToSourceDbIT.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/SpannerToSourceDbITBase.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/SpannerToSourceDbInterleaveMultiShardIT.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/SpannerToSourceDbLTBase.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/SpannerToSourceDbTimezoneIT.java
Labels: size/S

#1930 Increase timeout for DataTypesIT#allTypesTest
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/postgresql/DataTypesIT.java
Labels: size/XS

#1931 Add cutover time to help with flaky IT test due to eventual consistency of CDC propogation
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerShardedMigrationWithMigrationShardIdColumnIT.java
Labels: size/S

#1935 Remove superflous wait
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerShardedMigrationWithMigrationShardIdColumnIT.java
Labels: size/XS

#1933 Fix staging Dockerfile-based templates on release
  plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesStageMojo.java
Labels: size/XS

#1936 Add information on generating python dependencies
  contributor-docs/maintainers-guide.md
  python/generate_all_dependencies.sh
Labels: size/M

#1928 fixed extra table in session file
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/JdbcIoWrapper.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/PipelineController.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/JdbcIoWrapperTest.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/PipelineControllerTest.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/SourceDbToSpannerTest.java
Labels: size/XL

#1882 Add Job Builder server image
  metadata/src/main/java/com/google/cloud/teleport/metadata/Template.java
  plugins/core-plugin/src/main/java/com/google/cloud/teleport/plugin/DockerfileGenerator.java
  plugins/core-plugin/src/main/resources/Dockerfile-template-python
  plugins/core-plugin/src/main/resources/Dockerfile-template-xlang
  plugins/core-plugin/src/main/resources/Dockerfile-template-yaml
  plugins/core-plugin/src/test/java/com/google/cloud/teleport/plugin/DockerfileGeneratorTest.java
  plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesStageMojo.java
  python/src/main/java/com/google/cloud/teleport/templates/python/JobBuilderServer.java
  python/src/main/python/yaml-template/job-builder-server/server.py
Labels: size/XL

#1653 CassandraToBigtable classic template feature: Cassandra Writetime replication
  v1/README_Cassandra_To_Cloud_Bigtable.md
  v1/pom.xml
  v1/src/main/java/com/google/cloud/teleport/bigtable/BeamRowToBigtableFn.java
  v1/src/main/java/com/google/cloud/teleport/bigtable/CassandraColumnSchema.java
  v1/src/main/java/com/google/cloud/teleport/bigtable/CassandraKeyUtils.java
  v1/src/main/java/com/google/cloud/teleport/bigtable/CassandraRowMapperFn.java
  v1/src/main/java/com/google/cloud/teleport/bigtable/CassandraToBigtable.java
  v1/src/main/java/com/google/cloud/teleport/bigtable/CassandraWritetimeQueryProvider.java
  v1/src/main/java/com/google/cloud/teleport/util/GCSAwareValueProvider.java
  v1/src/main/java/com/google/cloud/teleport/util/GCSUtils.java
  v1/src/main/java/com/google/cloud/teleport/util/ValueProcessor.java
  v1/src/test/java/com/google/cloud/teleport/bigtable/BeamRowToBigtableFnTest.java
  v1/src/test/java/com/google/cloud/teleport/bigtable/CassandraColumnSchemaTest.java
  v1/src/test/java/com/google/cloud/teleport/bigtable/CassandraToBigtableIT.java
  v1/terraform/Cassandra_To_Cloud_Bigtable/dataflow_job.tf
Labels: size/XXL

#1941 [Draft] Fixed IT schema to map bigInt Unsigned to Numeric
  v2/sourcedb-to-spanner/src/test/resources/DataTypesIt/mysql/spanner-schema.sql
Labels: size/XS

#1890 Fix data type IT name
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/CustomTransformationsNonShardedIT.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataTypesIT.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/postgresql/DataTypesIT.java
  v2/sourcedb-to-spanner/src/test/resources/CustomTransformationsNonShardedIT/mysql-schema.sql
  v2/sourcedb-to-spanner/src/test/resources/DataTypesIT/mysql/data-types.sql
  v2/sourcedb-to-spanner/src/test/resources/DataTypesIT/mysql/spanner-schema.sql
  v2/sourcedb-to-spanner/src/test/resources/DataTypesIT/postgresql/data-types.sql
  v2/sourcedb-to-spanner/src/test/resources/DataTypesIT/postgresql/spanner-schema.sql
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/avro/GenericRecordTypeConvertor.java
  v2/spanner-custom-shard/src/main/java/com/custom/CustomTransformationWithShardForBulkIT.java
Labels: size/M

#1940 bug(bigtable): Handle default values
  v1/README_Cloud_Bigtable_to_GCS_Json.md
  v1/README_Cloud_Bigtable_to_Vector_Embeddings.md
  v1/src/main/java/com/google/cloud/teleport/bigtable/BigtableToJson.java
  v1/src/main/java/com/google/cloud/teleport/bigtable/BigtableToVectorEmbeddings.java
  v1/src/test/java/com/google/cloud/teleport/templates/BigtableToJsonIT.java
  v1/src/test/java/com/google/cloud/teleport/templates/BigtableToVectorEmbeddingsIT.java
Labels: size/L

#1942 Re-enabling unsigned tests
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataTypesIT.java
  v2/sourcedb-to-spanner/src/test/resources/DataTypesIT/mysql/spanner-schema.sql
Labels: size/S

#1917 Bump version of avro to avoid CVE-2024-47561
  pom.xml
  v2/googlecloud-to-googlecloud/pom.xml
Labels: size/S

#1918 Export resource manager metrics and custom counters for Spanner load tests
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/monitoring/MonitoringClient.java
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/pubsub/PubsubResourceManager.java
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/pubsub/PubsubResourceManagerException.java
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/spanner/SpannerResourceManager.java
  it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/pubsub/PubsubResourceManagerTest.java
  it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/spanner/SpannerResourceManagerTest.java
  v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/SpannerTransactionWriterDoFn.java
  v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/constants/DatastreamToSpannerConstants.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/loadtesting/DataStreamToSpannerLTBase.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/SpannerToMySqlSourceLT.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/SpannerToSourceDbLTBase.java
Labels: size/L

#1934 fix:modifying test names
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/loadtesting/DataStreamToSpannerBlobTableLT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/loadtesting/DataStreamToSpannerForeignKeyLT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/loadtesting/DataStreamToSpannerInterleavedTableLT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/loadtesting/DataStreamToSpannerTallTableLT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/loadtesting/DataStreamToSpannerWideTableLT.java
Labels: size/S

#1943 instructions to cut-back
  v2/spanner-to-sourcedb/README.md
Labels: size/M

#1950 updated reverse replication readme to include info on the change stream bug
  v2/spanner-to-sourcedb/README.md
Labels: size/XS

#1952 Fix for job-builder image release
  plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesReleaseMojo.java
Labels: size/S

#1939 adding more UTs to increase coverage
  v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/DataStreamToSpanner.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerTest.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/type/Type.java
  v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/type/TypeTest.java
Labels: size/L

#1945 test: add PostgreSQL load test
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/loadtesting/SourceDbToSpannerLTBase.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/loadtesting/postgresql/SourceDbToSpannerLT.java
  v2/sourcedb-to-spanner/src/test/resources/SourceDbToSpannerLT/postgresql/spanner-schema.sql
Labels: size/L

#1948 Bump Beam version to 2.60.0
  it/pom.xml
  pom.xml
  python/generate_all_dependencies.sh
  python/src/main/python/streaming-llm/requirements.txt
  python/src/main/python/word-count-python/requirements.txt
  python/src/main/python/yaml-template/requirements.txt
  python/src/test/java/com/google/cloud/teleport/templates/python/YAMLTemplateIT.java
  v2/googlecloud-to-elasticsearch/src/main/resources/requirements.txt
  v2/googlecloud-to-googlecloud/src/main/resources/requirements.txt
  v2/googlecloud-to-splunk/src/main/resources/requirements.txt
  v2/pubsub-binary-to-bigquery/src/main/resources/requirements.txt
  v2/pubsub-to-mongodb/src/main/resources/requirements.txt
Labels: size/XXL

#1947 Added secret manager support for sqlserver-to-bigquery template
  v2/jdbc-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/options/JdbcToBigQueryOptions.java
  v2/jdbc-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/JdbcToBigQuery.java
  v2/jdbc-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/JdbcToBigQueryIT.java
  v2/sqlserver-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/options/SQLServerToBigQueryOptions.java
Labels: size/M

#1953 Fixing typo in smallint_unsigned
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataTypesIT.java
  v2/sourcedb-to-spanner/src/test/resources/DataTypesIT/mysql/data-types.sql
  v2/sourcedb-to-spanner/src/test/resources/DataTypesIT/mysql/spanner-schema.sql
Labels: size/S

#1946 Terraform template for Reverse replication for sharded MySQL
  v2/spanner-to-sourcedb/terraform/samples/README.md
  v2/spanner-to-sourcedb/terraform/samples/spanner-to-sharded-mysql/README.md
  v2/spanner-to-sourcedb/terraform/samples/spanner-to-sharded-mysql/main.tf
  v2/spanner-to-sourcedb/terraform/samples/spanner-to-sharded-mysql/outputs.tf
  v2/spanner-to-sourcedb/terraform/samples/spanner-to-sharded-mysql/session.json
  v2/spanner-to-sourcedb/terraform/samples/spanner-to-sharded-mysql/terraform.tf
  v2/spanner-to-sourcedb/terraform/samples/spanner-to-sharded-mysql/terraform.tfvars
  v2/spanner-to-sourcedb/terraform/samples/spanner-to-sharded-mysql/terraform_simple.tfvars
  v2/spanner-to-sourcedb/terraform/samples/spanner-to-sharded-mysql/variables.tf
Labels: size/XXL

#1925 feat: add namespace support for PostgreSQL databases
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/options/OptionsToConfigBuilder.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/options/SourceDbToSpannerOptions.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/dialectadapter/postgresql/PostgreSQLDialectAdapter.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/PipelineController.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/options/OptionsToConfigBuilderTest.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/dialectadapter/postgresql/PostgreSQLDialectAdapterTest.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/postgresql/NamespaceIT.java
  v2/sourcedb-to-spanner/src/test/resources/NamespacesIT/postgresql-schema.sql
  v2/sourcedb-to-spanner/src/test/resources/NamespacesIT/spanner-schema.sql
Labels: size/L

#1960 refactor: rename tests
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/MySQLCustomTransformationsNonShardedIT.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/MySQLDataTypesIT.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/MySQLForeignKeyDependencyIT.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/MySQLIdentitySchemaMapperIT.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/MySQLIdentitySchemaMapperWithTransformationIT.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/MySQLSessionSchemaMapperIT.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/MySQLSessionSchemaMapperWithTableFilterIT.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/MySQLSessionSchemaMapperWithTransformationIT.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/MySQLSingleShardIT.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/MySQLSourceDbToSpannerSimpleIT.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/PostgreSQLDataTypesIT.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/PostgreSQLIdentitySchemaMapperIT.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/loadtesting/PostgreSQLSourceDbToSpannerLT.java
  v2/sourcedb-to-spanner/src/test/resources/DataTypesIT/mysql-data-types.sql
  v2/sourcedb-to-spanner/src/test/resources/DataTypesIT/mysql-spanner-schema.sql
  v2/sourcedb-to-spanner/src/test/resources/DataTypesIT/postgresql-data-types.sql
  v2/sourcedb-to-spanner/src/test/resources/DataTypesIT/postgresql-spanner-schema.sql
  v2/sourcedb-to-spanner/src/test/resources/SingleShardWithTransformation/postgresql-schema.sql
  v2/sourcedb-to-spanner/src/test/resources/SourceDbToSpannerLT/postgresql-spanner-schema.sql
Labels: size/M

#1963 Fixing Flaky tests
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/spanner/SpannerResourceManager.java
  it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/spanner/SpannerResourceManagerTest.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerDDLIT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerEventsIT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerITBase.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerSessionIT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerShardedMigrationWithMigrationShardIdColumnIT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerShardedMigrationWithoutMigrationShardIdColumnIT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DatastreamToSpannerSingleDFShardedMigrationIT.java
Labels: size/L

#1954 Fix flaky tests
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/model/helpers/MappingMapperTest.java
Labels: size/L

#1969 Add a release notes template
  .github/release.yml
Labels: size/S, ignore-for-release

#1970 Force users to add labels for release note generation
  .github/workflows/release-notes-labels.yml
  contributor-docs/code-contributions.md
Labels: size/S, ignore-for-release

#1973 Don't comment on pull requests
  .github/workflows/release-notes-labels.yml
Labels: size/XS, ignore-for-release

#1862 Build PRs using artifact registry packages
  .mvn/extensions.xml
  .mvn/settings.xml
  cicd/cmd/run-build/main.go
  cicd/cmd/run-it-smoke-tests/main.go
  cicd/cmd/run-it-tests/main.go
  cicd/cmd/run-load-test-observer/main.go
  cicd/cmd/run-load-tests/main.go
  cicd/cmd/run-unit-tests/main.go
  cicd/internal/workflows/maven-workflows.go
  pom.xml
Labels: size/L, ignore-for-release

#1815 Remove gcs notification tests from Datastream Spanner ITs
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerIT.java
Labels: size/M

#1967 fix doc generation
  metadata/src/main/java/com/google/cloud/teleport/metadata/Template.java
  plugins/core-plugin/src/main/java/com/google/cloud/teleport/plugin/TemplateSpecsGenerator.java
  plugins/core-plugin/src/test/java/com/google/cloud/teleport/plugin/TemplateSpecsGeneratorTest.java
  plugins/core-plugin/src/test/java/com/google/cloud/teleport/plugin/sample/AtoBNestedFlex.java
  plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesStageMojo.java
Labels: size/L, ignore-for-release

#1971 feat: allows for namespace in shard config file
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/config/defaults/PostgreSQLConfigDefaults.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/schema/typemapping/provider/PostgreSQLMappingProvider.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/PipelineController.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/PostgreSQLNamespaceIT.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/shard/Shard.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/utils/ShardFileReader.java
  v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/utils/ShardFileReaderTest.java
  v2/spanner-common/src/test/resources/bulk-migration-shards.json
  v2/spanner-common/src/test/resources/shard-with-secret.json
  v2/spanner-common/src/test/resources/shard.json
Labels: size/M

#1980 handling for empty tables with bigint keys
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/uniformsplitter/range/BoundaryExtractorFactory.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/uniformsplitter/range/BoundaryExtractorFactoryTest.java
Labels: size/S, bug-fix

#1979 Escaping column names to handle reserved keywords
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/JdbcIoWrapper.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/uniformsplitter/range/Boundary.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/JdbcIoWrapperTest.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/uniformsplitter/range/BoundaryExtractorFactoryTest.java
Labels: size/M, bug-fix

#1972 Add requirements.txt to job builder server
  plugins/core-plugin/src/main/java/com/google/cloud/teleport/plugin/DockerfileGenerator.java
  plugins/core-plugin/src/test/java/com/google/cloud/teleport/plugin/DockerfileGeneratorTest.java
  plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesStageMojo.java
  python/generate_all_dependencies.sh
  python/src/main/java/com/google/cloud/teleport/templates/python/JobBuilderServer.java
  python/src/main/python/yaml-template/job-builder-server/requirements.txt
Labels: size/XXL, ignore-for-release

#1982 remove redundant jinja parsing from YamlTemplate
  python/src/main/python/yaml-template/main.py
Labels: size/M, ignore-for-release
