Repository GoogleCloudPlatform/DataflowTemplates, pull requests merged in 2024-06, with the labels that each got.

#1622 Fix UI bug in KafkaReadOptions
  v2/kafka-common/src/main/java/com/google/cloud/teleport/v2/kafka/options/KafkaReadOptions.java
Labels: Google LGTM, size/XS

#1619 [BULK] Handle BIT type,Timestamp overflow and add stack trace to DLQ.
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/RowContext.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/transformer/SourceRowToMutationDoFn.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/writer/DeadLetterQueue.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/avro/AvroToValueMapper.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/avro/GenericRecordTypeConvertor.java
  v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/avro/AvroToValueMapperTest.java
  v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/avro/GenericRecordTypeConvertorTest.java
Labels: Google LGTM, size/L

#1623 Adding init seq to set session timezone.
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/JdbcIoWrapper.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/config/JdbcIOWrapperConfig.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/config/defaults/MySqlConfigDefaults.java
Labels: Google LGTM, size/M

#1627 corrected documentation
  v2/sourcedb-to-spanner/README.md
  v2/sourcedb-to-spanner/README_Sourcedb_to_Spanner.md
  v2/sourcedb-to-spanner/README_Sourcedb_to_Spanner_Flex.md
Labels: Google LGTM, size/L

#1626 Change None to SASL_PLAIN and mark schemaFormat as optional
  v2/kafka-common/src/main/java/com/google/cloud/teleport/v2/kafka/options/KafkaReadOptions.java
  v2/kafka-common/src/main/java/com/google/cloud/teleport/v2/kafka/options/SchemaRegistryOptions.java
  v2/kafka-common/src/main/java/com/google/cloud/teleport/v2/kafka/values/KafkaTemplateParameters.java
  v2/kafka-to-bigquery/src/main/java/com/google/cloud/teleport/v2/options/KafkaToBigQueryFlexOptions.java
  v2/kafka-to-bigquery/src/main/java/com/google/cloud/teleport/v2/templates/KafkaToBigQueryFlex.java
  v2/kafka-to-gcs/src/main/java/com/google/cloud/teleport/v2/templates/KafkaToGcsFlex.java
  v2/kafka-to-gcs/src/main/java/com/google/cloud/teleport/v2/transforms/AvroWriteTransform.java
  v2/kafka-to-gcs/src/main/java/com/google/cloud/teleport/v2/transforms/WriteTransform.java
  v2/kafka-to-gcs/src/test/java/com/google/cloud/teleport/v2/templates/KafkaToGcsIT.java
Labels: Google LGTM, size/L

#1628 Release readiness - Readme and terraform
  README.md
  v2/sourcedb-to-spanner/terraform/Sourcedb_to_Spanner_Flex/dataflow_job.tf
Labels: Google LGTM, size/M

#1616 Update bigtable-beam-import to 2.14.2 to support Data Boost
  pom.xml
  v1/pom.xml
Labels: Google LGTM, size/XS

#1630 [BULK] Integration tests for all data types
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/spanner/SpannerResourceManager.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataTypesIt.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/SourceDbToSpannerITBase.java
  v2/sourcedb-to-spanner/src/test/resources/DataTypesIt/data-types.sql
  v2/sourcedb-to-spanner/src/test/resources/DataTypesIt/spanner-schema.sql
Labels: Google LGTM, size/XL

#1634 adding integration test for forward transformation
  pom.xml
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerDDLIT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerEventsIT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerITBase.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerSessionIT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerShardedMigrationWithMigrationShardIdColumnIT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerShardedMigrationWithoutMigrationShardIdColumnIT.java
  v2/datastream-to-spanner/src/test/resources/DataStreamToSpannerDDLIT/mysql-backfill-AllDatatypeTransformation.avro
  v2/datastream-to-spanner/src/test/resources/DataStreamToSpannerDDLIT/mysql-cdc-AllDatatypeTransformation.avro
  v2/datastream-to-spanner/src/test/resources/DataStreamToSpannerDDLIT/mysql-schema.sql
  v2/datastream-to-spanner/src/test/resources/DataStreamToSpannerDDLIT/spanner-schema.sql
  v2/datastream-to-spanner/src/test/resources/DataStreamToSpannerDDLIT/statements.sql
  v2/datastream-to-spanner/src/test/resources/DataStreamToSpannerShardedMigrationWithMigrationShardIdColumnIT/Customers-shard1.avro
  v2/datastream-to-spanner/src/test/resources/DataStreamToSpannerShardedMigrationWithMigrationShardIdColumnIT/Customers-shard2.avro
  v2/datastream-to-spanner/src/test/resources/DataStreamToSpannerShardedMigrationWithMigrationShardIdColumnIT/mysql-schema.sql
  v2/datastream-to-spanner/src/test/resources/DataStreamToSpannerShardedMigrationWithMigrationShardIdColumnIT/mysql-session.json
  v2/datastream-to-spanner/src/test/resources/DataStreamToSpannerShardedMigrationWithMigrationShardIdColumnIT/mysql-statements.sql
  v2/datastream-to-spanner/src/test/resources/DataStreamToSpannerShardedMigrationWithMigrationShardIdColumnIT/spanner-schema.sql
  v2/spanner-custom-shard/src/main/java/com/custom/CustomTransformationWithShardForIT.java
Labels: Google LGTM, size/XXL

#1542 Add groupName attribute to v1 template where it's needed (part 3)
  v1/src/main/java/com/google/cloud/teleport/bigtable/AvroToBigtable.java
  v1/src/main/java/com/google/cloud/teleport/bigtable/BigtableToAvro.java
  v1/src/main/java/com/google/cloud/teleport/bigtable/BigtableToJson.java
  v1/src/main/java/com/google/cloud/teleport/bigtable/BigtableToParquet.java
  v1/src/main/java/com/google/cloud/teleport/bigtable/BigtableToVectorEmbeddings.java
  v1/src/main/java/com/google/cloud/teleport/bigtable/CassandraToBigtable.java
  v1/src/main/java/com/google/cloud/teleport/bigtable/ParquetToBigtable.java
  v1/src/main/java/com/google/cloud/teleport/spanner/ExportPipeline.java
  v1/src/main/java/com/google/cloud/teleport/spanner/ImportPipeline.java
  v1/src/main/java/com/google/cloud/teleport/spanner/TextImportPipeline.java
  v1/src/main/java/com/google/cloud/teleport/templates/BigQueryToTFRecord.java
  v1/src/main/java/com/google/cloud/teleport/templates/BulkCompressor.java
  v1/src/main/java/com/google/cloud/teleport/templates/BulkDecompressor.java
  v1/src/main/java/com/google/cloud/teleport/templates/CSVToBigQuery.java
  v1/src/main/java/com/google/cloud/teleport/templates/DLPTextToBigQueryStreaming.java
  v1/src/main/java/com/google/cloud/teleport/templates/DatastoreToBigQuery.java
  v1/src/main/java/com/google/cloud/teleport/templates/ExportJobPlaceholder.java
  v1/src/main/java/com/google/cloud/teleport/templates/ImportJobPlaceholder.java
  v1/src/main/java/com/google/cloud/teleport/templates/PubsubToAvro.java
  v1/src/main/java/com/google/cloud/teleport/templates/PubsubToPubsub.java
  v1/src/main/java/com/google/cloud/teleport/templates/PubsubToText.java
  v1/src/main/java/com/google/cloud/teleport/templates/SpannerToText.java
  v1/src/main/java/com/google/cloud/teleport/templates/SpannerVectorEmbeddingExport.java
  v1/src/main/java/com/google/cloud/teleport/templates/TextIOToBigQuery.java
  v1/src/main/java/com/google/cloud/teleport/templates/TextToPubsub.java
  v1/src/main/java/com/google/cloud/teleport/templates/common/SpannerConverters.java
  v1/src/main/java/com/google/cloud/teleport/templates/common/TextConverters.java
Labels: Google LGTM, size/L

#1541 Add groupName attribute to v2 template where it's needed (part 2)
  v2/common/src/main/java/com/google/cloud/teleport/v2/auto/blocks/PubsubMessageToTableRow.java
  v2/common/src/main/java/com/google/cloud/teleport/v2/auto/blocks/ReadFromPubSub.java
  v2/common/src/main/java/com/google/cloud/teleport/v2/auto/blocks/WriteToBigQuery.java
  v2/common/src/main/java/com/google/cloud/teleport/v2/auto/blocks/WriteToPubSub.java
  v2/common/src/main/java/com/google/cloud/teleport/v2/auto/dlq/WriteDlqToBigQuery.java
  v2/common/src/main/java/com/google/cloud/teleport/v2/auto/options/ReadFromJdbcOptions.java
  v2/common/src/main/java/com/google/cloud/teleport/v2/options/BigQueryCommonOptions.java
  v2/common/src/main/java/com/google/cloud/teleport/v2/options/PubsubCommonOptions.java
  v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/options/ElasticsearchWriteOptions.java
  v2/googlecloud-to-elasticsearch/src/main/java/com/google/cloud/teleport/v2/elasticsearch/options/PubSubToElasticsearchOptions.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/options/PubsubToJdbcOptions.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/options/SpannerChangeStreamsToBigQueryOptions.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/options/SpannerChangeStreamsToGcsOptions.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/options/SpannerChangeStreamsToPubSubOptions.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/options/SpannerToBigQueryOptions.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/PubSubToBigQuery.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/PubsubToAvro.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/TextIOToBigQuery.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/pubsubtotext/PubsubToText.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/transforms/WriteDataChangeRecordsToGcsAvro.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/transforms/WriteDataChangeRecordsToGcsText.java
  v2/kafka-to-pubsub/src/main/java/com/google/cloud/teleport/v2/options/KafkaToPubsubOptions.java
  v2/kinesis-to-pubsub/src/main/java/com/google/cloud/teleport/v2/options/KinesisToPubsubOptions.java
  v2/mongodb-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/mongodb/options/MongoDbToBigQueryOptions.java
  v2/mqtt-to-pubsub/src/main/java/com/google/cloud/teleport/v2/templates/MqttToPubsub.java
  v2/pubsub-cdc-to-bigquery/src/main/java/com/google/cloud/teleport/v2/templates/PubSubCdcToBigQuery.java
  v2/pubsub-to-jms/src/main/java/com/google/cloud/teleport/v2/templates/PubsubToJms.java
  v2/pubsub-to-kafka/src/main/java/com/google/cloud/teleport/v2/options/PubsubToKafkaOptions.java
  v2/pubsub-to-mongodb/src/main/java/com/google/cloud/teleport/v2/templates/PubSubToMongoDB.java
  v2/pubsub-to-redis/src/main/java/com/google/cloud/teleport/v2/templates/PubSubToRedis.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/options/SourceDbToSpannerOptions.java
  v2/spanner-change-streams-to-sharded-file-sink/src/main/java/com/google/cloud/teleport/v2/templates/SpannerChangeStreamsToShardedFileSink.java
Labels: Google LGTM, size/L

#1635 Update the skipOptions in Template annotation for kafka template
  v2/kafka-to-bigquery/README_Kafka_to_BigQuery_Flex.md
  v2/kafka-to-bigquery/src/main/java/com/google/cloud/teleport/v2/templates/KafkaToBigQueryFlex.java
  v2/kafka-to-gcs/README_Kafka_to_Gcs_Flex.md
  v2/kafka-to-gcs/src/main/java/com/google/cloud/teleport/v2/templates/KafkaToGcsFlex.java
Labels: size/M

#1643 Fix bug in Kafka To BigQuery Template
  v2/kafka-to-bigquery/src/main/java/com/google/cloud/teleport/v2/templates/KafkaToBigQueryFlex.java
Labels: size/S

#1640 fix for failing forward migration ITs
  cicd/internal/flags/common-flags.go
  cicd/internal/flags/common-flags_test.go
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerITBase.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerShardedMigrationWithMigrationShardIdColumnIT.java
  v2/spanner-change-streams-to-sharded-file-sink/src/test/java/com/google/cloud/teleport/v2/templates/SpannerChangeStreamToGcsITBase.java
Labels: Google LGTM, size/S

#1636 Add TLS authentication support for Kafka Templates
  v2/kafka-to-bigquery/src/main/java/com/google/cloud/teleport/v2/options/KafkaToBigQueryFlexOptions.java
  v2/kafka-to-bigquery/src/main/java/com/google/cloud/teleport/v2/templates/KafkaToBigQueryFlex.java
  v2/kafka-to-gcs/src/main/java/com/google/cloud/teleport/v2/templates/KafkaToGcsFlex.java
Labels: size/M

#1647 Allow flags to be used as jinja template variables.
  python/src/main/python/yaml-template/main.py
Labels: Google LGTM, size/M

#1646 Add integration test for KafkaToBigQuery Template for the JSON format
  v2/kafka-to-bigquery/src/test/java/com/google/cloud/teleport/v2/templates/KafkaToBigQueryFlexAvroIT.java
  v2/kafka-to-bigquery/src/test/java/com/google/cloud/teleport/v2/templates/KafkaToBigQueryFlexJsonIT.java
Labels: size/L

#1652 [BULK] Remove log param
  v2/common/src/main/java/com/google/cloud/teleport/v2/options/CommonTemplateOptions.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/SourceDbToSpanner.java
Labels: Google LGTM, size/S

#1633 [BULK] Shard id population in transformer
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/rowmapper/JdbcSourceRowMapper.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/row/SourceRow.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/SourceDbToSpanner.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/transformer/SourceRowToMutationDoFn.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/row/SourceRowTest.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/transform/ReaderTransformTestUtils.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataTypesIt.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/SingleShardIT.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/SourceDbToSpannerITBase.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/transformer/SourceRowToMutationDoFnTest.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/writer/DeadLetterQueueTest.java
  v2/sourcedb-to-spanner/src/test/resources/SingleShardWithTransformation/session.json
  v2/sourcedb-to-spanner/src/test/resources/SingleShardWithTransformation/source-schema.sql
  v2/sourcedb-to-spanner/src/test/resources/SingleShardWithTransformation/spanner-schema.sql
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/avro/GenericRecordTypeConvertor.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/schema/ISchemaMapper.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/schema/IdentityMapper.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/schema/SessionBasedMapper.java
  v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/avro/GenericRecordTypeConvertorTest.java
  v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/schema/IdentityMapperTest.java
  v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/schema/SessionBasedMapperTest.java
Labels: Google LGTM, size/XL

#1654 [Bulk] Add table name to source row
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/row/SourceRow.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/SourceDbToSpanner.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/transformer/SourceRowToMutationDoFn.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/writer/DeadLetterQueue.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/row/SourceRowTest.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/SourceDbToSpannerTest.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/transformer/SourceRowToMutationDoFnTest.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/writer/DeadLetterQueueTest.java
Labels: Google LGTM, size/L

#1651 timezone test
  v2/gcs-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/TimezoneIT.java
  v2/gcs-to-sourcedb/src/test/resources/TimezoneIT/session.json
  v2/gcs-to-sourcedb/src/test/resources/TimezoneIT/spanner-schema.sql
Labels: Google LGTM, size/L

#1656 [BULK] Add SourceSchemaReference to source row
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/JdbcIoWrapper.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/rowmapper/JdbcSourceRowMapper.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/row/SourceRow.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/rowmapper/JdbcSourceRowMapperTest.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/row/SourceRowTest.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/schema/SchemaTestUtils.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/transform/ReaderTransformTest.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/transform/ReaderTransformTestUtils.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/transformer/SourceRowToMutationDoFnTest.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/writer/DeadLetterQueueTest.java
Labels: Google LGTM, size/L

#1648 Refactor Avro code for Kafka templates
  v2/kafka-common/src/main/java/com/google/cloud/teleport/v2/kafka/transforms/AvroDynamicTransform.java
  v2/kafka-common/src/main/java/com/google/cloud/teleport/v2/kafka/transforms/AvroTransform.java
  v2/kafka-common/src/main/java/com/google/cloud/teleport/v2/kafka/transforms/KafkaRecordToGenericRecordFailsafeElementFn.java
  v2/kafka-to-bigquery/src/main/java/com/google/cloud/teleport/v2/templates/KafkaToBigQueryFlex.java
  v2/kafka-to-bigquery/src/main/java/com/google/cloud/teleport/v2/transforms/AvroDynamicTransform.java
  v2/kafka-to-bigquery/src/main/java/com/google/cloud/teleport/v2/transforms/AvroTransform.java
  v2/kafka-to-bigquery/src/main/java/com/google/cloud/teleport/v2/transforms/BigQueryWriteUtils.java
  v2/kafka-to-gcs/src/main/java/com/google/cloud/teleport/v2/templates/KafkaToGcsFlex.java
  v2/kafka-to-gcs/src/main/java/com/google/cloud/teleport/v2/transforms/AvroWriteTransform.java
  v2/kafka-to-gcs/src/main/java/com/google/cloud/teleport/v2/transforms/WriteTransform.java
  v2/kafka-to-gcs/src/test/java/com/google/cloud/teleport/v2/templates/KafkaToGcsAvroBinaryIT.java
  v2/kafka-to-gcs/src/test/java/com/google/cloud/teleport/v2/templates/KafkaToGcsFlexJsonIT.java
  v2/kafka-to-gcs/src/test/java/com/google/cloud/teleport/v2/templates/KafkaToGcsIT.java
  v2/kafka-to-gcs/src/test/resources/KafkaToGcsAvroBinaryIT/avro_schema.avsc
Labels: size/XXL

#1650 Add SSL authentication to read from Schema Registry
  v2/kafka-common/src/main/java/com/google/cloud/teleport/v2/kafka/options/SchemaRegistryOptions.java
  v2/kafka-common/src/main/java/com/google/cloud/teleport/v2/kafka/transforms/AvroDynamicTransform.java
  v2/kafka-common/src/main/java/com/google/cloud/teleport/v2/kafka/transforms/KafkaRecordToGenericRecordFailsafeElementFn.java
  v2/kafka-common/src/main/java/com/google/cloud/teleport/v2/kafka/utils/FileAwareSchemaRegistryFactoryFn.java
  v2/kafka-common/src/main/java/com/google/cloud/teleport/v2/kafka/utils/KafkaConfig.java
  v2/kafka-to-bigquery/src/main/java/com/google/cloud/teleport/v2/templates/KafkaToBigQueryFlex.java
  v2/kafka-to-gcs/src/main/java/com/google/cloud/teleport/v2/transforms/AvroWriteTransform.java
  v2/kafka-to-gcs/src/main/java/com/google/cloud/teleport/v2/transforms/WriteTransform.java
Labels: size/L

#1664 Enable PR reports for Spanner PR
  .github/workflows/java-pr-report.yml
Labels: Google LGTM, size/XS

#1639 Add runner_v2 variant to StreamingDataGeneratorIT
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/TemplateTestBase.java
  v2/streaming-data-generator/src/test/java/com/google/cloud/teleport/v2/templates/StreamingDataGeneratorIT.java
Labels: Google LGTM, size/M

#1637 Increase timeout for Java PRs
  .github/workflows/java-pr.yml
Labels: size/XS

#1662 Add PubSubCdcToBigQueryIT
  v2/pubsub-cdc-to-bigquery/pom.xml
  v2/pubsub-cdc-to-bigquery/src/main/java/com/google/cloud/teleport/v2/templates/PubSubCdcToBigQuery.java
  v2/pubsub-cdc-to-bigquery/src/test/java/com/google/cloud/teleport/v2/templates/PubSubCdcToBigQueryIT.java
Labels: size/L

#1576 Build out more CI/CD documentation
  contributor-docs/cicd.md
  contributor-docs/maintainers-guide.md
Labels: Google LGTM, size/L

#1663 Add terraform validator
  .github/workflows/spanner-terraform-validator.yml
  v2/sourcedb-to-spanner/terraform/samples/multiple-jobs/outputs.tf
  v2/sourcedb-to-spanner/terraform/samples/multiple-jobs/terraform.tf
  v2/sourcedb-to-spanner/terraform/samples/multiple-jobs/terraform.tfvars
  v2/sourcedb-to-spanner/terraform/samples/multiple-jobs/terraform_simple.tfvars
  v2/sourcedb-to-spanner/terraform/samples/multiple-jobs/variables.tf
Labels: Google LGTM, size/M

#1671 Fix return for Kafka Avro deserializer
  v2/kafka-common/src/main/java/com/google/cloud/teleport/v2/kafka/transforms/KafkaRecordToGenericRecordFailsafeElementFn.java
Labels: size/S

#1665 base64 handling simplified
  v2/gcs-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/processing/dml/DMLGenerator.java
  v2/gcs-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/processing/dml/DMLGeneratorTest.java
Labels: Google LGTM, size/L

#1659 Schema mapping itests
  v2/sourcedb-to-spanner/README.md
  v2/sourcedb-to-spanner/README_Sourcedb_to_Spanner.md
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/IdentitySchemaMapperIT.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/IdentitySchemaMapperWithTransformationIT.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/SessionSchemaMapperIT.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/SessionSchemaMapperWithTableFilterIT.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/SessionSchemaMapperWithTransformationIT.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/SourceDbToSpannerITBase.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/writer/DeadLetterQueueTest.java
  v2/sourcedb-to-spanner/src/test/resources/SchemaMapperIT/company-mysql-schema.sql
  v2/sourcedb-to-spanner/src/test/resources/SchemaMapperIT/company-session-with-transformation.json
  v2/sourcedb-to-spanner/src/test/resources/SchemaMapperIT/company-session.json
  v2/sourcedb-to-spanner/src/test/resources/SchemaMapperIT/company-spanner-schema-with-transformation.sql
  v2/sourcedb-to-spanner/src/test/resources/SchemaMapperIT/company-spanner-schema.sql
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/schema/SessionBasedMapper.java
  v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/schema/SessionBasedMapperTest.java
Labels: Google LGTM, size/XXL

#1673 Spanner to MySQL reverse replication Load test 100 TPS
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/LoadTestBase.java
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/datagenerator/DataGenerator.java
  it/jdbc/pom.xml
  it/jdbc/src/main/java/org/apache/beam/it/jdbc/conditions/JDBCRowsCheck.java
  it/jdbc/src/main/java/org/apache/beam/it/jdbc/conditions/package-info.java
  v2/gcs-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/SpannerToJdbcLTBase.java
  v2/gcs-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/SpannerToMySql100TpsLT.java
  v2/gcs-to-sourcedb/src/test/resources/SpannerToMySql100TpsLT/datagenerator-schema.json
  v2/gcs-to-sourcedb/src/test/resources/SpannerToMySql100TpsLT/mysql-schema.sql
  v2/gcs-to-sourcedb/src/test/resources/SpannerToMySql100TpsLT/session.json
  v2/gcs-to-sourcedb/src/test/resources/SpannerToMySql100TpsLT/spanner-schema.sql
Labels: Google LGTM, size/XL

#1660 Add CloudSql resource manager
  cicd/cmd/run-it-smoke-tests/main.go
  cicd/cmd/run-it-tests/main.go
  cicd/cmd/run-load-tests/main.go
  cicd/internal/flags/it-flags.go
  it/google-cloud-platform/pom.xml
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/bigquery/BigQueryResourceManagerUtils.java
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/bigtable/BigtableResourceManagerUtils.java
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/cloudsql/CloudMySQLResourceManager.java
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/cloudsql/CloudOracleResourceManager.java
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/cloudsql/CloudSqlContainer.java
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/cloudsql/CloudSqlResourceManager.java
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/cloudsql/CloudSqlResourceManagerException.java
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/cloudsql/CloudSqlResourceManagerUtils.java
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/cloudsql/package-info.java
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/datastream/DatastreamResourceManagerUtils.java
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/spanner/utils/SpannerResourceManagerUtils.java
  it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/cloudsql/CloudMySQLResourceManagerTest.java
  it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/cloudsql/CloudOracleResourceManagerTest.java
  it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/cloudsql/CloudSqlResourceManagerIT.java
  it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/cloudsql/CloudSqlResourceManagerTest.java
Labels: size/XXL

#1465 Allow custom endpoints for Spanner ITs
  .github/workflows/release.yml
  cicd/cmd/run-it-smoke-tests/main.go
  cicd/cmd/run-it-tests/main.go
  cicd/internal/flags/it-flags.go
  cicd/internal/workflows/maven-workflows.go
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/spanner/SpannerResourceManager.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ExportPipelineIT.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ImportPipelineIT.java
  v1/src/test/java/com/google/cloud/teleport/templates/SpannerToTextIT.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/SpannerChangeStreamsToGcsIT.java
Labels: size/L

#1462 Remove redundant PubSubToBigQuerySubscriptionIT
  v1/src/test/java/com/google/cloud/teleport/templates/PubSubSubscriptionToBigQueryIT.java
Labels: size/L

#1624 DataStream to spanner 100GB load test
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/spanner/SpannerResourceManager.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerLT100Gb.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerLTBase.java
  v2/datastream-to-spanner/src/test/resources/DataStreamToSpannerLT100Gb/spanner-schema.sql
Labels: Google LGTM, size/L

#1677 Explicitly enable AutoValue annotation processor
  it/pom.xml
  plaintext-logging/pom.xml
  structured-logging/pom.xml
  v1/pom.xml
  v2/pom.xml
Labels: Google LGTM, size/M

#1679 Fix upgrade bigtable-beam-import to 2.14.2 to support Data Boost (atttempt 2)
  v1/pom.xml
Labels: Google LGTM, size/XS

#1676 Add Kafka read topic and kafka write topic pickers replacing kafka topic picker
  metadata/src/main/java/com/google/cloud/teleport/metadata/TemplateParameter.java
  metadata/src/main/java/com/google/cloud/teleport/metadata/util/MetadataUtils.java
  plugins/core-plugin/src/main/java/com/google/cloud/teleport/plugin/model/ImageSpecParameter.java
  plugins/core-plugin/src/main/java/com/google/cloud/teleport/plugin/model/ImageSpecParameterType.java
  plugins/core-plugin/src/test/java/com/google/cloud/teleport/plugin/model/TemplateDefinitionsTest.java
  plugins/core-plugin/src/test/java/com/google/cloud/teleport/plugin/sample/AtoBOk.java
  v2/kafka-common/src/main/java/com/google/cloud/teleport/v2/kafka/options/KafkaReadOptions.java
  v2/kafka-common/src/main/java/com/google/cloud/teleport/v2/kafka/options/KafkaWriteOptions.java
  v2/kafka-to-bigquery/src/main/java/com/google/cloud/teleport/v2/options/KafkaToBigQueryFlexOptions.java
  v2/kafka-to-gcs/src/main/java/com/google/cloud/teleport/v2/templates/KafkaToGcsFlex.java
  v2/kafka-to-kafka/src/main/java/com/google/cloud/teleport/v2/templates/KafkaToKafka.java
Labels: size/L

#1684 Fix BQ deadletter queue for Kafka template
  v2/kafka-common/src/main/java/com/google/cloud/teleport/v2/kafka/dlq/BigQueryDeadLetterQueueOptions.java
  v2/kafka-common/src/main/java/com/google/cloud/teleport/v2/kafka/dlq/package-info.java
  v2/kafka-to-bigquery/src/main/java/com/google/cloud/teleport/v2/options/KafkaToBigQueryFlexOptions.java
  v2/kafka-to-bigquery/src/test/java/com/google/cloud/teleport/v2/templates/KafkaToBigQueryFlexAvroIT.java
Labels: size/L

#1661 Add full suite of Datastream to Spanner IT's
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/datastream/DatastreamResourceManager.java
  v2/datastream-to-spanner/pom.xml
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerIT.java
  v2/datastream-to-spanner/src/test/resources/DataStreamToSpannerIT/mysql-session.json
Labels: size/XXL

#1675 sharded migrations v1
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/options/OptionsToConfigBuilder.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/options/SourceDbToSpannerOptions.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/JdbcIoWrapper.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/config/JdbcIOWrapperConfig.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/rowmapper/JdbcSourceRowMapper.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/PipelineController.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/SourceDbToSpanner.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/options/OptionsToConfigBuilderTest.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/rowmapper/JdbcSourceRowMapperTest.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/SourceDbToSpannerITBase.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/SourceDbToSpannerTest.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/utilities/ShardedMySQLResourceManager.java
  v2/sourcedb-to-spanner/src/test/resources/SchemaMapperIT/company-session-sharded.json
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/schema/SessionBasedMapper.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/shard/Shard.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/utils/ShardFileReader.java
  v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/utils/ShardFileReaderTest.java
  v2/spanner-common/src/test/resources/bulk-migration-shards.json
Labels: Google LGTM, size/XXL

#1669 Terraform Sample: Live migration all infrastructure setup
  .github/workflows/spanner-terraform-validator.yml
  v2/datastream-to-spanner/terraform/samples/README.md
  v2/datastream-to-spanner/terraform/samples/mysql-end-to-end/README.md
  v2/datastream-to-spanner/terraform/samples/mysql-end-to-end/main.tf
  v2/datastream-to-spanner/terraform/samples/mysql-end-to-end/outputs.tf
  v2/datastream-to-spanner/terraform/samples/mysql-end-to-end/terraform.tf
  v2/datastream-to-spanner/terraform/samples/mysql-end-to-end/terraform.tfvars
  v2/datastream-to-spanner/terraform/samples/mysql-end-to-end/terraform_simple.tfvars
  v2/datastream-to-spanner/terraform/samples/mysql-end-to-end/variables.tf
Labels: Google LGTM, size/XXL

#1670 Terraform Sample: Live migration pre-configured profiles
  v2/datastream-to-spanner/terraform/samples/pre-configured-conn-profiles/README.md
  v2/datastream-to-spanner/terraform/samples/pre-configured-conn-profiles/main.tf
  v2/datastream-to-spanner/terraform/samples/pre-configured-conn-profiles/outputs.tf
  v2/datastream-to-spanner/terraform/samples/pre-configured-conn-profiles/terraform.tf
  v2/datastream-to-spanner/terraform/samples/pre-configured-conn-profiles/terraform.tfvars
  v2/datastream-to-spanner/terraform/samples/pre-configured-conn-profiles/terraform_simple.tfvars
  v2/datastream-to-spanner/terraform/samples/pre-configured-conn-profiles/variables.tf
Labels: Google LGTM, size/XL

#1579 [PubSub to Datadog] Updating Datadog template to include full pubSub message by default
  v1/README_Cloud_PubSub_to_Datadog.md
  v1/src/main/java/com/google/cloud/teleport/templates/PubSubToDatadog.java
  v1/src/main/java/com/google/cloud/teleport/templates/common/DatadogConverters.java
  v1/terraform/Cloud_PubSub_to_Datadog/dataflow_job.tf
Labels: Google LGTM, size/S

#1689 [BULK] Add type coverage for custom transformations
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/CustomTransformationsNonShardedIT.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataTypesIt.java
  v2/sourcedb-to-spanner/src/test/resources/CustomTransformationsNonShardedIT/mysql-schema.sql
  v2/sourcedb-to-spanner/src/test/resources/CustomTransformationsNonShardedIT/spanner-schema.sql
  v2/sourcedb-to-spanner/src/test/resources/DataTypesIt/data-types.sql
  v2/sourcedb-to-spanner/src/test/resources/DataTypesIt/spanner-schema.sql
  v2/spanner-custom-shard/src/main/java/com/custom/CustomTransformationWithShardForIT.java
Labels: Google LGTM, size/L

#1672 Terraform Sample: MySQL database setup for private connectivity
  .github/workflows/spanner-terraform-validator.yml
  v2/spanner-common/terraform/samples/README.md
  v2/spanner-common/terraform/samples/mysql-vpc-spanner/README.md
  v2/spanner-common/terraform/samples/mysql-vpc-spanner/main.tf
  v2/spanner-common/terraform/samples/mysql-vpc-spanner/mysql5.7-setup.sh
  v2/spanner-common/terraform/samples/mysql-vpc-spanner/mysql8.4-setup.sh
  v2/spanner-common/terraform/samples/mysql-vpc-spanner/outputs.tf
  v2/spanner-common/terraform/samples/mysql-vpc-spanner/terraform.tf
  v2/spanner-common/terraform/samples/mysql-vpc-spanner/terraform.tfvars
  v2/spanner-common/terraform/samples/mysql-vpc-spanner/terraform_simple.tfvars
  v2/spanner-common/terraform/samples/mysql-vpc-spanner/variables.tf
Labels: Google LGTM, size/XL

#1655 Added support for advanced transformation in reverse replication
  v2/gcs-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/GCSToSourceDb.java
  v2/gcs-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/processing/handler/GCSToSourceStreamingHandler.java
  v2/gcs-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/processing/handler/InputRecordProcessor.java
  v2/gcs-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/transforms/GcsToSourceStreamer.java
  v2/gcs-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/processing/handler/GCSToSourceStreamingHandlerTest.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/convertors/ChangeEventToMapConvertor.java
  v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/convertors/ChangeEventToMapConvertorTest.java
Labels: Google LGTM, size/L

#1688 ignoring views from ddl tables
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/dialectadapter/mysql/MysqlDialectAdapter.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/dialectadapter/mysql/MysqlDialectAdapterTest.java
  v2/sourcedb-to-spanner/src/test/resources/SchemaMapperIT/company-mysql-schema.sql
  v2/sourcedb-to-spanner/src/test/resources/SchemaMapperIT/company-spanner-schema.sql
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/ddl/Ddl.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/ddl/InformationSchemaScanner.java
  v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/ddl/InformationSchemaScannerTest.java
Labels: Google LGTM, size/M

#1685 Make Beam version validation for DataflowTemplates easier
  contributor-docs/maintainers-guide.md
  plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesStageMojo.java
  pom.xml
  python/src/test/java/com/google/cloud/teleport/templates/python/YAMLTemplateIT.java
  python/src/test/resources/YamlTemplateIT.yaml
Labels: size/XS

#1690 Retry 429 errors to Dataflow on IT's
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/dataflow/AbstractPipelineLauncher.java
Labels: size/S

#1695 Upgrade Beam version to 2.57
  pom.xml
  v1/pom.xml
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstopubsub/model/Mod.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstopubsub/BigtableChangeStreamsToPubSubIT.java
  v2/pom.xml
Labels: size/M
