Repository GoogleCloudPlatform/DataflowTemplates, pull requests merged in 2024-12, with the labels that each got.

#2041 Setting useCursorFetch for MySql if FetchSize is configured.
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/options/OptionsToConfigBuilder.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/options/SourceDbToSpannerOptions.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/options/OptionsToConfigBuilderTest.java
Labels: size/M, bug-fix

#2016 Add DLQ support to JdbcToBigQuery using BQ Storage Write API
  v2/common/src/main/java/com/google/cloud/teleport/v2/transforms/ErrorConverters.java
  v2/jdbc-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/options/JdbcToBigQueryOptions.java
  v2/jdbc-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/JdbcToBigQuery.java
  v2/jdbc-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/JdbcToBigQueryIT.java
Labels: size/L, improvement

#2029 [KafkaToBigQueryFlex Template]: Add support for Avro ENUM type and fix FLOAT type.
  v2/kafka-to-bigquery/src/main/java/com/google/cloud/teleport/v2/utils/BigQueryAvroUtils.java
  v2/kafka-to-bigquery/src/test/java/com/google/cloud/teleport/v2/templates/KafkaToBigQueryFlexAvroIT.java
  v2/kafka-to-bigquery/src/test/resources/KafkaToBigQueryFlexAvroIT/avro_schema.avsc
Labels: size/L, bug-fix

#2020 Parameterizing spanner Host in spanner tests
  cicd/cmd/run-it-smoke-tests/main.go
  cicd/cmd/run-it-tests/main.go
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/TemplateTestBase.java
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/spanner/SpannerResourceManager.java
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/spanner/SpannerTemplateITBase.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ExportPipelineIT.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ImportPipelineIT.java
  v1/src/test/java/com/google/cloud/teleport/templates/SpannerToTextIT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerIT.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/SpannerChangeStreamsToGcsIT.java
Labels: size/L, improvement

#2035 Add extra validation to SpannerToBigQuery Template
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/options/SpannerToBigQueryOptions.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/SpannerToBigQuery.java
Labels: size/XS, improvement

#2047 Update add-flex-template.md
  contributor-docs/add-flex-template.md
Labels: size/XS, ignore-for-release

#2040 custom transformation implementation
  v2/spanner-to-sourcedb/pom.xml
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/SpannerToSourceDb.java
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/constants/Constants.java
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/dbutils/dml/MySQLDMLGenerator.java
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/dbutils/processor/InputRecordProcessor.java
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/models/DMLGeneratorRequest.java
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/transforms/SourceWriterFn.java
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/transforms/SourceWriterTransform.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/dbutils/dml/MySQLDMLGeneratorTest.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/transforms/SourceWriterFnTest.java
  v2/spanner-to-sourcedb/src/test/resources/customTransformation.json
Labels: size/XL, improvement

#2042 Adding dataflow timestamp field in datastream-common json flow
  v2/datastream-common/src/main/java/com/google/cloud/teleport/v2/datastream/transforms/FormatDatastreamJsonToJson.java
  v2/datastream-common/src/test/java/com/google/cloud/teleport/v2/datastream/transforms/FormatDatastreamJsonToJsonTest.java
Labels: size/M, bug-fix

#2046 minor typo in logs
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/options/OptionsToConfigBuilder.java
Labels: size/XS, ignore-for-release

#2049 feat: introduce new configuration properties for bigquery source
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/helpers/BigQuerySpec.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/sources/BigQuerySource.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/sources/BigQuerySourceProvider.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/validation/BigQuerySourceProjectDatasetValidator.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/providers/bigquery/BigQueryImpl.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/providers/bigquery/BqQueryToRow.java
  v2/googlecloud-to-neo4j/src/main/resources/META-INF/services/org.neo4j.importer.v1.validation.SpecificationValidator
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/model/validation/BigQuerySourceProjectDatasetValidatorTest.java
Labels: size/L, improvement

#2027 Update `LoadTestBase.java` reference
  contributor-docs/add-integration-or-load-test.md
Labels: size/XS, ignore-for-release

#1812 feat(spanner): add support for identity columns in import/export
  v1/src/main/java/com/google/cloud/teleport/spanner/AvroSchemaToDdlConverter.java
  v1/src/main/java/com/google/cloud/teleport/spanner/AvroUtil.java
  v1/src/main/java/com/google/cloud/teleport/spanner/DdlToAvroSchemaConverter.java
  v1/src/main/java/com/google/cloud/teleport/spanner/ddl/Column.java
  v1/src/main/java/com/google/cloud/teleport/spanner/ddl/DatabaseOptionAllowlist.java
  v1/src/main/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScanner.java
  v1/src/main/java/com/google/cloud/teleport/spanner/ddl/Sequence.java
  v1/src/test/java/com/google/cloud/teleport/spanner/AvroSchemaToDdlConverterTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/CopyDbTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/DdlToAvroSchemaConverterTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ImportFromAvroTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ddl/DdlTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScannerIT.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScannerTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ddl/RandomInsertMutationGenerator.java
Labels: addition, size/XL, improvement

#2053 Creating new annotation and new workflow for spanner staging tests
  .github/workflows/spanner-staging-tests.yml
  cicd/cmd/run-it-smoke-tests/main.go
  cicd/cmd/run-it-tests/main.go
  cicd/internal/flags/it-flags.go
  metadata/src/main/java/com/google/cloud/teleport/metadata/SpannerStagingTest.java
  pom.xml
  v1/src/test/java/com/google/cloud/teleport/spanner/ExportPipelineIT.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ImportPipelineIT.java
  v1/src/test/java/com/google/cloud/teleport/templates/SpannerToTextIT.java
  v1/src/test/java/com/google/cloud/teleport/templates/TextImportPipelineIT.java
Labels: Spanner, size/L, improvement

#2062 regenerated docs to recover missing template parameters
  v1/README_Cassandra_To_Cloud_Bigtable.md
  v1/README_Cloud_Bigtable_to_GCS_Json.md
  v1/README_Cloud_Bigtable_to_Vector_Embeddings.md
  v1/README_Cloud_PubSub_to_Datadog.md
  v2/bigquery-to-bigtable/README_BigQuery_to_Bigtable.md
  v2/datastream-to-spanner/README_Cloud_Datastream_to_Spanner.md
  v2/googlecloud-to-elasticsearch/README_BigQuery_to_Elasticsearch.md
  v2/googlecloud-to-elasticsearch/README_BigQuery_to_Elasticsearch_Xlang.md
  v2/googlecloud-to-googlecloud/README_Cloud_Spanner_to_BigQuery_Flex.md
  v2/googlecloud-to-neo4j/README_Google_Cloud_to_Neo4j.md
  v2/jdbc-to-googlecloud/README_Jdbc_to_BigQuery_Flex.md
  v2/kafka-to-bigquery/README_Kafka_to_BigQuery_Flex.md
  v2/kafka-to-gcs/README_Kafka_to_Gcs_Flex.md
  v2/kafka-to-kafka/README_Kafka_to_Kafka.md
  v2/mysql-to-googlecloud/README_MySQL_to_BigQuery.md
  v2/oracle-to-googlecloud/README_Oracle_to_BigQuery.md
  v2/postgresql-to-googlecloud/README_PostgreSQL_to_BigQuery.md
  v2/sourcedb-to-spanner/README_Cloud_Datastream_to_Spanner.md
  v2/sourcedb-to-spanner/README_Sourcedb_to_Spanner_Flex.md
  v2/spanner-to-sourcedb/README_Spanner_to_SourceDb.md
  v2/sqlserver-to-googlecloud/README_SQLServer_to_BigQuery.md
Labels: size/L, ignore-for-release

#2048 Cassandra Schema and Value Mapping
  v2/datastream-common/src/main/java/com/google/cloud/teleport/v2/datastream/transforms/FormatDatastreamRecordToJson.java
  v2/datastream-common/src/test/java/com/google/cloud/teleport/v2/datastream/transforms/FormatDatastreamRecordToJsonTest.java
  v2/sourcedb-to-spanner/pom.xml
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/mappings/CassandraMappings.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/mappings/CassandraMappingsProvider.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/mappings/package-info.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/rowmapper/CassandraFieldMapper.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/rowmapper/CassandraRowMapper.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/rowmapper/CassandraRowValueExtractor.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/rowmapper/CassandraRowValueMapper.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/rowmapper/CassandraSourceRowMapper.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/rowmapper/package-info.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/schema/CassandraSchemaDiscovery.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/schema/typemapping/UnifiedTypeMapper.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/schema/typemapping/provider/unified/CustomSchema.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/schema/typemapping/provider/unified/UnifiedMappingProvider.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/rowmapper/CassandraSourceRowMapperTest.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/schema/CassandraSchemaDiscoveryTest.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/testutils/BasicTestSchema.java
  v2/sourcedb-to-spanner/src/test/resources/CassandraUT/basicTest.cql
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/avro/GenericRecordTypeConvertor.java
  v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/avro/AvroTestingHelper.java
  v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/avro/GenericRecordTypeConvertorTest.java
Labels: addition, size/XXL, ignore-for-release

#2012 Fix disabled algorithm default
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/templates/GoogleCloudToNeo4j.java
Labels: size/XS, bug-fix

#2005 tests: Bulk IT Tests
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/MySQLDDLIT.java
  v2/sourcedb-to-spanner/src/test/resources/DDLIT/company-mysql-schema.sql
  v2/sourcedb-to-spanner/src/test/resources/DDLIT/company-session.json
  v2/sourcedb-to-spanner/src/test/resources/DDLIT/company-spanner-schema.sql
Labels: size/XXL, ignore-for-release

#2069 update Java Version to 17 on GitHub Actions workers
  .github/scripts/startup-script.sh
  contributor-docs/cicd.md
Labels: size/S, ignore-for-release

#2070 update default it runner count to 5
  .github/scripts/configure-runners.sh
Labels: size/XS, ignore-for-release

#2054 Cassandra datatype handler
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/dbutils/dml/CassandraTypeHandler.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/dbutils/dml/CassandraTypeHandlerTest.java
Labels: size/XXL, improvement

#2073 Update uw-tests.yml
  .github/workflows/uw-tests.yml
Labels: size/XS

#2064 Correcting Partitioning Logic for `VarBinary` Primary Key Type.
  v2/sourcedb-to-spanner/pom.xml
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/dialectadapter/mysql/MysqlDialectAdapter.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/JdbcIoWrapper.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/uniformsplitter/range/BoundaryExtractorFactory.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/uniformsplitter/range/BoundarySplitterFactory.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/schema/SourceColumnIndexInfo.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/dialectadapter/mysql/MysqlDialectAdapterTest.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/JdbcIoWrapperTest.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/uniformsplitter/range/BoundaryExtractorFactoryTest.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/uniformsplitter/range/BoundarySplitterFactoryTest.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/MySQLDataTypesIT.java
  v2/sourcedb-to-spanner/src/test/resources/DataTypesIT/mysql-data-types.sql
  v2/sourcedb-to-spanner/src/test/resources/DataTypesIT/mysql-spanner-schema.sql
Labels: size/XL, bug-fix

#2072 Cassandra DAO Implementation
  v2/spanner-to-sourcedb/pom.xml
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/dbutils/dao/source/CassandraDao.java
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/models/PreparedStatementGeneratedResponse.java
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/models/PreparedStatementValueObject.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/dbutils/dao/source/CassandraDaoTest.java
Labels: addition, size/L, ignore-for-release

#2080 Use [self-hosted, it] for prepare java cache workflow
  .github/workflows/prepare-java-cache.yml
Labels: size/XS, ignore-for-release

#2083 Create README.md for UDF samples
  v2/common/src/main/resources/udf-samples/README.md
Labels: size/M, ignore-for-release

#2077 Cassandra Driver Config Loader for Cassandra Driver Config in GCS
  v2/spanner-common/pom.xml
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/utils/CassandraDriverConfigLoader.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/utils/JarFileReader.java
  v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/utils/CassandraDriverConfigLoaderTest.java
  v2/spanner-common/src/test/resources/test-cassandra-config-parse-err.conf
  v2/spanner-common/src/test/resources/test-cassandra-config.conf
Labels: size/XXL, ignore-for-release

#2085 add fetch-depth to uw workflow
  .github/workflows/uw-tests.yml
Labels: size/XS

#2087 updated readme with supported sources
  v2/sourcedb-to-spanner/README.md
Labels: size/S, Documentation, ignore-for-release

#2063 [Sourcedb-to-spanner] Bulk migration Mysql to spanner 1tb Load test
  it/google-cloud-platform/src/main/java/org/apache/beam/it/jdbc/StaticJDBCResource.java
  it/google-cloud-platform/src/main/java/org/apache/beam/it/jdbc/StaticMySQLResource.java
  it/google-cloud-platform/src/main/java/org/apache/beam/it/jdbc/StaticPostgresqlResource.java
  it/google-cloud-platform/src/main/java/org/apache/beam/it/jdbc/package-info.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/loadtesting/MySQLSourceDbToSpannerLT.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/loadtesting/SourceDbToSpannerLTBase.java
  v2/sourcedb-to-spanner/src/test/resources/SourceDbToSpannerLT/mysql-spanner-schema.sql
Labels: size/L, integration testing, improvement

#2086 PipelineController Changes for Cassandra Bulk
  v2/sourcedb-to-spanner/derby.log
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/options/SourceDbToSpannerOptions.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/IoWrapperFactory.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraIOWrapperFactory.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/DbConfigContainer.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/DbConfigContainerDefaultImpl.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/PipelineController.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/SourceDbToSpanner.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraIOWrapperFactoryTest.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DbConfigContainerDefaultImplTest.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/PipelineControllerTest.java
Labels: size/XL, ignore-for-release

#2092 Fix Spanner Load tests and add display test report
  .github/workflows/spanner-load-tests.yml
  .github/workflows/spanner-pr.yml
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/monitoring/MonitoringClient.java
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/pubsub/PubsubResourceManager.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/loadtesting/DataStreamToSpannerLTBase.java
Labels: size/S, integration testing, improvement
