Repository GoogleCloudPlatform/DataflowTemplates, pull requests merged in 2025-09, with the labels that each got.

#2722 add float32 support to spanner-to-sourcedb
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/dbutils/dml/MySQLDMLGenerator.java
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/transforms/AssignShardIdFn.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/transforms/AssignShardIdFnTest.java
Labels: size/M, bug-fix

#2739 ci(release): add package-upgrade label to release notes configuration
  .github/release.yml
  .github/workflows/release-notes-labels.yml
  .github/workflows/update-python-deps.yml
  contributor-docs/code-contributions.md
Labels: size/S, ignore-for-release

#2734 fix SourceDbToSpanner desc truncations
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/options/SourceDbToSpannerOptions.java
Labels: size/S, bug-fix

#2746 fix: update MongoDB container image tag in integration test setup
  v2/mongodb-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/mongodb/templates/MongoDbToBigQueryIT.java
Labels: size/XS, ignore-for-release

#2760 ci: include HTML reports in surefire test artifacts
  .github/workflows/bigtable-pr.yml
  .github/workflows/datastream-pr.yml
  .github/workflows/java-pr-report.yml
  .github/workflows/java-pr.yml
  .github/workflows/kafka-pr.yml
  .github/workflows/load-tests.yml
  .github/workflows/run-it-tests-beam-snapshots.yml
  .github/workflows/spanner-load-tests.yml
  .github/workflows/spanner-pr.yml
  .github/workflows/spanner-staging-tests.yml
  lt/observability/pom.xml
  pom.xml
  v2/cdc-parent/pom.xml
Labels: size/L, ignore-for-release

#2753 Spanner to sourceDb: source failure injection test
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/testutils/failureinjectiontesting/NetworkFailureInjector.java
  v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/testutils/failureinjectiontesting/NetworkFailureInjectorTest.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/failureinjectiontesting/SpannerToSrcDBMySQLSourceFT.java
Labels: size/XL, ignore-for-release

#2774 ci: Correcting syntax errors in workflow yaml files
  .github/workflows/load-tests.yml
  .github/workflows/spanner-load-tests.yml
  .github/workflows/spanner-pr.yml
  .github/workflows/spanner-staging-tests.yml
Labels: size/M, ignore-for-release

#2777 Update generate_dependencies.sh
  python/generate_dependencies.sh
Labels: size/XS, ignore-for-release

#2785 fix(build): correct sed command to handle test time formats
  pom.xml
Labels: size/XS, ignore-for-release

#2769 SourceDb to Spanner: SourceDb failure injection test
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/failureinjectiontesting/MySQLSrcDbToSpannerSourceFT.java
Labels: size/L, ignore-for-release

#2749 Introduce Schemaless graphs to import/export DDL
  v1/src/main/java/com/google/cloud/teleport/spanner/AvroSchemaToDdlConverter.java
  v1/src/main/java/com/google/cloud/teleport/spanner/AvroUtil.java
  v1/src/main/java/com/google/cloud/teleport/spanner/DdlToAvroSchemaConverter.java
  v1/src/main/java/com/google/cloud/teleport/spanner/ddl/GraphElementTable.java
  v1/src/main/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScanner.java
  v1/src/main/java/com/google/cloud/teleport/spanner/ddl/PropertyGraph.java
  v1/src/test/java/com/google/cloud/teleport/spanner/AvroSchemaToDdlConverterTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/DdlToAvroSchemaConverterTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ddl/DdlTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScannerIT.java
Labels: size/L, improvement

#2786 Revert "feat(dataflow): replace cancelJob with forceCancelJob"
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/TemplateTestBase.java
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/dataflow/AbstractPipelineLauncher.java
  it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/dataflow/AbstractPipelineLauncherTest.java
Labels: size/M, ignore-for-release

#2789 DataStreamToSpanner - Adding main table read at the beginning of main transaction
  v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/SpannerTransactionWriterDoFn.java
  v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/datastream/ChangeEventContext.java
  v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/datastream/MySqlChangeEventSequence.java
  v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/datastream/OracleChangeEventSequence.java
  v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/datastream/PostgresChangeEventSequence.java
  v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/datastream/ShadowTableReadUtils.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/datastream/MySqlChangeEventContextTest.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/datastream/ShadowTableReadUtilsTest.java
Labels: size/L, improvement

#2804 Changing Hikari Config for Reverse replication to not fail during initialization
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/dbutils/connection/JdbcConnectionHelper.java
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/transforms/SourceWriterFn.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/dbutils/connection/JdbcConnectionHelperTest.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/transforms/SourceWriterFnTest.java
Labels: size/M, ignore-for-release, bug-fix

#2802 Disabling flaky and incorrect LTs to unblock LT pipeline
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/loadtesting/MySQLSourceDbtoSpannerWideRow10MBPerCellLT.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/SpannerToCassandraSourceLT.java
Labels: ignore-for-release

#2806 Update ensurepip to avoid vulnerabilities in wheels
  plugins/core-plugin/src/main/resources/Dockerfile-template-yaml
Labels: size/XS, ignore-for-release

#2782 Add Run, Staging and Validation stages for KafkaToBigquery Yaml template
  contributor-docs/code-contributions.md
  plugins/templates-maven-plugin/pom.xml
  plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesStageMojo.java
  plugins/templates-maven-plugin/src/test/java/com/google/cloud/teleport/plugin/maven/TemplatesStageMojoTest.java
  yaml/README_Kafka_to_BigQuery_Yaml.md
  yaml/pom.xml
  yaml/src/main/java/com/google/cloud/teleport/templates/yaml/KafkaToBigQueryYaml.java
  yaml/src/main/python/main.py
  yaml/src/main/yaml/KafkaToBigQuery.yaml
  yaml/src/test/java/com/google/cloud/teleport/templates/yaml/KafkaToBigQueryYamlIT.java
Labels: addition, Documentation, size/XXL, java, python, improvement, yaml

#2151 Fix vector index detection
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/database/Neo4jCapabilities.java
Labels: size/XS, stale, bug-fix

#2830 Upgrade to Beam 2.68.0
  pom.xml
  python/default_base_python_requirements.txt
  python/default_base_yaml_requirements.txt
  python/src/main/python/job-builder-server/requirements.txt
  python/src/main/python/streaming-llm/base_requirements.txt
  python/src/main/python/streaming-llm/requirements.txt
  python/src/main/python/word-count-python/requirements.txt
  python/src/main/python/yaml-template/requirements.txt
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/spanner/DatastreamToSpannerExceptionClassifierIT.java
  v2/googlecloud-to-elasticsearch/src/main/resources/requirements.txt
  v2/googlecloud-to-googlecloud/src/main/resources/requirements.txt
  v2/googlecloud-to-splunk/src/main/resources/requirements.txt
  v2/mongodb-to-googlecloud/pom.xml
  v2/pubsub-binary-to-bigquery/src/main/resources/requirements.txt
  v2/pubsub-to-mongodb/src/main/resources/requirements.txt
  yaml/src/main/python/requirements.txt
Labels: size/XXL, package-upgrade
