Repository GoogleCloudPlatform/DataflowTemplates, pull requests merged in 2025-02, with the labels that each got.

#2152 Search indexes
  v1/src/main/java/com/google/cloud/teleport/spanner/ddl/Index.java
  v1/src/main/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScanner.java
  v1/src/test/java/com/google/cloud/teleport/spanner/DdlToAvroSchemaConverterTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ExportPipelineIT.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ddl/DdlTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScannerIT.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScannerTest.java
Labels: size/L, improvement

#2165 Cassandra Bulk - List and Set - Avro Mapping.
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/mappings/CassandraMappings.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/mappings/CassandraMappingsProvider.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/rowmapper/CassandraRowMapper.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/rowmapper/CassandraRowValueArrayMapper.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/rowmapper/CassandraRowValueExtractor.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/schema/CassandraSchemaDiscovery.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/schema/typemapping/UnifiedTypeMapper.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/schema/typemapping/UnifiedTypeMapping.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/schema/typemapping/provider/unified/Array.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/schema/typemapping/provider/unified/UnifiedMappingProvider.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraIOWrapperHelperTest.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/rowmapper/CassandraSourceRowMapperTest.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/schema/CassandraSchemaDiscoveryTest.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/testutils/BasicTestSchema.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/schema/typemapping/provider/unified/UnifiedMappingProviderTest.java
  v2/sourcedb-to-spanner/src/test/resources/CassandraUT/basicTest.cql
Labels: size/XL, ignore-for-release

#2170 Fix spanner terraform validator github action
  .github/workflows/spanner-terraform-validator.yml
Labels: size/XS, ignore-for-release

#2167 Added VIRTUAL column support to PG dataflow
  v1/src/main/java/com/google/cloud/teleport/spanner/ddl/Column.java
  v1/src/test/java/com/google/cloud/teleport/spanner/DdlToAvroSchemaConverterTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ddl/DdlTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScannerIT.java
Labels: size/M, improvement

#2169 Fix handling of empty arrays, json arrays and jsonb arrays.
  v2/datastream-to-sql/src/main/java/com/google/cloud/teleport/v2/utils/DatastreamToPostgresDML.java
  v2/datastream-to-sql/src/test/java/com/google/cloud/teleport/v2/utils/DatastreamToDMLTest.java
Labels: size/L, bug-fix

#2156 Terraform Sample - Spanner to Cassandra Reverse Replication
  .github/workflows/spanner-terraform-validator.yml
  v2/spanner-to-sourcedb/terraform/samples/spanner-to-cassandra/README.md
  v2/spanner-to-sourcedb/terraform/samples/spanner-to-cassandra/cassandra-config-template.conf
  v2/spanner-to-sourcedb/terraform/samples/spanner-to-cassandra/main.tf
  v2/spanner-to-sourcedb/terraform/samples/spanner-to-cassandra/outputs.tf
  v2/spanner-to-sourcedb/terraform/samples/spanner-to-cassandra/terraform.tf
  v2/spanner-to-sourcedb/terraform/samples/spanner-to-cassandra/terraform.tfvars
  v2/spanner-to-sourcedb/terraform/samples/spanner-to-cassandra/terraform_simple.tfvars
  v2/spanner-to-sourcedb/terraform/samples/spanner-to-cassandra/variables.tf
Labels: size/XXL, ignore-for-release

#2145 Add UUID support in import/export templates
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/spanner/matchers/SpannerAsserts.java
  v1/src/main/java/com/google/cloud/teleport/spanner/AvroRecordConverter.java
  v1/src/main/java/com/google/cloud/teleport/spanner/AvroSchemaToDdlConverter.java
  v1/src/main/java/com/google/cloud/teleport/spanner/BuildReadFromTableOperations.java
  v1/src/main/java/com/google/cloud/teleport/spanner/CSVRecordToMutation.java
  v1/src/main/java/com/google/cloud/teleport/spanner/DdlToAvroSchemaConverter.java
  v1/src/main/java/com/google/cloud/teleport/spanner/ExportTransform.java
  v1/src/main/java/com/google/cloud/teleport/spanner/SpannerRecordConverter.java
  v1/src/main/java/com/google/cloud/teleport/spanner/TextImportPipeline.java
  v1/src/main/java/com/google/cloud/teleport/spanner/TextImportTransform.java
  v1/src/main/java/com/google/cloud/teleport/spanner/common/SizedType.java
  v1/src/main/java/com/google/cloud/teleport/spanner/common/Type.java
  v1/src/main/java/com/google/cloud/teleport/spanner/ddl/Column.java
  v1/src/main/java/com/google/cloud/teleport/templates/TextToSpanner.java
  v1/src/main/java/com/google/cloud/teleport/templates/common/SpannerConverters.java
  v1/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerSchema.java
  v1/src/test/java/com/google/cloud/teleport/spanner/AvroRecordConverterTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/AvroSchemaToDdlConverterTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/BuildReadFromTableOperationsTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/CSVRecordToMutationTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/DdlToAvroSchemaConverterTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ExportPipelineIT.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ImportPipelineIT.java
  v1/src/test/java/com/google/cloud/teleport/spanner/SpannerRecordConverterTest.java
  v1/src/test/java/com/google/cloud/teleport/templates/SpannerToTextIT.java
  v1/src/test/java/com/google/cloud/teleport/templates/TextImportPipelineIT.java
  v1/src/test/java/org/apache/beam/sdk/io/gcp/spanner/SpannerSchemaTest.java
  v1/src/test/resources/ImportPipelineIT/googlesql/UuidTable-manifest.json
  v1/src/test/resources/ImportPipelineIT/googlesql/UuidTable.avro
  v1/src/test/resources/ImportPipelineIT/googlesql/spanner-export-uuid.json
  v1/src/test/resources/ImportPipelineIT/postgres/UuidTable-manifest.json
  v1/src/test/resources/ImportPipelineIT/postgres/UuidTable.avro
  v1/src/test/resources/ImportPipelineIT/postgres/spanner-export-uuid.json
Labels: size/XXL, improvement

#2162 Documentation - Cassandra Reverse Replication
  v2/spanner-to-sourcedb/README.md
  v2/spanner-to-sourcedb/README_Spanner_to_SourceDb.md
Labels: Documentation, size/M, ignore-for-release

#2157 [Infra] Do not generate shaded jar for common modules
  pom.xml
  v2/bigtable-common/pom.xml
  v2/cdc-parent/cdc-agg/pom.xml
  v2/cdc-parent/cdc-common/pom.xml
  v2/common/pom.xml
  v2/datastream-common/pom.xml
  v2/jdbc-common/pom.xml
  v2/kafka-common/pom.xml
  v2/pom.xml
  v2/spanner-custom-shard/pom.xml
  v2/spanner-migrations-sdk/pom.xml
Labels: size/S, ignore-for-release

#2173 Remove warning message
  v2/datastream-common/src/main/java/com/google/cloud/teleport/v2/datastream/transforms/FormatDatastreamRecordToJson.java
Labels: size/XS, cleanup, bug-fix

#2178 Adding support for float32 spanner writer
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/avro/AvroToValueMapper.java
  v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/avro/AvroToValueMapperTest.java
Labels: size/M, ignore-for-release

#2190 Fix Java PR report workflow
  .github/workflows/java-pr-report.yml
Labels: size/XS, ignore-for-release

#2182 Switch to use beam-sdks-java-io-aws2 for KinesisToPubsub
  v2/kinesis-to-pubsub/pom.xml
  v2/kinesis-to-pubsub/src/main/java/com/google/cloud/teleport/v2/options/KinesisToPubsubOptions.java
  v2/kinesis-to-pubsub/src/main/java/com/google/cloud/teleport/v2/templates/KinesisToPubsub.java
  v2/kinesis-to-pubsub/src/main/java/com/google/cloud/teleport/v2/transforms/KinesisDataTransforms.java
Labels: size/M, improvement

#2174 Add support for byte arrays and uuid arrays in datastream to sql template.
  v2/datastream-common/src/main/java/com/google/cloud/teleport/v2/datastream/transforms/FormatDatastreamRecordToJson.java
  v2/datastream-common/src/test/java/com/google/cloud/teleport/v2/datastream/transforms/FormatDatastreamRecordToJsonTest.java
  v2/datastream-common/src/test/resources/FormatDatastreamRecordToJsonTest/bytearray.avro
  v2/datastream-to-sql/src/main/java/com/google/cloud/teleport/v2/utils/DatastreamToDML.java
  v2/datastream-to-sql/src/main/java/com/google/cloud/teleport/v2/utils/DatastreamToPostgresDML.java
  v2/datastream-to-sql/src/test/java/com/google/cloud/teleport/v2/utils/DatastreamToDMLTest.java
Labels: size/M, improvement

#2192 Add test coverage for non-ascii Template parameter
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/TextIOToBigQueryIT.java
  v2/jdbc-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/JdbcToBigQueryIT.java
Labels: size/L, ignore-for-release

#2193 Fix github action concurrency to cancel old commit on new push
  .github/workflows/kafka-pr.yml
  .github/workflows/spanner-pr.yml
Labels: size/XS, ignore-for-release

#2160 IT for cross database transaction
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/spanner/SpannerResourceManager.java
  v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/DataStreamToSpanner.java
  v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/datastream/MySqlChangeEventSequence.java
  v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/datastream/OracleChangeEventSequence.java
  v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/datastream/PostgresChangeEventSequence.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerITBase.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/SeparateShadowTableDatabaseDDLIT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/SeparateShadowTableDatabaseEventsIT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/SeparateShadowTableDatabaseFileOverridesIT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/SeparateShadowTableDatabaseMixedIT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/SeparateShadowTableDatabasePKFocusedIT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/SeparateShadowTableDatabaseSessionIT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/SeparateShadowTableDatabaseShardedMigrationWithMigrationShardIdColumnIT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/SeparateShadowTableDatabaseShardedMigrationWithoutMigrationShardIdColumnIT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/SeparateShadowTableDatabaseSingleDFShardedMigrationIT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/SeparateShadowTableDatabaseStringOverridesIT.java
  v2/datastream-to-spanner/src/test/resources/SeparateShadowTableDatabaseIT/alltypes-test-3-inserts.avro
  v2/datastream-to-spanner/src/test/resources/SeparateShadowTableDatabaseIT/alltypes-test-pk-update.avro
  v2/datastream-to-spanner/src/test/resources/SeparateShadowTableDatabaseIT/alltypes-test-update-delete.avro
  v2/datastream-to-spanner/src/test/resources/SeparateShadowTableDatabaseIT/my_table-simpleTest-3-inserts.avro
  v2/datastream-to-spanner/src/test/resources/SeparateShadowTableDatabaseIT/my_table-simpleTest-pk-update.avro
  v2/datastream-to-spanner/src/test/resources/SeparateShadowTableDatabaseIT/my_table-simpleTest-update-delete.avro
  v2/datastream-to-spanner/src/test/resources/SeparateShadowTableDatabaseIT/mysql-schema.sql
  v2/datastream-to-spanner/src/test/resources/SeparateShadowTableDatabaseIT/spanner-schema.sql
Labels: size/XXL, improvement

#2202 Use a more recent version of cache action
  .github/actions/setup-java-env/action.yml
Labels: size/XS, ignore-for-release

#2203 Support inf and -inf values
  v2/datastream-common/src/main/java/com/google/cloud/teleport/v2/datastream/transforms/FormatDatastreamRecordToJson.java
Labels: bug, size/S, bug-fix

#2171 Fix issues for sequences and identity columns
  v1/src/main/java/com/google/cloud/teleport/spanner/DdlToAvroSchemaConverter.java
  v1/src/main/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScanner.java
  v1/src/test/java/com/google/cloud/teleport/spanner/DdlToAvroSchemaConverterTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ExportPipelineIT.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ImportPipelineIT.java
  v1/src/test/resources/ImportPipelineIT/googlesql/Identity-manifest.json
  v1/src/test/resources/ImportPipelineIT/googlesql/Identity.avro
  v1/src/test/resources/ImportPipelineIT/googlesql/Sequence1-manifest.json
  v1/src/test/resources/ImportPipelineIT/googlesql/Sequence1.avro
  v1/src/test/resources/ImportPipelineIT/googlesql/Sequence2-manifest.json
  v1/src/test/resources/ImportPipelineIT/googlesql/Sequence2.avro
  v1/src/test/resources/ImportPipelineIT/googlesql/spanner-export.json
  v1/src/test/resources/ImportPipelineIT/postgres/Identity-manifest.json
  v1/src/test/resources/ImportPipelineIT/postgres/Identity.avro
  v1/src/test/resources/ImportPipelineIT/postgres/Sequence1-manifest.json
  v1/src/test/resources/ImportPipelineIT/postgres/Sequence1.avro
  v1/src/test/resources/ImportPipelineIT/postgres/Sequence2-manifest.json
  v1/src/test/resources/ImportPipelineIT/postgres/Sequence2.avro
  v1/src/test/resources/ImportPipelineIT/postgres/spanner-export.json
Labels: size/L, bug-fix

#2207 fix: clean shadow tables
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/SeparateShadowTableDatabaseDDLIT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/SeparateShadowTableDatabaseEventsIT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/SeparateShadowTableDatabaseFileOverridesIT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/SeparateShadowTableDatabaseMixedIT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/SeparateShadowTableDatabaseSessionIT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/SeparateShadowTableDatabaseShardedMigrationWithMigrationShardIdColumnIT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/SeparateShadowTableDatabaseShardedMigrationWithoutMigrationShardIdColumnIT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/SeparateShadowTableDatabaseSingleDFShardedMigrationIT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/SeparateShadowTableDatabaseStringOverridesIT.java
Labels: size/S, bug-fix

#2175 Adding AvroToValueMapper (Spanner writer) for non-primitive types
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/mappings/CassandraMappingsProvider.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/rowmapper/CassandraRowValueArrayMapper.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/testutils/BasicTestSchema.java
  v2/sourcedb-to-spanner/src/test/resources/CassandraUT/basicTest.cql
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/avro/AvroToValueMapper.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/avro/GenericRecordTypeConvertor.java
  v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/avro/AvroToValueMapperTest.java
  v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/avro/GenericRecordTypeConvertorTest.java
Labels: size/XL, ignore-for-release

#2211 Set multi release manifest for classic template shadow jar
  v1/pom.xml
Labels: size/XS, ignore-for-release

#2186 Change default shadow table prefix of reverse replication template
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/SpannerToSourceDb.java
Labels: size/XS, improvement

#2187 Remove sdk_container_image example from terraform.tfvars
  v2/spanner-to-sourcedb/terraform/samples/spanner-to-cassandra/terraform.tfvars
  v2/spanner-to-sourcedb/terraform/samples/spanner-to-sharded-mysql/terraform.tfvars
Labels: size/XS, improvement

#2196 fix: Exception Handling for Retryable errors
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/transforms/SourceWriterFn.java
Labels: size/S, ignore-for-release

#2209 Adding support for Cassandra map
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/mappings/CassandraMappings.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/rowmapper/CassandraFieldMapper.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/rowmapper/CassandraRowValueMapMapper.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/schema/CassandraSchemaDiscovery.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/rowmapper/CassandraSourceRowMapperTest.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/schema/CassandraSchemaDiscoveryTest.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/testutils/BasicTestSchema.java
  v2/sourcedb-to-spanner/src/test/resources/CassandraUT/basicTest.cql
Labels: size/L, ignore-for-release

#2212 fix: disable flaky test
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/SpannerToSourceDbCustomTransformationIT.java
Labels: size/XS, bug-fix

#2206 Upgrade Beam version to 2.63.0
  pom.xml
  python/src/main/python/job-builder-server/requirements.txt
  python/src/main/python/streaming-llm/requirements.txt
  python/src/main/python/word-count-python/requirements.txt
  python/src/main/python/yaml-template/requirements.txt
  v1/pom.xml
  v1/src/main/java/com/google/cloud/teleport/templates/BigQueryToTFRecord.java
  v1/src/main/java/org/apache/beam/sdk/io/gcp/spanner/LocalSpannerIO.java
  v1/src/test/java/com/google/cloud/teleport/templates/BigQueryToTFRecordTest.java
  v2/bigtable-changestreams-to-hbase/src/test/java/com/google/cloud/bigtable/data/v2/models/ChangeStreamMutationBuilder.java
  v2/googlecloud-to-elasticsearch/src/main/resources/requirements.txt
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstopubsub/BigtableChangeStreamsToPubSub.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstopubsub/model/TestChangeStreamMutation.java
  v2/googlecloud-to-googlecloud/src/main/resources/requirements.txt
  v2/googlecloud-to-splunk/src/main/resources/requirements.txt
  v2/pom.xml
  v2/pubsub-binary-to-bigquery/src/main/resources/requirements.txt
  v2/pubsub-to-mongodb/src/main/resources/requirements.txt
Labels: size/XXL, improvement

#2194 SkipShade for Spanner common module
  v2/spanner-common/pom.xml
Labels: size/XS, ignore-for-release

#2199 Add load test for cross db txn
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/loadtesting/DataStreamToSpanner100GbLT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/loadtesting/DataStreamToSpannerLTBase.java
Labels: size/M, run-load-tests, improvement

#2205 Report Lineage for CsvToBigQuery template
  v1/src/main/java/com/google/cloud/teleport/templates/common/CsvConverters.java
Labels: size/M, improvement

#2128 Spanner Import/Export INTERLEAVE IN
  v1/src/main/java/com/google/cloud/teleport/spanner/AvroSchemaToDdlConverter.java
  v1/src/main/java/com/google/cloud/teleport/spanner/AvroUtil.java
  v1/src/main/java/com/google/cloud/teleport/spanner/DdlToAvroSchemaConverter.java
  v1/src/main/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScanner.java
  v1/src/main/java/com/google/cloud/teleport/spanner/ddl/Table.java
  v1/src/test/java/com/google/cloud/teleport/spanner/AvroSchemaToDdlConverterTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/DdlToAvroSchemaConverterTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ExportPipelineIT.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ddl/RandomDdlGenerator.java
Labels: size/L, improvement

#2216 Post 2.63.0 fixes
  v2/pom.xml
Labels: size/XS, ignore-for-release

#2198 bug-fix: Use jdbc connection properties for reverse migration
  v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/utils/ShardFileReaderTest.java
  v2/spanner-common/src/test/resources/shard.json
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/dbutils/connection/JdbcConnectionHelper.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/dbutils/connection/JdbcConnectionHelperTest.java
  v2/spanner-to-sourcedb/src/test/resources/shard.json
  v2/spanner-to-sourcedb/terraform/samples/spanner-to-sharded-mysql/README.md
  v2/spanner-to-sourcedb/terraform/samples/spanner-to-sharded-mysql/variables.tf
Labels: size/L, bug-fix

#2084 Support partitioned reads for DateTime column type in JDBC to BigQuery template
  v2/jdbc-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/options/JdbcToBigQueryOptions.java
  v2/jdbc-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/JdbcToBigQuery.java
  v2/jdbc-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/JdbcToBigQueryReadWithPartitionsTest.java
Labels: size/L, improvement

#2220 Disabling flaky test to unblock dataflow release
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerIT.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/SpannerToSourceDbInterleaveMultiShardIT.java
Labels: size/XS, ignore-for-release

#2219 Add logic to skip runnerV2 for the ITs
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/TemplateTestBase.java
Labels: size/XS, ignore-for-release
