Repository GoogleCloudPlatform/DataflowTemplates, pull requests merged in 2025-08, with the labels that each got.

#2616 Updates AvroConverters schema documentation
  v2/common/src/main/java/com/google/cloud/teleport/v2/transforms/AvroConverters.java
Labels: size/XS, improvement

#2588 Adding support for Enum, Hstore, and Ltree
  v2/datastream-to-sql/src/main/java/com/google/cloud/teleport/v2/utils/DatastreamToPostgresDML.java
  v2/datastream-to-sql/src/test/java/com/google/cloud/teleport/v2/utils/DatastreamToDMLTest.java
Labels: addition, size/L, improvement

#2561 Replace session file usage with ISchemaMapper and add string overrides support
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/schema/SchemaStringOverridesBasedMapper.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/schema/SessionBasedMapper.java
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/SpannerToSourceDb.java
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/dbutils/dml/CassandraDMLGenerator.java
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/dbutils/dml/MySQLDMLGenerator.java
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/dbutils/processor/InputRecordProcessor.java
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/models/DMLGeneratorRequest.java
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/transforms/AssignShardIdFn.java
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/transforms/SourceWriterFn.java
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/transforms/SourceWriterTransform.java
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/utils/ShardIdFetcherImpl.java
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/utils/ShardingLogicImplFetcher.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/SpannerToSourceDbFileOverridesSchemaMapperIT.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/SpannerToSourceDbStringOverridesSchemaMapperIT.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/dbutils/dml/CassandraDMLGeneratorTest.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/dbutils/dml/MySQLDMLGeneratorTest.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/transforms/AssignShardIdFnTest.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/transforms/SourceWriterFnTest.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/utils/ShardIdFetcherImplTest.java
  v2/spanner-to-sourcedb/src/test/resources/SpannerToSourceDbOverridesIT/file-overrides.json
  v2/spanner-to-sourcedb/src/test/resources/SpannerToSourceDbOverridesIT/mysql-schema.sql
  v2/spanner-to-sourcedb/src/test/resources/SpannerToSourceDbOverridesIT/spanner-schema.sql
Labels: size/XXL, improvement

#2624 Clean up metadata file and images after integration test run
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/TemplateTestBase.java
Labels: size/M, cleanup, integration testing, ignore-for-release

#2636 Revert "Clean up metadata file and images after integration test run"
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/TemplateTestBase.java
Labels: size/M, ignore-for-release

#2638 Reapply #2624 retain guava Cache
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/TemplateTestBase.java
Labels: size/M, ignore-for-release

#2644 Upgrade Templates to Beam 2.67.0
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/dataflow/AbstractPipelineLauncher.java
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/dataflow/DirectRunnerClient.java
  pom.xml
  python/default_base_python_requirements.txt
  python/default_base_yaml_requirements.txt
  python/src/main/python/job-builder-server/requirements.txt
  python/src/main/python/streaming-llm/base_requirements.txt
  python/src/main/python/word-count-python/requirements.txt
  python/src/main/python/yaml-template/requirements.txt
  v2/googlecloud-to-elasticsearch/src/main/resources/requirements.txt
  v2/googlecloud-to-googlecloud/src/main/resources/requirements.txt
  v2/googlecloud-to-splunk/src/main/resources/requirements.txt
  v2/pubsub-binary-to-bigquery/src/main/resources/requirements.txt
  v2/pubsub-to-mongodb/src/main/resources/requirements.txt
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/schema/SchemaDiscoveryImpl.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/schema/SchemaDiscoveryImplTest.java
Labels: size/XXL, improvement

#2647 Bump hivemq-mqtt-client to 1.3.7
  v2/mqtt-to-pubsub/pom.xml
Labels: size/XS, ignore-for-release

#2601 Exclude forward transaction from change streams
  v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/SpannerTransactionWriterDoFn.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/SpannerTransactionWriterDoFnTest.java
  v2/spanner-to-sourcedb/README.md
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/SpannerToSourceDbITBase.java
  v2/spanner-to-sourcedb/src/test/resources/SpannerToCassandraSourceIT/spanner-schema.sql
  v2/spanner-to-sourcedb/src/test/resources/SpannerToCassandraSourceIT/spanner-transformation-schema.sql
  v2/spanner-to-sourcedb/src/test/resources/SpannerToCassandraSourceLT/spanner-schema.sql
  v2/spanner-to-sourcedb/src/test/resources/SpannerToMySqlSourceLT/spanner-schema.sql
  v2/spanner-to-sourcedb/src/test/resources/SpannerToSourceDbCustomShardIT/spanner-schema.sql
  v2/spanner-to-sourcedb/src/test/resources/SpannerToSourceDbCustomTransformationIT/spanner-schema.sql
  v2/spanner-to-sourcedb/src/test/resources/SpannerToSourceDbDatatypeIT/spanner-schema.sql
  v2/spanner-to-sourcedb/src/test/resources/SpannerToSourceDbIT/spanner-schema.sql
  v2/spanner-to-sourcedb/src/test/resources/SpannerToSourceDbInterleaveMultiShardIT/spanner-schema.sql
  v2/spanner-to-sourcedb/src/test/resources/SpannerToSourceDbTimezoneIT/spanner-schema.sql
  v2/spanner-to-sourcedb/src/test/resources/SpannerToSourceDbWideRowIT/spanner-16mb-schema.sql
Labels: size/M, ignore-for-release

#2654 build: update astra-io dependency to 4.18.1
  v2/astradb-to-bigquery/pom.xml
  v2/astradb-to-bigquery/src/main/java/com/google/cloud/teleport/v2/astradb/transforms/AstraDbToBigQueryMappingFn.java
Labels: size/XS, improvement

#2661 build: add org.json dependency with secure version
  pom.xml
Labels: size/XS, improvement

#2670 update all python requirements
  python/src/main/python/job-builder-server/requirements.txt
  python/src/main/python/streaming-llm/requirements.txt
  python/src/main/python/word-count-python/requirements.txt
  python/src/main/python/yaml-template/requirements.txt
  v2/googlecloud-to-elasticsearch/src/main/resources/requirements.txt
  v2/googlecloud-to-googlecloud/src/main/resources/requirements.txt
  v2/googlecloud-to-splunk/src/main/resources/requirements.txt
  v2/pubsub-binary-to-bigquery/src/main/resources/requirements.txt
  v2/pubsub-to-mongodb/src/main/resources/requirements.txt
Labels: size/XXL, ignore-for-release

#2668 Update kafka to bq README etc
  plugins/core-plugin/src/main/resources/README-template.md
  yaml/README_Kafka_to_BigQuery_Yaml.md
  yaml/pom.xml
Labels: size/M, bug-fix

#2677 docs(maintainers-guide): add info about updating python dependency
  contributor-docs/maintainers-guide.md
Labels: size/XS, ignore-for-release

#2671 fix: remove setuptools wheel
  plugins/core-plugin/src/main/resources/Dockerfile-template-xlang
Labels: size/XS, ignore-for-release

#2620 feat: enforce cypher 5 for generated queries
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/database/CypherGenerator.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/database/Neo4jCapabilities.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/database/Neo4jConnection.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/transforms/Neo4jRowWriterTransform.java
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/database/BaseCypherGeneratorTest.java
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/database/CypherGeneratorTest.java
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/database/Neo4jCapabilitiesTest.java
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/database/Neo4jConnectionTest.java
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/templates/InlineDataToNeo4jIT.java
Labels: size/L, improvement

#2686 feat(import): add early index create threshold parameter
  v1/src/main/java/com/google/cloud/teleport/spanner/ImportPipeline.java
  v1/src/main/java/com/google/cloud/teleport/spanner/ImportTransform.java
  v1/src/test/java/com/google/cloud/teleport/spanner/CopyDbTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ExportRelatedTablesCheckTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ExportTimestampTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ImportFromAvroTest.java
Labels: size/M, improvement

#2704 fix readme outputs for python and yaml modules
  contributor-docs/code-contributions.md
  plugins/core-plugin/src/main/resources/README-template.md
  python/README_Yaml_Template.md
  yaml/README_Kafka_to_BigQuery_Yaml.md
Labels: size/S, Documentation, improvement, bug-fix

#2696 DataStreamToSpanner - Creating new Spanner instances in ITs
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/spanner/SpannerResourceManager.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerITBase.java
Labels: size/S, ignore-for-release

#2706 removed templateName flag
  contributor-docs/code-contributions.md
Labels: size/XS, ignore-for-release

#2707 fix(mongodb): handle special floating point values in Gson serialization
  v2/mongodb-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/mongodb/templates/MongoDbUtils.java
  v2/mongodb-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/mongodb/templates/MongoDbUtilsTest.java
Labels: size/M, bug-fix

#2705 SourceDb-to-Spanner and Spanner-to-SourceDb : Creating new Spanner instances in ITs
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/SourceDbToSpannerITBase.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/SpannerToSourceDbITBase.java
Labels: size/S, ignore-for-release
