Repository GoogleCloudPlatform/DataflowTemplates, pull requests merged in 2025-04, with the labels that each got.

#2290 Re-enable Datastream-to-sql tests and consolidate expensive datastream integration tests
  v2/datastream-to-bigquery/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToBigQueryIT.java
  v2/datastream-to-sql/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSQLIT.java
Labels: size/S, ignore-for-release

#2293 Move jdbc templates out of googlecloud-to-googlecloud to renamed jdbc-and-googlecloud
  v2/googlecloud-to-googlecloud/pom.xml
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/io/DynamicJdbcIO.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/io/DynamicJdbcIOTest.java
  v2/jdbc-and-googlecloud/README_Jdbc_to_BigQuery_Flex.md
  v2/jdbc-and-googlecloud/README_Jdbc_to_PubSub.md
  v2/jdbc-and-googlecloud/README_Jdbc_to_PubSub_Auto.md
  v2/jdbc-and-googlecloud/README_Pubsub_to_Jdbc.md
  v2/jdbc-and-googlecloud/pom.xml
  v2/jdbc-and-googlecloud/src/main/java/com/google/cloud/teleport/v2/io/DynamicJdbcIO.java
  v2/jdbc-and-googlecloud/src/main/java/com/google/cloud/teleport/v2/io/package-info.java
  v2/jdbc-and-googlecloud/src/main/java/com/google/cloud/teleport/v2/options/JdbcToBigQueryOptions.java
  v2/jdbc-and-googlecloud/src/main/java/com/google/cloud/teleport/v2/options/JdbcToPubsubOptions.java
  v2/jdbc-and-googlecloud/src/main/java/com/google/cloud/teleport/v2/options/PubsubToJdbcOptions.java
  v2/jdbc-and-googlecloud/src/main/java/com/google/cloud/teleport/v2/options/package-info.java
  v2/jdbc-and-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/JdbcToBigQuery.java
  v2/jdbc-and-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/JdbcToPubSubAuto.java
  v2/jdbc-and-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/JdbcToPubsub.java
  v2/jdbc-and-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/PubsubToJdbc.java
  v2/jdbc-and-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/package-info.java
  v2/jdbc-and-googlecloud/src/main/resources/jdbc-to-bigquery-command-spec.json
  v2/jdbc-and-googlecloud/src/main/resources/jdbc-to-pubsub-command-spec.json
  v2/jdbc-and-googlecloud/src/main/resources/pubsub-to-jdbc-command-spec.json
  v2/jdbc-and-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/JdbcToBigQueryIT.java
  v2/jdbc-and-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/JdbcToBigQueryLT.java
  v2/jdbc-and-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/JdbcToBigQueryReadWithPartitionsTest.java
  v2/jdbc-and-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/JdbcToBigQueryTest.java
  v2/jdbc-and-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/JdbcToPubSubAutoIT.java
  v2/jdbc-and-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/JdbcToPubsubIT.java
  v2/jdbc-and-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/JdbcToPubsubTest.java
  v2/jdbc-and-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/PubsubToJdbcIT.java
  v2/jdbc-and-googlecloud/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
  v2/jdbc-and-googlecloud/terraform/Jdbc_to_BigQuery_Flex/dataflow_job.tf
  v2/jdbc-and-googlecloud/terraform/Jdbc_to_PubSub/dataflow_job.tf
  v2/jdbc-and-googlecloud/terraform/Jdbc_to_PubSub_Auto/dataflow_job.tf
  v2/jdbc-and-googlecloud/terraform/Pubsub_to_Jdbc/dataflow_job.tf
  v2/mysql-to-googlecloud/README_Jdbc_to_PubSub.md
  v2/mysql-to-googlecloud/README_Jdbc_to_PubSub_Auto.md
  v2/mysql-to-googlecloud/pom.xml
  v2/oracle-to-googlecloud/README_Jdbc_to_PubSub.md
  v2/oracle-to-googlecloud/README_Jdbc_to_PubSub_Auto.md
  v2/oracle-to-googlecloud/pom.xml
  v2/pom.xml
  v2/postgresql-to-googlecloud/README_Jdbc_to_PubSub.md
  v2/postgresql-to-googlecloud/README_Jdbc_to_PubSub_Auto.md
  v2/postgresql-to-googlecloud/pom.xml
  v2/sqlserver-to-googlecloud/README_Jdbc_to_PubSub.md
  v2/sqlserver-to-googlecloud/README_Jdbc_to_PubSub_Auto.md
  v2/sqlserver-to-googlecloud/pom.xml
Labels: size/XL, improvement

#2298 Skip staging part of AR path for job-builder
  plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesStageMojo.java
  plugins/templates-maven-plugin/src/test/java/com/google/cloud/teleport/plugin/maven/TemplatesStageMojoTest.java
Labels: size/M, ignore-for-release

#2268 Bug fixes of handling null values and added missing IT
  v2/spanner-custom-shard/src/main/java/com/custom/CustomTransformationWithCassandraForIT.java
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/dbutils/dml/CassandraDMLGenerator.java
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/dbutils/dml/CassandraTypeHandler.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/SpannerToCassandraSourceDBCustomTransformationIT.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/SpannerToCassandraSourceDbIT.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/dbutils/dml/CassandraTypeHandlerTest.java
  v2/spanner-to-sourcedb/src/test/resources/SpannerToCassandraSourceIT/cassandra-schema.sql
  v2/spanner-to-sourcedb/src/test/resources/SpannerToCassandraSourceIT/cassandra-transformation-schema.sql
  v2/spanner-to-sourcedb/src/test/resources/SpannerToCassandraSourceIT/spanner-schema.sql
  v2/spanner-to-sourcedb/src/test/resources/SpannerToCassandraSourceIT/spanner-transformation-schema.sql
Labels: size/XL, ignore-for-release

#2277 Spanner Internal failure injector implementation
  v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/DataStreamToSpanner.java
  v2/failure-injected-spanner-service/pom.xml
  v2/failure-injected-spanner-service/src/main/java/com/google/cloud/teleport/v2/spanner/service/SpannerService.java
  v2/failure-injected-spanner-service/src/main/java/com/google/cloud/teleport/v2/spanner/service/package-info.java
  v2/failure-injected-spanner-service/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerServiceFactoryImpl.java
  v2/failure-injected-spanner-service/src/main/java/org/apache/beam/sdk/io/gcp/spanner/package-info.java
  v2/failure-injected-spanner-service/src/test/java/com/google/cloud/teleport/v2/spanner/service/SpannerServiceTest.java
  v2/failure-injected-spanner-service/src/test/java/org/apache/beam/sdk/io/gcp/spanner/SpannerServiceFactoryImplTest.java
  v2/failure-injection-policies/pom.xml
  v2/failure-injection-policies/src/main/java/com/google/cloud/teleport/v2/failureinjection/AlwaysFailPolicy.java
  v2/failure-injection-policies/src/main/java/com/google/cloud/teleport/v2/failureinjection/ErrorInjectionPolicy.java
  v2/failure-injection-policies/src/main/java/com/google/cloud/teleport/v2/failureinjection/ErrorInjectionPolicyFactory.java
  v2/failure-injection-policies/src/main/java/com/google/cloud/teleport/v2/failureinjection/package-info.java
  v2/failure-injection-policies/src/test/java/com/google/cloud/teleport/v2/failureinjection/AlwaysFailPolicyTest.java
  v2/pom.xml
  v2/real-spanner-service/pom.xml
  v2/real-spanner-service/src/main/java/com/google/cloud/teleport/v2/spanner/service/SpannerService.java
  v2/real-spanner-service/src/main/java/com/google/cloud/teleport/v2/spanner/service/package-info.java
  v2/real-spanner-service/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerServiceFactoryImpl.java
  v2/real-spanner-service/src/main/java/org/apache/beam/sdk/io/gcp/spanner/package-info.java
  v2/real-spanner-service/src/test/java/com/google/cloud/teleport/v2/spanner/service/SpannerServiceTest.java
  v2/real-spanner-service/src/test/java/org/apache/beam/sdk/io/gcp/spanner/SpannerServiceFactoryImplTest.java
Labels: size/XL, improvement

#2302 Revert "Skip the tests DataStreamToBigQueryIT and DataStreamTOSQLIT until they get fixed"
  v2/datastream-to-bigquery/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToBigQueryIT.java
  v2/datastream-to-sql/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSQLIT.java
Labels: size/XS

#2314 Small update to Cassandra Readme: Stressed on setting datacenter right
  v2/sourcedb-to-spanner/README_Sourcedb_to_Spanner.md
Labels: size/S

#2306 Fix: Sharded DB behavior should be the same regardless of shard count
  v2/spanner-to-sourcedb/README_Spanner_to_SourceDb.md
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/SpannerToSourceDb.java
Labels: size/S

#2272 Bulk Migration Widerow Integration Tests
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/MySQLSourceDBToSpannerWideRowInterleaveDepthIT.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/MySQLSourceDBToSpannerWideRowMaxSizeStringIT.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/MySQLSourceDbToSpannerWideRowMaxColumnsTableKeyIT.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/MySQLSourceDbToSpannerWideRowMaxSizeTableKeyIT.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/MySQLToSpannerWiderowForMaxColumnsPerTableIT.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/SourceDbToSpannerITBase.java
  v2/sourcedb-to-spanner/src/test/resources/WideRow/InterleaveDepthIT/mysql-schema.sql
  v2/sourcedb-to-spanner/src/test/resources/WideRow/InterleaveDepthIT/spanner-schema.sql
  v2/sourcedb-to-spanner/src/test/resources/WideRow/MaxColumnsTableKeyIT/mysql-schema.sql
  v2/sourcedb-to-spanner/src/test/resources/WideRow/MaxColumnsTableKeyIT/spanner-schema.sql
  v2/sourcedb-to-spanner/src/test/resources/WideRow/MaxSizeTableKey/mysql-schema.sql
  v2/sourcedb-to-spanner/src/test/resources/WideRow/MaxSizeTableKey/spanner-schema.sql
  v2/sourcedb-to-spanner/src/test/resources/WideRow/RowMaxSizeString/mysql-schema.sql
  v2/sourcedb-to-spanner/src/test/resources/WideRow/RowMaxSizeString/spanner-schema.sql
Labels: size/XL

#2312 Bulk Migration Low Priority Integration Test
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/MySQLSourceDBToSpannerWideRowMaxColumnAndTableSizeIT.java
  v2/sourcedb-to-spanner/src/test/resources/WideRow/RowMaxSizeLimit/mysql-schema.sql
  v2/sourcedb-to-spanner/src/test/resources/WideRow/RowMaxSizeLimit/spanner-schema.sql
Labels: size/L, ignore-for-release

#2297 Upgrade to Beam 2.64.0
  it/cassandra/pom.xml
  it/google-cloud-platform/pom.xml
  pom.xml
  python/default_base_python_requirements.txt
  python/default_base_yaml_requirements.txt
  python/src/main/python/job-builder-server/requirements.txt
  python/src/main/python/streaming-llm/base_requirements.txt
  python/src/main/python/streaming-llm/requirements.txt
  python/src/main/python/word-count-python/requirements.txt
  python/src/main/python/yaml-template/requirements.txt
  structured-logging/pom.xml
  v1/pom.xml
  v1/src/test/java/com/google/cloud/teleport/spanner/spannerio/SpannerIOReadTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/spannerio/SpannerIOWriteTest.java
  v1/src/test/java/com/google/cloud/teleport/templates/TextImportPipelineIT.java
  v2/bigtable-changestreams-to-hbase/pom.xml
  v2/bigtable-common/pom.xml
  v2/cdc-parent/cdc-embedded-connector/src/main/java/com/google/cloud/dataflow/cdc/connector/App.java
  v2/common/pom.xml
  v2/google-ads-to-googlecloud/pom.xml
  v2/googlecloud-to-elasticsearch/src/main/resources/requirements.txt
  v2/googlecloud-to-googlecloud/pom.xml
  v2/googlecloud-to-googlecloud/src/main/resources/requirements.txt
  v2/googlecloud-to-splunk/src/main/resources/requirements.txt
  v2/pubsub-binary-to-bigquery/src/main/resources/requirements.txt
  v2/pubsub-to-mongodb/src/main/resources/requirements.txt
  v2/sourcedb-to-spanner/pom.xml
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/SourceDbToSpanner.java
  v2/spanner-common/pom.xml
  v2/spanner-to-sourcedb/pom.xml
Labels: size/XXL, improvement

#2316 fix: Use ignored column families parameter in bigtable to pubsub conn…
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstopubsub/BigtableChangeStreamsToPubSub.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstopubsub/BigtableChangeStreamsToPubSubIT.java
Labels: size/L, bug-fix

#2294 Wide Row Bulk Migration Load Test
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/loadtesting/MySQLSourceDbtoSpannerWideRow10MBPerCellLT.java
  v2/sourcedb-to-spanner/src/test/resources/SourceDbToSpannerLT/WideRow/spanner-schema-10mib-per-cell.sql
Labels: size/M, run-load-tests, ignore-for-release

#2309 Forward migration low priority integration test
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/spanner/SpannerTemplateITBase.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerWideRowForMaxTableNameIT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerWideRowForMaxTableNameWithMaxColumnNameIT.java
Labels: size/XL, integration testing, improvement

#2322 Regenerate requitements to fix yaml template
  it/pom.xml
  plugins/core-plugin/src/main/resources/Dockerfile-template-yaml
  pom.xml
  python/default_base_python_requirements.txt
  python/default_base_yaml_requirements.txt
  python/src/main/python/job-builder-server/requirements.txt
  python/src/main/python/streaming-llm/base_requirements.txt
  python/src/main/python/streaming-llm/requirements.txt
  python/src/main/python/word-count-python/requirements.txt
  python/src/main/python/yaml-template/main.py
  python/src/main/python/yaml-template/requirements.txt
  v2/googlecloud-to-elasticsearch/src/main/resources/requirements.txt
  v2/googlecloud-to-googlecloud/src/main/resources/requirements.txt
  v2/googlecloud-to-splunk/src/main/resources/requirements.txt
  v2/pubsub-binary-to-bigquery/src/main/resources/requirements.txt
  v2/pubsub-to-mongodb/src/main/resources/requirements.txt
Labels: size/XXL, ignore-for-release

#2273 Add rowRestriction when fetching BQ schema
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/bigquery/BigQueryResourceManager.java
  it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/bigquery/BigQueryResourceManagerTest.java
  v2/bigquery-to-parquet/src/main/java/com/google/cloud/teleport/v2/templates/BigQueryToParquet.java
  v2/bigquery-to-parquet/src/test/java/com/google/cloud/teleport/v2/templates/BigQueryToParquetIT.java
Labels: size/L, bug-fix

#2326 Disable Spanner staging test
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/spanner/SpannerTemplateITBase.java
  v1/src/test/java/com/google/cloud/teleport/templates/TextImportPipelineIT.java
Labels: size/S, ignore-for-release

#2252 WideRowHandling: spanner to source db IT
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/SpannerToCassandraSourceDbMaxColumnsIT.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/SpannerToCassandraSourceDbMaxColumnsSizeIT.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/SpannerToCassandraSourceDbWideRow10MbIT.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/SpannerToMySqlSourceDbWideRow10MbIT.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/SpannerToMySqlSourceDbWideRowMaxColumnsIT.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/SpannerToSourceDbITBase.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/SpannerToSourceDbWideRowBasicIT.java
  v2/spanner-to-sourcedb/src/test/resources/SpannerToSourceDbWideRowIT/cassandra-10mb-schema.sql
  v2/spanner-to-sourcedb/src/test/resources/SpannerToSourceDbWideRowIT/cassandra-config-template.conf
  v2/spanner-to-sourcedb/src/test/resources/SpannerToSourceDbWideRowIT/col-mb-session.json
  v2/spanner-to-sourcedb/src/test/resources/SpannerToSourceDbWideRowIT/max-col-session.json
  v2/spanner-to-sourcedb/src/test/resources/SpannerToSourceDbWideRowIT/mysql-10mb-schema.sql
  v2/spanner-to-sourcedb/src/test/resources/SpannerToSourceDbWideRowIT/spanner-16mb-schema.sql
Labels: size/XXL, integration testing, ignore-for-release

#2327 Fixing TextImportPipelineIT integration test
  v1/src/test/java/com/google/cloud/teleport/templates/TextImportPipelineIT.java
  v1/src/test/resources/ExportPipelineIT/spanner-pg-ddl.sql
Labels: size/M, bug-fix

#2339 Update docs for inputFilePattern
  v2/datastream-to-spanner/README.md
  v2/datastream-to-spanner/README_Cloud_Datastream_to_Spanner.md
  v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/DataStreamToSpanner.java
  v2/sourcedb-to-spanner/README_Cloud_Datastream_to_Spanner.md
Labels: Documentation, size/L, bug-fix

#2337 added beam-sdks-java-extensions-sql-expansion-service
  plugins/core-plugin/src/main/resources/Dockerfile-template-yaml
Labels: size/XS, improvement

#2338 Updates to Bulk Readme - disable_v2_engine and Cassandra Partitions post scale test results
  v2/sourcedb-to-spanner/README_Sourcedb_to_Spanner.md
Labels: size/S, ignore-for-release

#2310 Reverse replication low priority integration tests
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/SpannerToCassandraSourceDbIT.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/SpannerToSourceDbIT.java
  v2/spanner-to-sourcedb/src/test/resources/SpannerToCassandraSourceIT/cassandra-schema.sql
  v2/spanner-to-sourcedb/src/test/resources/SpannerToCassandraSourceIT/spanner-schema.sql
  v2/spanner-to-sourcedb/src/test/resources/SpannerToSourceDbIT/mysql-schema.sql
  v2/spanner-to-sourcedb/src/test/resources/SpannerToSourceDbIT/session.json
  v2/spanner-to-sourcedb/src/test/resources/SpannerToSourceDbIT/spanner-schema.sql
Labels: size/L, ignore-for-release
