Repository GoogleCloudPlatform/DataflowTemplates, pull requests merged in 2025-01, with the labels that each got.

#2098 Use GITHUB_TOKEN instead of special release token
  .github/workflows/release.yml
Labels: size/XS, ignore-for-release

#2099 add fetch-depth to uw workflow
  .github/workflows/uw-tests.yml
Labels: size/XS, ignore-for-release

#2102 add candidateName and branchCommit to uw-tests workflow
  .github/workflows/uw-tests.yml
Labels: size/S, ignore-for-release

#2103 fix typo on uw-tests workflow
  .github/workflows/uw-tests.yml
Labels: size/XS, ignore-for-release

#2105 only build DEFAULT modules for uw-tests
  .github/workflows/uw-tests.yml
Labels: size/XS, ignore-for-release

#2104 Incorporating TODO for Ingesting GCS Config
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraConnector.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraDataSource.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraConnectorTest.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraDataSourceTest.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/rowmapper/CassandraSourceRowMapperTest.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/schema/CassandraSchemaDiscoveryTest.java
  v2/sourcedb-to-spanner/src/test/resources/CassandraUT/test-cassandra-config.conf
Labels: size/L, ignore-for-release, bug-fix

#2108 disable runner_v2 tests on classic streaming templates
  .github/workflows/uw-tests.yml
  cicd/cmd/run-it-tests/main.go
  cicd/internal/workflows/maven-workflows.go
  metadata/pom.xml
  metadata/src/main/java/com/google/cloud/teleport/metadata/SkipRunnerV2Test.java
  pom.xml
  v1/src/test/java/com/google/cloud/teleport/templates/DLPTextToBigQueryStreamingIT.java
  v1/src/test/java/com/google/cloud/teleport/templates/PubSubToAvroIT.java
  v1/src/test/java/com/google/cloud/teleport/templates/PubSubToBigQueryIT.java
  v1/src/test/java/com/google/cloud/teleport/templates/PubSubToDatadogIT.java
  v1/src/test/java/com/google/cloud/teleport/templates/PubSubToPubSubIT.java
  v1/src/test/java/com/google/cloud/teleport/templates/PubSubToSplunkIT.java
  v1/src/test/java/com/google/cloud/teleport/templates/PubSubTopicToBigQueryIT.java
  v1/src/test/java/com/google/cloud/teleport/templates/PubsubToTextIT.java
  v1/src/test/java/com/google/cloud/teleport/templates/TextToPubsubStreamIT.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/DLPTextToBigQueryStreamingIT.java
Labels: size/L, ignore-for-release

#2109 fix typo on RunIntegrationTests
  cicd/internal/workflows/maven-workflows.go
Labels: size/XS, ignore-for-release

#2110 Use latest release for uw-tests
  .github/workflows/uw-tests.yml
Labels: ignore-for-release

#2095 Correcting bulk migration load tests
  .github/workflows/spanner-load-tests.yml
  .github/workflows/spanner-pr.yml
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/loadtesting/MySQLSourceDbToSpannerLT.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/loadtesting/PostgreSQLSourceDbToSpannerLT.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/loadtesting/SourceDbToSpannerLTBase.java
Labels: size/M, ignore-for-release

#2113 Skip flaky test in reverse till its fixed
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/SpannerToSourceDbCustomTransformationIT.java
Labels: size/XS, ignore-for-release

#2106 Fix precision error for datetime
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/avro/GenericRecordTypeConvertor.java
  v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/avro/GenericRecordTypeConvertorTest.java
Labels: size/XS, bug-fix

#2116 Fix renamed template mongodb-to-bigquery-cdc
  v2/mongodb-to-googlecloud/src/main/resources/mongodb-to-bigquery-cdc-command-spec.json
Labels: size/XS, bug-fix

#2081 Metadata config and pipeline options
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/constants/Constants.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/metadata/CassandraSourceMetadata.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/schema/Schema.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/shard/CassandraShard.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/spanner/SpannerSchema.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/utils/CassandraConfigFileReader.java
  v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/metadata/CassandraSourceMetadataTest.java
  v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/schema/SchemaTest.java
  v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/shard/CassandraShardTest.java
  v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/spanner/SpannerSchemaTest.java
  v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/utils/CassandraConfigFileReaderTest.java
  v2/spanner-common/src/test/resources/test-cassandra-config.conf
  v2/spanner-to-sourcedb/pom.xml
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/SpannerToSourceDb.java
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/constants/Constants.java
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/dbutils/connection/CassandraConnectionHelper.java
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/dbutils/processor/SourceProcessorFactory.java
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/transforms/SourceWriterFn.java
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/utils/CassandraSourceSchemaReader.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/dbutils/connection/CassandraConnectionHelperTest.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/dbutils/dao/source/CassandraDaoTest.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/dbutils/processor/SourceProcessorFactoryTest.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/utils/CassandraSourceSchemaReaderTest.java
Labels: addition, size/XXL, ignore-for-release

#2071 fix: eager source row fetching logic
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/templates/GoogleCloudToNeo4j.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/utils/ModelUtils.java
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/templates/SyntheticFieldsIT.java
  v2/googlecloud-to-neo4j/src/test/resources/testing-specs/synthetic-fields/spec.yml
Labels: size/L, bug-fix

#2013 Favor built-in transform over custom one
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/transforms/CreateKvTransform.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/transforms/Neo4jRowWriterTransform.java
Labels: size/L, improvement

#2011 Simplify dependency manager: remove unused code
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/templates/GoogleCloudToNeo4j.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/utils/BeamBlock.java
Labels: size/M, improvement

#2068 feat: drop node target's key constraint requirement
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/validation/NodeKeyValidator.java
  v2/googlecloud-to-neo4j/src/main/resources/META-INF/services/org.neo4j.importer.v1.validation.SpecificationValidator
Labels: size/M, improvement

#2118 Fixing TypeMismatch in Cassandra Driver Config Loader
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/schema/CassandraSchemaDiscoveryTest.java
  v2/sourcedb-to-spanner/src/test/resources/CassandraUT/test-cassandra-config-all-params.conf
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/utils/CassandraDriverConfigLoader.java
  v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/utils/CassandraDriverConfigLoaderTest.java
Labels: size/XXL, bug-fix

#2121 Reverting integration test report in Spanner-PR gitaction
  .github/workflows/spanner-pr.yml
Labels: size/S, ignore-for-release

#2096 Parameterizing commit id and spanner host in spanner-staging-tests workflow
  .github/workflows/spanner-staging-tests.yml
  cicd/cmd/run-spanner-staging-it-tests/main.go
  cicd/internal/workflows/maven-workflows.go
Labels: size/L, ignore-for-release

#2131 Revert "feat: drop node target's key constraint requirement (#2068)"
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/model/validation/NodeKeyValidator.java
  v2/googlecloud-to-neo4j/src/main/resources/META-INF/services/org.neo4j.importer.v1.validation.SpecificationValidator
Labels: size/M, ignore-for-release

#2130 Enable SSL mode in embedded Cassandra used by unit tests.
  v2/sourcedb-to-spanner/pom.xml
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/testutils/EmbeddedCassandra.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/testutils/SharedEmbeddedCassandra.java
  v2/sourcedb-to-spanner/src/test/resources/CassandraUT/basicConfig.yaml
Labels: size/L, ignore-for-release

#2129 Basic Changes to use Upstream Cassandra io for Bulk Cassandra Migration
  v2/sourcedb-to-spanner/pom.xml
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraDefaults.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraIOWrapperFactory.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraIOWrapperHelper.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraIoWrapper.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraTableReaderFactory.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraTableReaderFactoryCassandraIoImpl.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/rowmapper/CassandraSourceRowMapperFactoryFn.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraIOWrapperFactoryTest.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraIOWrapperHelperTest.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraIoWrapperTest.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraTableReaderFactoryCassandraIoImplTest.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/testutils/BasicTestSchema.java
  v2/sourcedb-to-spanner/src/test/resources/CassandraUT/test-cassandra-config.conf
Labels: size/XL, ignore-for-release

#2050 Switch to Java 17 for all Dataflow Templates
  .github/actions/setup-env/action.yml
  .github/actions/setup-java-env/action.yml
  contributor-docs/code-contributions.md
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/artifacts/matchers/ArtifactsSubject.java
  metadata/pom.xml
  plaintext-logging/pom.xml
  plugins/core-plugin/pom.xml
  plugins/core-plugin/src/main/java/com/google/cloud/teleport/plugin/DockerfileGenerator.java
  plugins/templates-maven-plugin/pom.xml
  plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesReleaseFinishMojo.java
  pom.xml
  python/pom.xml
  v1/pom.xml
  v1/src/test/java/com/google/cloud/teleport/templates/BulkCompressorIT.java
  v2/astradb-to-bigquery/docs/AstraDbToBigQuery/README.md
  v2/azure-eventhub-to-pubsub/README.md
  v2/bigquery-to-bigtable/README.md
  v2/bigquery-to-parquet/README.md
  v2/datastream-to-bigquery/README.md
  v2/datastream-to-mongodb/readme.md
  v2/datastream-to-postgres/README.md
  v2/datastream-to-spanner/README.md
  v2/datastream-to-sql/README.md
  v2/file-format-conversion/README.md
  v2/gcs-to-sourcedb/README.md
  v2/googlecloud-to-elasticsearch/docs/BigQueryToElasticsearch/README.md
  v2/googlecloud-to-elasticsearch/docs/GCSToElasticsearch/README.md
  v2/googlecloud-to-elasticsearch/docs/PubSubToElasticsearch/README.md
  v2/googlecloud-to-googlecloud/docs/SpannerChangeStreamsToGcs/README.md
  v2/googlecloud-to-googlecloud/docs/SpannerToBigQuery/README.md
  v2/googlecloud-to-mongodb/docs/BigQueryToMongoDb/README.md
  v2/googlecloud-to-neo4j/docs/README.md
  v2/googlecloud-to-splunk/docs/GCSToSplunk/README.md
  v2/jms-to-pubsub/README.md
  v2/kafka-to-bigquery/README.md
  v2/kafka-to-gcs/README.md
  v2/kinesis-to-pubsub/README.md
  v2/kudu-to-bigquery/README.md
  v2/mongodb-to-googlecloud/docs/MongoDbToBigQuery/README.md
  v2/mongodb-to-googlecloud/docs/MongoDbToBigQueryCDC/README.md
  v2/mqtt-to-pubsub/README.md
  v2/pom.xml
  v2/pubsub-binary-to-bigquery/docs/PubSubAvroToBigQuery/README.md
  v2/pubsub-binary-to-bigquery/docs/PubSubProtoToBigQuery/README.md
  v2/pubsub-cdc-to-bigquery/README.md
  v2/pubsub-to-jms/README.md
  v2/pubsub-to-mongodb/README.md
  v2/pubsub-to-redis/README.md
  v2/sourcedb-to-spanner/README.md
  v2/spanner-change-streams-to-sharded-file-sink/README.md
  v2/streaming-data-generator/README.md
  yaml/pom.xml
Labels: size/L, improvement

#2127 Changing project id for spanner-staging-tests and run on spanner runners
  .github/workflows/spanner-staging-tests.yml
Labels: size/S, ignore-for-release

#2137 Small Fix for Cassandra bulk e2e test
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/config/SQLDialect.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/avro/GenericRecordTypeConvertor.java
Labels: size/S, bug-fix

#2138 Support shadow table in different database
  v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/DataStreamToSpanner.java
  v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/SpannerTransactionWriter.java
  v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/SpannerTransactionWriterDoFn.java
  v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/datastream/ChangeEventContext.java
  v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/datastream/ChangeEventContextFactory.java
  v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/datastream/ChangeEventSequenceFactory.java
  v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/datastream/MySqlChangeEventContext.java
  v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/datastream/MySqlChangeEventSequence.java
  v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/datastream/OracleChangeEventContext.java
  v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/datastream/OracleChangeEventSequence.java
  v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/datastream/PostgresChangeEventContext.java
  v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/datastream/PostgresChangeEventSequence.java
  v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/datastream/ShadowTableReadUtils.java
  v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/spanner/ProcessInformationSchema.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerTest.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/SpannerStreamingWriteIntegrationTest.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/SpannerTransactionWriterDoFnTest.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/datastream/ChangeEventContextFactoryTest.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/datastream/ChangeEventSequenceFactoryTest.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/datastream/MySqlChangeEventContextTest.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/datastream/MySqlChangeEventSequenceTest.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/datastream/OracleChangeEventContextTest.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/datastream/OracleChangeEventSequenceTest.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/datastream/PostgresChangeEventContextTest.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/datastream/PostgresChangeEventSequenceTest.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/datastream/ShadowTableReadUtilsTest.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/spanner/ProcessInformationSchemaIntegrationTest.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/spanner/ProcessInformationSchemaTest.java
Labels: size/XXL, improvement

#2142 Set maven version requirement to 3.6.3
  plugins/templates-maven-plugin/pom.xml
Labels: size/XS, ignore-for-release

#2136 feat: bump to Neo4j driver v5
  v2/googlecloud-to-neo4j/pom.xml
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/database/Neo4jConnectionTest.java
Labels: size/XS, improvement

#2143 Bump Beam to 2.62.0
  pom.xml
  python/src/main/python/job-builder-server/requirements.txt
  python/src/main/python/streaming-llm/requirements.txt
  python/src/main/python/word-count-python/requirements.txt
  python/src/main/python/yaml-template/requirements.txt
  v2/googlecloud-to-elasticsearch/src/main/resources/requirements.txt
  v2/googlecloud-to-googlecloud/src/main/resources/requirements.txt
  v2/googlecloud-to-splunk/src/main/resources/requirements.txt
  v2/pubsub-binary-to-bigquery/src/main/resources/requirements.txt
  v2/pubsub-to-mongodb/src/main/resources/requirements.txt
Labels: size/XXL, improvement

#2120 Cassandra DML Generator - Spanner to SourceDB
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/schema/Schema.java
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/constants/Constants.java
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/dbutils/dao/source/CassandraDao.java
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/dbutils/dml/CassandraDMLGenerator.java
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/dbutils/dml/CassandraTypeHandler.java
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/dbutils/processor/InputRecordProcessor.java
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/dbutils/processor/SourceProcessorFactory.java
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/models/DMLGeneratorRequest.java
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/transforms/SourceWriterFn.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/dbutils/dao/source/CassandraDaoTest.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/dbutils/dml/CassandraDMLGeneratorTest.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/dbutils/dml/CassandraTypeHandlerTest.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/dbutils/processor/SourceProcessorFactoryTest.java
  v2/spanner-to-sourcedb/src/test/resources/cassandraSession.json
Labels: size/XXL, ignore-for-release

#2124 Fix flaky IT in reverse replication
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/SpannerToSourceDbCustomTransformationIT.java
Labels: size/XS, ignore-for-release

#2146 Fix the additional sequence kind options
  v1/src/main/java/com/google/cloud/teleport/spanner/AvroSchemaToDdlConverter.java
  v1/src/main/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScanner.java
  v1/src/test/java/com/google/cloud/teleport/spanner/AvroSchemaToDdlConverterTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScannerIT.java
Labels: size/M, bug-fix

#2148 fix: revamp Neo4j kernel version sniffing
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/database/Neo4jCapabilities.java
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/database/Neo4jConnection.java
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/database/CypherGeneratorTest.java
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/database/Neo4jCapabilitiesTest.java
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/database/Neo4jConnectionTest.java
Labels: size/L, bug-fix

#2149 fix: account for on-premise Neo4j CalVer version format
  v2/googlecloud-to-neo4j/src/main/java/com/google/cloud/teleport/v2/neo4j/database/Neo4jCapabilities.java
  v2/googlecloud-to-neo4j/src/test/java/com/google/cloud/teleport/v2/neo4j/database/Neo4jCapabilitiesTest.java
Labels: size/S, bug-fix

#2144 Added support for Tokenlist columns
  v1/src/main/java/com/google/cloud/teleport/spanner/DdlToAvroSchemaConverter.java
  v1/src/main/java/com/google/cloud/teleport/spanner/common/SizedType.java
  v1/src/main/java/com/google/cloud/teleport/spanner/common/Type.java
  v1/src/main/java/com/google/cloud/teleport/spanner/ddl/Column.java
  v1/src/main/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScanner.java
  v1/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerSchema.java
  v1/src/test/java/com/google/cloud/teleport/spanner/AvroSchemaToDdlConverterTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/DdlToAvroSchemaConverterTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ExportPipelineIT.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ImportPipelineIT.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScannerTest.java
  v1/src/test/java/org/apache/beam/sdk/io/gcp/spanner/SpannerSchemaTest.java
Labels: size/M, improvement

#2153 Handle Frozen Case and Error Categorization
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/dbutils/dml/CassandraTypeHandler.java
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/transforms/SourceWriterFn.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/dbutils/dml/CassandraTypeHandlerTest.java
Labels: size/M, ignore-for-release

#2164 Upgrade upload-artifact version
  .github/actions/publish-site-report/action.yml
  .github/workflows/java-pr.yml
  .github/workflows/kafka-pr.yml
  .github/workflows/load-tests.yml
  .github/workflows/scorecards-analysis.yml
  .github/workflows/spanner-load-tests.yml
  .github/workflows/spanner-pr.yml
Labels: size/M, ignore-for-release
