Repository GoogleCloudPlatform/DataflowTemplates, pull requests merged in 2025-10, with the labels that each got.

#2836 Change default CPU priority of bulk template to HIGH
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/options/SourceDbToSpannerOptions.java
Labels: size/XS, bug-fix

#2843 fix: simplify sed command in surefire report time format conversion
  pom.xml
Labels: size/XS, ignore-for-release

#2840 Only read schema when the col in mod is not in the stored schema.
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/spannerchangestreamstobigquery/schemautils/SchemaUpdateUtils.java
Labels: size/S, improvement

#2813 feat: Add support for property graph on view
  v1/src/main/java/com/google/cloud/teleport/spanner/DdlToAvroSchemaConverter.java
  v1/src/main/java/com/google/cloud/teleport/spanner/ddl/Ddl.java
  v1/src/test/java/com/google/cloud/teleport/spanner/AvroSchemaToDdlConverterTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/DdlToAvroSchemaConverterTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ddl/DdlTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScannerIT.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ddl/PropertyGraphTest.java
Labels: size/XXL, improvement
