Repository GoogleCloudPlatform/DataflowTemplates, pull requests merged in 2025-05, with the labels that each got.

#2328 feat(bigtable): Add support for ignore columns
  v2/bigtable-changestreams-to-hbase/README_Bigtable_Change_Streams_to_HBase.md
  v2/bigtable-common/src/main/java/com/google/cloud/teleport/v2/bigtable/options/BigtableCommonOptions.java
  v2/googlecloud-to-googlecloud/README_Bigtable_Change_Streams_to_BigQuery.md
  v2/googlecloud-to-googlecloud/README_Bigtable_Change_Streams_to_Google_Cloud_Storage.md
  v2/googlecloud-to-googlecloud/README_Bigtable_Change_Streams_to_PubSub.md
  v2/googlecloud-to-googlecloud/README_Bigtable_Change_Streams_to_Vector_Search.md
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstobigquery/BigtableChangeStreamsToBigQuery.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstobigquery/model/BigtableSource.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstobigquery/model/Mod.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstobigquery/schemautils/BigQueryUtils.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstogcs/BigtableUtils.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstopubsub/BigtableChangeStreamsToPubSub.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstopubsub/model/BigtableSource.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstopubsub/model/Mod.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstopubsub/schemautils/PubSubUtils.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/utils/BigtableSource.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstobigquery/schemautils/BigQueryUtilTest.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstopubsub/BigtableChangeStreamsToPubSubIT.java
Labels: size/L, bug-fix

#2340 feat(bigtable): Send invalid elements to non retriable DLQ
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstopubsub/BigtableChangeStreamsToPubSub.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstopubsub/FailsafePublisher.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstopubsub/model/InvalidModException.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstopubsub/schemautils/PubSubUtils.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstopubsub/BigtableChangeStreamsToPubSubIT.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/bigtablechangestreamstopubsub/schemautils/PubSubUtilsTest.java
Labels: size/L, bug-fix

#2351 Added handling for spanner priority in bulk migration
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/options/SourceDbToSpannerOptions.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/SourceDbToSpanner.java
Labels: size/S, ignore-for-release

#2233 Add Option to run Incremental Export From Bigtable (Timestamp Filtering)
  v1/README_Cloud_Bigtable_to_GCS_Avro.md
  v1/src/main/java/com/google/cloud/teleport/bigtable/BigtableToAvro.java
  v1/src/test/java/com/google/cloud/teleport/bigtable/BigtableToAvroTimestampTest.java
Labels: size/L, improvement

#2295 feat: add interleave in feature to optimise bulk migration
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/SpannerStreamingWriteIntegrationTest.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/spanner/DatastreamToSpannerExceptionClassifierIT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/spanner/ProcessInformationSchemaIntegrationTest.java
  v2/datastream-to-spanner/src/test/resources/DataStreamToSpanner100GbLT/spanner-schema-interleaving.sql
  v2/datastream-to-spanner/src/test/resources/SpannerExceptionClassifierIT/spanner-schema.sql
  v2/sourcedb-to-spanner/src/test/resources/ForeignKeyDependencyIT/spanner-schema.sql
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/ddl/Ddl.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/ddl/InformationSchemaScanner.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/ddl/Table.java
  v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/ddl/DdlTest.java
  v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/ddl/InformationSchemaScannerTest.java
  v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/schema/IdentityMapperTest.java
  v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/spanner/SpannerSchemaTest.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/SpannerToSourceDbInterleaveMultiShardIT.java
  v2/spanner-to-sourcedb/src/test/resources/SpannerToSourceDbInterleaveMultiShardIT/mysql-schema.sql
  v2/spanner-to-sourcedb/src/test/resources/SpannerToSourceDbInterleaveMultiShardIT/session.json
  v2/spanner-to-sourcedb/src/test/resources/SpannerToSourceDbInterleaveMultiShardIT/spanner-schema.sql
Labels: size/XL, improvement

#2348 update the docs
  v2/jdbc-and-googlecloud/README_Pubsub_to_Jdbc.md
  v2/sourcedb-to-spanner/README_Sourcedb_to_Spanner_Flex.md
  v2/spanner-to-sourcedb/README_Spanner_to_SourceDb.md
Labels: size/S, ignore-for-release

#2363 Bulk Migration LT Fix
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/loadtesting/MySQLSourceDbtoSpannerWideRow10MBPerCellLT.java
Labels: size/S

#2253 Add UDF support to import/export workflows
  v1/src/main/java/com/google/cloud/teleport/spanner/AvroSchemaToDdlConverter.java
  v1/src/main/java/com/google/cloud/teleport/spanner/AvroUtil.java
  v1/src/main/java/com/google/cloud/teleport/spanner/DdlToAvroSchemaConverter.java
  v1/src/main/java/com/google/cloud/teleport/spanner/ExportTransform.java
  v1/src/main/java/com/google/cloud/teleport/spanner/ImportTransform.java
  v1/src/main/java/com/google/cloud/teleport/spanner/common/NameUtils.java
  v1/src/main/java/com/google/cloud/teleport/spanner/ddl/Ddl.java
  v1/src/main/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScanner.java
  v1/src/main/java/com/google/cloud/teleport/spanner/ddl/Udf.java
  v1/src/main/java/com/google/cloud/teleport/spanner/ddl/UdfParameter.java
  v1/src/main/proto/export.proto
  v1/src/test/java/com/google/cloud/teleport/spanner/AvroSchemaToDdlConverterTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/CopyDbTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/CopySchemaTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/DdlToAvroSchemaConverterTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ExportTransformTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ImportFromAvroTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ImportTransformTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/SpannerServerResource.java
  v1/src/test/java/com/google/cloud/teleport/spanner/TextImportTransformTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/common/NameUtilsTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ddl/DdlTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScannerIT.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScannerTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ddl/RandomDdlGenerator.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ddl/UdfParameterTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ddl/UdfTest.java
Labels: size/XXL, improvement

#2369 Upgrade to Beam 2.65.0
  it/cassandra/pom.xml
  it/google-cloud-platform/pom.xml
  it/jdbc/pom.xml
  plugins/core-plugin/src/main/java/com/google/cloud/teleport/plugin/DockerfileGenerator.java
  plugins/core-plugin/src/main/resources/Dockerfile-template-yaml
  plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesStageMojo.java
  pom.xml
  python/default_base_python_requirements.txt
  python/default_base_yaml_requirements.txt
  python/generate_dependencies.sh
  python/src/main/python/job-builder-server/requirements.txt
  python/src/main/python/streaming-llm/base_requirements.txt
  python/src/main/python/streaming-llm/requirements.txt
  python/src/main/python/word-count-python/requirements.txt
  python/src/main/python/yaml-template/requirements.txt
  v2/google-ads-to-googlecloud/pom.xml
  v2/google-ads-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/GoogleAdsToBigQuery.java
  v2/google-ads-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/transforms/GoogleAdsRowToReportRowJsonFn.java
  v2/google-ads-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/utils/GoogleAdsRateLimitPolicyFactory.java
  v2/google-ads-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/utils/GoogleAdsUtils.java
  v2/google-ads-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/transforms/GoogleAdsRowToReportRowJsonFnTest.java
  v2/google-ads-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/utils/GoogleAdsRateLimitPolicyFactoryTest.java
  v2/googlecloud-to-elasticsearch/src/main/resources/requirements.txt
  v2/googlecloud-to-googlecloud/src/main/resources/requirements.txt
  v2/googlecloud-to-splunk/src/main/resources/requirements.txt
  v2/pubsub-binary-to-bigquery/src/main/resources/requirements.txt
  v2/pubsub-to-mongodb/src/main/resources/requirements.txt
Labels: size/XXL, improvement

#2368 updated logic to reconsume errors from dlq in reverse replication
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/SpannerToSourceDb.java
Labels: size/XS, ignore-for-release

#2360 Disable maven cache
  .github/actions/setup-java-env/action.yml
  .github/workflows/prepare-java-cache.yml
Labels: size/M, ignore-for-release

#2372 Set default container image properties
  v2/pom.xml
Labels: size/XS, ignore-for-release

#2366 Use exluded semantics in PG update SQL
  v2/datastream-to-sql/src/main/java/com/google/cloud/teleport/v2/utils/DatastreamToPostgresDML.java
Labels: addition, size/S, Datastream, improvement

#2210 Adding BigQuery to ClickHouse Template
  v2/clickhouse-common/pom.xml
  v2/clickhouse-common/src/main/java/com/google/cloud/teleport/v2/clickhouse/options/ClickHouseWriteOptions.java
  v2/clickhouse-common/src/main/java/com/google/cloud/teleport/v2/clickhouse/options/package-info.java
  v2/clickhouse-common/src/main/java/com/google/cloud/teleport/v2/clickhouse/utils/ClickHouseUtils.java
  v2/clickhouse-common/src/main/java/com/google/cloud/teleport/v2/clickhouse/utils/package-info.java
  v2/googlecloud-to-clickhouse/pom.xml
  v2/googlecloud-to-clickhouse/src/main/java/com/google/cloud/teleport/v2/clickhouse/options/BigQueryToClickHouseOptions.java
  v2/googlecloud-to-clickhouse/src/main/java/com/google/cloud/teleport/v2/clickhouse/options/package-info.java
  v2/googlecloud-to-clickhouse/src/main/java/com/google/cloud/teleport/v2/clickhouse/templates/BigQueryToClickHouse.java
  v2/googlecloud-to-clickhouse/src/main/java/com/google/cloud/teleport/v2/clickhouse/templates/package-info.java
  v2/googlecloud-to-clickhouse/src/test/java/com/google/cloud/teleport/v2/clickhouse/BigQueryToClickHouseIT.java
  v2/googlecloud-to-clickhouse/src/test/java/com/google/cloud/teleport/v2/clickhouse/BigQueryToClickHouseTest.java
  v2/pom.xml
Labels: size/XL, improvement

#2376 Bulk schema overrides
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/options/SourceDbToSpannerOptions.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/PipelineController.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/MySQLFileOverridesSchemaMapperIT.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/MySQLStringOverridesSchemaMapperIT.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/PipelineControllerTest.java
  v2/sourcedb-to-spanner/src/test/resources/SchemaMapperIT/file-overrides.json
  v2/sourcedb-to-spanner/src/test/resources/SchemaMapperIT/mysql-overrides-src.sql
  v2/sourcedb-to-spanner/src/test/resources/SchemaMapperIT/spanner-overrides-target.sql
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/avro/GenericRecordTypeConvertor.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/schema/SchemaFileOverridesBasedMapper.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/schema/SchemaStringOverridesBasedMapper.java
  v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/schema/SchemaFileOverridesBasedMapperTest.java
  v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/schema/SchemaStringOverridesBasedMapperTest.java
Labels: size/XXL, improvement

#2355 Spanner Live forward migration template - Pubsub failure injection tests
  it/google-cloud-platform/pom.xml
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/logging/LoggingClient.java
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/logging/package-info.java
  it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/logging/LoggingClientTest.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/failureinjectiontesting/DataStreamToSpannerFTBase.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/failureinjectiontesting/DataStreamToSpannerMySQLSrcPubsubFT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/failureinjectiontesting/DataStreamToSpannerMySQLSrcSpannerFT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/failureinjectiontesting/utils/MySQLSrcDataProvider.java
Labels: size/XL, ignore-for-release

#2384 Generate BigQuery to ClickHouse documentation
  v2/googlecloud-to-clickhouse/README_BigQuery_to_ClickHouse.md
Labels: size/L, ignore-for-release

#2386 Temporarily disabling Cassandra.allDataTypesTest() until fix for https://github.com/apache/beam/issues/34863 gets merged into dataflow.
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/CassandraAllDataTypesIT.java
Labels: size/XS, bug-fix

#2361 Added PG support for vector indexes
  v1/src/main/java/com/google/cloud/teleport/spanner/ddl/Index.java
  v1/src/main/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScanner.java
  v1/src/main/java/com/google/cloud/teleport/spanner/spannerio/SpannerSchema.java
  v1/src/test/java/com/google/cloud/teleport/spanner/AvroSchemaToDdlConverterTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/DdlToAvroSchemaConverterTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ddl/DdlTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScannerIT.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScannerTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/spannerio/SpannerSchemaTest.java
Labels: size/L, improvement

#2390 Add FirestoreMigrationTool team as code owner of v2/datastream-mongodb-to-firestore
  .github/CODEOWNERS
Labels: size/XS, ignore-for-release

#2392 Revert "Ignore other Bulk Migration LT"
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/loadtesting/DataStreamToSpanner100GbLT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/loadtesting/DataStreamToSpannerBlobTableLT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/loadtesting/DataStreamToSpannerForeignKeyLT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/loadtesting/DataStreamToSpannerInterleavedTableLT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/loadtesting/DataStreamToSpannerTallTableLT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/loadtesting/DataStreamToSpannerWideTableLT.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/loadtesting/MySQLSourceDbToSpannerLT.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/loadtesting/MySQLSourceDbtoSpannerWideRow10MBPerCellLT.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/loadtesting/PostgreSQLSourceDbToSpannerLT.java
Labels: size/S, ignore-for-release

#2401 Bulk Migration LT - Changed to Private host
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/loadtesting/MySQLSourceDbtoSpannerWideRow10MBPerCellLT.java
Labels: size/XS

#2403 fixed the documentation inconsistency
  v2/datastream-to-bigquery/src/main/java/com/google/cloud/teleport/v2/templates/DataStreamToBigQuery.java
Labels: size/XS, ignore-for-release

#2262 [PropertyGraph] Explicitly output node reference key columns
  v1/src/main/java/com/google/cloud/teleport/spanner/ddl/GraphElementTable.java
  v1/src/test/java/com/google/cloud/teleport/spanner/AvroSchemaToDdlConverterTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ddl/DdlTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ddl/GraphElementTableTest.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ddl/PropertyGraphTest.java
Labels: size/S, improvement

#2404 optimized the run schedules
  .github/workflows/load-tests.yml
  .github/workflows/spanner-load-tests.yml
Labels: size/XS, ignore-for-release

#2406 Created the github issues when load tests fail
  .github/ISSUE_TEMPLATE/load-test-failure-issue-template.md
  .github/workflows/load-tests.yml
Labels: size/M, ignore-for-release
