Repository GoogleCloudPlatform/DataflowTemplates, pull requests merged in 2025-06, with the labels that each got.

#2354 Adding filter parameter to terraform in mongoDB to bigquery template …
  v2/mongodb-to-googlecloud/terraform/MongoDB_to_BigQuery/dataflow_job.tf
  v2/mongodb-to-googlecloud/terraform/MongoDB_to_BigQuery_CDC/dataflow_job.tf
Labels: size/M, ignore-for-release

#2411 added the v2 bigtable pr workflow
  .github/workflows/bigtable-pr.yml
  cicd/internal/flags/common-flags.go
  cicd/internal/flags/common-flags_test.go
Labels: size/L, ignore-for-release

#2418 added the status section
  README.md
Labels: size/S, ignore-for-release

#2397 fix breaking json in string variable
  v2/datastream-to-sql/src/main/java/com/google/cloud/teleport/v2/utils/DatastreamToDML.java
Labels: size/XS

#2425 Use more jobs for release
  .github/workflows/release.yml
Labels: size/L, ignore-for-release

#2434 need OIDC token
  .github/workflows/scorecards-analysis.yml
Labels: size/XS, ignore-for-release

#2439 added JDBC_DRIVER_CLASS_NAME
  python/src/test/java/com/google/cloud/teleport/templates/python/JdbcToBigQueryYamlIT.java
  python/src/test/resources/JdbcToBigQueryYamlIT.yaml
Labels: size/S, ignore-for-release

#2437 [DataStreamToSpanner] Skipping all the Live migration ITs which spawns Datastream
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerIT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerWideRowForMax16KeyTablePerDatabaseIT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerWideRowForMax9MibTablePerDatabaseIT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerWideRowForMaxColumnsPerTablesIT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerWideRowForMaxTableNameIT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerWideRowForMaxTableNameWithMaxColumnNameIT.java
Labels: size/S, ignore-for-release

#2343 Add support for Elasticsearch 9.0
  v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/utils/ElasticsearchIO.java
Labels: size/XS

#2457 removed adding labels
  .github/workflows/update-docs.yml
Labels: size/XS, ignore-for-release

#2462 Bulk migration lt for 10mb row
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/loadtesting/MySQLSourceDbtoSpannerWideRow10MBPerCellLT.java
Labels: size/S, run-load-tests, bug-fix

#2463 Use private IPs in Spanner to Sourcdb template ITs
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/SpannerToSourceDbITBase.java
Labels: size/XS, ignore-for-release

#2468 [Bulk Migration] Adding Support for `Timestamp` PKey Support. IT for fractional `DateTime` and fractional `Timestamp`
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/dialectadapter/mysql/MysqlDialectAdapter.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/dialectadapter/postgresql/PostgreSQLDialectAdapter.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/iowrapper/JdbcIoWrapper.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/uniformsplitter/range/BoundaryExtractorFactory.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/schema/SourceColumnIndexInfo.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/dialectadapter/postgresql/PostgreSQLDialectAdapterTest.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/uniformsplitter/range/BoundaryExtractorFactoryTest.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/jdbc/uniformsplitter/range/BoundarySplitterFactoryTest.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/MySQLDataTypesIT.java
  v2/sourcedb-to-spanner/src/test/resources/DataTypesIT/mysql-data-types.sql
  v2/sourcedb-to-spanner/src/test/resources/DataTypesIT/mysql-spanner-schema.sql
Labels: size/M, ignore-for-release

#2344 Fixed Typos
  contributor-docs/add-flex-template.md
  contributor-docs/code-contributions.md
  v2/datastream-to-postgres/README.md
  v2/datastream-to-sql/README.md
Labels: size/XS, ignore-for-release

#2479 removed the team reviewer
  .github/workflows/update-docs.yml
Labels: size/XS, ignore-for-release

#2417 tests: bulk forward and reverse it
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/datastream/DatastreamResourceManager.java
  it/google-cloud-platform/src/test/java/org/apache/beam/it/gcp/datastream/DatastreamResourceManagerTest.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/endtoend/BulkForwardAndReverseMigrationShardedEndToEndIT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/endtoend/EndToEndTestingITBase.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/endtoend/ForwardAndReverseMigrationNonShardedEndToEndIT.java
  v2/datastream-to-spanner/src/test/resources/EndToEndTesting/NonShardedMigration/mysql-schema.sql
  v2/datastream-to-spanner/src/test/resources/EndToEndTesting/NonShardedMigration/session.json
  v2/datastream-to-spanner/src/test/resources/EndToEndTesting/NonShardedMigration/spanner-schema.sql
  v2/datastream-to-spanner/src/test/resources/EndToEndTesting/ShardedMigration/mysql-schema.sql
  v2/datastream-to-spanner/src/test/resources/EndToEndTesting/ShardedMigration/session.json
  v2/datastream-to-spanner/src/test/resources/EndToEndTesting/ShardedMigration/spanner-schema.sql
Labels: size/XXL, improvement

#2477 move FileBasedDeadLetterQueueReconsumerTest.java to v2/common
  v2/common/src/test/java/com/google/cloud/teleport/v2/cdc/dlq/FileBasedDeadLetterQueueReconsumerTest.java
Labels: size/XS, ignore-for-release

#2483 added it-integration-test-parallelism and set this to 6
  .github/workflows/java-pr.yml
  .github/workflows/release.yml
  cicd/cmd/run-it-tests/main.go
  cicd/internal/flags/it-flags.go
Labels: size/S, ignore-for-release

#2427 supported BQ storage write and added the test for datastream-to-bq
  v2/datastream-to-bigquery/src/main/java/com/google/cloud/teleport/v2/templates/DataStreamToBigQuery.java
  v2/datastream-to-bigquery/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToBigQueryIT.java
Labels: size/L, improvement

#2490 use us-west2 for the it snapshots workflow
  .github/workflows/run-it-tests-beam-snapshots.yml
Labels: size/XS, ignore-for-release

#2481 Suppress error on cloud build Templates image nonzero return code
  plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesStageMojo.java
Labels: size/M, ignore-for-release

#2491 exposed it-thread-count for IT
  .github/workflows/java-pr.yml
  cicd/cmd/run-it-tests/main.go
  cicd/internal/flags/it-flags.go
  v1/src/test/java/com/google/cloud/teleport/templates/PubSubToSplunkIT.java
  v2/googlecloud-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/PubSubToBigQueryIT.java
Labels: size/S, ignore-for-release

#2494 use thread count 6 for release
  .github/workflows/release.yml
Labels: size/XS, ignore-for-release
