Repository GoogleCloudPlatform/DataflowTemplates, pull requests merged in 2025-03, with the labels that each got.

#2201 Custom transformation for Cassandra to Spanner SourceDB
  pom.xml
  v2/spanner-custom-shard/src/main/java/com/custom/CustomTransformationWithCassandraForIT.java
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/dbutils/dml/CassandraDMLGenerator.java
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/dbutils/dml/CassandraTypeHandler.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/SpannerToCassandraSourceDBCustomTransformationIT.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/SpannerToCassandraSourceDbIT.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/dbutils/dml/CassandraDMLGeneratorTest.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/dbutils/dml/CassandraTypeHandlerTest.java
  v2/spanner-to-sourcedb/src/test/resources/SpannerToCassandraSourceIT/cassandra-transformation-schema.sql
  v2/spanner-to-sourcedb/src/test/resources/SpannerToCassandraSourceIT/spanner-schema.sql
  v2/spanner-to-sourcedb/src/test/resources/SpannerToCassandraSourceIT/spanner-transformation-schema.sql
Labels: size/XL, ignore-for-release

#2226 Fix excludedGroups input for maven-surefire plugin.
  pom.xml
Labels: size/XS, ignore-for-release

#2234 Remove Python version from `pom.xml`
  python/pom.xml
Labels: size/XS, ignore-for-release

#2235 Add SkipRunnerV2Test category to JmsToPubsubIT and PubSubCdcToBigQueryIT
  v2/jms-to-pubsub/src/test/java/com/google/cloud/teleport/v2/templates/JmsToPubsubIT.java
  v2/pubsub-cdc-to-bigquery/src/test/java/com/google/cloud/teleport/v2/templates/PubSubCdcToBigQueryIT.java
Labels: size/XS, ignore-for-release

#2229 Fix a bug in CSVToBigQuery where commas in fields are not handled correctly.
  v1/src/main/java/com/google/cloud/teleport/templates/CSVToBigQuery.java
  v1/src/main/java/com/google/cloud/teleport/templates/common/CsvConverters.java
  v1/src/test/java/com/google/cloud/teleport/templates/common/CsvConvertersTest.java
  v1/src/test/resources/CsvConvertersTest/no_header.csv
  v1/src/test/resources/CsvConvertersTest/with_headers.csv
Labels: size/L, bug-fix

#2222 Update Dockerfile-template-yaml
  plugins/core-plugin/src/main/resources/Dockerfile-template-yaml
Labels: size/XS, improvement

#2230 Adding All Datatypes IT for Cassandra Migration
  v2/sourcedb-to-spanner/pom.xml
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/CassandraAllDataTypesIT.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/SourceDbToSpannerITBase.java
  v2/sourcedb-to-spanner/src/test/resources/DataTypesIT/cassandra-data-types.csql
  v2/sourcedb-to-spanner/src/test/resources/DataTypesIT/cassandra-spanner-schema.sql
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/avro/GenericRecordTypeConvertor.java
  v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/avro/GenericRecordTypeConvertorTest.java
Labels: size/XXL, integration testing, ignore-for-release

#2237 Add IF NOT EXISTS clause for spanner ddls used in ITs
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerIT.java
  v2/datastream-to-spanner/src/test/resources/DataStreamToSpanner100GbLT/spanner-schema-blob.sql
  v2/datastream-to-spanner/src/test/resources/DataStreamToSpanner100GbLT/spanner-schema-foreign-key.sql
  v2/datastream-to-spanner/src/test/resources/DataStreamToSpanner100GbLT/spanner-schema-interleaving.sql
  v2/datastream-to-spanner/src/test/resources/DataStreamToSpanner100GbLT/spanner-schema-tall-table.sql
  v2/datastream-to-spanner/src/test/resources/DataStreamToSpanner100GbLT/spanner-schema-wide-table.sql
  v2/datastream-to-spanner/src/test/resources/DataStreamToSpanner100GbLT/spanner-schema.sql
  v2/datastream-to-spanner/src/test/resources/DataStreamToSpannerDDLIT/spanner-schema.sql
  v2/datastream-to-spanner/src/test/resources/DataStreamToSpannerFileOverridesIT/spanner-schema.sql
  v2/datastream-to-spanner/src/test/resources/DataStreamToSpannerMixedIT/spanner-schema.sql
  v2/datastream-to-spanner/src/test/resources/DataStreamToSpannerSessionIT/spanner-schema.sql
  v2/datastream-to-spanner/src/test/resources/DataStreamToSpannerStringOverridesIT/spanner-schema.sql
  v2/datastream-to-spanner/src/test/resources/SeparateShadowTableDatabaseIT/spanner-schema.sql
  v2/datastream-to-spanner/src/test/resources/SpannerExceptionClassifierIT/spanner-schema.sql
  v2/gcs-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/SpannerToJdbcLTBase.java
  v2/gcs-to-sourcedb/src/test/resources/GCSToSourceDbInterleaveIT/spanner-schema.sql
  v2/gcs-to-sourcedb/src/test/resources/GCSToSourceDbInterleaveMultiShardIT/spanner-schema.sql
  v2/gcs-to-sourcedb/src/test/resources/GCSToSourceDbWithoutReaderIT/spanner-schema.sql
  v2/gcs-to-sourcedb/src/test/resources/SpannerToMySql100TpsLT/spanner-schema.sql
  v2/sourcedb-to-spanner/src/test/resources/CustomTransformationsNonShardedIT/spanner-schema.sql
  v2/sourcedb-to-spanner/src/test/resources/DDLIT/company-spanner-schema.sql
  v2/sourcedb-to-spanner/src/test/resources/DataTypesIT/mysql-spanner-schema.sql
  v2/sourcedb-to-spanner/src/test/resources/DataTypesIT/postgresql-spanner-schema.sql
  v2/sourcedb-to-spanner/src/test/resources/ForeignKeyDependencyIT/spanner-schema.sql
  v2/sourcedb-to-spanner/src/test/resources/NamespacesIT/spanner-schema.sql
  v2/sourcedb-to-spanner/src/test/resources/ReservedKeywordsIT/spanner-schema.sql
  v2/sourcedb-to-spanner/src/test/resources/SchemaMapperIT/company-spanner-schema-with-transformation.sql
  v2/sourcedb-to-spanner/src/test/resources/SchemaMapperIT/company-spanner-schema.sql
  v2/sourcedb-to-spanner/src/test/resources/SingleShardWithTransformation/spanner-schema.sql
  v2/spanner-change-streams-to-sharded-file-sink/src/test/java/com/google/cloud/teleport/v2/templates/SpannerChangeStreamToGcsITBase.java
  v2/spanner-change-streams-to-sharded-file-sink/src/test/resources/SpannerChangeStreamToGcsCustomShardIT/spanner-schema.sql
  v2/spanner-change-streams-to-sharded-file-sink/src/test/resources/SpannerChangeStreamToGcsMultiShardIT/spanner-schema.sql
  v2/spanner-change-streams-to-sharded-file-sink/src/test/resources/SpannerChangeStreamToGcsSingleShardIT/spanner-schema.sql
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/SpannerToSourceDbITBase.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/SpannerToSourceDbLTBase.java
  v2/spanner-to-sourcedb/src/test/resources/SpannerToMySqlSourceLT/spanner-schema.sql
  v2/spanner-to-sourcedb/src/test/resources/SpannerToSourceDbCustomShardIT/spanner-schema.sql
  v2/spanner-to-sourcedb/src/test/resources/SpannerToSourceDbCustomTransformationIT/spanner-schema.sql
  v2/spanner-to-sourcedb/src/test/resources/SpannerToSourceDbInterleaveMultiShardIT/spanner-schema.sql
Labels: size/L, improvement

#2223 Using set of random buckets for spanner ITs
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/TemplateTestBase.java
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/TestConstants.java
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/storage/GcsResourceManager.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerDDLIT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerEventsIT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerFileOverridesIT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerIT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerITBase.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerMixedIT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerSessionIT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerShardedMigrationWithMigrationShardIdColumnIT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerShardedMigrationWithoutMigrationShardIdColumnIT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerStringOverridesIT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DatastreamToSpannerSingleDFShardedMigrationIT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/SeparateShadowTableDatabaseDDLIT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/SeparateShadowTableDatabaseEventsIT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/SeparateShadowTableDatabaseFileOverridesIT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/SeparateShadowTableDatabaseMixedIT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/SeparateShadowTableDatabasePKFocusedIT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/SeparateShadowTableDatabaseSessionIT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/SeparateShadowTableDatabaseShardedMigrationWithMigrationShardIdColumnIT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/SeparateShadowTableDatabaseShardedMigrationWithoutMigrationShardIdColumnIT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/SeparateShadowTableDatabaseSingleDFShardedMigrationIT.java
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/SeparateShadowTableDatabaseStringOverridesIT.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/SpannerToCassandraSourceDBCustomTransformationIT.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/SpannerToCassandraSourceDbIT.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/SpannerToSourceDbCustomShardIT.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/SpannerToSourceDbCustomTransformationIT.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/SpannerToSourceDbDatatypeIT.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/SpannerToSourceDbIT.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/SpannerToSourceDbITBase.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/SpannerToSourceDbInterleaveMultiShardIT.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/SpannerToSourceDbTimezoneIT.java
Labels: size/XL, ignore-for-release

#2227 Add promote artifact method in release plugin
  plugins/templates-maven-plugin/pom.xml
  plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/PromoteHelper.java
  plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesReleaseMojo.java
  plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesRunMojo.java
  plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesStageMojo.java
  plugins/templates-maven-plugin/src/test/java/com/google/cloud/teleport/plugin/maven/PromoteHelperTest.java
Labels: size/XL, ignore-for-release

#2241 Fixed default DLQ path for Cloud Spanner Change Streams to Big Query
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/spannerchangestreamstobigquery/SpannerChangeStreamsToBigQuery.java
Labels: size/XS, bug-fix

#2243 Fix stagingArtifactRegistry support raw us.gcr.io artifact registry
  plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesStageMojo.java
  plugins/templates-maven-plugin/src/test/java/com/google/cloud/teleport/plugin/maven/TemplatesStageMojoTest.java
Labels: size/M, ignore-for-release

#2245 Print error response on wget call
  plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/PromoteHelper.java
  plugins/templates-maven-plugin/src/test/java/com/google/cloud/teleport/plugin/maven/PromoteHelperTest.java
Labels: size/XS, ignore-for-release

#2242 Adding Cassandra Type Options to IT test
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraIOWrapperHelper.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/mappings/CassandraMappingsProvider.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraIOWrapperHelperTest.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/testutils/BasicTestSchema.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/CassandraAllDataTypesIT.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/SourceDbToSpannerITBase.java
  v2/sourcedb-to-spanner/src/test/resources/DataTypesIT/cassandra-spanner-schema.sql
Labels: size/L, integration testing, ignore-for-release

#2239 Bump timeouts for tests involving FKs/interleaved dependenceis
  v2/gcs-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/GCSToSourceDbInterleaveIT.java
  v2/gcs-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/GCSToSourceDbInterleaveMultiShardIT.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/SpannerToSourceDbInterleaveMultiShardIT.java
Labels: size/S, improvement

#2250 Skip Datastream oracle to spanner IT
  v2/datastream-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSpannerIT.java
Labels: size/XS, bug-fix

#2238 Reverse Replication - IT for Boundary values and extended map datatypes
  v2/spanner-to-sourcedb/pom.xml
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/dbutils/dml/CassandraTypeHandler.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/SpannerToCassandraSourceDbIT.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/dbutils/dml/CassandraTypeHandlerTest.java
  v2/spanner-to-sourcedb/src/test/resources/SpannerToCassandraSourceIT/cassandra-schema.sql
  v2/spanner-to-sourcedb/src/test/resources/SpannerToCassandraSourceIT/spanner-schema.sql
Labels: size/XL, ignore-for-release

#2259 Force timeout for DataStreamToSQLIT
  .github/workflows/kafka-pr.yml
  cicd/internal/flags/common-flags.go
  cicd/internal/flags/common-flags_test.go
  v2/datastream-to-sql/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSQLIT.java
Labels: size/XS, ignore-for-release

#2256 Add cleanup scripts for spanner tests
  .github/workflows/cleanup-spanner-test-infra.yml
  test-infra/cleanup_pubsub_notifications.py
  test-infra/cleanup_spanner_databases.py
  test-infra/requirements.txt
Labels: size/L, ignore-for-release, improvement

#2255 Add the support of default_time_zone database option.
  v1/src/main/java/com/google/cloud/teleport/spanner/ddl/DatabaseOptionAllowlist.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ExportPipelineIT.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ImportPipelineIT.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ddl/InformationSchemaScannerIT.java
  v1/src/test/resources/ImportPipelineIT/googlesql/spanner-export.json
  v1/src/test/resources/ImportPipelineIT/postgres/spanner-export.json
Labels: size/M, improvement

#2249 Adding DDL parsing for Cassandra annotations
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/CassandraAllDataTypesIT.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/ddl/Column.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/ddl/annotations/cassandra/CassandraAnnotations.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/ddl/annotations/cassandra/CassandraList.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/ddl/annotations/cassandra/CassandraMap.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/ddl/annotations/cassandra/CassandraSet.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/ddl/annotations/cassandra/CassandraType.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/ddl/annotations/cassandra/package-info.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/ddl/annotations/package-info.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/avro/AvroJsonToCassandraMapConvertor.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/avro/GenericRecordTypeConvertor.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/schema/ISchemaMapper.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/schema/IdentityMapper.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/schema/SessionBasedMapper.java
  v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/ddl/DdlTest.java
  v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/ddl/annotations/cassandra/CassandraAnnotationsTest.java
  v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/ddl/annotations/cassandra/CassandraTypeTest.java
  v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/avro/AvroJsonToCassandraMapConvertorTest.java
  v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/avro/AvroTestingHelper.java
  v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/avro/AvroToValueMapperTest.java
  v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/avro/GenericRecordTypeConvertorTest.java
  v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/schema/IdentityMapperTest.java
  v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/schema/SessionBasedMapperTest.java
Labels: size/XXL, ignore-for-release

#2265 Fixing a failing Spanner Integration test
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/TemplateTestBase.java
  v1/src/test/java/com/google/cloud/teleport/spanner/ExportPipelineIT.java
Labels: size/M, improvement

#2264 Skip the tests DataStreamToBigQueryIT and DataStreamTOSQLIT until they get fixed
  v2/datastream-to-bigquery/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToBigQueryIT.java
  v2/datastream-to-sql/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSQLIT.java
Labels: size/XS, ignore-for-release

#2260 Adding InsertOnly Mode for Bulk.
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/options/SourceDbToSpannerOptions.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/MigrateTableTransform.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/transformer/SourceRowToMutationDoFn.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/MySQLSourceDbToSpannerSimpleIT.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/transformer/SourceRowToMutationDoFnTest.java
Labels: size/L, ignore-for-release

#2270 Adding Documentation for Running Cassandra Migrations
  v2/sourcedb-to-spanner/README_Sourcedb_to_Spanner.md
Labels: size/M, ignore-for-release

#2261 Update protobuf version
  v1/pom.xml
  v2/pom.xml
Labels: size/S, bug-fix

#2093 Cassandra io fork
  v2/sourcedb-to-spanner/pom.xml
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraDataSource.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraTableReaderFactoryCassandraIoImpl.java
  v2/sourcedb-to-spanner/src/main/java/org/apache/beam/sdk/io/localcassandra/CassandraIO.java
  v2/sourcedb-to-spanner/src/main/java/org/apache/beam/sdk/io/localcassandra/ConnectionManager.java
  v2/sourcedb-to-spanner/src/main/java/org/apache/beam/sdk/io/localcassandra/DefaultObjectMapper.java
  v2/sourcedb-to-spanner/src/main/java/org/apache/beam/sdk/io/localcassandra/DefaultObjectMapperFactory.java
  v2/sourcedb-to-spanner/src/main/java/org/apache/beam/sdk/io/localcassandra/ReadFn.java
  v2/sourcedb-to-spanner/src/main/java/org/apache/beam/sdk/io/localcassandra/RingRange.java
  v2/sourcedb-to-spanner/src/main/java/org/apache/beam/sdk/io/localcassandra/SplitGenerator.java
  v2/sourcedb-to-spanner/src/main/java/org/apache/beam/sdk/io/localcassandra/package-info.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraDataSourceTest.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraTableReaderFactoryCassandraIoImplTest.java
  v2/sourcedb-to-spanner/src/test/java/org/apache/beam/sdk/io/localcassandra/CassandraIOTest.java
  v2/sourcedb-to-spanner/src/test/java/org/apache/beam/sdk/io/localcassandra/SplitGeneratorTest.java
  v2/sourcedb-to-spanner/src/test/resources/CassandraUT/beamUTConfig.yaml
Labels: size/XXL, ignore-for-release

#2274 fix: distribute load on multiple telport spanner instances
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/TestConstants.java
  it/google-cloud-platform/src/main/java/org/apache/beam/it/gcp/spanner/SpannerResourceManager.java
  test-infra/cleanup_spanner_databases.py
Labels: size/S

#2275 Configuring numPartitions for Cassandra and allowing Spanner Mutation BatchSize to be configurable
  v2/sourcedb-to-spanner/README_Sourcedb_to_Spanner.md
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/options/SourceDbToSpannerOptions.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraDataSource.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraIOWrapperFactory.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraIOWrapperHelper.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraIoWrapper.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraTableReaderFactoryCassandraIoImpl.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/MigrateTableTransform.java
  v2/sourcedb-to-spanner/src/main/java/com/google/cloud/teleport/v2/writer/SpannerWriter.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraDataSourceTest.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraIOWrapperFactoryTest.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraIOWrapperHelperTest.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraIoWrapperTest.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/source/reader/io/cassandra/iowrapper/CassandraTableReaderFactoryCassandraIoImplTest.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/writer/SpannerWriterTest.java
Labels: size/L, bug-fix

#2271 Don't assert on datetime row because this could vary by timezone
  v2/jdbc-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/templates/JdbcToBigQueryReadWithPartitionsTest.java
Labels: size/M, ignore-for-release

#2284 Surface error on cloud build
  plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesStageMojo.java
Labels: size/M, ignore-for-release

#2283 Deduplicate template staging and release from dependent modules
  plugins/core-plugin/src/main/java/com/google/cloud/teleport/plugin/TemplateDefinitionsParser.java
  plugins/core-plugin/src/main/java/com/google/cloud/teleport/plugin/TemplateSpecsGenerator.java
  plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesBaseMojo.java
  plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesReleaseMojo.java
  plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesRunMojo.java
  plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesSpecMojo.java
  plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesStageMojo.java
  plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesTerraformMojo.java
  plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesValidateMojo.java
Labels: size/M, ignore-for-release

#2287 Test adjustments
  .github/workflows/kafka-pr.yml
  .github/workflows/spanner-pr.yml
  v1/src/test/java/com/google/cloud/teleport/bigtable/CassandraToBigtableIT.java
  v2/datastream-to-sql/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSQLIT.java
Labels: size/XS, ignore-for-release

#2286 Do not set null Spanner Host in SpannerChangeStreamsToBigQuery Templates
  v1/src/main/java/com/google/cloud/teleport/spanner/spannerio/SpannerAccessor.java
  v2/googlecloud-to-googlecloud/src/main/java/com/google/cloud/teleport/v2/templates/spannerchangestreamstobigquery/SpannerChangeStreamsToBigQuery.java
Labels: size/S, bug-fix
