Repository GoogleCloudPlatform/DataflowTemplates, pull requests merged in 2025-07, with the labels that each got.

#2484 [Fix]: Normalize Years and Months while constructing ISO8601 Duration String
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/CassandraAllDataTypesIT.java
  v2/spanner-common/src/main/java/com/google/cloud/teleport/v2/spanner/migrations/avro/GenericRecordTypeConvertor.java
  v2/spanner-common/src/test/java/com/google/cloud/teleport/v2/spanner/migrations/avro/GenericRecordTypeConvertorTest.java
Labels: size/L, bug-fix

#2496 Upgrade Templates to Beam 2.66.0
  plugins/core-plugin/src/main/resources/Dockerfile-template-yaml
  pom.xml
  python/default_base_python_requirements.txt
  python/default_base_yaml_requirements.txt
  python/src/main/python/job-builder-server/requirements.txt
  python/src/main/python/streaming-llm/base_requirements.txt
  python/src/main/python/word-count-python/requirements.txt
  python/src/main/python/yaml-template/main.py
  python/src/main/python/yaml-template/requirements.txt
  v2/datastream-mongodb-to-firestore/pom.xml
  v2/googlecloud-to-elasticsearch/src/main/resources/requirements.txt
  v2/googlecloud-to-googlecloud/src/main/resources/requirements.txt
  v2/googlecloud-to-splunk/src/main/resources/requirements.txt
  v2/pubsub-binary-to-bigquery/src/main/resources/requirements.txt
  v2/pubsub-to-mongodb/src/main/resources/requirements.txt
Labels: size/XXL, ignore-for-release

#2507 Remove outdated example
  .github/dependabot.yml
  v2/flex-wordcount-python/Dockerfile
  v2/flex-wordcount-python/README.md
  v2/flex-wordcount-python/spec/python_command_spec.json
  v2/flex-wordcount-python/wordcount.py
Labels: size/L, ignore-for-release

#2537 Remove additional job params and vpc settings from bulk ITs
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/MySQLSourceDBToSpannerWideRowInterleaveDepthIT.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/MySQLSourceDBToSpannerWideRowMaxColumnAndTableSizeIT.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/MySQLSourceDBToSpannerWideRowMaxSizeStringIT.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/MySQLSourceDbToSpannerWideRowMaxColumnsTableKeyIT.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/MySQLSourceDbToSpannerWideRowMaxSizeTableKeyIT.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/MySQLToSpannerWiderowForMaxColumnsPerTableIT.java
  v2/sourcedb-to-spanner/src/test/java/com/google/cloud/teleport/v2/templates/SourceDbToSpannerITBase.java
Labels: size/M, bug-fix

#2531 docs: Updates incorrect default value
  v1/README_Cloud_PubSub_to_Datadog.md
  v1/src/main/java/com/google/cloud/teleport/templates/common/DatadogConverters.java
Labels: size/XS, bug-fix

#2530 fix parent project in BigQueryToParquet
  v2/bigquery-to-parquet/src/main/java/com/google/cloud/teleport/v2/templates/BigQueryToParquet.java
  v2/bigquery-to-parquet/src/test/java/com/google/cloud/teleport/v2/templates/BigQueryToParquetTest.java
Labels: size/S, improvement

#2536 Reverse Replication:: All Datatypes PK IT for delete pKey changes
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/dbutils/dml/MySQLDMLGenerator.java
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/transforms/AssignShardIdFn.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/SpannerToSourceDbDatatypeIT.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/dbutils/dml/MySQLDMLGeneratorTest.java
  v2/spanner-to-sourcedb/src/test/java/com/google/cloud/teleport/v2/templates/transforms/AssignShardIdFnTest.java
  v2/spanner-to-sourcedb/src/test/resources/SpannerToSourceDbDatatypeIT/mysql-schema.sql
  v2/spanner-to-sourcedb/src/test/resources/SpannerToSourceDbDatatypeIT/session.json
  v2/spanner-to-sourcedb/src/test/resources/SpannerToSourceDbDatatypeIT/spanner-schema.sql
Labels: size/XXL, bug-fix

#2552 Fix codecov upload failure
  .github/workflows/bigtable-pr.yml
  .github/workflows/datastream-pr.yml
  .github/workflows/java-pr.yml
  .github/workflows/kafka-pr.yml
  .github/workflows/spanner-pr.yml
Labels: size/S, ignore-for-release

#2570 feat: add support for JDBC to BigQuery pipeline without driver jars
  python/src/test/java/com/google/cloud/teleport/templates/python/JdbcToBigQueryYamlIT.java
  python/src/test/resources/JdbcToBigQueryYamlITWithoutDriverJars.yaml
Labels: size/M, ignore-for-release

#2569 Update FormatDatastreamJsonToJson.java
  v2/datastream-common/src/main/java/com/google/cloud/teleport/v2/datastream/transforms/FormatDatastreamJsonToJson.java
  v2/datastream-common/src/test/java/com/google/cloud/teleport/v2/datastream/transforms/FormatDatastreamJsonToJsonTest.java
Labels: size/S, improvement

#2568 Bq to Bt support for sparse data format and user defined cell timestamps
  v2/bigquery-to-bigtable/src/main/java/com/google/cloud/teleport/v2/templates/BigQueryToBigtable.java
  v2/bigtable-common/src/main/java/com/google/cloud/teleport/v2/bigtable/transforms/BigtableConverters.java
  v2/bigtable-common/src/test/java/com/google/cloud/teleport/v2/bigtable/transforms/BigtableConvertersTest.java
Labels: size/L, improvement

#2576 Revert "Bump aiohttp from 3.12.13 to 3.12.14 in /v2/pubsub-binary-to-bigquery/src/main/resources"
  v2/pubsub-binary-to-bigquery/src/main/resources/requirements.txt
Labels: size/L, ignore-for-release

#2577 docs: add getting help section to README
  README.md
Labels: size/XS, ignore-for-release

#2551 added loginTimeout for the datasource connection
  v2/datastream-common/src/main/java/com/google/cloud/teleport/v2/datastream/io/CdcJdbcIO.java
  v2/datastream-common/src/test/java/com/google/cloud/teleport/v2/datastream/io/CdcJdbcIOTest.java
  v2/datastream-common/src/test/java/com/google/cloud/teleport/v2/datastream/io/LoginTimeoutIntegrationTest.java
  v2/datastream-to-sql/src/main/java/com/google/cloud/teleport/v2/templates/DataStreamToSQL.java
  v2/datastream-to-sql/src/test/java/com/google/cloud/teleport/v2/templates/DataStreamToSQLIT.java
Labels: size/L, improvement

#2499 Add data record count metrics to reverse replication
  v2/spanner-to-sourcedb/README.md
  v2/spanner-to-sourcedb/src/main/java/com/google/cloud/teleport/v2/templates/transforms/FilterRecordsFn.java
Labels: size/M, ignore-for-release

#2598 BigQuery to Bigtable handle empty rows
  v2/bigquery-to-bigtable/src/main/java/com/google/cloud/teleport/v2/templates/BigQueryToBigtable.java
  v2/bigquery-to-bigtable/src/test/java/com/google/cloud/teleport/v2/templates/VerifyAndFilterMutationsTest.java
Labels: size/L, improvement

#2592 Change stage prefix to tag
  plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/PromoteHelper.java
  plugins/templates-maven-plugin/src/main/java/com/google/cloud/teleport/plugin/maven/TemplatesStageMojo.java
  plugins/templates-maven-plugin/src/test/java/com/google/cloud/teleport/plugin/maven/PromoteHelperTest.java
  plugins/templates-maven-plugin/src/test/java/com/google/cloud/teleport/plugin/maven/TemplatesStageMojoTest.java
Labels: size/L, ignore-for-release

#2608 Removing Spanner templates from the Datastream PR workflow
  cicd/cmd/run-it-smoke-tests/main.go
  cicd/cmd/run-it-tests/main.go
  cicd/internal/flags/common-flags.go
  cicd/internal/flags/common-flags_test.go
  v2/datastream-common/pom.xml
Labels: size/S, ignore-for-release
